chipsalliance/chisel

- src/main/scala/Chisel/util/Decoupled.scala
- src/test/scala/chiselTests/VectorPacketIO.scala
This fix is specifically to enable continued work on Chisel tutorials that use DeqIO and EnqIO
There are more general issues in  [Chisel Emits firrtl files with undeclared wires #104](https://github.com/ucb-bar/chisel3/issues/104) that can be addressed later.  This PR eliminates assignment statements in DeqIO/EnqIO which is generally agreed to be unsupported.
> Fix init in deq io

- src/main/scala/Chisel/Driver.scala
This fix suppresses the STMTDLY AND WIDTH warning messages generated by verilator and adds the verilator command line to the standard out, so it can be seen.
> Verilator suppress warnings

- src/main/scala/Chisel/Driver.scala
- src/main/scala/Chisel/testers/TesterDriver.scala
- src/test/scala/chiselTests/Assert.scala
- src/test/scala/chiselTests/Harness.scala
Changes to make Chisel self-testing work with https://github.com/ucb-bar/firrtl/pull/92 (which is the solution to #121 and replacement for #122)
Also add same test from #122 to check that pipelined resets are supported.
**Note:** This should fail testing without https://github.com/ucb-bar/firrtl/pull/92 being merged to FIRRTL.
> Fix assert

- project/plugins.sbt
Scalastyle "scalastyle-sbt-plugin" % "0.7.0) dies with:
[error] .../chisel3/src/main/scala/Chisel/Data.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,4360,<)
[error] .../chisel3/src/main/scala/Chisel/Driver.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,3418,<)
...
Upgrade to "scalastyle-sbt-plugin" % "0.8.0"
(and bump the the others to "current" versions while we're here.)
> Bump plugin versions.

- src/main/scala/Chisel/Aggregate.scala
- src/main/scala/Chisel/Data.scala
There's a separate debate to be had about whether we want to
default-initialize Wires to invalid.  This patch just fixes the
implementation of the previous, unsafe approach, which was usually,
but not always, defaulting to invalid.
> Make Wire(init = x) behave the same as Wire(t = x) := x

- src/main/scala/Chisel/Bits.scala
This makes chisel2's behaviour and makes it
easier to read large constants.
> Remove underscores from constant creation

- src/main/scala/Chisel/Main.scala
I'm not sure what I was doing, but I had a def instead of a val that was
causing the circuit to be elaborated twice.  When fixing this I changed
output_file to a val as well, but that throws a None.get exception.  I
don't understand why.
> Only elaborate once in chiselMain.run()

- src/main/scala/Chisel/Main.scala
It's deprecated, but warning didn't show up on chiselMain and just failed.
> more kind assert on chiselMain

- build.sbt
Hopefully fixes #177 
Fix uses macro project distribution setup here: http://www.scala-sbt.org/0.12.1/docs/Detailed-Topics/Macro-Projects.html
Also refactors scalaVersion to commonSettings. Staying with a single multi-project .sbt file since official documentation (http://www.scala-sbt.org/release/docs/Basic-Def.html) recommends this form.
> Include Chisel Frontend in JAR

- chiselFrontend/src/main/scala/Chisel/Bits.scala
- chiselFrontend/src/main/scala/Chisel/Mem.scala
The return value of Bits.toBools doesn't need to be dynamically indexed
(as you could have just dynamically indexed the Bits itself), so returning
a Seq instead of a Vec is mroe appropriate.
This breaks a circular dependence between Bits and Vec, which helps with
macros/frontend refactoring.
> Have Bits.toBools return Seq, not Vec

- chiselFrontend/src/main/scala/Chisel/internal/firrtl/Emitter.scala
- chiselFrontend/src/main/scala/Chisel/internal/firrtl/IR.scala
- src/main/scala/Chisel/Driver.scala
Emit really has no business being in Circuit since the stuff in IR.scala is mostly just dumb structs without code. This moves the invocations of emit into Driver and allows access to Emitter throughout the entire Chisel package.
This is related to source locators, since it helps break another dependency and allows Emitter to be part of Chisel instead of Chisel Frontend.
> Move emit out of IR

- chiselFrontend/src/main/scala/Chisel/Module.scala
Option(null) returns None, but Some(null) returns Some(null), which we do not expect.
> Some -> Option

- src/main/scala/Chisel/Driver.scala
- src/main/scala/Chisel/testers/TesterDriver.scala
- src/test/scala/chiselTests/Harness.scala
This prevents Verilator from erroring when it cannot determine the top-module.
It also changes the PRINTF_COND guard to correctly use the top-level reset
instead of just the top of the Chisel-generated code.
This is useful because FIRRTL has so far duplicated all of the functionality in BackendCompilationUtilities, but now that we have releases, I'd like to just include chisel3 as a test dependency for FIRRTL. This specification of top-module is a problem in FIRRTL when modules are inlined (but consequently not deleted, perhaps this should be done instead?), so without this fix, FIRRTL still has to duplicate the functionality of verilogToCpp because it needs the ability to specify top-module.
Also, using $dutFile.reset is a bug if dutFile doesn't have the top-level module.
> Update BackendCompilationUtilities.verilogToCpp to specify top-module

- build.sbt
- chiselFrontend/src/main/scala/Chisel/Aggregate.scala
- chiselFrontend/src/main/scala/Chisel/Assert.scala
- chiselFrontend/src/main/scala/Chisel/BitPat.scala
- chiselFrontend/src/main/scala/Chisel/Bits.scala
- chiselFrontend/src/main/scala/Chisel/BlackBox.scala
- chiselFrontend/src/main/scala/Chisel/Data.scala
- chiselFrontend/src/main/scala/Chisel/Mem.scala
- chiselFrontend/src/main/scala/Chisel/Module.scala
- chiselFrontend/src/main/scala/Chisel/Printf.scala
- chiselFrontend/src/main/scala/Chisel/Reg.scala
- chiselFrontend/src/main/scala/Chisel/SeqUtils.scala
- chiselFrontend/src/main/scala/Chisel/When.scala
- chiselFrontend/src/main/scala/Chisel/internal/SourceInfo.scala
- chiselFrontend/src/main/scala/Chisel/internal/firrtl/IR.scala
- coreMacros/src/main/scala/Chisel/internal/sourceinfo/SourceInfoTransform.scala
- src/main/scala/Chisel/internal/firrtl/Emitter.scala
- src/main/scala/Chisel/testers/BasicTester.scala
This basically adds the SourceInfo trait and several concrete classes for when source information isn't available and a concrete class for source information from a Scala source line.
Source information is also added to the FIRRTL IR nodes and emitter as an explicit parameter. Source information is propagated through the Chisel frontend and internals as an implicit parameter. For methods that don't return Unit (aka nothing), a macro transform explicitly adds the SourceInfo parameter as implicitly[SourceInfo] so apply() calls can be chained after. The transformed versions of methods are of the same name, except with `do_` prepended. One of the macros (`SourceInfoTransform`) automatically detects the function name, which eliminates a lot of boilerplate.
The package split is up for debate. …
> Source locators

- chiselFrontend/src/main/scala/Chisel/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
This bug breaks Bundles with two empty Vectors... if you connect them. This was a latent bug affecting Rocket (utl and ptw in RoCCInterface) as well as any attempts to use multiple optional interfaces in TopIO.
> Fix a fairly serious bug whereby Vec's could incorrectly compare as equal

- src/main/scala/chisel/util/Mux.scala
There was an incongruity between the classes Mux could take and what MuxCase/MuxLookup could take. This changes the type signature of MuxCase and MuxLookup to support all subclasses of Data, as Mux does.
> Make sure MuxCase and MuxLookup can take all subclasses of Data

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/test/scala/chiselTests/BetterNamingTests.scala
For Chisel nodes defined in Module class-level values of type Option or
Iterable, we can still use reflection to assign names based on the name
of the value. This works for arbitrary nesting of Option and Iterable so
long as the innermost type is HasId. Note that this excludes Maps which
always have an innermost type of Tuple2[\_,\_].
Does not fix #190 but does improve things a little.
> Generate better names for nodes (#190)

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/main/scala/chisel3/util/BitPat.scala
- src/main/scala/chisel3/util/Bitwise.scala
- src/test/scala/chiselTests/Reg.scala
Resolves #256.
Since width was used to determine whether getWidth would succeed, I added
def isWidthKnown: Boolean
but another option would be to expose something like
def widthOption: Option[Int]
...thoughts?
> Make "def width" a private API; expose isWidthKnown instead

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
- src/test/scala/chiselTests/AnnotatingExample.scala
From discussion with @chick, @ucbjrl, and @azidar, this change provides chisel obejct names for FIRRTL annotation and chisel testers. Chisel's internal `HasId` now extends `Signald` having four public methods:
* `signalName`: returns the CHIRRTL name of the signal
* `pathName`: returns the full path name of the signal from the top module
* `parentPathName`: returns the full path of the signal's parent module instance from the top module
* `parentModName`: returns the signal's parent **module(not instance)** name. This is not final until CHIRRTL is actually emitted because duplication checks are done in this stage.
To annotate chisel objects and pass them to FIRRTL, users may have containers of `SignalId` and create annotation for signals with `signalName` and `parentModName` after CHIRRTL …
> Public APIs for chisel object names

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
Vec[Element] can have heterogeneous widths.
Vec[Aggregate] cannot (but possibly could relax this by stripping widths
from constituent Elements and relying on width inference).
> Check that Vecs have homogeneous types

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Printable.scala
- chiselFrontend/src/main/scala/chisel3/core/Printf.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
- src/main/scala/chisel3/package.scala
- src/test/scala/chiselTests/PrintableSpec.scala
- src/test/scala/chiselTests/Printf.scala
Printable is a new type that changes how printing of Chisel types is represented
It uses an ordered collection rather than a format string and specifiers
Main Features:
- Custom String Interpolator for Scala-like printf
- String-like manipulation of "hardware strings" for custom pretty-printing
- Default pretty-printing for Chisel data types
A few notes and questions:
- This does *not* remove the old printf functionality
- This partially resolves @ccelio's need for hardware strings, it allows for strings to be constructed naturally although it will emit the full string for each printf that results
- There is a bit of an inconsistency between the new naming API and this which uses FullName and Name. FullName corresponds to instanceName, and Name is just the local name of a field (eg. …
> Add Printable

- chiselFrontend/src/main/scala/chisel3/core/Printable.scala
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
- src/test/scala/chiselTests/PrintableSpec.scala
Printable was using HasId.instanceName to get full names of Chisel nodes.
instanceName uses the parent module of the HasId to get the Component to use in
calling fullName on the underlying Ref. Unfortunately this means that any
reference to a port of a instance will leave off the instance name. Fixing this
required the following:
- Add Component argument to Printable.unpack so that we can call Arg.fullName
directly in the Printable
- Pass the currently emitting module as the Component to Printable.unpack in
the Emitter
- Remove ability to create FullName Printables from Modules since the Module
name is not known until after the printf is already emitted
This commit also updates the PrintableSpec test to check that FullName and
Decimal printing work on ports of instances
> Fix bug in Printable FullName of submodule port

- src/main/scala/chisel3/util/Decoupled.scala
… that promises not to change the contents of .bits on a cycle after .valid is high and .ready is low. This is useful for detecting whether queues have been correctly inserted in front of modules that require these additional semantics.
> Add IrrevocableIO alternative to DecoupledIO

- src/main/scala/chisel3/util/Decoupled.scala
We can cast an output IrrevocableIO to DecoupledIO.
Likewise, we can cast an input DecoupledIO to an IrrevocableIO.
> Decoupled: cast DecoupledIO to IrrevocableIO as an input

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/resources/top.cpp
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
In the Chisel frontend, the implicit clock is named clock, but in the
generated FIRRTL, it is named clk.  There is no reason for this
discrepancy, and yet fixing it is painful, as it will break test harnesses.
Better to take the pain now than later.
Resolves #258.
> Make implicit clock name consistent

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/Clock.scala
This allows people to write clock-management circuitry in Chisel, rather
than mandating the use of BlackBoxes.
> Expose FIRRTL asClock construct

- chiselFrontend/src/main/scala/chisel3/core/SeqUtils.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/BitPat.scala
- src/main/scala/chisel3/util/Bitwise.scala
- src/main/scala/chisel3/util/Cat.scala
- src/main/scala/chisel3/util/CircuitMath.scala
- src/main/scala/chisel3/util/Conditional.scala
- src/main/scala/chisel3/util/Counter.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/Enum.scala
- src/main/scala/chisel3/util/LFSR.scala
- src/main/scala/chisel3/util/Mux.scala
- src/main/scala/chisel3/util/OneHot.scala
- src/main/scala/chisel3/util/Reg.scala
Add scaladocs for chisel3.util functions which didn't have them, and improves scaladocs for some others.
Except Lookup, that was undocumented and I can't figure out what it's supposed to do.
Treat this as a first pass ("basically usable") towards nicer scaladoc. More work needed (later) to make formatting / tone / style more consistent.
> Scaladocs for utils

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/main/scala/chisel3/util/Decoupled.scala
`firrtlDirection` should only be used for emitting firrtl. Any checks on the actual direction should use the bound Direction `dir`.
> Don't use firrtlDirection for direction checks - fix #298.

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/test/scala/chiselTests/ModuleExplicitResetSpec.scala
class Module has three other constructors (for variations on whether clock, reset, or both are explicitly provided). These also require an implicit CompileOptions parameter.
> Add CompileOptions implicits to all Module constructors - fix #310.

- build.sbt
- project/plugins.sbt
Use aggregate to run project tasks in subprojects
Use sbt-unidoc to generate combined scaladoc for project and subprojects.
> Generate scaladoc for all subprojects.

- chiselFrontend/src/main/scala/chisel3/core/CompileOptions.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/Error.scala
- src/test/scala/chiselTests/CompileOptionsTest.scala
Code that imports Chisel._ shouldn't see them.
Not sure if requireIOWrap is the right condition... or if cyan is a
good choice of color for deprecation warnings.
> Make asInput/asOutput/flip deprecation warnings dynamic

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/CompileOptions.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/CompileOptionsTest.scala
This makes <> and := do what they did two weeks ago (bidirectional connect with weak semantics for aggregates; unidirectional connect with weak semantics for elements), so that legacy code that imports Chisel._ will work seamlessly.
This means legacy code may emit incorrect FIRRTL, as was the case before; only new code that imports chisel3._ will be safe from this possibility.
> Give <> and := legacy behavior in compatibility mode

- src/main/scala/chisel3/Driver.scala
- src/test/scala/chiselTests/MultiAssign.scala
Merge with master and support checking for failure with an explicit assertion message. Update LastAssignTester() so it doesn't fail with a timeout.
> Update Driver: Check the simulation exit code #281

- src/test/scala/cookbook/Bundle2UInt.scala
- src/test/scala/cookbook/CookbookSpec.scala
- src/test/scala/cookbook/UInt2Bundle.scala
- src/test/scala/cookbook/UInt2VecOfBool.scala
- src/test/scala/cookbook/VecOfBool2UInt.scala
These tests are intended to be the examples in the Chisel3 Wiki Cookbook.
The primary idea is that the Cookbook examples should always be working so I want to generate the actual documentation on the Wiki from these examples. I am looking into tools to help do this, but haven't been able to get one working yet.
https://github.com/ucb-bar/chisel3/wiki/Cookbook
> Add Cookbook tests

- src/main/scala/chisel3/internal/firrtl/Emitter.scala
Is this a typo, or is there a reason one would want a space following the source annotations?
> remove trailing whitespace for annotations

- build.sbt
- src/main/scala/chisel3/ChiselExecutionOptions.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/testers/TesterDriver.scala
- src/test/scala/chiselTests/DriverSpec.scala
- src/test/scala/chiselTests/Reg.scala
Provide support for chisel options
Provide support for firrtl options when called as part of chisel compile
provide command line support the above options via scopt
provide and execution result class that can be used when chisel3 is part
of some externally controlled toolchain
Depends on [Firrtl PR 337](/ucb-bar/firrtl/pull/337)
> Implement a standardized execution scheme for chisel

- src/main/scala/chisel3/Driver.scala
This causes Verilator tests to compile faster and use less memory
I'm PRing this because Firrtl Travis checks out chisel3 and then runs sbt test. Firrtl Travis builds are failing due to g++ using too much memory. Using O0 is fixing the problem
Generally, projects that want O2 are going to be invoking Verilator themselves, so I think it's reasonable that the built-in Verilator invocation uses O0.
> Change verilogToCpp to use O0

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/scala/chisel3/package.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
FixedPoint numbers have a width and a binary position
Either, neither or both maybe inferred.
Firrtl will convert these to SInts during lowering passes
These changes are necessary for support of the DSP project
> FixedPoint number support for chisel3

- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
Unfortunately, 41674d5e130f64d7489fdb8583b8f4ad88b64aeb broke read enable inference for SeqMems in `RemoveCHIRRTL` of firrtl, and also broke `inferReadWrite` because port creation generates additional wires to truncate index bits. This will help firrtl correctly infer read enables for SeqMems.
> fix SeqMem's read port creation

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- chiselFrontend/src/main/scala/chisel3/core/SeqUtils.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
f1507aa7cec86ca8f5de13ddc96fd046370dfe1d is a compatibility-mode regression, since previously cloneType did not preserve flippedness.  Disable this new behavior whenever legacy connection behavior is in effect (i.e., !checkSynthesizable).
This fix is made more complicated by several holes CompileOptions propagation.  defaultCompileOptions frequently foils the compatibility layer by providing strict defaults rather than inheriting the user's CompileOptions.  In this case, it manifests when the Vec internals invoke the wrong cloneType behavior.
This patch removes all reliance on defaultCompileOptions within chisel3.core.  Ideally, we'd statically prevent it from being used in the internals, and only supply it to people who import chisel3.  Not sure how feasible that is.
> Preserve legacy cloneType behavior in compatibility mode

- chiselFrontend/src/main/scala/chisel3/core/Binding.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/util/Decoupled.scala
So when you do `sbt publish-local` or `sbt doc` you can have three less warnings.
The one that I couldn't fix is in Data.getWidth in Data.scala, where it has `@throws java.util.NoSuchElementException` that scaladoc can't generate the link for (since NoSuchElementException isn't in Chisel). One possible workaround is to disable all link warnings, but a proper clean fix would probably need to be in the scaladoc generator itself.
> Eliminate some doc warnings

- chiselFrontend/src/main/scala/chisel3/core/BlackBox.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
- src/main/scala/chisel3/package.scala
- src/test/resources/BlackBoxTest.v
- src/test/scala/chiselTests/BlackBox.scala
Also restrict black boxes to not allow hardware inside of them since it was
being silently dropped anyway.
Resolves #289 
This PR obviously depends on ucb-bar/firrtl#314 in order to pass tests. Also, thanks to the new Firrtl feature where extmodules can overwrite their name, Chisel emits BlackBoxes that will always get their desired names.
The current API proposed by this PR is to make blackbox parameters be an argument to the BlackBox abstract class of type Map[String, Any] where Any is dynamically checked to be only be Int, Long, BigInt, Double, or String. This leads to the use in one of the test cases of:
``` scala
class BlackBoxConstant(params: Map[String, Any]) extends BlackBox(params) {
val io = new Bundle {
val out = UInt(width = params("WIDTH").asInstanceOf[Int]).asOutput
}
} …
```
> Add support for parameterized BlackBoxes

- build.sbt
(Hopefully) a fix for #208 
chisel-testers still appears to compile fine (with publish-local) and the generated docs still include everything.
> Don't publish sub-project JARs

- build.sbt
Make rocket-chip compile again.
Previously, when a project depended on chisel3 through the project (i.e. submoduling chisel3 rather than using Maven dependencies), it wouldn't see coreMacros and chiselFrontend classes, since compile-internal means those dependencies aren't exposed past chisel3 and sbt doesn't export the JAR (which does contains those dependencies) by default. This exposes the whole JAR instead of the default chisel3 toplevel-only compiled files directory.
> Fix for direct dependencies

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/util/Enum.scala
- src/test/scala/chiselTests/Risc.scala
- src/test/scala/chiselTests/VendingMachine.scala
Get rid of some cruft exposed in #373 
This also allows `Bits.fromtInt(...)` to be removed. Yay!
All old APIs (with some new restrictions, rocket still works fine) are preserved without deprecation in `Chisel._`, aside from the non-compile-time-checkable Map[] enum constructor which probably should have been deprecated during chisel2. The Map[] enums have been removed from chisel3._ without deprecation.
The new restriction is that `nodeType` (legacy API) may only be of `UInt` type with unspecified width. Note that `Bits()` creates a `UInt`, and if you can't control the enum values, it makes little sense to specify a bitwidth.
> Simplify Enum API

- build.sbt
Workaround for #401.
It might also be a good idea to address this as the recommended way in template projects and documentation: users should have feature warnings, but should disable reflective call warnings in Chisel RTL.
> Can The Spam: disable reflective call warnings on tests

- src/main/resources/top.cpp
- src/main/scala/chisel3/Driver.scala
- src/test/scala/chiselTests/Harness.scala
- src/test/scala/chiselTests/Stop.scala
As seen in https://github.com/ucb-bar/chisel3/pull/422, you currently need to double stop() to actually stop in Verilator, this fixes that for our tests.
> Make stop() immediately end simulation for Verilator tests

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
- src/test/scala/chiselTests/FromBitsTester.scala
- src/test/scala/cookbook/UInt2Bundle.scala
My attempt to address #421 
Data now has no default implementation for do_fromBits. The previous default implementation is moved to Aggregate, and each flavor of Bits has it's own implementation too.
I'm not sure if fromBits should be legal for a clock, or if it should just throw and exception. Right now it just makes a clock wire and uses the := operator.
> Make fromBits work with types other than UInt

- build.sbt
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/Namer.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/NamingAnnotations.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/test/scala/chiselTests/NamingAnnotationTest.scala
Implementation for #303.
Doesn't use it anywhere (yet), so this only adds infrastructure. Hopefully also makes this less like to break things.
A (near) future PR would add this annotation to some core utils and replace TransitName.
> Better name propagation by macros

- src/main/scala/chisel3/Driver.scala
Problem: For Driver.execute, when you tried passing transforms/annotations via FirrtlOptions, they'd get overwritten before they ever got to Firrtl. Now I'm just appending the new stuff to what was already there...
Execution options are really hairy and poorly maintained across the various levels of Chisel hierarchy...
> doesn't lose old firrtl options annotations + transforms

- build.sbt
Use the root project's `unmanagedBase` (".../lib") in all sub-projects.
> Use the same firrtl for all sub-projects - fixes #447.

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/Decoupled.scala
After looking at the public API for Queue (see all of the public vals https://chisel.eecs.berkeley.edu/api/index.html#chisel3.util.Queue), I wanted to clean it up a little bit.
So it turns out that Chisel already names private vals, Scala just gives them really crazy names (like chisel3$util$Queue$$ram) so I wrote a function to clean these names up. I have not been able to figure out a way to detect if something is a private val via java reflection so this cleanup is my hacky alternative. Suggestions welcome.
I also changed all of the public fields in util that I could find that have no business being public (since accessing them externally would result in invalid Firrtl)
> Private vals

- README.md
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/testers/TesterDriver.scala
Also remove uses of firrtlToVerilog within chisel3.  Invoking Firrtl
programmatically is preferred to on the command line.
@ucbjrl @chick Is anything using firrtlToVerilog or runFirrtlAsProcess argument of TesterDriver.execute? As far as I can tell, [chisel-testers doesn't](https://github.com/ucb-bar/chisel-testers/search?utf8=%E2%9C%93&q=TesterDriver).
> Deprecate firrtlToVerilog in favor of compileFirrtlToVerilog

- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/util/BlackBoxUtils.scala
- src/test/resources/BlackBoxTest.v
- src/test/scala/chiselTests/BlackBoxImpl.scala
FOR REVIEW:  depends on [Firrtl PR#418](https://github.com/ucb-bar/firrtl/pull/418)
Blackbox implementers can annotate the modules with information on where to get the source verilog.
This API is very lightweight, real work is done in firrtl in companion PR
Added some verilog to BlackBoxTest.v resource for testing
> Move blackbox verilog implementations within reach of verilator

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/main/scala/chisel3/Driver.scala
- src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
- src/test/scala/chiselTests/AnnotationNoDedup.scala
- src/test/scala/chiselTests/BlackBoxImpl.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/DedupSpec.scala
- src/test/scala/chiselTests/DriverSpec.scala
Fixing one subtle bug led me to another which led to this fix (and a couple of minor other improvements). As all 3 commits are kind of orthogonal, I request a rebase and merge rather than squash.
Copy-paste most important commit message here:
Make Module and Bundle properly use empty namespaces
Also fix default suggested name of Module instances (now based on desired name
rather than actual assigned name).
Previously, Module and Bundle namespaces were "children" of the Module
definition namespace. This could lead to collisions that would give unexpected
names for module instances or Bundle elements. In particular, otherwise
identical modules that instantiate other identical modules in such a way that
the instance cannot be named via reflection would not be deduplicated because
the names …
> Fix namespace

- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
Retain un-deprecated SeqMem in compatibility mode, deprecate in chisel3.
Fixes #102.
> Rename SeqMem to SyncReadMem - fixes #102.

- chiselFrontend/src/main/scala/chisel3/core/CompileOptions.scala
Implemented using macros.
The implicit needs to be defined low priority in the resolution order (https://stackoverflow.com/questions/5598085/where-does-scala-look-for-implicits) so that the user could overload it (instead of triggering an ambiguous implicit error). The companion object must be defined in the same source file (so we can't move the definition to the chisel3 package, for instance) so this relies on what is an implementation limitation of the Scala macro system.
Implementation for #460
> Don't allow CompileOptions to materialize in Chisel core

- coreMacros/src/main/scala/chisel3/internal/sourceinfo/NamingAnnotations.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/CircuitMath.scala
- src/main/scala/chisel3/util/Counter.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/LFSR.scala
- src/main/scala/chisel3/util/Valid.scala
Won't work in all cases but is better than nothing.
Annotations aren't added in places where it obviously won't work (like recursive functions without a val definition). More discussion is needed on how to handle those cases (perhaps with variable interpolation?), but that's a later thing, preferably as we get more use cases.
Rocket builds and tests fine. Note that when compiling code with this, you may get warnings with "dependencies are invalidated unconditionally" - I think this means forced recompilation as a result of macros and should only show up once.
> Add naming transforms to chisel utils

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
- src/test/scala/chiselTests/IntegerMathSpec.scala
Defines .abs() in Num.  Implements Issue #466 
Implement .abs() in UInt
Change .abs() in SInt to return an SInt
Change .abs() in FixedPoint to return a FixedPoint
Added  a couple of tests
Add some scala style suppression to Bits so I can read code in IntelliJ
> Fix up Absolute value #abs

- src/test/scala/chiselTests/CompatibiltySpec.scala
0 failed because log2Ceil requires > 0, 1 failed because (1 << 1) - 1 = 1 which is a power of 2, and 32 (+more >32 probably) failed the isPow2 tests because integer overflow.
> Fix random failures in CompatibilitySpec

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/package.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
creation of FixedPoint types and literals was not consistent with current practices
for other types.  This commit brings them in-line, deprecated previous usages.
Also fixed a couple of return type  problems with shift operators on FixedPoint
> Fixed point factory stuff

- src/main/scala/chisel3/Driver.scala
Annotations coming from circuit elaboration were overwriting
this annotations that can be passed in on the command line
> Command line --repl-seq-mem lost before firrtl invoked

- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
@terpstra -- apparently I don't have the ability to push to Chisel3. 
This does what I'd expect, but seems perhaps FIRRTL can't handle numbers as names either.
Note the difference between how a Vec (the uarts) and a Record (the spis) are output to FIRRTL.
```
io.uarts[0] <- uart_0.io.port @[UARTPeriphery.scala 36:8]
io.uarts[1] <- uart_1.io.port @[UARTPeriphery.scala 36:8]
io.spis.0 <- spi_0.io.port @[SPIPeriphery.scala 32:8]
io.spis.1 <- spi_1.io.port @[SPIPeriphery.scala 32:8]
...
uart_pins_0.io.uart <- RocketChipTop.io.uarts[0]
uart_pins_1.io.uart <- RocketChipTop.io.uarts[1]
spi_pins_0.io.spi <- RocketChipTop.io.spis.0 
spi_pins_1.io.spi <- RocketChipTop.io.spis.1 
```
FIRRTL gives these errors on the SPI lines:
```
line 265272:12 no viable alternative at input 'io.spis.0'
line …
```
> Remove check on potentialy empty string for Record names.

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
> Bugfix #513. Fix BPSet width inference in Chisel3

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
This turned up after updating #494 (Remove explicit import of NotStrict) and adding the missing implicit CompileOptions to `:=`'s signature at which point Scala pointed out FixedPoint's `:=` could not override Data's `final :=` with the same signature: the implicit time bomb.
> Fend off future bug - replace FixedPoint ":=" with "connect".

- chiselFrontend/src/main/scala/chisel3/core/Assert.scala
- src/test/scala/chiselTests/Assert.scala
Note that currently assertions with % in the message or in the line or with % in the filename will all fail to compile
> Escape % in assertion messages

- src/test/scala/chiselTests/Vec.scala
> Test that large Vecs can have widths inferred

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/UIntOps.scala
Fixes #501. Also added UIntOps test.
> Fix mismatch between Chisel and Firrtl on UInt -& UInt

- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/Bitwise.scala
- src/main/scala/chisel3/util/Counter.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/Enum.scala
- src/main/scala/chisel3/util/Math.scala
- src/main/scala/chisel3/util/OneHot.scala
- src/test/scala/chiselTests/BlackBox.scala
- src/test/scala/chiselTests/Stack.scala
- src/test/scala/chiselTests/Tbl.scala
- src/test/scala/chiselTests/Vec.scala
- src/test/scala/examples/VendingMachineGenerator.scala
These methods are a scourge.  They are mathematically incorrect (log2(1) should yield 0, not 1), and so their use results in corner-case bugs that never fail to surprise good programmers.  For an example that occurred just this evening, see: https://github.com/ucb-bar/rocket-chip/pull/563
For historical context, log2Up was created within rocket-chip to work around zero-width wire limitations in chisel1.  A chisel maintainer imported them into chisel, apparently without much regard for the fact that they were deliberately defined incorrectly.  So, while we must keep them in the compatibility layer, we should take this compatibility-breaking opportunity to purge them.
This PR moves these methods to the compatibility layer and purges all of their use in the chisel codebase itself.  In most …
> Remove log2Up and log2Down from API

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/MonoConnect.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Counter.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/LFSR.scala
- src/main/scala/chisel3/util/Reg.scala
- src/main/scala/chisel3/util/Valid.scala
- src/test/scala/chiselTests/Assert.scala
- src/test/scala/chiselTests/Counter.scala
- src/test/scala/chiselTests/EnableShiftRegister.scala
- src/test/scala/chiselTests/GCD.scala
- src/test/scala/chiselTests/LFSR16.scala
- src/test/scala/chiselTests/MemorySearch.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
- src/test/scala/chiselTests/Reg.scala
- src/test/scala/chiselTests/Risc.scala
- src/test/scala/chiselTests/Stack.scala
- src/test/scala/chiselTests/Stop.scala
- src/test/scala/chiselTests/Vec.scala
- src/test/scala/cookbook/FSM.scala
- src/test/scala/cookbook/RegOfVec.scala
- src/test/scala/examples/ImplicitStateVendingMachine.scala
- src/test/scala/examples/SimpleVendingMachine.scala
- src/test/scala/examples/VendingMachineGenerator.scala
*cleaning up Chisel, removing null at a time*
Implementation for resolution in #438. With some clean-up in Wire, eliminating more nulls.
Up for debate is a Reg constructor with an explicit model and init, which isn't supported under RegNext/RegInit. I just did Reg.Init for now, but feel free to come up with a better API. Conceptually, Reg creates a type with explicit model, and its Init variant allows an optional initializer. Specifying init after the Reg is declared would not be easy to implement.
Also for consideration is Reg semantics. For compatibility reasons, if next and init are defined (here: RegNext(next, init)), the resulting model type has no width, but is init is defined without next, the resulting mode type has width in init, but only if it is explicitly specified. The rule …
> Deprecate old Reg with nulls constructor

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
Resolves #557 
The implementation is ugly, but I can't think of a better way and this is a feature that makes sense. The larger problem seems to be that Chisel is duplicating width inferencing work with FIRRTL, but without all the information. The larger discussion might be whether that is a good practice, as removing width propagation in Chisel can remove a lot of complexity and special cases.
> Fixed fix, allow Mux of different binary points and widths

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
Use fold(0) instead of reduce to handle the corner case.
> Fix getWidth on empty Vecs; add test

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
This also allows asUInt/asTypeOf to work properly on those Bundles,
even though zero-width wire support is lacking.
> Support Vec(0) fields in Bundles, just like Option[Data]; add test

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
Creating FixedPoint literals was throwing away width even when specifically provided.
This caused one hot muxing problems in dsptools
FixedPoint spec fixed based on error uncovered by this change
> Creating FixedPoint literals was throwing away width

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
> Make Module instantiations draw clock from Builder instead of parent

- chiselFrontend/src/main/scala/chisel3/core/CompileOptions.scala
- src/test/scala/chiselTests/CompileOptionsTest.scala
Make it relatively easy to override a single CompileOption.
> Define CompileOptions case class to support CompileOptions manipulation.

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
Using the sample_element of the created wire is incorrect because Wires have no
direction so the Wire constructed for a Vec of Module IO was constructed
incorrectly. Fixes #569 and resolves #522.
Once I figured out that this was the problem, I was confused how you could index into a wire that was of type Vec of Module io and still correctly bulk connect to the directioned inputs. It turns out that this works by using the direction of the other side of the bulk connect as a hint. This has the following two nasty consequences that should be fixed in the Binding refactor:
1. You cannot bulk connect the Bundle ports of two modules that are elements of Vecs.
1. If you try to bulk connect some Bundle port of a module (not in a Vec) to the Bundle port of another module (**is** in a Vec), and the …
> Use input element to decide if Vec of values has direction

- src/main/scala/chisel3/util/Enum.scala
- src/test/scala/chiselTests/EnumSpec.scala
Fixes #554 
Tried to changed ULit to allow zero-width wires but this seems to have exposed some bugs in Firrtl so I think a workaround is fine.
> Change Enum to emit minimum widths of 1

- README.md
On macOS, running `brew cask install sbt` from the install instructions results in:
Error: No available Cask for sbt
Looks like `sbt` moved from cask to the official homebrew repository. Correct command seems to be `brew install sbt`
Check with official [sbt documentation](http://www.scala-sbt.org/download.html)
> Fix macOS install instructions for homebrew package manager

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
I attempted to fix this in 8e4ddc62db448b613ae327792e72defca4d115d4, but
that fix was incomplete, as my additional regression test shows.  Since
then I found the root cause: 375e2b6a0a456c55298d82837d28986de6211ebc
introduced a regression for bundles containing zero-entry Vecs.  Until
zero-width UInts are supported, the zero-entry Vecs need to be flattened
out before doing asUInt/asTypeOf on a bundle.  Undoing that commit's
replacement of Data.flatten with Aggregate.getElements is the best
interim fix.
> 	Fix assignment from 0-entry Vec: add test

- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
Resolves #189 
It doesn't seem like any actual uses of Mem relied on VecLike behavior (which is to be expected - a SRAM with ridiculous ports is pretty much useless), so this is a short, sweet PR.
> Remove VecLike/IndexedSeq from Mem type

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/SeqUtils.scala
- chiselFrontend/src/main/scala/chisel3/core/UserModule.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/test/scala/chiselTests/BundleSpec.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
- src/test/scala/chiselTests/FromBitsTester.scala
- src/test/scala/chiselTests/ModuleExplicitResetSpec.scala
- src/test/scala/chiselTests/RecordSpec.scala
- src/test/scala/chiselTests/ReinterpretCast.scala
- src/test/scala/cookbook/UInt2Bundle.scala
fromBits should be replaced with asTypeOf, clock / reset Module constructors should use withClockAndReset instead.
One breaking change is that the Queue constructor (as in `new Queue(...)`, not `Queue(...)`) no longer has the override_reset with default pipe, flow options. I don't know of any use cases of this.
Compatibility layer fromBits and clock / reset Module should continue to work without deprecation warnings.
rocket-chip appears to elaborate fine with this change.
Resolves #461, #433.
> Deprecate fromBits and clock/reset constructors

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/BiConnect.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
Helps distinguish between Records/Bundles defined in Chisel._ vs.
chisel3._. Also override compilationOptions when bulk connecting
Records/Bundles defined in Chisel._. This allows Records/Bundles defined
in Chisel._ code to be correctly bulk connected in chisel3._ code.
> Add implicit CompileOptions to Record and Bundle. Fixes #495

- src/main/scala/chisel3/util/Valid.scala
- src/test/scala/chiselTests/ConnectSpec.scala
Replace ambiguous bi-connect ("<>") with mono-connect (":=") for internal Pipe wiring.
> Update internal Pipe wiring - fixes #615

- src/main/scala/chisel3/util/Decoupled.scala
Create modules by wrapping them in Module()
> Correct misleading example code

- chiselFrontend/src/main/scala/chisel3/core/ChiselAnnotation.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/package.scala
- src/test/scala/chiselTests/DontTouchSpec.scala
Adds annotation for ensuring things don't get DCE-d.
The same annotation should be used to prevent CSE and ConstProp of certain signals, but this has not yet been implemented in Firrtl.
> Dont touch

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
@chick I'm not sure how this escaped some of the mixed width/binary point tests... Basically, if I was subtracting a <<9>><<0>> number from a <<22>><<21>> number, the immediate output was right... but when the output was passed through subsequent ops, getWidth was wrong (therefore cloneType was wrong... and everything after that was wrong).
> Fixed point width inference was wrong when binary points didn't align.

- README.md
This is a follow up to https://github.com/ucb-bar/chisel3/pull/575.
To review this pull request, have a look at the `README.md` as rendered by GitHub at [https://github.com/yep/chisel3](https://github.com/yep/chisel3).
The sections `Mac OS X` and `Arch Linux` have been changed slightly.
For `Mac OS X`, use one command instead of two.
For `Arch Linux`, removed ``` in front and after the code block.
Section `(Ubuntu-like) Linux` could need some cleanup as well. The numbers shown next to the install instruction steps are not monotonically increasing (`1.`,  `1.`,  `2.`,  `1.`,  `1.`,  `1.`) and there more instances of ``` . I can have a look at that next.
> More Documentation Updates

- chiselFrontend/src/main/scala/chisel3/core/package.scala
- src/test/scala/chiselTests/IntegerMathSpec.scala
Literal creators for UInt, SInt and Bool were declared with parens, but virtually all uses of these methods do not use parens.  This is for issue #539.
This fix is an API breaking change. If anyone has used parens, e.g.
```val x = 1.U()```
This will now be an error
> Fix style of literal creators

- src/test/scala/chiselTests/RebindingSpec.scala
Looks like rebinding detection already addresses #368, this just adds a test to verify.
> Add rebinding test

- chiselFrontend/src/main/scala/chisel3/core/BlackBox.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
- src/test/resources/chisel3/BlackBoxTest.v
- src/test/scala/chiselTests/BlackBox.scala
- src/test/scala/chiselTests/Direction.scala
Resolves #282 in a hack-patchy way (direction of the top-level io object added to the DefBlackBox, since the io object itself is dropped during BlackBox generateComponent).
Also adds a test for a similar issue with regular Module direction, which may have been broken for entirely different reasons.
> Black box top-level IO fix

- build.sbt
or sbt-scoverage is updated to deal with dependencies.
Unfortunately, enabling this revives the publishing of the coreMacros and chiselFrontend jars and we don't want that.
> Disable aggregation until we can apply it selectively

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
While it is true that Analog is a chisel3 feature, for pragmatic reasons you generally want to be able to pass Analog ports through compatibility code without having to migrate your entire code base.
> Don't assign default direction to Analog in Chisel._

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
Basically, in compatibility mode direction assigning, Vecs were being treated like Records/Bundles defined in `chisel3._` code and thus not actually assigning default directions to their children.
> Give default direction to children of Vecs in compatibility code

- README.md
For a start from a plain Ubuntu you need Java first before sbt
> README: Java package

- src/main/scala/chisel3/compatibility.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
This is a partial solution to #668, it makes `.dir` correct for Module io and just errors if you try it on unbound types. I still would rather we had support for "resolved direction" so that we didn't regress on the `.dir` API. Regardless this is an improvement that solves the only uses of `.dir` that I know about. Most importantly, it's noisy about what isn't supported rather than silently wrong.
> Make .dir give correct direction for Module io in compatibility

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/BitPat.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/test/scala/chiselTests/AnalogSpec.scala
- src/test/scala/chiselTests/BetterNamingTests.scala
- src/test/scala/chiselTests/DontTouchSpec.scala
- src/test/scala/chiselTests/EnumSpec.scala
- src/test/scala/chiselTests/IOCompatibility.scala
- src/test/scala/chiselTests/MissingCloneBindingExceptionSpec.scala
- src/test/scala/chiselTests/Module.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
- src/test/scala/chiselTests/PrintableSpec.scala
- src/test/scala/chiselTests/TesterDriverSpec.scala
- src/test/scala/chiselTests/Vec.scala
- src/test/scala/examples/ImplicitStateVendingMachine.scala
- src/test/scala/examples/VendingMachineGenerator.scala
Rest of the Bindings refactor
- Separate out initialization constructors, with deprecation:
- Wire(init=...) => WireInit
- Vec(elts) => VecInit
- Require Vec, Wire, and Mem constructors to take a chisel type, not a hardware type.
- Fixes to test suite to make it pass, because it was creating Wires from hardware types
Tests with rocket-chip pending, will fix the use cases in chisel test suite soon so they stop spewing deprecated warnings.
It's likely that rocket-chip will need some fixes to match the new semantics. That list to come soon...
Part 2 (of probably 3?) in a series of PRs for #578
> More of the bindings refactor

- Makefile
- build.sbt
- project/build.properties
- project/plugins.sbt
To clean, test, and build Scala 2.11 and Scala 2.12 versions:
```shell
% sbt +clean +test +publishLocal
```
**You need to be running Java 8 to build the 2.12 version.**
> Update sbt to 0.13.16; add Scala 2.12 support.

- chiselFrontend/src/main/scala/chisel3/core/Binding.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/MultiAssign.scala
Assigning to the result of a bit slice now errors out in Chisel instead of propagating to FIRRTL.
A similar check is also performed for bulk-connect, but won't catch all cases as it is performed before sinks and sources are resolved.
Fix for #399. The error text isn't perfect (just says "Cannot reassign to read-only $this"), but at least you get a line number which should narrow down the issue. With a richer set of bindings (like a BitExtractBinding) it may be possible to generate a more specific error message (like "Cannot reassign to $this, bit extract results are read-only")
> Disallow assignment to op results, including bit slices

- src/main/scala/chisel3/util/Decoupled.scala
This warning doesn't give any line number or other information so it's not very helpful and just spams the screen for rocket-chip designs.
> Remove warning in Queue for compatibility code

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/Reg.scala
- src/test/scala/chiselTests/Module.scala
- src/test/scala/chiselTests/Vec.scala
Addresses #419 
Overview:
- cloneType is now marked (through comments only) as an internal API.
- chiselCloneType deprecated (and changed to cloneTypeFull internally, analogous to cloneTypeWidth).
- chiselTypeOf(data) introduced as the external API to get a chisel type from a hardware object
- Intended usage: cloning is an implementation detail, and chisel types and hardware objects both should act as immutable types, with operations like Input(...), Reg(...), etc returning a copy and leaving the original unchanged. Hence, the clone operations are all deprecated.
- Deletes what appears to be an unused Bundle companion object.
- Input(...), Output(...), Flipped(...) require the object to be unbound
Remaining issues:
- Several uses of chiselCloneType remain in utils and tests for …
> the cloneType and chiselCloneType hot mess 🔥

- src/test/scala/chiselTests/InvalidateAPISpec.scala
Use DontCare on `outs` not `ins` in InvalidateAPISpec.
Add additional InvalidateAPISpec tests demonstrating selective override of Strict/NotStrict behavior.
> Update InvalidateAPISpec tests.

- src/main/scala/chisel3/Driver.scala
The chisel3.Driver example was mixing in case classes as opposed to the traits that were (assumedly) intended. This corrects that.
> Fix chisel3.Driver example documentation

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/AutoNestedCloneSpec.scala
Currently, this uses an "early out" and checks the `Bundle` for inner-ness first, and returns if it can auto-clone it this way. This made testing it easier (it fixed 40 of the 70 exisiting test failures), since it avoids the problems in the rest of the body of `cloneType`.
> Add auto clone implementation for inner Bundles

- src/main/scala/chisel3/util/Conditional.scala
- src/test/scala/chiselTests/SwitchSpec.scala
While theoretically emitting independent whens for each "is" *could* make better hardware, Firrtl currently just emits a bad mux tree with lots of coverage holes. This change matches common use where each "is" is mutually exclusive and users would prefer then same result as when, elsewhen. 
@terpstra
> Change switch to emit when, elsewhen, instead of when, when

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/ChiselAnnotation.scala
- chiselFrontend/src/main/scala/chisel3/core/Printable.scala
- chiselFrontend/src/main/scala/chisel3/core/Printf.scala
- src/main/scala/chisel3/util/Conditional.scala
- src/main/scala/chisel3/util/Counter.scala
- src/main/scala/chisel3/util/Enum.scala
- src/main/scala/chisel3/util/ImplicitConversions.scala
- src/main/scala/chisel3/util/Valid.scala
- src/main/scala/chisel3/util/util.scala
Documentation needs work. This doesn't quite do enough in `chisel3.util`, but it's better.
* **Impact**
General ScalaDoc improvements.
> Some ScalaDoc improvements

- .gitignore
- src/main/scala/chisel3/compatibility.scala
- src/test/scala/chiselTests/IOCompatibility.scala
- src/test/scala/chiselTests/InvalidateAPISpec.scala
- src/test/scala/chiselTests/Printf.scala
- src/test/scala/chiselTests/RecordSpec.scala
* **Impact**
Fix some warnings
I set out with the plan to remove all warnings from compilation, but some of them are harder so I just fixed the easy ones.
> Fix a few compiler warnings

- build.sbt
- project/build.properties
- project/plugins.sbt
This requires anyone including chisel as a submodule to bump their version of sbt as well.
* **Impact**
Bump SBT version
> Bump SBT to 1.0.4 and update plugins

- src/test/scala/chiselTests/ConnectSpec.scala
- src/test/scala/chiselTests/RecordSpec.scala
- src/test/scala/chiselTests/VectorPacketIO.scala
Needed for https://github.com/freechipsproject/firrtl/pull/706
Firrtl wasn't properly checking that submodule ports were invalidated, now it will. The Firrtl PR is failing the Chisel tests without this fix.
* **Impact**
Fix tests
> Properly invalidate submodule IOs in tests

- chiselFrontend/src/main/scala/chisel3/core/BlackBox.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/core/UserModule.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
- src/test/scala/chiselTests/Util.scala
- src/test/scala/chiselTests/Vec.scala
- src/test/scala/chiselTests/When.scala
Fixes #746
Also add test for https://github.com/freechipsproject/firrtl/issues/705
Basically, for invalidating ports of a submodule, we need to use the compile options for where the module is constructed, not defined. I added this to Module.apply and used it in initializeInParent
* **Impact**
Fix bug where chisel3.Modules instantiated in Chisel.Modules would not have their inputs properly invalidated
> Add compileOptions to Module.apply, use for invalidating submod ports

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- src/test/scala/chiselTests/AutoNestedCloneSpec.scala
Also change Data.outerModule to Bundle._outerInst since it is only used
in autoclonetype. _outerInst is also Option[Object] instead of
Option[BaseModule] because the outer object could also be a Bundle.
**Note that the target of this PR is autoclonetype**
Replaces #751 
This still provides the functionality I wanted but without attempting to address the more complex problem of how to memoize autoclonetype. I did benchmark memoize-autoclonetype on a large Chisel design and it had virtually no effect so I think doing the simpler thing for now is fine.
> Add support for autoclonetype of bound, anonymous inner Bundles

- src/test/scala/chiselTests/MissingCloneBindingExceptionSpec.scala
Fixes a 2.12 issue discovered on the after-party discussion for #723, by structuring the tests to be autoclonetype friendly.
@ucbjrl can you verify that this indeed does fix things for 2.12?
* **Impact**
Text from here to the end of the body will be considered for inclusion in the release notes for the version containing this pull request.
> Change clonetype test to be autoclonetype friendly

- build.sbt
`BuildInfo.BuildTime` appears to cause sbt to always recompile `BuildInfo` to get the latest time, which causes a recompile on any package that depends on chisel3. This is quite painful for doing development on any Chisel projects. BuildTime doesn't actually appear to be in use, and removing it fixes the unnecessary recompilation issue.
* **Impact**
Changes the firrtl file header, removing the chisel build time.
Removed unused `BuildInfoOption.BuildTime`, which causes sbt to unnecessarily recompile Chisel and all dependent projects.
> Remove unused BuildInfo.BuildTime.

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/Valid.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
Short-term (until 3.1.1/3.2) patch for #765 to work better with autoclonetype
This does not attempt to give an informative error message for `MixedDirectionAggregateException `, because the exception will not be raised in all cases (for example, if the Bundle contents were not directioned), it will require significant heuristic code to catch what seems to be a very uncommon edge case, sufficient debugging information is already printed, and an API addition for 3.1.1/3.2 should remove ambiguity.
Also makes ArbiterIO cloneable through a cloneType implementation.
* **Impact**
Autoclonetype will work with Bundle that have fields defined in their constructors.
I personally don't think that's …
> Autoclonetype will clone args that are of type data

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/AutoNestedCloneSpec.scala
Use a Bundle Stack in Builder to keep track of currently open bundles, and use those as autoclonetype candidates.
On each Bundle's construction, it appends itself onto the stack.
Before each element is added to the stack, previous elements are pruned if their classes are no longer on the stack trace.
This allows Bundles guesses at enclosing Bundles for autoclonetype.
The previous proposal for traversing Bundle elements and marking them with parents doesn't work, because if you have code like
```scala
val io = IO(new Bundle {
val inner = Input(new Bundle {
val x = UInt(8.W)
})
})
```
the `Input(new Bundle{...})` is called (and attempts to bind the inner) before the outer finishes construction and before the outer `IO(...)` is called. So a solution to that problem requires that references …
> Better support for autoclonetype of nested Bundles

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/Error.scala
It appears #754 breaks more code than I thought, so this makes it a soft error (with a runtime deprecation warning - to get people to fix their stuff before we break it for real) for now.
@ucbjrl can you see if this fixes those breaking projects, and also produces informative error messages?
This additionally changes the autoclonetype errors to be more deterministic (reporting class names instead of object names) in the most common cases, to allow the deprecations manager to deduplicate warnings.
The error messages should look like:
```
[info] [0.001] Elaborating design...
[deprecated] class chiselTests.BundleWithIntArg (1 calls): Unable to automatically infer cloneType on class chiselTests.BundleWithIntArg: constructor has parameters (i, j) that are not both immutable and accessible. …
```
> Make uncloneable IO deprecated instead of error, improve error handling

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
- src/test/scala/chiselTests/UIntOps.scala
I'm not sure why it wasn't abstract.
The basic motivation is that autoclonetype doesn't work on instances of Bundle because it can't figure out what to do about the CompileOptions. It **does** however, work on `new Bundle {}` because it's an anonymous subclass with no constructor arguments. I'm really not sure why the UIntOps test didn't fail in https://github.com/freechipsproject/chisel3/pull/754. We could of course special case this and make it work, but I'm honestly not sure why Bundle isn't abstract?
* **Impact**
Make Bundle abstract
> Make Bundle abstract

- coreMacros/src/main/scala/chisel3/internal/RangeTransform.scala
- coreMacros/src/main/scala/chisel3/internal/RuntimeDeprecationTransform.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/NamingAnnotations.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Workaround for unconditional invalidation of macro classes in
incremental recompilation
* **Related issue** 
It's unclear if this is a bug in sbt incremental recompilation or an issue with our use of macros. In either case, this fixes unconditional recompilation of all scala files for projects that use chisel3 in multiproject builds (eg. rocket-chip).
sbt issue describing the problem this is working around: https://github.com/sbt/sbt/issues/3966
* **Impact**
Workaround for unconditional invalidation of macro classes in incremental recompilation
> Add companion objects to macro classes

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
Allows autoclonetype to work on Bundle classes nested in companion objects, by detecting class symbols that are static and not trying to assign an outer instance in those cases, because one isn't necessary.
**Related issue**: #785 
> Auto Clone Bundles in Companion Objects

- chiselFrontend/src/main/scala/chisel3/core/Annotation.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/BlackBoxUtils.scala
- src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
- src/test/scala/chiselTests/AnnotationNoDedup.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/DontTouchSpec.scala
- src/test/scala/chiselTests/DriverSpec.scala
This makes it much easier to write annotations. As an example, check out identity annotation from the tests:
```scala
// Annotation used in Firrtl
case class IdentityAnnotation(target: Named, value: String) extends SingleTargetAnnotation[Named] {
def duplicate(n: Named) = this.copy(target = n)
}
object identify {
// Convenient constructor for this annotation in Chisel code on Chisel InstanceIds
def apply(component: InstanceId, value: String): Unit = {
val anno = LazyAnnotation(() => IdentityAnnotation(component.toNamed, value))
annotate(anno)
// We have a transform we want to run whenever something is identified
annotate(RunTransformAnnotation(classOf[IdentityTransform]))
}
}
```
* **Related issue**
This is a companion to https://github.com/freechipsproject/firrtl/pull/721
* **Type of …
> Refactor Annotations

- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
Makes Builder.updateBundleStack a bit stricter in deciding how many stack frames to discard by additionally matching against method names and deleting stack frames at or above the frame currently being inserted.
**Related issue**: Fixes #792 
> Stricter updateBundleStack

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
- src/test/scala/chiselTests/AutoNestedCloneSpec.scala
If autoclonetype is unable to determine an outer class, this attempts to insert a null (and give a deprecation warning), preserving old behavior (in some cases) where the new behavior doesn't work.
This doesn't provide full compatibility with old autoclonetype: this does not attempt null insertion in the general first argument (if it's not an outer class reference). Reasoning is that inserting a null for an explicit argument is probably not the right thing to do, and will likely cause a difficult-to-debug NullPointerException (whereas that would be unlikely for an outer class, which is not always referenced in Bundle subclass code).
@colinschmidt would this have prevented some of your autoclonetype errors when porting code?
**Related issue**: N/A …
> Fallback null insertion for autoclonetype

- build.sbt
- src/main/scala/chisel3/ChiselExecutionOptions.scala
- src/main/scala/chisel3/tester/BackendInterface.scala
- src/main/scala/chisel3/tester/Testers2.scala
- src/main/scala/chisel3/tester/TreadleBackend.scala
**Enhancement**:
Add treadle backend intergration
**No functional change**: 
default backend is now treadle, can be optionally changed.
Functionality of backend should be the same
**Initial implementation**: proposal |  implementation
Treadle scala simulator is a faster more modern implementation of the firrtl-interpreter
> Add treadle as an additional backend to new testers2

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/main/scala/chisel3/util/OneHot.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
UIntToOH(foo, bar) fails when bar > (2^foo.getWidth).
**Related issue**: https://github.com/freechipsproject/chisel3/issues/822
**Type of change**: bug report +/- feature request
> Fix UIntToOH for output widths larger than 2^(input width)

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
This removes an unnecessary traversal, it does mean that non-bits type can end up in the `reduce` rather than the `else`, but this is an error case anyway and the error message is identical (it will, however, use different elements of the Seq to express the error, but it's the same error).
VecInit is especially slow, this PR halves the runtime of `VecInit(Seq.fill(16384)(true.B))` from ~10s to ~5s. Even 5s is atrocious considering the `Seq.fill` call takes ~30**ms** on the same machine, but this is still a big win.
Improve performance of Mux and VecInit cloning
> Remove extraneous traversal in cloneSupertype

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
The Vec constructor invokes the gen argument for each element in the
Vec. Since VecInit invokes cloneSupertype which touches every element of
the input Seq, this was an n^2 operation. Vec.apply accepts its
arguments by value so cloneSupertype is only called once. It then calls
cloneType on that once for each element in the Vec, which is constant
time reducing the overall complexity of VecInit to just n.
Speed up VecInit performance by a factor of n
> Use Vec.apply instead of new Vec in VecInit.apply

- chiselFrontend/src/main/scala/chisel3/core/Binding.scala
It's almost always forgetting `IO(_)`. I think this suggestion will help a little.
Suggest wrapping in `Wire(_)` or `IO(_)` in requireIsHardware
> Suggest wrapping in Wire(_) or IO(_) in requireIsHardware

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/DedupSpec.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
Have literals set their ref so that a name isn't allocated
This has a few implications
* Constructing a literal no longer increments `_T_` suffixes
* Internally, wrapping a literal Bits in Node(...) will work
* Literal Bools work in withReset/withClockAndReset
* Data.ref is potentially redundant
**Related issue**:  Fixes #763.
@azidar beat me to fixing #472, but this would also have fixed that issue (I added a test in this PR as well)
Literal Bools work for reset in withClockAndReset and withReset
Literals no longer increment temporary names suffix
> Literals set the ref so that they no longer get named

- src/main/scala/chisel3/util/Arbiter.scala
Documentation for example had parameters in wrong order, and was missing @param. Additionally, it was lacking a module wrapper. This has been corrected.
Documentation Fixes in Arbiter.scala
> Correcting documentation errors in Arbiter.scala

- .gitignore
Apparently I'm the only one doing development on Chisel with Emacs... This adds the usual `*~`, `.#*` Emacs backups/temporary files to the top-level `.gitignore`.
**Related issue**: N/A
- Add Emacs temporaries, backups to top-level .gitignore
> Add Emacs temporaries, backups to .gitignore

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/core/When.scala
- src/test/scala/chiselTests/When.scala
Resolves #841 
It turns out that non-local returns are an exception so we can catch this 💯 
**Related issue**:  #841 
**Impact**: no functional change (better error message)
Returns within when scopes used to give opaque error messages. Now they are caught earlier (with a stack trace) and explained in the error message.
> Catch returns from within when blocks and provide an error message

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Assert.scala
- chiselFrontend/src/main/scala/chisel3/core/BiConnect.scala
- chiselFrontend/src/main/scala/chisel3/core/Binding.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/BlackBox.scala
- chiselFrontend/src/main/scala/chisel3/core/Clock.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- chiselFrontend/src/main/scala/chisel3/core/MonoConnect.scala
- chiselFrontend/src/main/scala/chisel3/core/Printf.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- chiselFrontend/src/main/scala/chisel3/core/UserModule.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/main/scala/chisel3/testers/BasicTester.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/BitPat.scala
- src/main/scala/chisel3/util/Conditional.scala
- src/test/scala/chiselTests/BundleLiteralSpec.scala
- src/test/scala/chiselTests/ConnectSpec.scala
- src/test/scala/chiselTests/LiteralExtractorSpec.scala
**Related issue**: #805
**Impact**: API addition, API deprecation
**Development Phase**: proposed implementation
- Adds litToBigInt[Option], litToBoolean[Option], and litToDouble[Option] APIs. Deprecates previous isLit, litArg, litValue APIs, since those expose implementation details (LitArg), do not have Option variants, and may not return the type desired (BigInt/Boolean/Double).
- [internal] literals now specified in Bindings, instead of in Data subtypes.
- [internal] adds support for Bundle literals by introducing a Bundle literal binding that contains a map of leaf subelements to their literal values.
- ~[internal] ids are now persistent through runs, necessary to allow Bundle literals outside a Builder context (otherwise, a new …
> Bundle Literals Framework

- src/main/scala/chisel3/util/Math.scala
They should not be deprecated until zero-width wires actually work. See https://github.com/freechipsproject/firrtl/pull/530.
Obviously the better solution is to make zero-width wires fully work but it's been a year and it hasn't happened. Lots of people are using chisel3 now and are pretty annoyed by the deprecation warnings when they really can't switch to `log2Ceil` and `log2Floor` yet.
People have reported problems with this https://github.com/freechipsproject/chisel3/issues/652 and more have complained to me directly.
Undo the deprecation of log2Up and log2Down until zero-width wires work.
> Undeprecate log2Up and log2Down

- README.md
**Related issue**: #806
Update the recommended Verilator version in README.md
> Bump recommended Verilator version to 3.922

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
https://github.com/freechipsproject/chisel3/pull/820 changed the implementations of `ref` and `lref` to do error checking which was problematic for compatibility mode. I changed `legacyConnect` to manually use the old implementation of `Node(this)` which fixes the issue in this instance. I'm a bit worried that other examples of this can creep up so we'll have to be vigilant but I have searched for all uses of `ref` and `lref` and I can't see any other problematic cases.
Fix bug preventing the use of the output of aggregate Muxes on the rhs of a connection in compatibility mode.
> Fix use of read-only refs on rhs of connect in compatibility mode

- src/main/scala/chisel3/compatibility.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
**Related issue**: #861
`Input()` and `Output()` have been available in Chisel2 since ucb-bar/chisel2-deprecated#734. Provide support for them in the compatibility package.
> Add support for Input() and Output() and test for same.

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- src/test/scala/chiselTests/FixedPointSpec.scala
- src/test/scala/chiselTests/SIntOps.scala
- src/test/scala/chiselTests/UIntOps.scala
#820 removed what looked like vestigial code but it turns out to be a useful API that is being used in rocket-chip and elsewhere. This PR restores the ability to do "out of range" extractions on literals. FIRRTL does not allow out-of-range extraction so something like:
```scala
0.U(10) // === false.B
```
became a FIRRTL error post #820.
This PR includes tests that illustrate behavior that worked before #820 and in this PR but does not work on current master.
**Related issue**:
**Impact**: | API addition (no impact on existing code)/restoration
> Revert removal of bit extraction const prop for literals

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/InstanceNameSpec.scala
**Related issue**: #852
An alternative solution would be to address the "point of failure" - the removal of forceName in UserModule.scala
Ensure that `instanceName` can be called on any signal.
> Ensure names work for bundles and literals.

- chiselFrontend/src/main/scala/chisel3/core/package.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/test/scala/chiselTests/ImplicitConversionsSpec.scala
Remove public vals from implicit classes that can surprisingly be
invoked yet do nothing. Many implicit classes were Value Classes which
require the argument to be a public val but the avoidance of runtime
objects compared to the rest of Chisel runtime is minimal at best.
**Related issue**: NA
This PR is not source-code compatible since someone could be accidentally invoking one of these "methods". We could instead do this via a deprecation schedule.
Removed implicitly added identity methods `.data` and `.target` from `Data` and `DecoupledIO`, and removed `.x` from `String`, `Int`, `Long`, `BigInt`, and `Boolean`
> Cleanup implicit conversions

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/MixedVec.scala
- src/main/scala/chisel3/util/util.scala
- src/test/scala/chiselTests/BundleSpec.scala
- src/test/scala/chiselTests/MixedVecSpec.scala
As discussed with @jackkoenig, this implements the action items which fell out of our discussion in #844.
This PR creates a new `HeterogeneousVec` type inspired by rocket-chip's `HeterogeneousBag` or `HetVec` from dsptools. This is a dynamically indexable type like `Vec` but supports different underlying types - e.g. `myVec(0)` could return a `UInt(8.W)` while `myVec(1)` could return `UInt(16.W)`, which is not supported by `Vec`, and as shown in #844 we cannot use the Seq alternative in Bundle construction as we can in Module construction.
Additionally, as discussed in #844, this PR also adds an (optionally-overridable) warning when public `Seq[Data]` members are present so that users can get a better error message than the current one. The ability to have non-Chisel `Data` `Seq`s are …
> Heterogeneous Vec (MixedVec)

- src/main/scala/chisel3/util/experimental/Inline.scala
- src/test/scala/chiselTests/InlineSpec.scala
This adds a circuit/module/instance inlining and flattening API. This adds three new traits:
- `InlineInstance` that will inline any Module/Instance it's mixed into
- `FlattenInstance` that will flatten any Module/Instance it's mixed into
This provides Chisel-level access to existing FIRRTL annotations (`InlineAnnotation` and `FlattenAnnotation`) that map to existing FIRRTL passes/transforms (`InlineInstances` and `Flatten`).
Resolves #602
- Add instance inlining and flattening API
> Add instance inline API

- src/main/scala/chisel3/testers/TesterDriver.scala
**Related issue**: #883.
Although this should have minimal impact on existing code, it is observable.
Minimize the name mangling of output resource files.
> Inhibit aggressive resource file name mangling.

- build.sbt
- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/core/Mux.scala
- chiselFrontend/src/main/scala/chisel3/core/SeqUtils.scala
- coreMacros/src/main/scala/chisel3/SourceInfoDoc.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/BitPat.scala
**Related issue**: #872 
This migrates all `do_*` methods into a dedicated ScalaDoc group: `SourceInfoTransformMacro`. This is done using a bare trait to have inheritance propogate the group description (as opposed to a ScalaDoc macro).
This also adds API documentation and additional groups: `Arithmetic`, `Comparison`, and `Connect`. 
~This includes two small (apparent?) bug fixes where both `SInt` and `FixedPoint` were missing their `do_unary-` and `do_unary-%` methods. These were provided as `unary-` and `unary-%`. I _think_ this was a mistake, but I'm not entirely sure why it wasn't tripping anything.~
- Improve API documentation using ScalaDoc groups
> API Documentation Improvements

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
The litOption field currently has no type that can be inferred. Some subtypes override it and give it a type, but the original declaration should have a type so things like bundles can override it.
> Give type annotation to litOption.

- src/main/scala/chisel3/Driver.scala
This adds a utility method to Chisel's `Driver` for writing the annotations associated with a specific Chisel circuit to a file.
Patch 2 for https://github.com/freechipsproject/firrtl/issues/764 implementation.
This can be merged in any order before F764.4+.
> [F764.2] Add dumpAnnotations method to Driver

- src/main/scala/chisel3/util/Decoupled.scala
**Impact**: no functional change (probably)
Modified ReadyValidIO (also used in DecoupledIO) to set the data payload (.bits) to don't care when a no enqueue action (noenq) is called. This will clean up the frequently used idiom:
````scala
c.noenq
when( cond) {
c.enq( data)
}
````
This currently needs to be written as:
````scala
c.noenq
c.bits := DontCare
when( cond) {
c.enq( data)
}
````
It is possible that `noenq` was used like this in some existing code:
````scala
c.bits := 47.U
c.noenq
when( cond) {
c.valid := true.B
}
````
If this was the case, then the PR will change the behavior of the circuit.
The comment for `noenq` is:
````
/** Indicate no enqueue occurs. Valid is …
```
> Modify ReadyValidIO noenq to set the data payload to DontCare.

- chiselFrontend/src/main/scala/chisel3/core/BlackBox.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/test/scala/chiselTests/BlackBox.scala
- src/test/scala/chiselTests/ExtModule.scala
- src/test/scala/chiselTests/Module.scala
Adds `modulePorts(module: BaseModule): Map[String, Data]` to `experimental.DataMirror`. This provides the necessary interfaces to split out Testers2 development (#866) into its own repo.
Points which may or may not warrant discussion:
- This returns things as an unordered Map. Are there ever cases where we want to preserve ordering? Alternatives would be either a ListMap or a Seq.
- BlackBox has its `io` contents flattened out in the return here, consistent with the generated component. Note that using `io` directly on a BlackBox can be illegal in some cases, because the top-level object actually does not get emitted (as an artifact of dropping the `io_` prefix in the pre-ExtModule/MultiIOModule dats). The only alternative would be to error out if a BlackBox is passed in.
**Related …
> Add DataMirror.modulePorts

- Makefile
- build.sc
This does quite a few things, each commit is an individual piece of work.
An important addendum to the commit "Support firrtl as either an ivy and a module dependency" is that it nests the coreMacros and chiselFrontend modules within the chisel3 Module which makes it possible to set `firrtlDep` once and thus change it for the full build.
@ucbjrl I manually inspected that this preserves mono-jar properly, but can you verify?
> Mill ivy or module dep

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Clock.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/MonoConnect.scala
- chiselFrontend/src/main/scala/chisel3/core/StrongEnum.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/main/scala/chisel3/internal/firrtl/Converter.scala
- src/main/scala/chisel3/internal/firrtl/Emitter.scala
- src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/util/Conditional.scala
- src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
- src/test/scala/chiselTests/StrongEnum.scala
- src/test/scala/cookbook/FSM.scala
This is an implementation of the strongly-typed enums proposed in #885. It satisfies all the conditions laid out there, along with these extra features:
- UInts can be cast into enums
- The user can retrieve a list of all valid enum values through the `StrongEnum.all` function
The enums do have two primary caveats that should be considered:
- An enum class must be "static" in the Java sense. In other words, you can't define an enum class inside of another class, although you can define it globally, or in an object, as in this example:
```scala
object FSM { // The companion object to a module named FSM
class State extends EnumType
object State extends StrongEnum[EnumType] {
val s1, s2 = Value
}
}
```
- Casting non-literal UInts to enums is an inherently dangerous procedure, because Chisel …
> Strong enums

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/test/scala/chiselTests/Module.scala
Fixes #911 
This makes `BaseModule.name` lazy (previously eager) so that a Module's `desiredName` can be a function of some property associated with a sub-instance.
- Make BaseModule.name lazy to enable better name parameterization, e.g., a module name can now be a function of a submodule name
> Make BaseModule.name lazy

- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
Quickfix for LoadMemoryTransform that gets this to work with Instance
Annotations. The new Instance Annotations caused a corner case where a
LoadMemoryAnnotation would be duplicated (via update/renaming) and the
resulting annotation would differ from the original in only their
originalMemoryNameOpt field. This corrects that by having the
ChiselLoadMemoryAnnotation also emit the originalMemoryNameOpt field where
it did not previously.
First part of a fix for freechipsproject/firrtl#922.
Signed-off-by: Schuyler Eldridge <schuyler.eldridge@ibm.com>
> Fix LoadMemoryTransform for Instance Annotations

- chiselFrontend/src/main/scala/chisel3/core/package.scala
- src/test/scala/chiselTests/LiteralExtractorSpec.scala
I think there are cases where it's cleaner to use `0.B` and `1.B` instead of `false.B` and `true.B`, especially as testers is going to use chisel literals.
(the use case is in testing interface code, where signal levels are usually specified as 0 and 1 instead of false and true)
**Development Phase**: proposal, implementation
> Add BigInt / Int to Bool conversion (0.B, 1.B)

- src/main/scala/chisel3/util/Decoupled.scala
Previously, io.count would report 2 when it should've reported 1.
**Related issue**: https://github.com/freechipsproject/chisel3/issues/917
Queues with depth 1 now correctly report how many entries are present.
> Fix Queue.io.count when entries=1

- README.md
Replaces the 'Chisel3' header at the top entirely.
> Add Chisel logo to README

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/Direction.scala
Fixes #893
The added tests test way more than just this fix, I just decided to test several (working) similar things with them
Fix bug where Chisel might lose the direction of elements of Vecs
> Make Vec cloneType keep directions of elements

- build.sbt
- project/build.properties
Bump sbt version to 1.2.6
Update dependency versions
> Bump sbt to 1.2.6; update dependencies

- chiselFrontend/src/main/scala/chisel3/core/Assert.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Printf.scala
- coreMacros/src/main/scala/chisel3/SourceInfoDoc.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/testers/BasicTester.scala
- src/main/scala/chisel3/util/Bitwise.scala
- src/main/scala/chisel3/util/ImplicitConversions.scala
- src/main/scala/chisel3/util/OneHot.scala
- src/test/scala/chiselTests/AsTypeOfTester.scala
- src/test/scala/chiselTests/Assert.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
- src/test/scala/chiselTests/UIntOps.scala
- src/test/scala/cookbook/UInt2VecOfBool.scala
- src/test/scala/examples/VendingMachineGenerator.scala
* toBools -> asBools (toBools deprecated)
* toBool -> asBool (toBool deprecated)
* Fix chaining of apply after `.asBools`
> asBools, asBool, and chained apply on asBools

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
Emit it as
tail(sub(x, y), 1)
rather than
tail(asUInt(sub(x, y)), 1)
This is semantically equivalent, but gets rid of a bunch of Firrtl text.  It also gets rid of a bunch of Verilog, because Firrtl is capable of  pattern-matching the new expression into SubWrap.  The effect is that  we now get
wire [4:0] in;
wire [4:0] res;
assign res = 5'h0 - in;
instead of
wire [4:0] in;
wire [5:0] _T_40;
wire [5:0] _T_41;
wire [4:0] res;
assign _T_40 = 5'h0 - in;
assign _T_41 = $unsigned(_T_40);
assign res = _T_41[4:0];
Improved code generation for modular UInt subtraction.
> Improve quality of code generation for UInt.-%

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/WidthSpec.scala
As part of the Bundle literals framework PR, (https://github.com/freechipsproject/chisel3/pull/820) it appears a minor code refactor accidentally changed the width inference semantics of `WireInit` and `RegInit`.
For example
```scala
val wire1 = Wire(UInt(8.W))
val wire2 = WireInit(wire1)
```
prior to #820, wire2 would have it's width inferred. After #820, wire2 gets its width set to 8.
This PR restores the previous behavior and adds some tests that pass prior to #820, fail on current master, and pass on this branch
I noticed this issue while trying to bump Chisel because it changed the functionality of the output FIRRTL ever so slightly but enough to make simulations fail.
Future work is to make similar tests that show and check the width inferencing semantics for other constructors (eg. …
> Fix width inferencing issue

- build.sbt
**NOTE**: A `publishLocal` should replace the downloaded `.ivy2/cache/...` version with a pointer to the `.ivy2/local/...` version. To force re-fetching of the Sonatype repository version, you should delete both `.ivy2/{cache,local}/...` versions.
> Add explicit Sonatype resolvers so SNAPSHOTs can be found remotely.

- src/main/scala/chisel3/Driver.scala
JDK 11 `java.lang.String#lines` conflicts with Scala `StringOps#lines`.
This has been fixed in scalac 2.12.8 but projects using 2.11 in their
cross-build need the `Predef.augmentString` patch.
[Scala bug & fix reference](https://github.com/scala/bug/issues/11125)
> Fix build error due to scala bug #11125

- src/test/resources/chisel3/VerilogVendingMachine.v
Running the tests with Verilator 4.008 (which Ubuntu apparently updated for me) will fail with a `PROCASSWIRE` error due to an old Verilog test resource using this. Apparently the Verilog standard disallows procedural wire assignments and Verilator decided to hard align with this. This has odd implications as it effectively means that the `always @ *` construct is effectively disabled. It's weird, but whatever.
See: https://www.veripool.org/news/246-Verilator-Verilator-4-008-Released
This is a test-only fix, so no release notes.
> Avoid procedural wire assignment in test resource

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/Namer.scala
- src/test/scala/chiselTests/NamingAnnotationTest.scala
I noticed that chiselName wasn't naming some things that reflective naming does name.  This is because chiselName only looks for HasId, whereas reflective naming will dig through Options and Iterables to look for a HasId.  This PR changes chiselName to use the same algorithm as reflective naming.
> Improve chiselName to name Iterable[Data], Option[Data]

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
In the case that the width is known, we can emit one fewer Firrtl node.
This obviously synthesizes the same way, but compiles/simulates faster.
> Generate better code for UInt.andR

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
It performs the operation (x === 0.U), just like in C.   The scaladoc incorrectly described it as performing the operation !x(0).  (Obviously, these are equivalent for Bool, but not for UInt in general).
> Fix scaladoc for UInt.unary_!

- build.sbt
- project/plugins.sbt
I don't know if this GhpagesPlugin is important to anyone, but I'm proposing removing it from firrtl and Chisel3 to eliminate some friction it is causing in another project.
If this plugin is in fact useful to anyway, I would like to make it configurable so that it may be disabled where it is not needed.
**Related issue**: https://github.com/freechipsproject/firrtl/pull/979
Removed sbt dependency on GhpagesPlugin.
> Remove GhpagesPlugin.

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Mux.scala
- src/test/scala/chiselTests/MuxSpec.scala
- src/test/scala/chiselTests/Vec.scala
Adds general support for DontCare to cloneSupertype, and add special case handling in Mux for the chisel style (DontCare object) to firrtl style (invalidate wire) conversion. Not sure how to actually test the DontCare case, but this tests the other case.
Note that it will still be difficult to use DontCare in a Mux, because Scala doesn't understand that DontCare should be a bottom type of Data, so it will infer the output type of Mux to be the common supertype of DontCare (which extends Element) and your Data, which usually means you'll get a Element or Data out, instead of something more specific eg UInt.
This also kind of feels like a game of whackamole, since DontCare support may be subtly broken in other contexts, though I guess it also makes no sense to do something like `1.U + …
> Support DontCare in Mux and cloneSupertype

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- src/main/scala/chisel3/package.scala
- src/test/scala/chiselTests/CloneModuleSpec.scala
**Related issue**: #618 
**Type of change**:  feature request
**Development Phase**: proposal &&  implementation
**EXAMPLE USAGE**
```
val q1 = Module(new Queue(...))
val q2_io = CloneAndGetIO(q1)("io").asInstanceOf[q1.io.type]
q2_io.enq <> q1.io.deq
```
**Release Notes**:
This is a port of Rocket Chip's `CloneModule` functionality (which returns a `Record`) as `chisel3.experimental.CloneAndGetIO`. This simplifies the implementation drastically, as it can live inside chisel3. The idea here is that there may be some desire to have this live alongside a full `CloneModule` implementation that returns a `Module`, as the API for using the `Record`-returning version is much simpler for basic use cases.
**Pros**: it makes the simple use cases …
> RFC: Add Rocket Chip-style clonemodule as CloneAndGetIO to experimental

- src/main/scala/chisel3/util/experimental/BoringUtils.scala
- src/test/scala/chiselTests/BoringUtilsSpec.scala
- Fix BoringUtils.addSinks bug where sinks would still be
deduplicated even if the user or BoringUtils.bore requested
that they not be
- Correct BoringUtils.{addSinks, addSources} parameter name from
dedup to disableDedup
> Boring utils dedup fix

- chiselFrontend/src/main/scala/chisel3/core/package.scala
@jackkoenig does this fix rocket-chip?
**Related issue**: Fixes bug in #994
**Impact**: compatibility for the foolish
Don't import from chisel3.core. It's not part of the public API. You'll have a bad day when we muck with the internals, because you'll need to update your code. Unless that's your thing, or you're doing some kind of bleeding edge stuff and are OK with breakages. In which case, carry on.
> Import aliases for chisel3.core

- src/test/scala/chiselTests/QueueSpec.scala
**Development Phase**: Implementation
Tests for Queues.
> Queue Tests

- src/main/scala/chisel3/util/Valid.scala
This adds Scaladoc to `Valid` and `Pipe`. This also adds a requirement that the `Pipe` latency is >= 0. Without this, you wind up with a stack overflow on nonsensical negative latencies.
- Add Scaladoc for chisel3.util.{Pipe, Valid}
- Add requirement that Pipe latency is >= 0
> Valid/Pipe Improvements: Scaladoc, latency requirement

- src/main/scala/chisel3/util/TransitName.scala
- src/test/scala/chiselTests/TransitNameSpec.scala
Adds some verbose documentation from a test case that I wrote. This could likely be converted to an actual test of TransitName.
This also removes the unneeded "import everything in chisel3". It's not needed here.
- Update documentation for util.TransitName
> Add Scaladoc for chisel3.util.TransitName

- src/main/scala/chisel3/util/Math.scala
- src/main/scala/chisel3/util/MixedVec.scala
Adds recommended usage and examples to the Math utils (log2* and isPow2).
Slight improvement to documentation for MixedVec, primarily deduping method ScalaDoc into the object / class ScalaDoc, and clarifying wires / types.
**Related issue**: #411 
Scaladocs for Math (log2*, isPow2) and MixedVec.
> ScalaDocs improvement for utils Math, MixedVec

- README.md
Update recommended Verilator version to 4.006 in README
> Update recommended verilator version to 4.006

- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
**Related issue**: freechipsproject/firrtl#1055
Don't assume that the `hexOrBinary` field has a `.toString` method that returns "h" or "b".
> Decouple implementation details from LoadMemoryAnnotation.

- src/main/scala/chisel3/util/Valid.scala
This switches to using `TransitName` for name generation inside the `Pipe` factory. This then uses the suffix of `Pipe_valid` and Pipe`_bits` for the delayed versions of signals. I'm open to an alternative naming convention if there are any suggetsions. Oddly, from what I can tell, `chiselName` wasn't helping with naming before.
```scala
class Foo extends MultiIOModule {
val in = IO(Input(Valid(UInt(2.W))))
val bar = Pipe(in, 2)
}
```
Before:
```
circuit PipeSpecFoo1 :
module PipeSpecFoo1 :
input clock : Clock
input reset : UInt<1>
input in : { valid : UInt<1>, bits : UInt<2>}
reg _T : UInt<1>, clock with :
reset => (reset, UInt<1>("h0")) @[Valid.scala 121:22]
_T <= in.valid @[Valid.scala 121:22]
reg _T_1 : UInt<2>, clock with :
reset => (UInt<1>("h0"), _T_1) @[Reg.scala 11:16]
when …
```
> Generate better names for Pipe via TransitName

- chiselFrontend/src/main/scala/chisel3/core/SeqUtils.scala
- src/test/scala/chiselTests/PopCount.scala
An artifact of SeqUtils.count's implementation strategy makes its result one bit too wide, except for the case that the number of inputs is exactly a power of two.
`count(Seq(b, c))` expands to `b +& c`, which is 2 bits wide, as you'd hope.
`count(Seq(a, b, c))` expands to `count(Seq(a)) +& count(Seq(b, c))`, which is 3 bits wide, even though only 2 bits are needed to represent the result.
A simple fix is to truncate the sum at every step.
Reduce width of PopCount output to minimal possible value.
> Tighten inferred width for PopCount

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
As the title says, changes the logic to check for reference equality, which is really what is meant anyways.
The partial root cause of the bug is that printing the Circuit includes printing all the Ports, which invokes the new code that tries to detect if a Data is a Port of a Module. This calls equals (through ==) on the MixedVec object, but it's not the overloaded equals as defined in MixedVec.scala (at least by a println() trace), nor does it appear to invoke Data.equals either. So I've really no clue what MixedVec.equals is doing (other than not the right thing - and for some reason trying to invoke the DynamicNamingStack), but this prevents the wrong equals from being called in the first place.
**Related issue**: Resolves #1027
**Impact**: no functional …
> Change == to reference equality (eq) in Data print

- src/main/scala/chisel3/util/MixedVec.scala
`@chiselName` can only be invoked by things running in a Builder context. In this case, it seemed to have inserted naming stack (unavailable outside a Builder context) pushes and pops into each function, which would cause it to assert out in a completely unhelpful way.
I also don't think `chiselName` does anything useful inside MixedVec?
**Related issue**: Fixes #1031
> Remove @chiselName from MixedVec

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
Goes with `litValue`
Undeprecate `Data.isLit`
> Undeprecate isLit

- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- chiselFrontend/src/main/scala/chisel3/internal/Namer.scala
- coreMacros/src/main/scala/chisel3/internal/sourceinfo/NamingAnnotations.scala
- src/test/scala/chiselTests/NamingAnnotationTest.scala
Exactly as the title says. If there is no Builder context upon entering a naming annotated function, all the naming calls become nops. It does check that the Builder context remained stable at function entry and exit.
**Related issue**: Fixes #1046
> Allow naming annotation to work outside builder context

- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
When running multiple tests in parallel, we occasionally experience JVM hangs which appear to be due to static initialization deadlock when `Builder` initialization collides with `chisel3.package` initialization of the `DontCare` value.
Let the initialization in `chisel3.package` take responsibility, and assume this will happen before any user code creates (and owns) the `DontCare` element.
See:
- http://ternarysearch.blogspot.com/2013/07/static-initialization-deadlock.html
- https://bugs.openjdk.java.net/browse/JDK-8037567
- https://stackoverflow.com/questions/28631656/runnable-thread-state-but-in-object-wait
> Try to eliminate JVM hang due to static initialization deadlock

- chiselFrontend/src/main/scala/chisel3/core/Data.scala
Force clients to access `DontCare` through the chisel3 package to ensure it's created as a chisel3 object and not a client object.
**Related issue**: #1053
`chisel3.core.DontCare` should have been private to `chisel3` to prevent client code from referencing it directly and creating the object. This corrects that short-coming.
> Make core.DontCare private to chisel3

- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/main/scala/chisel3/internal/firrtl/Converter.scala
- Introduce internal helper `castToInt`, which issues an error when the input
BigInt can't be represented as Int.
- Use `castToInt` wherever we were using `toInt` in a potentially unsafe way.
Technically, this is an API modification, since previously users could have done such things as `UInt.apply(BigInt.pow(2, 32))`, which would have silently wrapped around and extracted bit 0.
> Avoid silently truncating BigInt to Int

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/Mem.scala
Relies on https://github.com/freechipsproject/firrtl/pull/1075
**Related issue**: Fixes https://github.com/freechipsproject/chisel3/issues/856
Support memories larger than 2^(31)-1 (not supported by most simulators)
> Change size of memories from Int to BigInt

- chiselFrontend/src/main/scala/chisel3/core/Mem.scala
- src/test/scala/chiselTests/Mem.scala
This is necessary to support code that imports an implicit conversion from Int to UInt
I thought they were unnecessary in #1076 but I was wrong.
**Impact**: API ~addition~ restoration (no impact on existing code)
> Add back Int forms of Mem do_apply methods

- chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
- src/test/scala/chiselTests/AsTypeOfTester.scala
Closes #1075.
**Related issue**: #1075 
> Make asTypeOf work for bundles with zero-width fields.

- src/main/scala/chisel3/Driver.scala
Many of the methods in Driver are undocumented and require a look through the source to understand. This PR adds documentation to make it easier to understand what they are doing.
**Release Notes**:
- Improves ScalaDoc documentation for methods in Driver.
> Expand upon ScalaDoc in Driver

- src/main/scala/chisel3/util/random/FibonacciLFSR.scala
- src/main/scala/chisel3/util/random/GaloisLFSR.scala
- src/main/scala/chisel3/util/random/LFSR.scala
- src/main/scala/chisel3/util/random/PRNG.scala
- src/test/scala/chiselTests/LFSR16.scala
- src/test/scala/chiselTests/util/random/LFSRSpec.scala
- src/test/scala/chiselTests/util/random/PRNGSpec.scala
Changes the internal state of PRNG to use Vec[Bool] instead of UInt.
This fixes an @aswaterman identified future problem with asynchronous
reset.
A register with an asynchronous reset can only be reset to a literal.
Previously, an LFSR would store state as a UInt. If it was not
parameterized with a seed it should have its least significant bit
reset to something to avoid locking up. It's ideal to not reset the
full UInt (better test coverage, decreased reset fanout). However,
it's difficult to only reset one bit of a UInt. Conversely, it's
trivial to reset one bit of a Vec[Bool]. This also moves PRNG/LFSR
closer to a canonical representation of their internal state, i.e.,
it's natural to think of generalizing Vec[Bool] to arbitrary finite
fields (Vec[A <: Field]) whereas UInt is tightly …
> LFSR/PRNG Asynchronous Safety, Use Vec[Bool] to store internal state

- src/main/scala/chisel3/util/LFSR.scala
- src/test/scala/chiselTests/LFSR16.scala
This fixes LFSR16, which after #1088 ignored its `increment` argument and began incrementing unconditionally.
> Fix LFSR regression

- build.sbt
- chiselFrontend/src/main/scala/chisel3/core/Annotation.scala
- chiselFrontend/src/main/scala/chisel3/core/Bits.scala
- chiselFrontend/src/main/scala/chisel3/core/Data.scala
- chiselFrontend/src/main/scala/chisel3/core/Reg.scala
- coreMacros/src/main/scala/chisel3/SourceInfoDoc.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/util/Valid.scala
- src/main/scala/chisel3/util/experimental/BoringUtils.scala
- src/main/scala/chisel3/util/experimental/Inline.scala
- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
This is a smattering of improvements to Scaladoc:
1. This modifies `build.sbt` to include links to the GitHub sources in each generated Scaladoc page. This will use `master` for any `*-SNAPSHOT` and `v$version` for any versioned release.
2. `@usecase` is deprecated in Scala 2.13.x. This removes the six uses of `@usecase`. See: https://github.com/scala/scala/pull/7462
3. This cleans up `loadMemoryFromFile` by moving its documentation to the object as opposed to the `apply` method. Miscellaneous fixes are applied related to grammar, captialization, and addition of an outbound link to the associated tests.
4. All warnings stemming from Scaladoc generation are cleared. This was primarily related to fixing bad links.
Note: to fix ambigous method calls (e.g., which `Driver.execute` do you mean …
> Miscellaneous Scaladoc Cleanup

- chiselFrontend/src/main/scala/chisel3/core/Module.scala
- chiselFrontend/src/main/scala/chisel3/core/MultiClock.scala
- chiselFrontend/src/main/scala/chisel3/core/RawModule.scala
- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/Clock.scala
Fixes bug identified in Issue #1041 
A user defining defining a `Module` with a clock and no reset cannot use the 
`withClock(clock) { val r = RegNext(...) }`. Attempting to do so will generate an exception saying
there is no reset even though no reset is required.
- refactor ClockAndReset
- now has `clockOpt: Option[Clock]` and `resetOpt: Option[Reset]` constructor params
- convenience methods clock and reset tries to deref the option
- ClockAndReset.empty is factory method for (None, None)
- In Builder
- forcedClock does not check resetOpt now
- forcedReset does not check clockOpt now
- withClock no longer looks at resetOpt
- withReset no longer looks at clockOpt
- Module starts with empty ClockAndReset
Internal API change.
> RawModule with no reset should be able to use withClock method.

- build.sc
Note: right now this still doesn't work (not caused by this PR) since FIRRTL snapshots hasn't been bumped yet.
> Include snapshots by default in mill

- src/main/scala/chisel3/ChiselExecutionOptions.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselCli.scala
- src/main/scala/chisel3/stage/ChiselOptions.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/package.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala
- src/main/scala/chisel3/stage/phases/Checks.scala
- src/main/scala/chisel3/stage/phases/Convert.scala
- src/main/scala/chisel3/stage/phases/DriverCompatibility.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/main/scala/chisel3/stage/phases/Emitter.scala
- src/main/scala/chisel3/stage/phases/MaybeFirrtlStage.scala
- src/test/scala/chisel3/stage/phases/DriverCompatibilitySpec.scala
- src/test/scala/chiselTests/DriverSpec.scala
- src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala
- src/test/scala/chiselTests/stage/ChiselOptionsViewSpec.scala
- src/test/scala/chiselTests/stage/phases/AddImplicitOutputAnnotationFileSpec.scala
- src/test/scala/chiselTests/stage/phases/AddImplicitOutputFileSpec.scala
- src/test/scala/chiselTests/stage/phases/ChecksSpec.scala
- src/test/scala/chiselTests/stage/phases/ConvertSpec.scala
- src/test/scala/chiselTests/stage/phases/ElaborateSpec.scala
- src/test/scala/chiselTests/stage/phases/EmitterSpec.scala
This PR provides a reimplementation of the Chisel Driver as a `Stage`. This involves three major additions/modifications:
1. Addition of a `chisel3.stage` package that implements `ChiselStage`
2. Addition of tests for `chisel3.stage`
3. Modification of `chisel3.Driver` to use `ChiselStage` with a compatibility layer
For a more exhaustive introduction to Stage/Phase, see freechipsproject/firrtl#1005.
- This is an `implicit object` and can't be deprecated. Instead it's now `private [chisel3]`
This PR 
1. Add expected annotations
2. Write the CLI
3. Add the `xOptions` class (which is not a case class)
4. Write an options view to construct your …
> Chisel stage

- README.md
- SETUP.md
Note this will be merged onto the branch for #1106, not master.
This is by no means the way it has to be, but just my take on what I think the README should look like, with the goal of addressing as wide an audience as possible. Bikeshedding (and it probably does need a few copyediting passes) and discussion is welcome!
Main changes:
- The overview / introduction text is more focused from a user's point of view: what does Chisel provide them, instead of what Chisel is.
- The code examples are written with the Verilog-analogue first, and generators second. The idea is to provide something familiar (but still better, hopefully) while the writing style should keep readers reading onto the second example which shows the generator approach and usage.
- Note: it would be nice to have an …
> Ducky readme changes

- .circleci/config.yml
- SETUP.md
Now that ucbbar/chisel3-tools has Verilator 4.016, use that for tests.
Reverting this PR will revert back to Verilator 4.006
Now that [ucbbar/chisel3-tools](https://github.com/ucb-bar/chisel-ci-infra/blob/master/chisel3-tools/Dockerfile) has Verilator 4.016, use that for tests.
> Use Verilator 4.016

- chiselFrontend/src/main/scala/chisel3/internal/MonoConnect.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/VerifyConnectionProperties.scala
Add exceptions for attempts to mono connect `Analog` to anything other than `DontCare`.
Provide explicit type to `ChiselPropSpec.generatorDrivenConfig`.
Add VerifyConnectionProperties tests to verify connection properties and build spreadsheets of same.
> Analog dont care+no analog mono+connection properties

- chiselFrontend/src/main/scala/chisel3/Bits.scala
Change `Num.+` Scaladoc to state that this is not a growing
addition. Note that this is problematic either way as this macro is
resolved to an abstract method. Classes implementing this typeclass
are technically free to violate what we put in the Scaladoc here.
h/t @kammoh
- See: https://gitter.im/freechipsproject/chisel3?at=5d38a6b935e05c099394c591
An alternative would be to remove the width documentation in the Scaladoc.
> Fix Num.+ Scaladoc

- chiselFrontend/src/main/scala/chisel3/core/package.scala
I was looking at trying to index things that were deprecated and noticed that the core deprecation messages (introduced by #1078) should be "3.2" and not "3.3". My understanding is that the second argument of `@deprecated` is the version since which things were deprecated, not the version when things will disappear. I think this was your intention @ucbjrl?
> Core deprecation "since" should be "3.2" not "3.3"

- README.md
> Fix shift register in README

- src/test/scala/chiselTests/CompatibilitySpec.scala
The checks in the `Dummy` module inside the `CompatibilitySpec` were never actually running. This fixes these up to work and runs the test.
**Type of change**: bug report | other enhancement
> Fixup and enable Dummy CompatibilitySpec test

- src/test/scala/chiselTests/CompatibilitySpec.scala
This adds tests to make sure that compatibility mode features which are currently deprecated will be preserved going forward.
Most of these are relatively light tests that only check the return type of some method. However, it provides some interlocking to make sure that PRs like #1139 can be done safely while preserving the compatibility mode.
**Related issue**: https://github.com/freechipsproject/chisel3/pull/1139#issuecomment-516657292
> Improve compatibility mode testing

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/Annotation.scala
- chiselFrontend/src/main/scala/chisel3/Bits.scala
- chiselFrontend/src/main/scala/chisel3/Data.scala
- chiselFrontend/src/main/scala/chisel3/Mem.scala
- chiselFrontend/src/main/scala/chisel3/Module.scala
- chiselFrontend/src/main/scala/chisel3/RawModule.scala
- chiselFrontend/src/main/scala/chisel3/Reg.scala
- chiselFrontend/src/main/scala/chisel3/core/package.scala
- chiselFrontend/src/main/scala/chisel3/experimental/package.scala
- chiselFrontend/src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/util/BitPat.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/Enum.scala
- src/main/scala/chisel3/util/LFSR.scala
This removes most deprecations `since` before `"3.2"`. Notably `!=` is not removed.
Anything deprecated that was previously available via compatibility mode (`import Chisel._`) that is removed by this PR is migrated to live inside the compatibility mode.
The `!=` operator, while deprecated for a long time, is difficult to move into the compatibility mode for reasons elucidated below.
When removing something and adding it to the compatibility mode, there are two approaches:
- Add the removed functionality back in using an `implicit class`
- Define a new type hierarchy inside the compatibility mode
Implicit classes don't work when trying to override methods (and apparently for `!=`). Certain Chisel3 types are `sealed` which limits inheritance as a path to add functionality. Additionally, …
> Remove Deprecations since before 3.2

- src/main/scala/chisel3/util/random/LFSR.scala
- src/main/scala/chisel3/util/random/PRNG.scala
Muxes and resets are only isomorphic with synchronous reset.  Use a reset
instead of a conditional to make this async-reset-safe.
Unfortunately, the cleanest fix for this involves resetting some of the bits to DontCare, which is not currently optimized by Firrtl (https://github.com/freechipsproject/firrtl/issues/1149).  Merging this as-is will therefore cause a performance regression.
> Avoid when(reset) construct in LFSR

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
Adds a check that a Vec being indexed by a UInt is, in fact, a
hardware type. This includes a test for this.
h/t @schoeberl
cc: @aswaterman 
Consider the following where a Chisel type Vec is indexed by a hardware type:
```scala
property("Indexing a Chisel type Vec(Vec) should give a sane error message") {
assertThrows[ExpectedHardwareException] {
elaborate{
new Module {
val io = IO(new Bundle{})
val foo = Vec(2, Bool())
foo(0.U) := false.B
}}
}
}
```
On master, this will generate:
```
[info] - Indexing a Chisel type Vec(Vec) should give a sane error message *** FAILED ***
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:349)
[info]   at scala.None$.get(Option.scala:347)
[info]   at chisel3.Data.direction(Data.scala:343)
[info]   at …
```
> Require target is hardware for Vec.apply(a: UInt)

- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala
- src/main/scala/chisel3/stage/phases/Checks.scala
- src/main/scala/chisel3/stage/phases/Convert.scala
- src/main/scala/chisel3/stage/phases/DriverCompatibility.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/main/scala/chisel3/stage/phases/Emitter.scala
- src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
- src/main/scala/chisel3/stage/phases/MaybeFirrtlStage.scala
This uses the new `firrtl.options` Dependency API to determine a valid `Phase` ordering instead of statically encoding one. This supersedes #1080.
This primarily consists of:
- Adding prerequisites and dependencies to every `Phase`
- Defining `ChiselStage` to use a `PhaseManager` internally
- Defining `Driver` to user a `PhaseManager` internally
Note: this PR is very explicit in terms of targets. You can get away with being more terse, but after going through this with FIRRTL, it seems that it's clearer to define all the `targets` you want to run as opposed to hiding the targets from the user.
While support does not yet exist for this, it should be trivial to start thinking about a `RunChiselPhaseAnnotation` that is injected into `ChiselStage`.
**Type of change**: …
> Dependency API (take 2)

- README.md
I changed the API directory structure to match the old chisel.eecs.berkeley.edu layout (to avoid breaking existing links and search engine results). This, however, re-breaks the API links in the chisel3 README.
This PR corrects the two API links in the README.
**Type of change**: documentation | other enhancement
> Switch to new API links

- src/main/scala/chisel3/util/Decoupled.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
- src/test/scala/chiselTests/QueueSpec.scala
Incredibly, this didn't work (in `import chisel3.`) and may never have worked.
This really ought to go in to 3.2
> Fix Queue.apply for size 0 in chisel3._ code

- src/main/scala/chisel3/util/Decoupled.scala
FIRRTL barfs on negative and zero-sized memories
**Type of change**:  other enhancement
**Impact**: no functional change (errors in FIRRTL currently)
Improve error reporting on invalid Queue sizes
> Add requirements to Queue class

- README.md
- Scaladoc for "latest" is 2.11, so use a 2.11-style link
- Use full path for SETUP.md
- Switch migration guide to point to website version over wiki
Signed-off-by: Schuyler Eldridge <schuyler.eldridge@ibm.com>
> More README.md fixes

- src/main/scala/chisel3/util/Mux.scala
- src/test/scala/chiselTests/MuxSpec.scala
@seldridge, this shows what I was talking about with the `0.U` vs `4096.U` and the false "full case" detection.
Fortunately, we don't have to deal with sometimes-negative `SInt` mapping keys :)
> Use masked litOption comparisons to detect exhaustive MuxLookup

- chiselFrontend/src/main/scala/chisel3/Module.scala
- src/test/scala/chiselTests/DataPrint.scala
This implements the fix proposed in #1166. 
In effect, this strips package names, object names, and outer classes from inner classes when computing the `desiredName`. This mirrors the behavior of what I *think* `desiredName` is supposed to be, i.e., behaving like `getSimpleName`.
An effect of this is that naming behaves much better in the REPL.
**Related issue**: Fixes #1166
> Strip Object and Outer Class from desiredName

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/Direction.scala
Dynamically indexing a Vec of Flipped bidirectional Bundles would get
the wrong directions on the elements of the Bundles
Fixes #1192
See https://github.com/freechipsproject/chisel3/issues/1192#issuecomment-536018644 for insight into the issue. Basically, we were copying the direction from the `sample_element` to the `Vec` itself as an optimization, but if you have a Flipped Bundle as the element this could result in double flipping. Instead, we want to maintain a different direction for the Vec itself so that we can differentiate between complex flippedness.
**Related issue**: #1192
Fix bug where dynamically indexing a Vec of Flipped bidirectional Bundles would get the …
> Fix direction of dynamic index in complex Vec

- src/main/scala/chisel3/util/experimental/BoringUtils.scala
- src/test/scala/chiselTests/BoringUtilsSpec.scala
This fixes a bug introduced in the original `BoringUtils.bore` implementation. This was using `instanceName` which meant that it could only be used for closed modules. The user-facing impact of this is an exception if you use `BoringUtils.bore` for signals in the module in which you do the bore (because that module is not closed). This adds one small test for this case.
This PR will introduce worse Verilog naming for boring signals using `BoringUtils.bore`.
Fixes #1212.
**Type of change**: bug report | other enhancement
- Bugfix for BoringUtils.bore with signals in the same module
> Internal BoringUtils.bore Bug Fix

- src/main/scala/chisel3/stage/ChiselStage.scala
**Development Phase**:implementation
This enables users to use the nice run method of `ChiselStage` with their own set of phases.
> Make ChiselStage targets not private

- chiselFrontend/src/main/scala/chisel3/Module.scala
- src/test/scala/chiselTests/Module.scala
This provides a fix for #1223 where modules that are either anonymous or defined in function bodies now produce non-purely-numeric names.
This is an amalgamation of a fix proposed by @aswaterman (which actually is necessary to fix classes in modules) and the use of an `_Anon` prefix for anonymous modules.
This includes tests and more documentation for `desiredName`.
**Related issue**: Fixes #1223 
**Type of change**: bug report | documentation
**Impact**: No functional change
- Better naming of anonymous modules and modules defined in functions
> Improve naming of anonymous/class-in-function Modules

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/AsyncResetSpec.scala
Accomplished by changing the code gen for casting literals to
aggregates. Rather than connecting the literal to a wire that is then
bit selected from, just bit select from the literal which saves the
creation of an intermediate wire and matches FIRRTL's semantics for
legal async reset initial values.
Turned out to be a very clean implementation, most work (as usual) in the testing.
**Related issue**: https://github.com/freechipsproject/firrtl/pull/1201
**Impact**: API addition? (only in that it fixes a bug)
Fix bug where literals cast to aggregates could not be used as async reset register initial values.
> Support literals cast to aggregates as async reset reg init values

- src/main/scala/chisel3/util/Mux.scala
- src/test/scala/chiselTests/MuxSpec.scala
If you use `MuxLookup` with a full mapping, i.e., you fully enumerate all possible values for a key, you still wind up with unused hardware being generated in the case of a `Mux` failure case that is never used and which FIRRTL does *not* optimize away.
This PR modifies `MuxLookup` to examine if the user has provided a full mapping and to *not* emit the additional failure case for the initial `Mux`. In effect, the `default` is immediately discarded and the first mapping becomes the default.
This generally improves Verilog generation for users that are using `MuxLookup` like a Verilog case statement.
This would benefit from tests, but there weren't any tests already written. :sob: I can write them (read: I have not fully tested this). I just figured I would drop the PR first.
For the …
> Don't use MuxLookup default for full mapping

- build.sbt
- build.sc
Bump version for 3.2-20191106-SNAPSHOT
> Bump for 3.2-20191106-SNAPSHOT.

- .mergify.yml
Bugfix mergify, because jenkins builds are not run on backport branches
> Fix mergify to backports: omit jenkins CI

- chiselFrontend/src/main/scala/chisel3/experimental/Analog.scala
- src/test/scala/chiselTests/AnalogSpec.scala
For direction purposes, Analogs were treated differently in IOs vs. in Wires. This difference was added in https://github.com/freechipsproject/chisel3/pull/617, specifically commit https://github.com/freechipsproject/chisel3/commit/f4a1c40fa147924087065bf7024038cc465b95ae, but I am unable to ascertain why. @ducky64 as a reviewer in case he has insight.
The motivating reason for fixing this is that `BundleBridge` in rocket-chip materializes the tunneled Bundle via a Wire in the destination module. Currently, you cannot have BundleBridges with any mix of Analog and non-Analog components. This fixes that issue.
Support bidirectional …
> Fix bidirectional Wire with Analog

- src/main/scala/chisel3/compatibility.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
This switches from using an implicit val that required awkward
suppression (as illustrated in CompileOptionsSpec) to allowing
overriding in the same way as done in "import chisel3._" via the
creation of an implicit val in lexical scope.
The motivation is attempting to partially migrate Diplomatic stuff in rocket-chip to `import chisel3._`. I currently have to do the following:
```scala
import Chisel.{defaultCompileOptions => _, _}
import freechips.rocketchip.util.CompileOptions.NotStrictInferReset
```
It would be nice if we could just write
```scala
import Chisel._
import freechips.rocketchip.util.CompileOptions.NotStrictInferReset
```
This is probably backportable to `3.2.x`, although if so we should (probably) exclude the deprecation of `Chisel.defaultCompileOptions`.
**Related issue**: …
> Compat compile options macro

- src/main/scala/chisel3/compatibility.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
This is a manual backport of pull request https://github.com/freechipsproject/chisel3/pull/1253 excluding the deprecation of `Chisel.defaultCompileOptions`.
This switches from using an implicit val that required awkward
suppression (as illustrated in CompileOptionsSpec) to allowing
overriding in the same way as done in "import chisel3._" via the
creation of an implicit val in lexical scope.
> Use macro to materialize CompileOptions in Chisel._ (bp #1253)

- chiselFrontend/src/main/scala/chisel3/Data.scala
Data.isLit called Data.litArg which would trigger a Chisel runtime
deprecation warning in user code with source locator Data.scala:488
As reported in https://stackoverflow.com/questions/59049673/how-to-initialize-a-reg-of-bundle-in-chisel/59058082?noredirect=1#comment104418728_59058082
Fix internal deprecation warning on Data.isLit that leaked into user code
> Fix deprecation warning that leaks into user code

- chiselFrontend/src/main/scala/chisel3/Clock.scala
- src/test/scala/chiselTests/AsTypeOfTester.scala
See the test. Currently, you cannot cast via `.asTypeOf` to a `Clock`. You can legally cast from a `Bool` to a `Clock` via `.asClock`, but when you have `Aggregate`s with `Clock` members, you would like `.asTypeOf` to work. This isn't common because it's generally unsafe, but it's reasonable to do in testbench code and obviously our casting should be consistent.
Support Clock in `asTypeOf` casting
> Fix asTypeOf for Clock

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/BundleLiteralSpec.scala
**Related issue**: #1214 
This PR enables the use of EnumType in BundleLiterals. For example, the following code should work:
```scala
object ENUM extends ChiselEnum {
val a, b, c = Value
}
class t extends Bundle {
val a = ENUM()
}
class tIO extends Bundle {
val a = Output(new t())
}
class TestModule extends Module {
val io = IO(new tIO())
io.a := (new t).Lit(_.a -> ENUM.b)
}
```
> Add ChiselEnum to BundleLiterals

- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/IntervalRangeSpec.scala
- Change getPossibleValues of Interval to return a NumericRange formerly Seq materialized all values
- Fixed computation in getHighestPossibleValue, erroneously was using lower intead of upper
Fixed bug that miscalculated the highest possible value of an IntervalRange
>  Bug fixes to support code for Interval

- src/main/scala/chisel3/stage/package.scala
This removes a dead line where a WriteEmitted phase is constructed.
This PR should be merged before https://github.com/freechipsproject/firrtl/pull/1277.
None.
> Remove unused WriteEmitted phase

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
This is just a band aid until an Aggregate `isLit()` method (for which work has begun) is implemented.
**Related issue**: #1256, ucb-bar/dsptools#184
Prevent `isLit()` on Aggregates failing with a `scala.NotImplementedError: an implementation is missing` error.
> Band aid until litOption is implemented for Aggregates.

- chiselFrontend/src/main/scala/chisel3/Bits.scala
- src/test/scala/chiselTests/IntervalSpec.scala
- boundary testing was not taking binary point into account correctly
- add tests to show where things work and where they are supposed to fail
A bug that affected could cause exceptions when creating intervals with range specifiers was fixed, e.g. `val iLit = 6.0.I(range"[0,6]")` would fail even though 6 is legal in that range.
> Fixed problem creating Interval literals with full ranges

- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
**Impact**: no functional changemodification
`rename` is private, and it only is called when  `names` contains new name string in method `def name` . Thus no need to use `getOrElse`
```scala
if (this contains sanitized) {
name(rename(sanitized))
}
```
> Remove over design

- src/main/scala/chisel3/aop/Select.scala
- src/test/scala/chiselTests/aop/SelectSpec.scala
Previously, `Select.instances` would fail on a cast error if called on a module that was a black box. Now, it just returns `Nil`, because a black box by default has no instances. This enables other functions to rely on more consistent behavior, such as `Select.collectDeep`.
> Bugfix: Select.instances now works with blackboxes

- src/main/scala/chisel3/util/BitPat.scala
- src/test/scala/chiselTests/Decoder.scala
The whitespace and _ are presumably for human readability.
This is a fix for chisel3 PR #1069
The BitPat.parse factory though did take these into account when 
reporting the bit pattern size in `BitPat.parse`.
This fixes that adds whitespace and underscores to the unit tests
Fixes `BitPat.parse` returned value for the size of the bit pattern, which was not
adjusted for the presence of _ or whitespace (legal formatting characters)
> BitPat supports whitespace and underscores

- chiselFrontend/src/main/scala/chisel3/When.scala
- src/main/scala/chisel3/util/Conditional.scala
This changes the type of the thunk used by `when` and `switch` method from `=> Unit` to `=> Any`.
This avoids a warning related to discarding a non-Unit value (`-Ywarn-value-discard` ) if you do something like what is describe in #1298.
Alternatively, and as I suggested in #1298, I think you could also get rid of this by making the methods polymorphic in the type of the thunk, e.g., `apply[A](a: => A): FooContext`. However, this is not like `withClock` where the type of the thunk is returned. Therefore, I opted for the simpler solution of using `Any`.
**Related issue**: Fixes #1298 
- Prevent warnings from -Ywarn-value-discard in when/switch
> Change when/switch thunk type to Any

- chiselFrontend/src/main/scala/chisel3/Bits.scala
- chiselFrontend/src/main/scala/chisel3/Num.scala
Cosmetic changes - update comments, use MaxBitsBigIntToBigDecimal instead of '108'.
> Big decimal methods for num types.2

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
- chiselFrontend/src/main/scala/chisel3/Reg.scala
> Fixed code example typo in comment

- chiselFrontend/src/main/scala/chisel3/Clock.scala
- src/test/scala/chiselTests/Clock.scala
Addresses Chisel issue #1238
**Impact**: Minor API addition (no impact on existing code)
There is now a short cut method for turning a clock to a bool
`clock.asBool`. Previously had to do `clock.asUInt.asBool`
> Add method asBool to Clock.

- chiselFrontend/src/main/scala/chisel3/Reg.scala
Updates Scaladoc for RegNext to make it more clear about its behavior:
**Related issue**: #1311 
- Add Scaladoc for RegNext about unset/inferred widths
> Add Scaladoc about RegNext Unset/Inferred Widths

- chiselFrontend/src/main/scala/chisel3/Bits.scala
- chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/BitwiseOps.scala
Change the emission strategy for `Bits` methods `andR` and `orR` to emit FIRRTL bitwise reduce operations `andr` and `orr`. The CHIRRTL emission strategy for these two operations now matches the emission of `xorR` (which already used `xorr`).
Add two tests that assert the correct behavior of these operations in `BitwiseOpsSpec`.
This should fix one of the Verilog emission problems shown in freechipsproject/firrtl#1338 of:
```scala
class Foo(n: Int) extends RawModule {
val in = IO(Input(UInt(n.W)))
val out = IO(Output(Vec(3, Bool())))
out(0) := in.andR
out(1) := in.orR
out(2) := in.xorR
}
```
This will now emit the following CHIRRTL for `Foo(4)`:
```
circuit Foo : 
module Foo : 
input in : UInt<4>
output out : UInt<1>[3]
node _T = andr(in)
out[0] <= _T
node _T_1 = orr(in)
out[1] <= _T_1 …
```
> Emit FIRRTL andr, orr for Bits.{andR, orR}

- chiselFrontend/src/main/scala/chisel3/Printf.scala
- src/test/scala/chiselTests/PrintableSpec.scala
https://github.com/freechipsproject/chisel3/issues/1321
I added support for \t in printf. I also made the `require` statements give more information if you do something wrong which is how I figured out the tab was the problem.
Printables printf now supports \t characters.
> Printf: Add support for tabs, and give helpful error messages

- README.md
Link to an old but good tutorial for Chisel
> README: have a linke to the classic tutorial

- src/main/scala/chisel3/util/Decoupled.scala
- src/test/scala/chiselTests/QueueSpec.scala
Close #1134
**Type of change**: bugfix
**Release Notes**: Fix unexpected error from attempting to use Queue.irrevocable in chisel3.
> Make Queue.irrevocable work properly in chisel3

- chiselFrontend/src/main/scala/chisel3/Aggregate.scala
Credit to @aswaterman for this idea while we walked across Bordeaux at ORConf. We can lazily clone the elements of `Vecs` to improve performance. The key observation is that most clones are thrown away, so why do we bother creating more than just the `sample_element` for a `Vec` unless necessary?
This simple change has an absolutely **massive** performance impact on SiFive designs:
| Design | Runtime - master | Runtime - this branch |
| -- | -- | -- |
| Small | 108 seconds | 39 seconds |
| Large | 8 minutes | 3 minutes |
If anyone isn't convinced, try running the following:
```scala
object MyBundle {
private var count = 0L
def inc(): Unit = this.synchronized {
count += 1
println(s"Cloned $count times")
}
}
class MyBundle extends Bundle {
MyBundle.inc()
val foo = UInt(8.W)
}
class MyModule …
```
> Clone child elements lazily in Vec

- chiselFrontend/src/main/scala/chisel3/Bits.scala
- src/test/scala/chiselTests/AsyncResetSpec.scala
- src/test/scala/chiselTests/ResetSpec.scala
Fix a bug where you couldn't monoconnect to `Reset()` nor `AsyncReset()`, and add tests.
**Impact**: API addition (no impact on existing code) (bugfix)
Fix bug where you couldn't `:=` `AsyncReset` and `Reset` to `DontCare`
> Fix := of Reset and AsyncReset to DontCare

- README.md
Two changes:
- Removes the CCC20 as an "upcoming event"
- Adds Developer meetings with Google Docs link as upcoming event.
**Type of change**: documentation 
None.
> Upcoming Events: Remove CCC, add Dev Meetings

- chiselFrontend/src/main/scala/chisel3/RawModule.scala
This isn't a full fix, but it's an improvement of the status quo we've had for months.
Given something like:
```scala
class MyModule extends RawModule {
def func(): Unit = {
val port = IO(Output(UInt(8.W))) //.suggestName("port")
port := 3.U
}
func()
}
object MyMain extends App {
println(chisel3.Driver.emit(() => new MyModule))
}
```
Currently, you get the following error:
```
[error] Exception in thread "main" java.lang.ClassCastException: chisel3.internal.firrtl.Ref cannot be cast to chisel3.internal.firrtl.ModuleIO
```
Pretty worthless. This PR changes the error to
```
[info] [error] RawModule.scala:53: Unable to name port UInt<8>(IO <UNNAMED> in MyModule) in MyModule@a67c67e, try making it a public field of the Module in class chisel3.RawModule
```
It does not …
> Patch fix #1109

- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala
- src/main/scala/chisel3/stage/phases/AspectPhase.scala
- src/main/scala/chisel3/stage/phases/Checks.scala
- src/main/scala/chisel3/stage/phases/Convert.scala
- src/main/scala/chisel3/stage/phases/DriverCompatibility.scala
- src/main/scala/chisel3/stage/phases/Emitter.scala
- src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
- src/main/scala/chisel3/stage/phases/MaybeFirrtlStage.scala
This changes Phase dependency specification to use the new Dependency
wrapper. Previously, dependencies were specified as classes.
Signed-off-by: Schuyler Eldridge <schuyler.eldridge@ibm.com>
**Related issue**: https://github.com/freechipsproject/firrtl/pull/1275
Dependes on https://github.com/freechipsproject/firrtl/pull/1357
- Migrate ChiselStage to use Dependency wrappers
> Migrate to Dependency Wrapper

- build.sc
Currently mill will only publish in `~/.ivy2/local/edu.berkeley.cs/chisel3-2.12.10_2.12/3.3-SNAPSHOT/`, which is non-compatible to sbt build.
This patch will overwrite `artifactName` from `chisel3-$crossVersion_$artifactScalaVersion` to `chisel3-$artifactScalaVersion`, giving the same directory with sbt.
> sbt compatible publish for mill

- build.sc
Sorry, it's me again, this PR adds a `testOnly` command to run a single test like sbt did. Mill didn't support it out-of-box.
> add testOnly

- build.sc
The release process uses python to scan and set expected versions for a release. The `val defaultVersions = ` stanza should be present for this to work.
Restore the `defaultVersions` map to facilitate release generation and testing.
> Retain default version assignment

- chiselFrontend/src/main/scala/chisel3/RawModule.scala
- src/test/scala/chiselTests/ResetSpec.scala
Introduces mutually-exclusive traits RequireAsyncReset and
RequireSyncReset to set the type of the implicit reset in
MultiIOModules. The Scala-type remains Reset, but the Chisel
elaboration-time checks apply.
This implements my proposal from the Chisel Dev Meeting today (24 Feb 2020). In the notes this is the "subtractive" approach because `MultiIOModule` has an implicit reset of type `Reset` and these traits allow us to constrain the runtime type. There is an alternative "additive" approach that I still plan to prototype but I do think this is pretty slick and relatively intuitive.
**Type of change**: feature
**Development Phase**: proposal &  implementation
Add RequireAsyncReset and …
> Provide API to set concrete type of implicit reset

- chiselFrontend/src/main/scala/chisel3/RawModule.scala
Overriding will always result in a `NullPointerException` due to https://github.com/freechipsproject/chisel3/blob/aac6e175645960b65eace70d16d0e4df523e0327/chiselFrontend/src/main/scala/chisel3/RawModule.scala#L155 which 
This is definitely not source compatible, so I don't think we should backport it. Although if someone is doing this it cannot be a Module they ever actually construct because it's `NullPointerException` 100% of the time.
Make implicit clock and reset final vals fixing buggy hole in API
> Make implicit clock and reset final vals

- .mergify.yml
See freechipsproject/firrtl#1439.
This fixes the rule to apply the "Backport" label (which is a prerequisite for the no-review merge) after some upstream changes in the mergify engine.
> [mergify] Update match string for labeling backported PRs

- chiselFrontend/src/main/scala/chisel3/internal/Error.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
This is an intended fix for the unreported issue of Chisel elaboration failures resulting in `ChiselMain` reporting an `OptionsException` for any exception originating from elaboration. This manifested as bad error messages like [this StackOverflow question](https://stackoverflow.com/questions/60479390/sbt-trapexitsecurityexception-error-message-in-from-chisel-rocket-chip/):
```
[info] [0.003] Elaborating design...
------------------------------------------------------------------------------
Error: Exception thrown when elaborating ChiselGeneratorAnnotation
Try --help for more information.
------------------------------------------------------------------------------
Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
```
With this PR …
> Dont wrap elaboration annotations

- chiselFrontend/src/main/scala/chisel3/internal/Error.scala
Change the logic for determining which nested ChiselException cause to
use for a trimmed stack trace. Previously, this would use the
outermost. This commit changes this to use the innermost.
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/2340#pullrequestreview-378778943
For the example @jackkoenig is showing, with this PR cherry-picked onto 3.2.x you get:
```
[error] java.lang.IllegalArgumentException: requirement failed: hello world
[error] 	...
[error] 	at freechips.rocketchip.rocket.DCacheModule.<init>(DCache.scala:96)
[error] 	at freechips.rocketchip.rocket.DCache.module$lzycompute(DCache.scala:84)
[error] 	at freechips.rocketchip.rocket.DCache.module(DCache.scala:84)
[error] ocketchiat freechips.rocketchip.rocket.DCache.module(DCache.scala:83)
[error] 	at …
```
> Use innermost builder cause to trim stack trace

- README.md
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Deprecate existing `Driver` methods that have exact `ChiselStage` equivalents.
**Type of change**: documentation | other enhancement
- Deprecate old Driver methods with ChiselStage equivalents
> Deprecate Driver methods in favor of ChiselStage

- core/src/main/scala/chisel3/package.scala
- project/plugins.sbt
- src/main/scala/chisel3/util/Bitwise.scala
Three things:
1. This appends to the build.sbt apiMappings so that linking against Java API docs (for the appropriate version of Java) works. I reuse the same build.sbt from Scala upstream.
1. This shows an example of this working to link to a Java exception
1. This shows an example of this working to link to Scala main API docs (which already worked before this PR)
Example:
This then links to:
- Scaladoc now can link against Javadoc
> Java API Documents Linking

- core/src/main/scala/chisel3/experimental/package.scala
- src/test/scala/chiselTests/LiteralExtractorSpec.scala
Since RocketChip use `Record` for `AutoBunlde` and diplomatic bundles like `TLBundle`, if we need to test RocketChip with native chisel tester, we should allow `Lit` to `Record`. 
This PR changes all `BundleLiterals` to `RecordLiterals`, which enables `Lit` method for `Record`, and deprecate original `BundleLiterals`, it won't affect existing code, and enalbe peek/poke for Diplomatic Bundle in chiseltester.
> Change BundleLiteral to RecordLiteral

- core/src/main/scala/chisel3/internal/Builder.scala
I tried to come up with a self-contained test for this, but was unable to.
I tested it by using this to build/run the [bundleStackCrash branch of chisel-template](https://github.com/freechipsproject/chisel-template/tree/bundleStackCrash).
**Related issue**: #1334
Use thread local storage for ChiselContext.
> Use thread local storage for ChiselContext.

- core/src/main/scala/chisel3/Data.scala
- src/test/scala/chiselTests/RecordSpec.scala
This PR expose typeEquivalent method to DataMirror for compile time reflection to Data Type, it can help chiseltester with more strict `peek`/`poke` constraint.
> expose typeEquivalent

- chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
Backport #1404
(cherry picked from commit e55c00fe09a795adae15b6383a75300d6cfa9e7a)
> Use thread local storage for ChiselContext. (#1404)

- src/test/scala/chiselTests/AsyncResetSpec.scala
Add some tests that would've caught an embarrassing bug
Will fail until https://github.com/freechipsproject/firrtl/pull/1523 is merged
Marked for backport, will fail because of Intervals, I'll fixup manually.
**Type of change**: add tests
> Add tests for async reset regs of non-UInt types

- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/Decoupled.scala
At the bequest of @jackkoenig, this reverts commit c279860c36a73984cd1b7b0ac6c213e8b44a7143.
To properly name private and protected fields in `chisel3.util.Arbiter` and `chisel3.util.Decoupled` with the `@chiselName` macro annotation, these fields were made public, and thus retain a better name.
> Revert "Make uselessly public fields in utils private"

- .mergify.yml
This replaces the rules for 3.2.x
Note that the milestone is named `3.3.x` with a lowercase `x` as opposed to the uppercase of `3.2.X`.
Companion of https://github.com/freechipsproject/chisel3/pull/1428 for backport automation
> Update Mergify rules to backport to 3.3.x

- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/phases/Emitter.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
This is a replacement for #1412 that also fixes the double elaboration problem in a backwards compatible way. This PR does the following things:
1. It removes the requirement that `Elaborate` run in `ChiselStage` (you don't care that elaboration ran and wasn't invalidated)
2. It removes the invalidation of `Elaborate` by the `Emitter` (the emitter doesn't touch any annotations)
3. It adds an `optionalPrerequisiteOf` from `Emitter` -> `Convert` to get the correct ordering (this is @davidbiancolin's #1412)
To test this, this adds:
4. An API expansion where `ChiselStage` exposes it's phase manager
5. It adds a test that elaboration runs once by looking at this phase manager
When running `ChiselStage`, you now get the following phase order:
```
[info] - should only run elaboration once
[info] …
```
> Fix Double Elaboration Backportably

- SETUP.md
**Related issue**: Branch verilator_4_016 does not exist anymore.
**Impact**: no functional change 
**Development Phase**: proposal 
It seems Verilator creators changed the way they organize their branches/version in their repository, so instead of the branch verilator_4_016, there is a version v4.016 now.
> verilator_4_016 --> v4.016

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/ImplicitConversionsSpec.scala
Some errors that were previously hidden when calling Chisel API methods outside of an active hardware generation context (see #1422) will now be immediately thrown as exception.
> Report Builder.error errors as exceptions outside hardware context

- src/main/scala/chisel3/stage/ChiselAnnotations.scala
We hash all of the annotations between phases so this makes that *much* faster after Chisel elaboration. @seldridge discussed changing the hashcode to be either a constant or just hash the name of the top-module or something so that we don't even both hashing the circuit, but I'll leave that for a later change. I would really like this in 3.3.2 because it's costing a lot of runtime.
Memoize hashcode of ChiselCircuitAnnotation, improves performance of multi-phase generators
> Memoize the hashcode of the ChiselCircuitAnnotation

- .mergify.yml
Brings it inline with the config used in FIRRTL
> Fix Mergify Backport labeling for 3.2.x

- src/test/scala/chiselTests/InlineSpec.scala
Fix a bug in FlattenSpec where ChiselStage was running the FIRRTL
compiler in ChiselStage and then re-running the FIRRTL compiler. This
changes it to be like InlineSpec and to not run FIRRTL during
ChiselStage.
This produced a bug in 3.3.x, but not in the master branch slated for 3.4.0.
This was manually backported to 3.3.x as part of https://github.com/freechipsproject/chisel3/pull/1492.
**Related issue**: None.
None.
> Don't run FIRRTL in FlattenSpec's ChiselStage

- src/main/scala/chisel3/testers/TesterDriver.scala
~This reverts changes to `TesterDriver` introduced in #1481 that broke chisel-testers.~
Fix a regression in chisel-iotesters introduced in #1481. This restored a mistakenly removed call to `finishWrapper`.
**Related issue**: https://github.com/freechipsproject/chisel3/pull/1481#issuecomment-648486923
None.
> Fix TesterDriver.scala regression #1481

- build.sc
**Type of change**: bug report 
**Impact**: no functional change 
Fix Bug introduced by #1483, which add tredale to chisel dependency.
> fix treadle dependency for mill

- .circleci/config.yml
Change CI to build Treadle master from source. This fixes a bug where
Treadle would be pulled from the latest snapshot (which would pull the
latest FIRRTL snapshot). For bleeding edge PRs that rely on new FIRRTL
features, using a FIRRTL snapshot may result in compilation failures.
Signed-off-by: Schuyler Eldridge <schuyler.eldridge@ibm.com>
**Related issue**: https://github.com/freechipsproject/chisel3/pull/1499#issuecomment-658963659
None.
> Add Treadle to CI builds

- src/main/scala/chisel3/aop/Select.scala
This PR updates `Select.getLeafs`/`Select.getIntermediateAndLeafs` to match on the broader `Record` type instead of `Bundle`. Necessary for selecting `LazyModule` IOs since the `AutoBundle` that wraps `LazyModule` IOs only extends `Record`.
> update Select.get(IntermediateAnd)Leafs to work with records

- src/main/scala/chisel3/util/Counter.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/Counter.scala
This PR adds the ability for a counter to be instantiated using a Scala range.
The original API has been preserved, but the counter now works internally with a range. Using a range to configure the counter allows us to do interesting things.
Counting upwards:
```scala
val (value, wrap) = Counter(0 to 3)
// 0, 1, 2, 3, 0, 1...
```
Counting downwards:
```scala
val (value, wrap) = Counter(3 to 0)
// 3, 2, 1, 0, 3, 2...
```
Counting upwards by twos:
```scala
val (value, wrap) = Counter(0 to 9 by 2)
// 0, 2, 4, 6, 8, 0, 2...
```
It also allows an optional condition attribute (similar to the existing API):
```scala
val enable = true.B
val (value, wrap) = Counter(0 to 3, enable)
// 0, 1, 2, 3, 0, 1...
```
I'm fairly new to Chisel, but I think that having the condition as the second parameter …
> Allow a counter to be instantiated using a Scala range

- src/main/scala/chisel3/stage/ChiselStage.scala
Adds a method for emitting SystemVerilog to the top level API, which previously required a workaround of a few lines of code.
> Add emitSystemVerilog method to ChiselStage

- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Mem.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/Reg.scala
- core/src/main/scala/chisel3/When.scala
- core/src/main/scala/chisel3/internal/Binding.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/MonoConnect.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
- src/test/scala/chiselTests/CompileOptionsTest.scala
- src/test/scala/chiselTests/IllegalRefSpec.scala
**Related issue**: #1409 freechipsproject/firrtl#1505 #1512 
**Type of change**: improvement
**Impact**: freechipsproject/firrtl#1528 will make code that violates when scopes illegal. This will help enforce this at the Chisel level, but some code (like the old counter implementation from before #1408) will now fail to elaborate.
**Release Notes**:
Previous versions of Chisel and FIRRTL did not adequately enforce the scoping of declarations to `when` blocks. Using a reference to a signal that has escaped a closed scope will result in an elaboration-time error.
> Check whether signals escape their when scopes

- src/main/scala/chisel3/util/Counter.scala
- src/test/scala/chiselTests/Counter.scala
Includes special case support for Counter(0) which has identical
behavior to Counter(1) except for the value of n.
Restore API accidentally deleted in https://github.com/freechipsproject/chisel3/pull/1515. I'm a bit unsure about the `oldN` which is added only to support the case of `Counter(0)`. It's private so not a big deal to add or remove, but it shows that the API when passed `0` is funky.
Also, `Counter.n` makes sense to me for ranges starting at 0 with step 1, but it's unclear what it *should* mean for other cases so I made it throw an exception in those cases.
**Impact**: API ~modification~ restoration
> Restore Counter.n API

- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/package.scala
- src/main/scala/chisel3/stage/phases/Convert.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/MuxSpec.scala
This removes the `chisel3.stage.phases.Emitter` and moves its emission logic into the `ChiselCircuitAnnotation`. This uses the new `HowToSerialize` mix-in provided by https://github.com/freechipsproject/firrtl/pull/1277. 
A consequence of this is that there is no longer a need for generating `DeletedAnnotation`s and for introspection of `DeletedAnnotation`s to determine an execution result or a view of some sequence of annotations.
**Related issue**: Depends on https://github.com/freechipsproject/firrtl/pull/1277
> Switch to HowToSerialize for Emission

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/RawModule.scala
I was experimenting with some stuff in Scala 2.13 and realized that `-Xsource:2.11` is no longer supported in 2.13. In fact, it was never recommended as an option to Scalac for anything but debugging, let alone our recommended way of supporting Scala 2.12. Thus I had a [discussion](https://gitter.im/scala/contributors?at=5f3324e82aa0fd6b0aa9e92b) on the Scala Contributors Gitter to figure out what to do.
For a long time, we thought the issue only had to do with structural typing. This was incorrect, there were actually *2* different problems:
1. Structural Typing
* [formerly unsupported](https://contributors.scala-lang.org/t/better-type-inference-for-scala-send-us-your-problematic-cases/2410/73?u=jackkoenig) in Scala 3, [now supported](https://github.com/lampepfl/dotty/issues/7920#issuecom …
> Deprecate Module.io and BlackBox.io

- src/main/scala/chisel3/util/Counter.scala
- src/test/scala/chiselTests/Counter.scala
This PR adds a `reset` parameter to the Counter API, that allows a counter to be reset to its initial value.
It is sometimes useful to be able to reset a counter arbitrarily. By default the `reset` parameter is `false`, which means the proposed change is compatible with the existing API.
For example
```scala
val counterReset = WireInit(false.B)
val (value, wrap) = Counter(0 to 3, reset = counterReset)
// Trigger a reset
counterReset := true.B
```
Allow counters to be reset
> Allow a counter to be manually reset

- build.sbt
- core/src/main/scala/chisel3/internal/Builder.scala
Leverages chiselRuntimeDeprecated infrastructure. As such it is not
currently suppressible.
Related to https://github.com/freechipsproject/firrtl/pull/1842. This doesn't have suppression because nothing in Chisel elaboration does. I looked at adding suppression via annotations like in the FIRRTL PR, but some invocations of the Builder don't have annotations to propagate (like aspects). Also nothing else is suppressible so I figured this needs further thought.
Deprecate support for Scala 2.11
> Deprecate support for Scala 2.11

- build.sbt
- build.sc
Also fix BuildInfo in mill
@chick This is important for the release because otherwise the plugin isn't published for Scala 2.12.12
Bump Scala to 2.12.12
> Bump Scala to 2.12.12

- build.sbt
- build.sc
- src/main/scala/chisel3/testers/TesterDriver.scala
- src/test/scala/chisel3/testers/TestUtils.scala
- src/test/scala/chisel3/testers/TreadleBackend.scala
- src/test/scala/chiselTests/ChiselSpec.scala
Use inheritance to make TesterDriver Backend API extensible, then define
a TreadleBackend in the test project
Now, Treadle is only a dependency of the test configuration. When doing this manual modification
* Treadle is only a dependency of the test configuration now
* It doesn't run out of the box (requires modifying `ChiselSpec.scala`), but it is similar to the case before
* ~~Tests that require Verilator no longer work when you do the modification to use Treadle.~~
* ~~This needs to be fixed but I would argue is less important than getting this in to remove an unnecessary dependency.~~
* This is fixed
* While FIRRTL can be built from source, this does not allow building Treadle from source
* I don't think the old code worked anyway--2 fat jars as unmanaged dependencies would have …
> Move Treadle dependency to the tests

- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala
- src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala
- src/main/scala/chisel3/stage/phases/Checks.scala
- src/main/scala/chisel3/stage/phases/Convert.scala
- src/main/scala/chisel3/stage/phases/DriverCompatibility.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/main/scala/chisel3/stage/phases/Emitter.scala
- src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
- src/main/scala/chisel3/stage/phases/MaybeFirrtlStage.scala
Remove usages of the deprecated trait PreservesAll and use an explicit
false invalidates. Additionally, all phases are converted to be more
canonical in there specification of dependencies by:
1. Overriding all default dependency implementations
2. Using def instead of val
None
> Remove use of PreservesAll, cleanup dependencies

- plugin/src/main/scala-2.12/chisel3/plugin/ChiselPlugin.scala
It must run after the typer, but doesn't need to "run right after". The
stricter dependency conflicted with the semanticdb-typer.
h/t Øyvind for finding this bug https://groups.google.com/g/chisel-users/c/K_vuliudgLg/m/IYx-QPd4AQAJ
I locally verified that I could reproduce the bug and this fixes it. Unfortunately this is a pretty hard thing to test for (in this repo at least)
- bug fix
No change
No change
- Squash
Relax plugin scalac phase order. This makes the plugin work with tools like Scala Metals.
> Relax plugin scalac phase order

- src/main/scala/chisel3/stage/ChiselPhase.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/test/scala/chiselTests/BetterNamingTests.scala
- src/test/scala/chiselTests/Clock.scala
- src/test/scala/chiselTests/Direction.scala
- src/test/scala/chiselTests/InvalidateAPISpec.scala
- src/test/scala/chiselTests/MuxSpec.scala
- src/test/scala/chiselTests/PrintableSpec.scala
- src/test/scala/chiselTests/ResetSpec.scala
- src/test/scala/chiselTests/experimental/verification/VerificationSpec.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Adds a new `private[chisel3]` phase called `ChiselPhase` which does the work of the one-off phase manager inside the existing `ChiselStage`. This is then used inside `ChiselStage`. `ChiselStage` companion object methods, `elaborate` and `convert`, are then switched to use `ChsielStage` so that they stop writing files.
This adds new APIs to the `ChiselStage` object that write no files:
- `emitChirrtl(gen: => RawModule): String`
- `emitFirrtl(gen: => RawModule): String`
- `emitVerilog(gen: => RawModule): String`
- `emitSystemVerilog(gen: => RawModule): String`
Tests are added, thanks to Java security manager magic, to assert that these methods do, in fact, write no files. Existing tests that use the `ChiselStage` class are modified to use the object if they are only checking a string output …
> Add ChiselPhase, Stop writing files in ChiselStage$ methods, Expand ChiselStage$ helpers

- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/compatibility.scala
It shouldn't be removed until we also remove underlying chisel3.Driver
- bug fix 
`Chisel.Driver` will continue to work, for the time being
None
- Squash
Restore `Chisel.Driver`
> Restore and deprecate Chisel.Driver

- build.sc
- new feature/API                   
None
None
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit. 
Add chisel-plugin to mill build system.
> Add chisel plugin to mill build system.

- build.sc
So sorry, my bad, Intellij automatically added the type which I didn't import. 
- bug fix
none
none
> bug fix for build.sc

- README.md
- build.sbt
- project/plugins.sbt
This allows you to build FIRRTL from source in a much cleaner way. In this repo you can do so in the following way:
```bash
git clone git@github.com:freechipsproject/firrtl.git
sbt -Dsbt.sourcemode=true -Dsbt.workspace=$PWD
```
This will use the source checkout of firrtl, having SBT manage both (much better for use with IDEs and other tooling). You can commit those `-D` arguments in `.sbtopts` and SBT will pick it up automatically.
There is a companion rocket-chip PR to come.
TODO
- new feature/API    (in the build at least)
This breaks the `firrtl.jar` unmanaged dependency technique for building chisel3 with firrtl from source. This new API works a lot better
No impact
-   - Squash
Improve chisel3 support for building against …
> Better Building of FIRRTL From Source

- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
- src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
Passed in hexOrBinary parameter to ChiselLoadMemoryAnnotation
Test included
Fixes #1582
No change in API
Allows $readmemb to be generated when the user specifies MemoryLoadFileType.Binary.
Squash
Fixed bug in loadMemoryFromFile that caused the hexOrBinary parameter to be ignored.
> Fix load memory from file to work with binary

- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselCli.scala
- src/main/scala/chisel3/stage/ChiselPhase.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/package.scala
- src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
- src/test/scala/chiselTests/stage/phases/AddSerializationAnnotationsSpec.scala
ChiselCircuitAnnotation no longer extends CustomFileEmission, rather it
is Unserializable. Also the --chisel-output-file is added to the
ChiselCli.
New phase AddSerializationAnnotations constructs a
CircuitSerializationAnnotation from ChiselCircuitAnnotation and
ChiselOutputFileAnnotation. Both .fir and .pb file formats are
supported. Default format is .fir unless a --chisel-output-file is
specified with a .pb extension.
This relies on a bugfix in https://github.com/freechipsproject/firrtl/pull/1887 to work.
- bug fix 
- new feature/API  
This is a binary incompatible modification from RC1, instead of `ChiselCircuitAnnotation` extending `CustomFileEmission` and only serializing to `.fir`, I added a new annotation `CircuitSerializationAnnotation` that can serialize to both `.fir` and …
> Add new annotation for Chisel Circuit serialization

- core/src/main/scala/chisel3/SeqUtils.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
The primary motivation for this is to enable optimization passes over elements of an Aggregate that would otherwise be unable to propagate across the UInt conversion.
> Recursively generate one-hot multiplexers for aggregates

- plugin/src/main/scala-2.12/chisel3/internal/plugin/ChiselPlugin.scala
Use caching to reduce number of expensive lookups. Also make methods private so we can improve them without breaking binary compatibility
I think this could be better, like only doing a single lookup, but I was having trouble getting it working so thought it better to just get this out here. This reduces the runtime of the Chisel plugin in rocket-chip compile by quite a bit (collected with scalacOption `-Ystatistics`):
```
Before:
[info]   typer                       : 1 spans, ()32910.11ms (27.8%)
[info]   chiselcomponent             : 1 spans, ()29308.0ms (24.7%)
After:
[info]   typer                       : 1 spans, ()26130.235ms (42.1%)
[info]   chiselcomponent             : 1 spans, ()6523.072ms (10.5%)
```
Typer included for reference (also shows how noisy the measurements are). …
> Faster ChiselPlugin

- docs/src/wiki-deprecated/cookbook.md
- src/main/scala/chisel3/util/Conditional.scala
- src/test/scala/chiselTests/SwitchSpec.scala
Fixes https://github.com/ucb-bar/chisel-tutorial/issues/166
Just a minor issue where `switch` basically assumes you're always doing `import chisel3.util._`. Simple fix.
- bug fix  
Fixes a bug in API
None
- Squash
Fix bug where using `chisel3.util.switch` required the user to import `chisel3.util.SwitchContext`
> Support using switch without importing SwitchContext

- .circleci/config.yml
- docs/src/cookbooks/naming.md
- docs/src/explanations/naming.md
- bug fix
No change.
None.
Fixed bug in docs/mdoc, where they aren't building properly.
> Fix broken mdoc

- .circleci/config.yml
- build.sbt
- project/plugins.sbt
- new test
Enforces the API
No impact
- Squash
None
> Add MiMa binary compatibility checking to 3.4.x

- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/prefix.scala
- src/test/scala/chiselTests/naming/PrefixSpec.scala
Fixes #1606
Previously, the Data itself would be put on the prefix stack and its
full name would be used as the prefix for subsequent names. This meant
that prefixes would grow quadratically as the prefix is present both on
the Data pushed to the stack, and on the stack itself. This is fixed by
just using the "local" name of the Data being pushed on the stack.
A related issue is deferring the name resolution. This led to unintuitive
behavior when the name of a Data used as a prefix is overridden later
(usually when the Data is a return value). The overriding name would
show up in prefixes twice instead of once. It is much more intuitive to
grab the name at the moment of the connection creating the prefix rather
than deferring to later.
TODO
- bug fix  
No impact on API (changing types of …
> When prefixing with a data, eagly get local name

- core/src/main/scala/chisel3/internal/Error.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
Package chisel3 was not properly marked as an internal package so source
locators in reported errors would point to files like Bits.scala.
This issue has existed since 3.2.0.
Example showing the issue: https://scastie.scala-lang.org/ujhmuUv4RjWklwY7KtiToA
```
[info] [0.000] Elaborating design...
[error] Bits.scala:159: Invalid bit range (3,-1) in class chisel3.Bits
[error] There were 1 error(s) during hardware elaboration.
```
`Bits.scala` is not a very useful source locator, this PR fixes it.
- bug fix
No impact
No impact
- Squash
Fix bug where some error messages would give source locators inside Chisel's code instead of user code
> Provide user source locators in Builder.error errors

- core/src/main/scala/chisel3/SeqUtils.scala
- src/main/scala/chisel3/util/Cat.scala
- src/test/scala/chiselTests/util/CatSpec.scala
Prevent an exception thrown if you apply `Cat` to a zero-element `Vec`. This will now return `0.U` if you do that.
Fixes #1622 
- bug fix                            
None. This enables new behavior which was previously an error.
No change to existing Verilog.
- Cat of a zero-element Vec now returns 0.U
> Enable Cat of Zero Element Vec

- core/src/main/scala/chisel3/internal/Builder.scala
This allows for sharing of the prefix stacks between Data, and removes a
boxing per prefix stack element that is no longer necessary.
My intuition is that this should reduce memory by quite a bit and thus improve performance, but I'd like to try it out on complex designs before we merge.
This should improve memory and performance for a few reasons:
1. `construction_prefix` for each `Data` is now free (it formerly copied from ArrayBuffer to List)
2. Structural sharing of common prefix stacks and intermediate prefix stacks
3. No more `Either` in prefix stack, removes an object allocation per stack element 
While we do have to copy the prefix stack when we `reverse` for naming, this is a copy on naming of `Data` rather than on construction. In theory, most `Data` should not be named, but due …
> Change prefix stack to List[String]

- src/main/scala/chisel3/stage/ChiselStage.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Prevent a `None.get` where a user passes a `-e` (one-file-per-module) option to one of the `ChiselStage` methods. This was previously checking for the only a circuit, but throwing in `-e` would cause modules to be emitted. Append all the modules together and return this string.
Fixes #1629 
- [n/a] Did you add Scaladoc to every public function/method?
- [n/a] Did you add appropriate documentation in `docs/src`?
- bug fix
None.
None.
None.
> Make `-e` option work with ChiselStage methods

- docs/src/cookbooks/naming.md
- docs/src/explanations/blackboxes.md
- docs/src/explanations/bundles-and-vecs.md
- docs/src/explanations/naming.md
- docs/src/wiki-deprecated/chisel3-vs-chisel2.md
- docs/src/wiki-deprecated/cookbook.md
- docs/src/wiki-deprecated/data-types.md
- docs/src/wiki-deprecated/developers.md
- docs/src/wiki-deprecated/faqs.md
- docs/src/wiki-deprecated/memories.md
- docs/src/wiki-deprecated/reset.md
- docs/src/wiki-deprecated/supported-hardware.md
- [ N/A Did you add at least one test demonstrating the PR?
- [N/A] Did you delete any extraneous printlns/debugging code?
- [N/A] Did you state the API impact?
- [N/A] Did you specify the code generation impact?
- bug fix
> Fix crosslinks in mdoc. Can't use md suffix

- core/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
This requires a combination of things, but it happens to be a
combination used by Diplomacy in Rocket Chip. It must be a Record in
compatibility code with Vecs as fields and a mix of components with and
without set directions.
Bug introduced in https://github.com/freechipsproject/chisel3/pull/1616, not yet released so no need for release notes
h/t to @azidar for helping me debug this, I seriously thought I was losing my mind. I never use `try-catch` to recover from exceptions (only to report more precise errors) so I just wasn't expecting it to be skipping over a critical line of code and continuing. Might be better to replace this pattern with a more explicit `Try` but in any case the fix is simple.
- bug fix
No impact
No …
> Fix bug where refs may not get set for Records

- src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
- src/test/scala/chiselTests/aop/InjectionSpec.scala
- [N/A] Did you specify the code generation impact?
- bug fix
No change - fixes bug introduced in #1635 
N/A
N/A
> Bugfix - adding external modules was broken (bug introduced in #1635)

- core/src/main/scala/chisel3/SeqUtils.scala
- backend code generation
this changes the Chisel Naming from https://github.com/freechipsproject/chisel3/pull/1448 to notate endianness as "hi/lo" instead of "right/left", because Scala and Verilog use opposite endianness in lists/arrays
With https://github.com/freechipsproject/chisel3/pull/1448, this Chisel
```
val out2 = Seq(signalname(0), signalname(1)).asUInt
val out4 = Seq(signalname(0), signalname(1), signalname(2), signalname(3)).asUInt
```
would generate this Verilog:
```
wire [1:0] out2 = {signalname_right, signalname_left};
wire [3:0] out4 = {signalname_right_right, signalname_right_left, signalname_left_right, signalname_left_left};
```
This looks backwards to me when reading the Verilog: the rights and lefts are reversed.  So instead, with this change:
```
wire [1:0] out2 = …
```
> SeqUtils asUInt endian-ness: hi/lo instead of right/left

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/BundleSpec.scala
It causes issues for some legal (if awkward) patterns. A larger refactor
of when refs are set could reinstate this check.
Bug introduced in #1616, no release notes necessary.
- bug fix   
This removes a check added in https://github.com/freechipsproject/chisel3/pull/1616 (not yet released) that causes some legal code to error. See the test for an example. While this check is a good thing to have, it will prevent the use of Chisel v3.4.1 in FireSim which currently uses this pattern. Some of the internals cleanups related to https://github.com/freechipsproject/chisel3/pull/1624 may be able to …
> Remove Data.setRef assertion

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/BundleSpec.scala
This is a refinement of the assertion added in #1616 then removed in
#1654. Because Records now set the refs of children upon binding,
later, unbound Records could incorrectly override the refs. The first
set should win.
This relates to https://github.com/firesim/firesim/issues/653.
This issue was found from the following declaration (relevant code pasted below):
https://github.com/firesim/firesim/blob/c2d8e3a46e59222e115a1fdaa7267592e1d3c503/sim/firesim-lib/src/main/scala/bridges/SerialBridge.scala#L39
Basically, we have a `Record` that intentionally does not clone its argument (not even upon calling `cloneType` on itself). This means that all clones of this `Record` have the same exact Data object as a field.
```scala
// We're using a Record here because reflection in Bundle prematurely …
```
> For HasId.setRef, have first set win (with force override)

- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/plugin/package.scala
- docs/src/cookbooks/naming.md
- docs/src/explanations/naming.md
- plugin/src/main/scala-2.12/chisel3/internal/plugin/ChiselPlugin.scala
- src/test/scala/chiselTests/naming/NamePluginSpec.scala
Last name in an Expression wins, while the first Statement to name wins.
This is done via checking the _id of HasIds during autonaming and only
applying a name if the HasId was created in the scope of autonaming.
There is no change to `.autoSeed` or `.suggestName` behavior.
Behavior of chisel3-plugins from before this change is maintained. More precisely, assuming this PR is released with Chisel v3.4.1, if you use Chisel v3.4.1 with the v3.4.0 (or v3.4.0-RC3) plugin, you'll get the v3.4.0 behavior. 
The bulk of the work here was making `unapply` continue to work because it previously worked via overriding names. Now, a signal will only be named by `autoNameRecursively` or `autoNameRecursivelyProduct` calls that wrap the `Expression` within which the `Data` is created.
Fixes …
> Refine autonaming to have more intuitive behavior

- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
The SecurityManager is global so is not thread-safe. This is the source
of flaky tests in FIRRTL CI.
None
- bug fix (flaky tests)
No impact
No impact
- Squash
> Ignore tests using System.setSecurityManager

- src/main/scala/chisel3/util/Conditional.scala
- src/test/scala/chiselTests/SwitchSpec.scala
This fixes #1648.
- bug fix
No impact.
The source locators in the code generated from the `switch` statements will no longer reference `Conditional.scala`. They will now reference the source line of the `is` statement.
- Squash
N/A
> Improve source locators for switch statements.

- README.md
Partially to test CI and integrations
> Update some README links to chipsalliance

- README.md
> readme: simplify sbt snippet and update to the latest stable release

- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Element.scala
- src/test/scala/chiselTests/BundleLiteralSpec.scala
Implemented by folding Element.ref into Data.ref. Element.ref had
special handling for literals, but because Bundles can also be literals,
there were code paths that tried to get the ref of a Bundle literal
which was non-existent. Now, all literals are handled together.
Because FIRRTL does not have support for Bundle literals, Bundle literal
refs are implemented by materializing a Wire.
This also handles the DontCare fields of partially initialized Bundle literals in the same way.
Fixes #1671
I could not find a good way to fix the related issue with Bundle literals and Printable. Given the v3.4.1 release going out tomorrow, I thought it prudent to at least get this fix in.
This basically does 2 things:
1. Support literals and DontCares in `requireVisible` and improve error message when …
> Fix RegInit of Bundle lits

- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/Error.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
This PR is the encore of #1474 and add test and deprecation notes requested by review.
> (encore) Builder: use LazyLogging.logger.warn to print elaboration message

- build.sbt
- build.sc
Fix settings so maven will show license as apache 2.0
- fix build.sbt
- fix build.sc
- [-] Did you add Scaladoc to every public function/method?
- [-] Did you add at least one test demonstrating the PR?
- [-] Did you delete any extraneous printlns/debugging code?
- [-] Did you add appropriate documentation in `docs/src`?
- [-] Did you specify the code generation impact?
- [ x] Did you add text to be included in the Release Notes for this change?
License Issue
None
No code gen implications
Squash
This fixes the problem where Maven says that chisel3 is bsd license, when it actually is apache-2.0
> Make Maven show chisel3 as apache-2.0

- .github/workflows/test.yml
- .mergify.yml
- build.sbt
- project/plugins.sbt
~~Currently WIP,~~ this is partially in the interest of reducing the number of CI vendors for Chisel Working Group Projects. Once this is done we can turn on auto publishing of SNAPSHOTs as in https://github.com/chipsalliance/treadle/pull/277
Notably, this no longer builds dependencies (`firrtl` and `treadle`) from source. Those projects publish up-to-date `SNAPSHOT`s on every push to a release branch and master, so there's no need to build them.
No impact
No impact
- Squash
> Switch to using Github Actions CI

- build.sbt
- build.sc
- version bumping
This ensures that master is now `3.5-SNAPSHOT` so that `3.4.x` can publish `3.4-SNAPSHOT`
No impact
- Squash
> Bump SNAPSHOT and SNAPSHOT dependencies

- .github/workflows/test.yml
- build.sbt
- project/plugins.sbt
Based on https://github.com/chipsalliance/treadle/pull/277 + https://github.com/chipsalliance/treadle/pull/281
- new feature
- 
No impact
No impact
- Squash
- 
Automatically publish SNAPSHOTs on pushes to relevant branches
> Automate publishing of SNAPSHOTS with sbt-ci-release

- docs/src/wiki-deprecated/upgrading-from-scala-2-11.md
The Scala 2.11 deprecation warning in FIRRTL has a link that has been broken for a while: https://github.com/chipsalliance/firrtl/blob/031fe1382660867750e6eeebea5665c137dbccbe/src/main/scala/firrtl/stage/transforms/CheckScalaVersion.scala#L10
This provides a redirect so the link will remain alive.
I've verified this works by building the website locally. I don't know all the details of how Jekyll works, but I figured it out from the documentation on the `jekyll-redirect-from` plugin which just so happens to be part of the website build: https://github.com/jekyll/jekyll-redirect-from
- bug fix    
No impact
No impact
- Squash
Fix broken link on website for Scala 2.11 …
> Add redirect for Scala 2.11 upgrade page

- core/src/main/scala/chisel3/Reg.scala
No impact
No impact
- Squash
Fix incorrect example in ScalaDoc for width behavior of RegInit
> Fix incorrect comment in ScalaDoc

- .github/workflows/test.yml
- build.sbt
- build.sc
- project/plugins.sbt
- new feature/API 
This allows users of the Chisel plugin to use Scala 2.12.13 (plugins require publishing for each minor version)
No impact
- Squash
- 
Bump to Scala 2.12.13, publish chisel3-plugin for 2.12.13.
> Bump to Scala 2.12.13

- core/src/main/scala/chisel3/Bits.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/SIntOps.scala
- src/test/scala/chiselTests/UIntOps.scala
- src/test/scala/chiselTests/WidthSpec.scala
See #1746. I think it's reasonable to add a test where op result `.getWidth` values are compared against FIRRTL IR values using a few nested for loops, so I will update this soon.
**Type of improvement:** bug fix
**API impact:** `getWidth` now returns correct width for div/rem results
**Backend code-generation impact:** the most notable case is where a user supplies a computed width depending on `getWidth` as a specified width for a declared Wire/Reg/IO. These widths will change; while the error in the `rem` cases led to over-provisioned widths, the `SInt` `div` case led to excessively small widths. Therefore, the existing behavior of signed division in Chisel could have led to observable functional bugs in hardware.
**Release Notes:**
Previously, Chisel returned incorrect values when …
> Update reported width from div/rem to match FIRRTL results

- .github/workflows/test.yml
- build.sbt
- build.sc
- project/plugins.sbt
(cherry picked from commit 445b5cecb267adcd556627ffea2486b20740d6d4)
This is a manual backport of pull request #1766 done by @jackkoenig.
> Bump to Scala 2.12.13 (bp #1766)

- src/main/scala/chisel3/util/experimental/decoder/QMCDecoder.scala
- src/test/scala/chiselTests/util/experimental/decoder/QMCDecoderSpec.scala
Remove a meaningless `toInt` type conversion in `QMCDecoder` which causes a limitation of 32 on the number of output values.
- bug fix
None.
None.
> Remove a buggy type conversion in decoder

- build.sbt
Very simple change but very helpful when navigating from scaladoc to github.
Also update repo path renaming and use the more universal `€{FILE_PATH_EXT}` rather than `€{FILE_PATH}.scala`
documentation
None
None
squash
Add file line to source link from scaladoc
> Add file line to source link from scaladoc

- .github/workflows/test.yml
- build.sbt
- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Element.scala
- core/src/main/scala/chisel3/Mem.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/experimental/Analog.scala
- core/src/main/scala/chisel3/internal/Binding.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- no-plugin-tests/src/test/scala/chisel3/testers/TestUtils.scala
- no-plugin-tests/src/test/scala/chiselTests/ChiselSpec.scala
- no-plugin-tests/src/test/scala/chiselTests/InstanceNameSpec.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
As you can see in the diff of `Builder.scala`, currently, every single `HasId` (which `Data`, `BaseModule` and `MemBase` extend) is added to the `_ids` of its parent Module. Thus, no `HasId` can ever be garbage collected. This is obviously terrible for memory use, especially because we create a lot of unnecessary `Data` objects that are never used. By changing the behavior so that `BaseModule` and `MemBase` are still added, but `Data` is only added upon binding, now `Data` can be GC-ed.
This PR also adds a new test-suite `noPluginTests`. This is essentially a Scala project that just recompiles some of the normal Chisel tests without the Chisel compiler plugin and runs them. I found that the tests `InstanceNameSpec.scala` failed without the plugin, so I made a minimal project that just …
> Make Data GC-able

- core/src/main/scala/chisel3/experimental/Analog.scala
- core/src/main/scala/chisel3/internal/Error.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Fix bug in stack trace trimming behavior. Now, the following is what
happens:
1. The Builder, if catching accumulated errors, will now throw a
ChiselException with a Scala-trimmed Stack trace. Previously, this
would throw the full excpetion.
2. The Elaborate phase handles stack trace trimming. By default, any
Throwable thrown during elaboration will have its stack
trace *mutably* trimmed and is rethrown. A logger.error is printed
stating that there was an error during elaboration and how the user
can turn on the full stack trace. If the --full-stacktrace option
is on, then the Throwable is not caught and only the first
logger.error (saying that elaboration failed) will be printed.
3. ChiselStage (the class), ChiselStage$ (the object), and ChiselMain
all inherit the behavior of (2). …
> Fix stack trace trimming across Driver/ChiselStage

- core/src/main/scala/chisel3/experimental/Analog.scala
- core/src/main/scala/chisel3/internal/Error.scala
- src/main/scala/chisel3/Driver.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselStage.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala
- src/test/scala/chiselTests/DriverSpec.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Manual backport of #1771.
This adds everything in #1771 and also fixes exception behavior for the `Driver`. Stack trace trimming is handled inside the `Elaborate` phase. The `Driver` then swallows the exception and prints it a fake stack trace.
This removes any usage of `StageError` inside the `Driver`.
> Dev/seldridge/issue 1763 3.4.x

- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/aop/Aspect.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/phases/AspectPhase.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/main/scala/chisel3/util/experimental/getAnnotations.scala
- src/test/scala/chiselTests/Module.scala
Resolve #1729
depends on #1730
add API `chisel3.util.experimental.getAnnotations` to get `AnnotationSeq` in current phase.
None
Expose AnnotationSeq to Module.
> Expose AnnotationSeq to Module.

- src/main/scala/chisel3/util/Decoupled.scala
- bug fix
None
None
Fix conversions between DecoupledIO and IrrevocableIO
> Fix conversions between DecoupledIO and IrrevocableIO

- .gitignore
- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
- src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
This annotation adds memory import with inline generation for the
emmiter.
Supports both readmemh and readmemb statements based on argument.
This PR depends on FIRRTL version with merged PR https://github.com/chipsalliance/firrtl/pull/2107.
Example code:
```scala
package utils
import chisel3.util.experimental.loadMemoryFromFileInline
class DualPortRAM(words: Int = 1, width: Int = 32, memoryFile: String = "")
extends Module {
val addrWidth = chiselTypeOf((words * 1024).U)
val io = IO(new Bundle {
// Port 1
val addr1 = Input(addrWidth)
val addr2 = Input(addrWidth)
val dataIn1 = Input(UInt(width.W))
val we1 = Input(Bool())
val dataOut1 = Output(UInt(width.W))
val dataOut2 = Output(UInt(width.W))
})
val mem = SyncReadMem(words, UInt(width.W))
loadMemoryFromFileInline(mem, …
```
> Import memory files inline for Verilog generation

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
Some 2.11 tests caught this issue in https://github.com/chipsalliance/chisel3/pull/1810 since they don't run with the plugin.
Because this is already fixed there, this PR doesn't need backporting.
Basically, the problem is that the check I added in https://github.com/chipsalliance/chisel3/pull/1804 for disabling reflective autoclonetype triggers if reflective autoclonetype happens outside of a Builder context. This changes makes `Builder.allowReflectiveAutoCloneType` succeed if there is no `DynamicContext`. Because `allowReflectiveAutoCloneType` is only used in testing, this is the correct thing to do.
- [NA] Did you add text to be included in the Release Notes for this …
> allowReflectiveAutoCloneType must work outside of Builder context

- src/test/scala/chiselTests/experimental/verification/VerificationSpec.scala
Change a test to use emitChirrtl instead of emitFirrtl. This test
isn't supposed to be running the Scala FIRRTL Compiler, but the latter
method causes this to happen.
This fixes a mistake I introduced in b0389cc905eb19103cc4bc55e9ec9666c9939dca.
- [n/a] Did you add Scaladoc to every public function/method?
- [n/a] Did you add at least one test demonstrating the PR?
- code cleanup
None.
None.
> Fix incorrect usage of emitFirrtl in test

- src/main/resources/chisel3/top.cpp
Change top.cpp to deassert reset one time unit before the clock
asserts.  This avoids a simultation race condition if Chisel and a
FIRRTL compiler emit Verilog where a synchronous reset is not inside
the always block even though the Verilog is formally equivalent.
Reset now deasserts on time unit 10 and the clock ticks on time unit
11.
Concretely, the previous formulation of `top.cpp` is sensitive to changes in the Verilog emission that cropped up when trying to use `llvm/circt` purely for the Low -> Verilog path. This would result in things like the following two formally equivalent circuits resulting in simulation mismatches.
The Scala FIRRTL Compiler produces something like:
```verilog
module A(input clock, reset);
reg [1:0] count;
wire [1:0] _wrap_value_T_1 = count + 2'h1;
always …
```
> Don't toggle top.cpp clock and reset on same cycle

- src/main/scala/chisel3/util/BitPat.scala
- src/test/scala/chiselTests/util/BitPatSpec.scala
Required by `util.experimental.decoder` (WIP, new name is `util.experimental.minimizer`). Use the string representation of BitPat as key of the cache map to provide reusability when generating minimized logic.
And also useful for normal usages.
- new feature
Add `toString` method to `BitPat`
No
- Squash: The PR will be squashed and merged.
BitPat can now produce meaningful string representation.
> Add toString method to BitPat

- build.sbt
- plugin/src/main/scala-2.12/chisel3/internal/plugin/ChiselPlugin.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
Follow on to https://github.com/chipsalliance/chisel3/pull/1804, make the compiler plugin autoclonetype be always on and thus used in chisel3 itself.
- performance improvement 
- new feature/API  
As described in the release notes in https://github.com/chipsalliance/chisel3/pull/1804 and reflected in the test change, this will cause issues for any Bundle that inherits from a Bundle in `chisel3.util` if the code is not also compiled using the compiler plugin. Thus, this change can only occur on the major version bump.
- Squash
Always generate `cloneType` methods for Bundles using the compiler plugin. This causes a binary and source incompatible change for any Chisel code that does not use the compiler plugin but extends a …
> Make plugin autoclonetype always on

- core/src/main/scala/chisel3/Aggregate.scala
- bug fix  
No impact
No impact
- Squash
Provide explanation on requirement that Vec values be non-empty
> Provide useful message on Vec.apply require

- README.md
Change the link of the chat room from https://gitter.im/chipsalliance/chisel3 to https://gitter.im/freechipsproject/chisel3, no other impact.
> Fix Gitter chat room link

- docs/src/appendix/experimental-features.md
- docs/src/explanations/memories.md
This PR adds documentation to the user guide on using memory initialization.
No API impact, added new documentation for memory initialization.
No backend code generation impacts.
Added documentation on inline memory initialization and usage on synthesis.
> Add documentation guide about memory initialization

- docs/src/explanations/memories.md
- docs/src/explanations/polymorphism-and-parameterization.md
- docs/src/explanations/sequential-circuits.md
No API impact. Just fix for documentation generation.
No impact.
> Fix doc formatting and generation

- README.md
- documentation                      
> Add a link to the Chisel book

- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
Add source locator context to any `.getRefs` in the `Converter` so that when users do unfortunately hit an internal bug, they at least know which line to look at so they can do _something_.
Related to #1466 
This is sort of impossible to test because if we do hit this, it's a bug that needs to be fixed. I happen to be working on some changes where I did hit this so I used my local changes for developing this.
I wanted to make the `SourceInfo` argument implicit since we're just threading it through and it's a bit of a pain, but because we have a materializer macro for `SourceInfo`, that's no good (if we forget to have one in scope it'll just point into the Converter.scala file itself lol).
- [NA] Did you add appropriate …
> Add some error context to Converter .getRefs

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Element.scala
- core/src/main/scala/chisel3/experimental/package.scala
- core/src/main/scala/chisel3/internal/Binding.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- docs/src/appendix/experimental-features.md
- src/test/scala/chiselTests/BundleLiteralSpec.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/VecLiteralSpec.scala
Add support for Vec literals
Similar to Bundle literals, this PR extends the API with two methods of creating Vec literals.
Inferred:
```
Vec.Lit(0x1.U, 0x2.U)
```
or explicit:
```
Vec(2, UInt(4.W)).Lit(0 -> 0x1.U, 1 -> 0x2.U)
```
Explicit form allows for partial, or sparse, literals, and provides a mechanism for creating a literal from an existing
Vec literals can be used as Register initializers
Inferred form will set the element width to largest element width
Error checks in include: elements specified twice, width larger than
explicit type
Extensive test suite.
Features
- Can be defined outside of module (enables use with chiseltest library)
- Can be sparsely specified (with the effect that top level `litOption` returns None)
- litOption behaves like to UInt in bit ordering
- works as …
> Introduce VecLiterals

- docs/src/cookbooks/cookbook.md
Elaborating the Chisel module Salt yields our “desire name” for Salt and Coffee in the output Verilog: Elaborating design… [[34mdeprecated[0m] class repl.MdocSession$App12$Salt\(anonfun$80\)anonfun$apply$38\(anon$7 (1 calls): chisel3.1 autoclonetype failed, falling back to 3.0 behavior using null as the outer instance. Autoclonetype failure reason: Unable to determine instance of outer class class repl.MdocSession$App12$Salt\)anonfun$80\(anonfun$apply$38, no candidates assignable to outer class types; examined List(repl.MdocSession$App12$Salt@2b5e67c4) [[34mdeprecated[0m] class repl.MdocSession$App12$Coffee\)anonfun$77\(anonfun$apply$37\)anon$6 (1 calls): chisel3.1 autoclonetype failed, falling back to 3.0 behavior using …
> Cookbook: clean up desiredName example

- core/src/main/scala/chisel3/experimental/verification/package.scala
- src/test/scala/chiselTests/experimental/verification/VerificationSpec.scala
- x Did you add Scaladoc to every public function/method?
- behavior change for consistency
- guards the new `assert`, `assume` and `cover` statements with the current default reset
- this will change the Verilog to disable verification statements when reset is active
- squash
Assert, assume and cover statements are now disabled during reset by default. If you want your assertion to be active at all times, you can create a reset scope with reset=false.
> verification: guard statements with module reset

- src/main/scala/chisel3/util/Reg.scala
- src/test/scala/chiselTests/Reg.scala
- bug fix
This PR adds API `ShiftRegisters` to expose each register inside the original ShiftRegister, which only return the last instance of register.
This PR enable rename, annotate internal registers for a `ShiftRegister`.  
Fix bug #1722 
API addition: add `ShiftRegisters`, return the sequence of shift register
> add ShiftRegisters to expose register inside ShiftRegister.

- src/main/scala/chisel3/util/Reg.scala
- src/test/scala/chiselTests/Reg.scala
if ShiftRegisters is empty, scala will complain:
```
java.util.NoSuchElementException
scala.collection.LinearSeqOptimized.last(LinearSeqOptimized.scala:150)
```
This PR:
1. fix this issue and return `in` directly when ShiftRegister size is 0.
1. Add test to check ShiftRegister(s) with delay is 0. 
- bug fix
None
No
> Fix ShiftRegister with 0 delay. 

- build.sbt
- build.sc
ChiselStage -> Stage(from firrtl) -> scopt, Chisel no longer explicitly depends on scopt. 
I forgot to remove this in #1730
- code cleanup
None
None
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit. 
None
> remove scopt dependency.

- src/test/scala/chiselTests/EndToEndSMTBaseSpec.scala
- src/test/scala/chiselTests/SMTModelCheckingSpec.scala
This PR depends on #1904 
This PR implements a basic model checking for chisel internal test with @ekiwi's great work.
Add EndToEndSMTBaseSpec for chiselTests(internal test)
None
None
> implement model checking API for chiseltest

- src/main/scala/chisel3/util/experimental/pla.scala
- src/main/scala/chisel3/util/pla.scala
- src/test/scala/chiselTests/util/experimental/PlaSpec.scala
This PR implements PLA, authored by @yqszxx
> Implement PLA

- src/main/scala/chisel3/util/BitPat.scala
- src/test/scala/chiselTests/util/BitPatSpec.scala
fix #1919 
- bug fix
None
None
> throw exception if BitPat width is 0 

- src/main/scala/chisel3/util/BlackBoxUtils.scala
- src/main/scala/chisel3/util/ExtModuleUtils.scala
- src/test/scala/chiselTests/BlackBoxImpl.scala
- src/test/scala/chiselTests/ExtModuleImpl.scala
Other.
Change Chisel to never emit `BlackBoxResourceAnno`. This improves the separation between Chisel and a FIRRTL compiler. The semantics of locating the file associated with a `BlackBoxResourceAnno` is that of Java Resources. This is fine if a FIRRTL compiler is implemented on top of the JVM. However, if the FIRRTL compiler is _not_ implemented on the JVM, then it makes the Chisel classpath part of what is necessary to pass to the FIRRTL compiler (and that a FIRRTL compiler needs to handle Java resource finding).
No.
> Stop Emitting BlackBoxResourceAnno

- src/main/scala/chisel3/util/Reg.scala
- src/test/scala/chiselTests/Reg.scala
Backport #1903 to 3.4.x as 3.4.x is currently busted without it. 😭
> Manual Backport of #1903

- src/main/scala/chisel3/util/experimental/decode/DecodeTableAnnotation.scala
- src/main/scala/chisel3/util/experimental/decode/Minimizer.scala
- src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
- src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
- src/main/scala/chisel3/util/experimental/decode/decoder.scala
- src/test/scala/chiselTests/util/experimental/DecoderSpec.scala
- src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
- src/test/scala/chiselTests/util/experimental/minimizer/MinimizerSpec.scala
- src/test/scala/chiselTests/util/experimental/minimizer/QMCSpec.scala
> Implement QMC decoder

- build.sbt
- build.sc
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/ExtModuleImpl.scala
I sometimes run into issues where the build is trying to use scalatest 3.2.2 even though we still have it set for 3.1.2. I think this is due to https://github.com/chipsalliance/chisel3/pull/1908 which itself depends on scalatest 3.2.2 so there might be inconsistency between different dependency resolvers (whether one uses Ivy or Coursier) that causes some builds to fail.
Easiest way to fix this issue is to just go ahead and bump.
- test dependency bump
- 
No impact, but in our tests we have to use the `Any*spec` style now
No impact
- Squash
> Bump scalatest to 3.2.9

- src/test/scala/chiselTests/SMTModelCheckingSpec.scala
Hard coded `\n` results in false-positive assertion failures and confusing error messages in SMT checker when using Z3 on Windows.
The output log was: `java.lang.AssertionError: assertion failed: Unexpected output: unsat` but `unsat` is actually an acceptable output.
- bug fix
No.
No.
> Replace hard coded line separators with system specific ones in SMT checker

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/CloneModuleSpec.scala
This fixes an issue where you cannot currently annotate the fields of the `Record` returned by `CloneModuleAsRecord`.
This is due to the fact that `CloneModuleAsRecord` violates many assumptions in the Chisel internals and currently only works for generating FIRRTL by coincidence. I wanted to make it as first class as possible without a full refactor of the internals.
Basically, there are 3 pieces of bookkeeping (often with duplicated information) that need to be in sync and "correct" with regard to the baked-in assumptions in the compiler:
* binding - used mostly for correctness checking 
*  `_ref` - the "IR" information for most things, used for generating FIRRTL and for generating targets
* `_parent` - the parent module, used for generating targets, correctness checking, and in …
> Fix CloneModuleAsRecord support for .toTarget

- core/src/main/scala/chisel3/Module.scala
- src/main/scala/chisel3/aop/Select.scala
- src/test/scala/chiselTests/aop/SelectSpec.scala
It turns out the behavior of `Select` differs from what we discussed in dev today, it actually returns the same module multiple times when you have `CloneModuleAsRecord` clones. Perhaps this isn't what we want, but I decided to add a test (that passed prior to https://github.com/chipsalliance/chisel3/pull/1974 and failed after it).
We could filter out these duplicates, but I wanted to document the behavior and discuss on this PR.
**EDIT:**
I have pushed another commit that changes this behavior to the intended behavior
Previously, CloneModuleAsRecord clones would result in the same BaseModule object coming up multiple times when using APIs like .instances, .collectDeep, and .getDeep. This was not the intended behavior and can lead to very subtle bugs.
- [NA] Did you add Scaladoc to every …
> Fix aop.Select behavior for CloneModuleAsRecord

- core/src/main/scala/chisel3/StrongEnum.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/Error.scala
- docs/src/explanations/chisel-enum.md
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/StrongEnum.scala
Add ChiselEnum.safe factory method and avoid warning
Previously, ChiselEnum would warn any time a UInt is converted to an
Enum. There was no way to suppress this warning. Now there is a factory
method (`.safe`) that does not warn and returns (Enum, Bool) where the
Bool is the result of calling .isValid on an Enum object. The regular
UInt cast is also now smarter and will not warn if all bitvectors of the
width of the Enum are legal states.
I also added a useful testing utility to capture Logging information
I need to update the mdoc to include this information (and a few stylistic changes), will push another commit with that.
- bug fix     
- new feature/API   
Adds `ChiselEnum.safe` for safely casting from `UInt` to an Enum
No impact
- Rebase
Stop warning when casting from `UInt` to a …
> Fix ChiselEnum warnings and use Logger for warnings instead of println

- docs-target/src/main/scala/chisel3/docs/VerilogMdocModifier.scala
- docs/src/explanations/chisel-enum.md
Also add newline to end of `verilog` modifier code blocks so that there
is always a newline between code blocks and following material.
- documentation           
No impact
No impact
- Squash
> Fix ChiselEnum docs

- core/src/main/scala/chisel3/dontTouch.scala
Change the Scaladoc for the dontTouch utility.  Indicate that this is an
_optimization barrier_ and not just a guarantee that the signal won't be
removed.  The optimization barrier interpretation is the current
implementation in the Scala FIRRTL Compiler.
- [n/a] Did you add at least one test demonstrating the PR?
- documentation                      
None.
None.
> Update docs on dontTouch as optimization barrier

- core/src/main/scala/chisel3/StrongEnum.scala
- docs/src/explanations/chisel-enum.md
- src/test/scala/chiselTests/StrongEnum.scala
- Adds user-facing `isOneOf` method to `ChiselEnum` value type (`EnumType`).
- No impact
- Added `isOneOf` method to `ChiselEnum` to reduce boilerplate when checking if the current value is in a set of given values.
> Add `isOneOf` method to `ChiselEnum`

- core/src/main/scala/chisel3/internal/BiConnect.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
BiConnect in chisel3 delegates to FIRRTL <- semantics whenever it hits a
Bundle defined in `import Chisel._`. Because chisel3 <> is commutative
it needs to be mindful of flippedness when emitting a FIRRTL <- (which
is *not* commutative).
- bug fix
No impact, just a bugfix
No impact
- Squash
Fix handling of `import Chisel._` Bundles when used as elements in `import chisel3._` Bundles when connecting with `<>`.
> Fix chisel3 <> for Bundles that contain compatibility Bundles

- core/src/main/scala/chisel3/Bits.scala
- core/src/main/scala/chisel3/internal/MonoConnect.scala
- src/test/scala/chiselTests/ResetSpec.scala
This has been legal in FIRRTL since v1.2.3 (when reset inference started
using a unification-style algorithm) but was never exposed in the Chisel
API.
Also delete the overridden connects in AsyncReset and ResetType which
just duplicate logic from MonoConnect.
- new feature/API  
This makes it legal to drive a concrete reset (`Bool()` or `AsyncReset()`) with an abstract reset (`Reset()`), this has been legal in FIRRTL since v1.2.3 and was always intended to be exposed in Chisel but I forgot 🙃 
No impact
- Squash
Make it legal to drive a concrete reset (`Bool()` or `AsyncReset()`) with an abstract reset (`Reset()`). Reset inference in FIRRTL works both forwards and backwards so the connection to the concrete reset will influence …
> Make it legal for concrete resets to drive abstract reset

- core/src/main/scala/chisel3/internal/BiConnect.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
PR #2023 fixed a composition issue for chisel3 biconnects delegating to
FIRRTL partial connect when compatibility mode Bundles are elements of
chisel3 Bundles. It missed an important case though that caused
previously working code to break.
The bug is fixed by doing the automatic flipping for compatibility mode
Bundles that have "Input" as a direction in addition to those that are
"Flipped".
- bug fix
No impact
No impact
- Squash
(Not applicable - fixing an unreleased bug)
> Fix chisel3 <> for Bundles that contain compatibility Bundles (Take 2)

- .github/workflows/test.yml
- src/main/scala/chisel3/util/experimental/decode/EspressoMinimizer.scala
- src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
- src/main/scala/chisel3/util/experimental/decode/decoder.scala
- src/test/scala/chiselTests/util/experimental/minimizer/EspressoSpec.scala
<del> 1. Implement espresso wrapper. </del>
<del> 2. upstream espresso. </del>
<del> 3. add espresso CI. #2003 </del>
4. merge this PR
Espresso generated PLA maybe different from QMC generated, for legacy QMC users, including SiFive and RocketChip users.
Decode circuit maybe different, but formally equivalent. 
Add Espresso Decoder
> Espresso Decoder

- core/src/main/scala/chisel3/SeqUtils.scala
- no-plugin-tests/src/test/scala/chiselTests/BetterNamingTests.scala
- no-plugin-tests/src/test/scala/chiselTests/CatSpec.scala
- no-plugin-tests/src/test/scala/chiselTests/CustomBundle.scala
- no-plugin-tests/src/test/scala/chiselTests/NamingAnnotationTest.scala
- src/test/scala/chiselTests/CustomBundle.scala
- src/test/scala/chiselTests/RecordSpec.scala
- src/test/scala/chiselTests/util/CatSpec.scala
- bug fix
No
It would rename intermediate node to `hi` or `lo` when use `SeqUtils.asUInt` for a sequence.
Rebase
Fix #2010
> Fix Cat rename signal #2010

- README.md
The example in the README is a sum, not an average.
h/t @soronpo and @BracketMaster for discussions on Gitter: https://gitter.im/freechipsproject/chisel3?at=60f4adc0ec10653d5a49fe18, also discussed in dev: https://github.com/chipsalliance/chisel3/discussions/2049
I thought about making it average over 4 cycles and using a right-shift to do a proper divide, but the purpose of the example is leading into the generalized FIR filter that follows so I kept it the same and just renamed it.
Marked 3.4.x so this change is reflected on the website.
- [NA] Did you add text to be included in the Release Notes for this …
> MovingAverage3 => MovingSum3

- core/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/BundleSpec.scala
Bug fix
Changes existing API: Code previously taking advantage of `Bundle`s with bound hardware elements will crash.
No impact
`Bundle`s can no longer be instantiated with value bindings or bound hardware. Fixes #1894
> Bundles can no longer be instantiated with bound hardware

- .github/workflows/test.yml
Something is wrong with the Z3 caching and it rebuilds every time. On @ekiwi's suggestion, since the version of Z3 really doesn't matter for our tests and doesn't affect users (unlike Verilator and Espresso), we should just use the apt-get version.
If we need to build from source in the future for some reason, we can, but there's really no need for the complexity at the moment.
- CI fix
No impact
No impact
- Squash (**Please squash** I screwed up the branch name lol)
> Install Z3 with apt-get in CI

- core/src/main/scala/chisel3/Aggregate.scala
- macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- src/test/scala/chiselTests/Vec.scala
- new feature/API                    
This PR adds additional companion object factory methods to the VecInit class, such as .fill and .iterate.
A .empty method was not added because VecInit does not allow for empty hardware values at this time.
This should not change the backend code generation as it only provides different ways to fill a Vec.
This PR adds additional companion object factory methods to the VecInit class, such as .fill and .iterate.
> Added VecInit factory methods (fill,iterate)

- docs/src/cookbooks/cookbook.md
This question came up on gitter: https://gitter.im/freechipsproject/chisel3?at=6117c83e7555e333510edb83
No impact
No impact
- Squash
> [docs] Add example of stripping directions from type

- core/src/main/scala/chisel3/internal/Builder.scala
This does break user visible behavior. However, I see no other way to prevent unit tests that go through a bunch of different designs from printing out:
```
Elaborating design...
Done elaborating.
Elaborating design...
Done elaborating.
Elaborating design...
Done elaborating.
Elaborating design...
Done elaborating.
Elaborating design...
Done elaborating.
```
with no end and no information to the user where this message is coming from.
- change message severity from `warn` to `info`
- elaborating a design does not print out `Elaborating` design by default anymore.
- none
- squash
- Builder: when elaborating a chisel design the "Elaborating design..." and "Done elaborating." message is no longer shown by default. Set the log level to `info` in order to see it.
> Builder: downgrade "Elaborating design" message to info

- .github/workflows/test.yml
- core/src/main/scala/chisel3/Aggregate.scala
- docs/src/cookbooks/cookbook.md
- macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- src/test/scala/chiselTests/Vec.scala
- new feature/API   
This extends the tabulate and fill functions for VecInit to create multi-dimensional Vecs 
Ex. Vec[Vec[UInt]]
This should not change the backend code generation as it only provides different ways to fill a multi-dimensional Vec.
This PR adds builds upon companion object factory methods for the VecInit class, .fill and .iterate, to include multi-dimensional Vecs.
> Add multiple dimensions to VecInit fill and iterate 

- core/src/main/scala/chisel3/Mem.scala
- integration-tests/src/test/scala/chiselTest/MemFormalSpec.scala
This essentially fixes a bug where in the following code, the read enable would always be false:
```.scala
class BrokenMem extends MultiIOModule {
val addr = IO(Input(UInt(5.W)))
val out = IO(Output(UInt(8.W)))
val mem = SyncReadMem(32, UInt(8.W))
out := mem.read(addr)
}
```
You can see the full example [here](https://scastie.scala-lang.org/wLIQK1bKQvaD6FkMTb04Vg)
- bug fix
- none
- read enables now work in the one situation that I described above
- squash
> SyncReadMem: fix bug with read(addr) and add some formal tests

- core/src/main/scala/chisel3/internal/BiConnect.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
Third time's the charm?
Previous incomplete fixes in #2023 and #2031.
The legality of a FIRRTL connection is determined by type and flow.
Chisel does not have access to true flow information. Previous fix
attempts tried to use ActualDirection as a stand-in for flow, but it is
incorrect in many cases. This new approach checks the flows of the
lvalue and rvalues in the connect and flips the connection if either
the lvalue cannot be a sink or the rvalue cannot be a source.
**Note** I marked this for backporting to 3.2.x because the previous 2 PRs were and this is a fix to those fixes.
- bug fix   
No impact
No impact
- Squash
Fix handling of `import Chisel._` Bundles when …
> Fix chisel3 <> for compatibility Bundles (Take 3)

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Instance.scala
- core/src/main/scala/chisel3/experimental/hierarchy/IsInstantiable.scala
- core/src/main/scala/chisel3/experimental/hierarchy/IsLookupable.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
- core/src/main/scala/chisel3/experimental/hierarchy/package.scala
- core/src/main/scala/chisel3/internal/Binding.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- docs/src/cookbooks/hierarchy.md
- macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
- macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
- src/main/scala/chisel3/aop/Select.scala
- src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/aop/SelectSpec.scala
- src/test/scala/chiselTests/experimental/DataView.scala
- src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Annotations.scala
- src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Utils.scala
Starting to work on an official PR. More edits coming! For now, this is a DRAFT PR.
- (Jack) Dogfood Queue with this API (the companion object apply method that returns `Decoupled[T]`)
- Try to make `@instantiable` optional
- Try to make `@public` optional on ports
- Try to make `@public` work on vals in the class constructor
- Try to put the `@instantiable` implicit class in the type's companion object for better implicit resolution
- Write explanation mdoc (not just cookbook)
- Consider making module visible from definition, so you can inspect a definition's parameters etc.
- Consider composition of Definitions outside of a chisel stage. For example, should we have an emitDefinition from a stage?
- Enable reconstitution of a definition which was elaborated in a separate JVM invocation, …
> Instance/Definition (formerly Template)

- src/main/scala/chisel3/util/pla.scala
- src/test/scala/chiselTests/util/experimental/PlaSpec.scala
- bug fix
No.
Extracted from ScalaDoc:
```
There is one special case which we call it `? -> 1`. In this scenario, for some of the output functions (bits),
all input terms that make this function value to `1` is purely composed by `?`. In a real pla, this will result in
no connection to the gates in the AND Plane (verilog `z` on gate inputs), which in turn makes the outputs of the
AND Plane undetermined (verilog `x` on outputs). This is not desired behavior in most cases, for example the
minimization result of following truth table:
0 -> 1
1 -> 1
which is:
? -> 1
actually means something other than a verilog `x`. To ease the generation of minimized …
```
> Fix a bug causes incorrect pla generation when input is `?`

- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Instance.scala
- core/src/main/scala/chisel3/internal/Builder.scala
Definition/Instance introduced the need for representing the targets of
instances as InstanceTargets. This original implementation changed the
return type of BaseModule.toTarget to express this need. This is a
backwards incompatible change that is actually unnecessary because it is
impossible for users to get references to the internal InstanceClone
objects, instead only accessing such modules via Instance[_] wrappers
and cloned Data. We restored the old API by adding a new internal method
"getTarget" which will give the correct targets for InstanceClones while
maintaining the API of BaseModule.toTarget.
This fixes the issue @sequencer noted https://github.com/chipsalliance/chisel3/pull/2045#issuecomment-913349957. I expect similar issues to drop up elsewhere so I thought it best to try …
> Restore return type of BaseModule.toTarget to ModuleTarget

- .github/workflows/test.yml
- build.sbt
- build.sc
Also update previous version for binary compatibility checking.
- new feature/API     
Should have done this before release Chisel 3.4.4, this will ensure the chisel3 plugin will be published for Scala 2.12.14 and 2.12.15 in Chisel 3.4.5
No impact
- Squash
Update Scala, publish chisel3-plugin for Scala 2.12.14 and 2.12.15
> [3.4.x] Update Scala so that plugin (mainly for plugin)

- .github/workflows/test.yml
Z3 caching is again broken and increasing CI latency by ~50%, and worse than that, the entire added latency occurs before the useful CI checking. I'm failing to see the value of building it from source so why don't we just install such things from packages until it becomes a problem and only then build from source.
- bug fix                   
- CI performance improvement       
None
None
- Squash
> Just install Z3 from apt-get in CI

- .github/workflows/test.yml
- build.sbt
Bump Scala to so that plugin publishes for more minor versions of Scala.
- new feature/API 
This publishes the plugin for more minor versions of Scala
No impact
- Squash
Publish chisel3-plugin for Scala 2.12.14, 2.12.15, and 2.13.6
> Update Scala and publish plugin for more minor versions

- core/src/main/scala/chisel3/experimental/Trace.scala
- src/test/scala/chiselTests/experimental/TraceSpec.scala
This API provides a function to inspect the final `Target` via `Data` name, which provides a better functionality for verifications flow to get the REAL hierarchy and signal name with chisel in-memory `Data`.
More tests and demos is TBD.
Basically, this can improves a symbol table from `HasId`(`Data`, `Module`) to `Target`, you can `tap` in the code during the elaboration time, and `view` it `Target` out of `Builder`.
For different simulation backends, this can enable internal signal peek/poke flow via:
1. Verilator has [config](https://verilator.org/guide/latest/extensions.html?highlight=config#cmdoption-verilator-public_flat_rw) file.
2. VCS can directly see internal signal if a full name/hierarchy is provided.
3. just convert the Target to treadle symbol table is enough to use treadle …
> Signal Trace API

- src/main/scala/chisel3/experimental/verification/package.scala
The deprecation message in my previous PR was off by one.
> verification: fix off by one error in deprecation message

- build.sbt
- documentation  
No impact
No impact
- Squash
> Turn on fatal warnings in mdoc documentation

- docs/src/explanations/dataview.md
This was fixed in the latest version of mdoc (that we have already bumped to).
No impact
No impact
- Squash
> Remove workaround for fixed issue in mdoc crash blocks

- core/src/main/scala/chisel3/internal/plugin/package.scala
This only existed to maintain binary compatibility with the v3.4.0 version of the chisel3-plugin in version v3.4.1 and beyond. We break binary compatibility in v3.5.0 anyway.
- code cleanup      
This does break a technically public API but not one users are supposed to use (and hidden from ScalaDoc). It also breaks binary compatibility with the v3.4.0 version of the plugin but that is expected in a major release and we will likely have further breakages (like requiring the plugin in v3.5.0 and beyond).
No impact
- Squash
Break binary compatibility with v3.4.0 version of chisel3-plugin.
> Remove v3.4.0 version of autoNameRecursively

- src/main/scala/chisel3/util/Decoupled.scala
Using factory `Queue(..., hasFlush = true)` won't take effects, since in the `Queue.apply` API, `Queue` Module is not exposed, thus even user defines `hasFlush = true`, there is no place for them to give the `flush` signal.
This commit fix this, refactor `Queue.hasFlush: Boolean` to `Queue.flush: Option[Bool]`, makes user be able to pass the flush signal into `Queue` Module.
- bug fix
change API Queue.apply API
None
None
> refactor Queue.hasFlush: Boolean to Queue.flush: Option[Bool].

- src/test/scala/chiselTests/IntervalSpec.scala
Compiling bug introduced by chipsalliance/firrtl#2421, safe to remove
Fixes https://github.com/chipsalliance/chisel3/issues/2255
- bug fix
> fix for chipsalliance/firrtl#2421

- src/test/scala/chiselTests/BlackBoxImpl.scala
- src/test/scala/chiselTests/InlineSpec.scala
- src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
- src/test/scala/chiselTests/TransitNameSpec.scala
This fixes CI which fails with current firrtl 1.5-SNAPSHOT.
- bug fix (in tests)
No impact
No impact
- Squash
> Remove unused imports for API removed from firrtl

- core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
- bug fix                          
Extends Builder `build` by adding an optional `forceModName` parameter 
Definitions created with the D/I API that have the same name will be indexed as `Defn`, `Defn_1`, ... instead of `Defn`, `Defn_2`, ... . This matches the behavior for module instances created without D/I (that is, as `Module(new Defn())`
> Bugfix - definition name index skipping with D/I

- README.md
Include plugin in instructions since it will be required in 3.5.
Also make sure the example actually works.
Needed `-Xsource:2.11` to compile normal Chisel using a structurally-typed IO Bundle. Also the chisel3 plugin is not published for 2.12.14 and 2.12.15 for chisel3 3.4.4 so we need to pin the Scala version as well.
No impact
No impact
- Squash
> Update REAMDE instructions for building projects

- docs/src/cookbooks/cookbook.md
Remove the body from the emitted Verilog. This was the original intent
of the example, and it avoids an issue where Jekyll was not able to
render the Markdown file due to Verilog concatenation looking like a
variable escape.
This works around an issue (see https://github.com/freechipsproject/www.chisel-lang.org/pull/216) where https://github.com/chipsalliance/chisel3/pull/2278 is not yet live on the website because Jekyll thinks Verilog concatenation in the code example is a variable escape. We could work around this in different ways, but @oharboe's original intent (see https://github.com/chipsalliance/chisel3/pull/2278#discussion_r762405572) was that the Verilog would just have the ports anyway
- [NA] Did you add text to be …
> [docs] Remove body from minimizing output bits recipe

- core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala
- core/src/main/scala/chisel3/experimental/dataview/DataView.scala
- core/src/main/scala/chisel3/experimental/package.scala
- docs/src/explanations/dataview.md
- src/main/scala/chisel3/experimental/conversions/package.scala
- src/test/scala/chiselTests/experimental/DataView.scala
- src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
- src/test/scala/chiselTests/experimental/Tuple.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Fixes https://github.com/chipsalliance/chisel3/issues/864 (at long last!)
Implemented in new chisel3.experimental.conversions package. Includes:
* Implementations of DataProduct
* Implementations of DataView from Seq to Vec and Tuple to HWTuple
* Implicit conversions from Seq to Vec and Tuple to HWTuple
Examples are buried in the tests, but this makes it possible to write stuff like:
```scala
class MyModule extends Module {
val a, b, c, d = IO(Input(UInt(8.W)))
val sel = IO(Input(Bool()))
val y, z = IO(Output(UInt(8.W)))
(y, z) := Mux(sel, (a, b), (c, d))
}
```
and
```scala
class MyModule extends Module {
val a, b, c, d = IO(Input(UInt(8.W)))
val out = IO(Output(Vec(4, UInt(8.W)))
out := Seq(a, b, c, d)
}
```
I still haven't implemented more than just Tuple2, I intend to do several, maybe …
> Implement DataViews for Seq and Tuple

- docs/src/appendix/versioning.md
Marked for backport so that this info is available on current website (especially since 3.5.0-RC1 has been released).
- documentation        
No impact
No impact
- Squash
> [docs] Update versioning appendix to include 3.5

- src/main/scala/chisel3/util/BitPat.scala
- src/test/scala/chiselTests/util/BitPatSpec.scala
Resolves #2268, thanks @Tang-Haojin 
- bug fix
None
None
None
> catch None.get in BitPat.apply(x: UInt): BitPat

- core/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
preserves input/output information of the type being reduced.
> reduceTree() now operates on Seq

- core/src/main/scala/chisel3/package.scala
This returns an internal API after #2274 being merged.
- code cleanup
> deprecate getModulePorts

- docs/src/appendix/appendix.md
- docs/src/appendix/upgrading-from-chisel-3-4.md
- docs/src/appendix/upgrading-from-scala-2-11.md
This new document is a place to describe issues users may run into when
upgrading from Chisel 3.4 to 3.5. This initial version includes the
solution for the removal of virtual method "val io".
Inspired by the question on chisel-users: https://groups.google.com/g/chisel-users/c/OtRSISNvHeA/m/DQNzCSj3AgAJ
Here's the result of running mdoc: https://gist.github.com/jackkoenig/4949f6a455ae74923bbcce10dbf846b5
- [NA] Did you state the API impact?
- documentation  
No impact
No impact
- Squash
> Add "Upgrading From Chisel 3.4 to 3.5"

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/Module.scala
Also clean up deprecation warnings for replacement APIs and add
clarifying ScalaDoc.
https://github.com/chipsalliance/chisel3/pull/2274 made `Port` private but it's present in public (and used) APIs so I've reverted that and deprecated it. Rather than a crazy dance to avoid internal deprecation warnings, I've just embraced the new `@nowarn` annotation to suppress the warnings internally.
Also, the deprecation warnings from https://github.com/chipsalliance/chisel3/pull/1945 and https://github.com/chipsalliance/chisel3/pull/2284 were suggesting the wrong replacement API so I added tests and ScalaDoc to help clarify which `DataMirror` API to use.
- API restoration
This restores a removed API but deprecates it and fixes some deprecation warnings
No impact
- Squash
Deprecate (instead of …
> Restore Port to public API and deprecate

- core/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/BundleSpec.scala
- src/test/scala/chiselTests/RecordSpec.scala
Improve exception message for aliased bundle fields
- Shows groups of field names that share a common id (i.e. aliased)
- Show, as much as possible, them in the order that fields appear in bundle
- Updated BundleSpec's relevant tests
Improves error message
None
None
Squash
The exception thrown when a bundle contains aliased field will now show the field names of the
aliased fields.
> Improve exception message for aliased bundle fields

- .github/workflows/test.yml
- build.sbt
- plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
- plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
- plugin/src/main/scala/chisel3/internal/plugin/ChiselPlugin.scala
Unidoc was apparently not running in CI and it was broken by https://github.com/chipsalliance/chisel3/pull/2277. The issue isn't that #2277 is broken, it's that it exposed the fact that `unidoc` actually runs the same scalacOptions on all of the files being built into 1 doc. This is a problem because Chisel3 `core` needs to not have the compiler plugin run on it, while the downstream `chisel` project does. This is a hacky solution, but it's the best I have, see https://github.com/sbt/sbt-unidoc/issues/107.
Note that this has 3 useful commits. There is a little of refactoring of how the plugin skips components (a component is a Scalac compiler phase).
- [NA] Did you add …
> Fix unidoc

- core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
- src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
- new feature/API   
Adds a LookupableEither implicit, such that one can have `Either`s inside Instances and Definitions that can be looked up.
No change on generated verilog.
Lookupable: Add an Either version
> Lookupable: add Either version

- .github/configs/mergify_config.yml
- .github/workflows/test.yml
- .mergify.yml
* Enable CI for 3.5.x branch
* Enable Mergify for 3.5.x branch
* Drop 3.5.x from Mergify
- code cleanup
No impact
No impact
- Squash
> Update master for 3.5.0 release

- .github/ISSUE_TEMPLATE.md
- README.md
- build.sbt
- build.sc
- version bump
This allows breaking APIs on master (without accidentally breaking 3.5.x SNAPSHOTs
No impact
- Squash
Bump to 3.6-SNAPSHOT
> Bump to 3.6-SNAPSHOT

- integration-tests/src/test/scala/chiselTests/util/GrayCodeTests.scala
- src/main/scala/chisel3/util/GrayCode.scala
- adds two new utility functions to convert binary to gray code and back
- this change does not impact existing code
- squash
> util: add GrayCode

- CONTRIBUTING.md
This only includes a merge-based flow which will presumably be
squash-and-merged for any merged PRs. It is possible to do this with
rebasing but it is tricky and hard to describe in a fool-proof way.
No impact
No impact
- Squash
> Add instructions for updating branches from before Scalafmt

- docs/src/cookbooks/cookbook.md
#naming implies within the current file. Removing the # refers to a file in the current directory.
- documentation     
No impact
No impact
- Squash
> Fix link to Naming Cookbook

- macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
- bug fix
Now supports more modifiers on the val's marked with `@public`, including `final` and `override`.
Support more `val` modifiers like `final` and `override` for `@public`.
> Update supported val modifiers for @public

- integration-tests/src/test/scala/chiselTests/util/experimental/minimizer/MinimizerSpec.scala
- src/main/scala/chisel3/util/experimental/decode/EspressoMinimizer.scala
- src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
Should be optimized to 0
```
00->0
01->?
10->0
11->0
?
```
Should be optimized to `DontCare`
```
00->?
01->?
10->?
11->?
?
```
QMC will optimize to empty for case 0 and case `DontCare`, since it only cares `ON set`.
Espresso by default(`-of`) will return `ON set` as well, so it will also be empty on these two cases.
Espresso will also return another result by `-ofd`(However that's the return which PLA cannot consume).
```
.type fd
.i 2
.o 1
.p 1
01 2
.end
```
So this behavior is because `PLA`, which is the circuit backend of these logic minimizer, only consumes `ON set`.
Both QMC and espresso algorithm are optimizing to a PLA, which means `?` and `0` will finally land to 'OFF set'. This will have a correct behavior for PLA. 
This seems less optimized: circuit result should be `DontCare`, …
> Fix Decoder bug for constant 0 and DC

- core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/Error.scala
- src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselCli.scala
- src/main/scala/chisel3/stage/ChiselOptions.scala
- src/main/scala/chisel3/stage/package.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Inspired by @oharboe's comments here: https://github.com/ucb-bar/chiseltest/pull/501#issuecomment-1024878100.
This gives a little bit of refinement to error reporting.
1. Making sure that our stack trace trimming doesn't accidentally add stack traces to exceptions that don't have them otherwise.
2. Providing a name to the exception thrown by collected errors so that it doesn't have `$$anon$1` in the error message
3. Add `--throw-on-first-error` to give users the option to throw exceptions instead of aggregating recoverable errors
- code cleanup  
This changes how errors are reported to make them a little more clear
No impact
- Squash
Improve recoverable error reporting and add `--throw-on-first-error` for throwing exceptions instead of aggregating recoverable errors.
> Improve error reporting

- core/src/main/scala/chisel3/Mem.scala
- macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
Warn if clock at memory instantiation differs from clock bound at port creation, add tests to MultiClockSpec
- code refactoring                  
- new feature/API                   
Apply functions for creating read/write accessors to Mem and SyncReadMem have an optional parameter `clock`. If this parameter is not passed, the clock for the port is inferred from the context. If the clock passed to the ports (implicit or otherwise) does not match the clock at memory instantiation, a warning is issued. 
No impact
`Mem` and `SyncReadMem` read/write ports accept an optional parameter `clock` for binding a clock that is different from the implicit clock in the current context.
> Optional clock param for memory ports

- build.sbt
Needed so that 3.5.1 [plugin] release will be available for Scala 2.13.8
- new feature/API      
Downstream users will now be able to use Scala 2.13.8 (compiler plugin must be published for every minor version)
No impact
- Squash
The chisel3 plugin is now published for Scala 2.13.8.
> Add Scala 2.13.8 to plugin cross-compilation

- core/src/main/scala/chisel3/Aggregate.scala
- plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
* Change type of `Bundle._elementsImpl` to Iterable
It was previously SeqMap (ListMap on Scala 2.12). This change gives us
more freedom to optimize the implementation without breaking binary
compatibility. It is scala.collection.Iterable because it is perfectly
fine to return mutable collections (like Arrays) since the only use is
to Iterate on them.
* Disallow users implementing `Bundle._elementsImpl`
Currently, it would result in a runtime linkage error. This turns it
into a compile-time error.
Tweak to unreleased feature, no release notes necessary
- code refactoring    
This widens the type of `Bundle._elementsImpl` to `Iterable` so that we can be …
> Tweak Bundle._elementsImpl

- src/main/scala/chisel3/util/Bitwise.scala
no functional change
no generation change
FillInterleaved documentation: order of elements was backwards in Seq example
> FillInterleaved documentation: order of elements was backwards in Seq example

- core/src/main/scala/chisel3/Aggregate.scala
I previously measured that https://github.com/chipsalliance/chisel3/pull/2306 improved the performance of Chisel3 on a typical large SiFive design by 16%, more careful measurements show that number to actually be **30%**.
**However,** this benefit only comes if the user uses the scalacOption `-P:chiselplugin:genBundleElements` which tells the Chisel compiler plugin to generate `Bundle.elements`. I then tried this typical large SiFive design without that scalacOption and I found Chisel to run 21% **slower**. Considering most users will bump to 3.5.1 and won't apply that new scalacOption immediately (if they ever do), this slowdown is unacceptable.
This PR changes 2 small things:
1. Only call _elementsImpl once in Bundle.elements -- this mitigates most of the slowdown but not all of it. It …
> Fix bundle elements performance regression

- core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
- src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
- new feature/API     
- 
Adds Tuple2 as something which is Lookupable (can be marked @public).
It doesnt change any verilog.
Make Tuple2 Lookupable
> Make Tuple2 Lookupable

- core/src/main/scala/chisel3/Mem.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/experimental/hierarchy/Annotations.scala
- src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
`@public` can now be used on definitions/instances of `Mem`s and `SyncReadMem`s.
> Hierarchy API: make `Mem`s lookupable

- src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
- src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
During the migration to RC.
I encountered this issue: sometime input or output width are unknown.
I originally think the input to decoder was a set of MicroOp, which is certainly a known width. in RC CSR, it shows the usage as an address decoder. I think it's reasonable to have an input unknown width.
However in the output side, the result of decode logic is always a control logic, padding it is an anti-pattern design.
So, this PR makes TruthTable accepting an unknown width to fit to the use cases like RC CSR.
- bug fix
TruthTable will accept unknown width input now.
None
TruthTable will accept unknown width input now.
> Make truthtable being able to accept unknown input width.

- core/src/main/scala/chisel3/Bits.scala
- src/test/scala/chiselTests/UIntOps.scala
Firrtl will catch this later on, but better to error early if possible.
Improved error reporting
None, if you consider Chisel + Firrtl together: the same error would've been generated downstream.
N/A
Out-of-bounds bit and field extracts from UInts of known width now issue errors earlier in compilation.
> Issue errors on out-of-range extracts when width is known

- docs/src/cookbooks/cookbook.md
- docs/src/cookbooks/verilog-vs-chisel.md
- bug fix    
No impact
No impact
Minor tweaks to the Verilog-vs-Chisel Documentation page
@Shorla FYI
> Tweaks to the Verilog-vs-Chisel Page

- integration-tests/src/test/scala/chiselTests/util/experimental/algorithm/Bitwise.scala
- src/main/scala/chisel3/experimental/util/algorithm/Bitwise.scala
new feature/API
Add utility `LSBOr` and `MSBOr` similar to rocket-chip's `leftOr` and `rightOr`. These functions are generally very useful and can be used to implementing other useful utilities such as bitfield arbitration
N/A
Rebase
Add experimental utility `LSBOr` and `MSBOr`.
> Add scanLeftOr and scanRightOr utilies

- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
- src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Also delete an errant println in InstanceSpec.
Yeah I don't love the special casing. A cleaner solution is to improve `DataView` slightly (to support dynamic indexing of Vecs within a view), and then reimplement `BlackBox` to make it's `val io` `Bundle` be a view. This is a larger change though that requires touching a lot fo the codebase, and my goal was to fix this bug.
- bug fix   
This makes `BlackBox` work when used as an `Instance`
No impact
- Squash
Fix handling of `BlackBoxes` in Definition/Instance.
> Support BlackBoxes in D/I

- src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
- src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
- [N/A] Did you delete any extraneous printlns/debugging code?
- code cleanup
None
None
> Add improved numbering for InstanceSpec and DefinitionSpec

- docs/src/cookbooks/cookbook.md
See [post mdoc rendered markdown here](https://gist.github.com/jackkoenig/299c16ba1be0144340ca580a4d2336d0#aliased-bundle-fields).
- documentation        
No impact
No impact
- Squash:
> [docs] Add Cookbook section on aliased Bundle fields

- project/build.properties
Reverts chipsalliance/chisel3#2377
I forgot we had this same issue with 1.6.1 (https://github.com/chipsalliance/chisel3/pull/2374)
See filed issue: https://github.com/sbt/sbt/issues/6838
> Revert "Update sbt to 1.6.2"

- core/src/main/scala/chisel3/internal/Builder.scala
This is very much a micro-optimization, but I was looking at Flamegraphs and noticed 2 `StringBuilders` when there should only be 1. The String concatenation before adding to the String builder results in an unnecessary String copy. This is peanuts compared to most of the object creation going on in Chisel, but it is noticeable in a Flamegraph so I figured I'd fix it.
No impact
No impact
- Squash
Micro-optimize performance of computing names of signals
> Micro-optimize String building in _computeName

- core/src/main/scala/chisel3/internal/Builder.scala
* During sanitize, only filter the String if needed
* Do not recurse on name, saving an unnecessary call to sanitize
Filtering a String unconditionally builds a new `String` (actually a `StringBuilder` and a `String`), so this saves that allocation in the common case with a `forall` (which early outs on failing the predicate).
Also the recursion on `Namespace.name` which was presumably to keep the code DRY actually resulted in calling `sanitize` twice for every call that collided in the `Namespace`.
- performance improvement 
No impact
No impact
- Squash
Speed up naming of signals
> Micro-optimize Namespace.name

- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Element.scala
- core/src/main/scala/chisel3/experimental/dataview/package.scala
- core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
- core/src/main/scala/chisel3/experimental/package.scala
- core/src/main/scala/chisel3/internal/Binding.scala
- docs/src/cookbooks/cookbook.md
- src/test/scala/chiselTests/experimental/DataView.scala
- src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
- src/test/scala/chiselTests/experimental/FlatIOSpec.scala
h/t @davidbiancolin for the implementation idea
@oharboe I promised you this a while ago, here it finally is!
The best way to understand this PR is to look at the tests (including the `DataViewTargetSpec` which is a subtle change but an enhancement). Basically, I changed the AggregateViewBinding to include mappings between Aggregates when there is a 1-1 correspondence. This enables dynamically indexing Vecs that are themselves elements of larger Aggregates in views when the corresponding element of the view is a Vec of the same type. It also increases the number of cases where a single Target can represent part of a view.
It also enabled implementing `FlatIO` (which really needed dynamic indexing to work), so I went ahead and did that too!
- new feature/API        
This enables dynamic …
> Enhance views to [sometimes] support dynamic indexing and implement FlatIO

- core/src/main/scala/chisel3/internal/Builder.scala
* Use a single field instead of two in HasId (4-bytes per HasId)
* Set the prefix to Nil after setting ref to free up memory
Draft PR for now because I'm having a bit of trouble measuring a memory improvement from this (perhaps I should write a synthetic benchmark), but analytically, it is easy to see how it should be beneficial.
This also has minor bug potential because the behavior of `_computeName` will change if someone calls it after `forceName` is called on a `HasId`. Auditing the code, that doesn't happen, but it might be worth having `_computeName` get the name from the `_ref` if it's available or perhaps error if called when it shouldn't be.
> Optimize memory use of naming prefixes

- core/src/main/scala/chisel3/Clock.scala
- src/test/scala/chiselTests/InvalidateAPISpec.scala
Loosen restrictions on clocks to enable them to be connected to
DontCare, i.e., be invalidated.
Co-authored-by: Jack Koenig <koenig@sifive.com>
> Enable Clock Invalidation

- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/hierarchy/LibraryHooks.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/IsInstantiable.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/IsLookupable.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/LibraryHooks.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Underlying.scala
- core/src/main/scala/chisel3/experimental/hierarchy/package.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/main/scala/chisel3/aop/Select.scala
- [N/A] Did you delete any extraneous printlns/debugging code?
- [N/A] Did you specify the code generation impact?
Moves files around and added a new package, so its possible that existing code may break if it is relying on these. However, most of the non-internal types and objects are aliased in the hierarchy package.
Move D/I internals to a `core` package, aliased public types and objects to keep mostly backwards compatible.
> Moved D/I internals to new core package

- macros/src/main/scala/chisel3/internal/naming/NamingAnnotations.scala
In Scala 2.13, Auto-application to `()` is deprecated. Any nullary
method (ie. a method with no arguments) that is defined with () must now
be called with (). @chiselName used to inject a case of this warning
into user code which would then cause a warning on the @chiselName macro
that the user has no way to fix.
To see this warning, compile Chisel with Scala 2.13, you'll see something like:
```
[warn] .../chisel3/src/main/scala/chisel3/util/Arbiter.scala:119:2: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method length,
[warn] or remove the empty argument list from its definition (Java-defined methods are exempt).
[warn] In Scala 3, an unapplied method like this will be eta-expanded into a function.
[warn] @chiselName
[warn]  ^
[warn] …
```
> Fix warning injected into user code by @chiselName

- core/src/main/scala/chisel3/BlackBox.scala
- src/test/scala/chiselTests/BlackBox.scala
Fixes https://github.com/chipsalliance/chisel3/issues/2451
- bug fix 
No impact
No impact
- Squash
Fix bad error message for BlackBoxes without `val io` or with `val io` of the wrong type.
> Fix error message for BlackBox without val io <: Record

- plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
For traits or abstract classes that extend Bundle but have no concrete
methods, the plugin will print a benign warning that the user cannot
fix. It will no longer print that warning.
- bug fix   
No impact
No impact
- Squash
Fix benign but annoying warning `Unable to determine primary constructor!`printed by the compiler plugin in user code.
> Fix spurious warning from Bundle plugin

- src/main/scala/chisel3/util/Bitwise.scala
- src/main/scala/chisel3/util/Cat.scala
- src/main/scala/chisel3/util/Reg.scala
These methods will start using def macros and since def macros do not
supported named arguments this will be a source-incompatible change.
This deprecation will warn users that they need to remove any uses of
named arguments on these methods.
This resolves the issue discussed in https://github.com/chipsalliance/chisel3/pull/2515.
This doesn't give perfect error messages, but it's not bad. For the following
```scala
RegEnable(next = 0.U, enable = true.B)
```
You'll get the warnings:
```
[warn] .../Example.scala:5:18: naming parameter next is deprecated (since Chisel 3.5).
[warn]   RegEnable(next = 0.U, enable = true.B)
[warn]                  ^
[warn] .../Example.scala:5:32: naming parameter enable is deprecated (since Chisel 3.5).
[warn]   RegEnable(next = 0.U, enable = true.B)
[warn] …
```
> [3.5.x] Deprecate named arguments for methods moving to macros in 3.6

- core/src/main/scala/chisel3/Aggregate.scala
- src/test/scala/chiselTests/Vec.scala
Fixes https://github.com/chipsalliance/chisel3/issues/1953
- bug fix 
It is now possible to create Vecs of empty Bundles
No impact
- Squash
Support creating Vecs of empty Bundles. Hardware components of this type are removed by the time of Verilog emission (similar to components of empty Bundles or zero-width UInts).
> Support Vecs of empty Bundles

- build.sbt
- build.sc
- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/experimental/package.scala
- plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
- plugin/src/main/scala/chisel3/internal/plugin/ChiselPlugin.scala
Feature originally added in [v3.5.1](https://github.com/chipsalliance/chisel3/releases/tag/v3.5.1), it was technically a binary incompatible change so in v3.6.0 it will become mandatory.
This enables removing reflection.
- performance improvement  
- code cleanup  
No impact since the plugin is required and the same names are given.
No impact
- Squash
Make Chisel-plugin generation of `Bundle.elements` mandatory. Scalac option `-P:chiselplugin:genBundleElements` no longer does anything.
> Plugin generation of Bundle elements is now mandatory

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- src/test/scala/chiselTests/ExtModule.scala
ExtModule now uses the same namePorts implementation as regular Modules.
Previously, ExtModules only allowed port naming via runtime reflection.
This meant that .suggestName and other naming APIs do not work. It also
breaks FlatIO for ExtModule which is a potential replacement API for
BlackBox's special `val io` handling.
This is an API expansion (see `API Impact` below) but it is arguably a bugfix that the APIs that work for normal modules just don't work for `ExtModule`. I can be convinced that this should be done in 3.6.0 as this fix/change is a necessary piece of my effort to remove runtime reflection naming in 3.6.0, but I think there's value in getting this piece out as a bugfix in 3.5.4.
- bug fix 
- code cleanup 
- new …
> Make ExtModule port naming consistent with Module

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/InstanceNameSpec.scala
- src/test/scala/chiselTests/ToTargetSpec.scala
This includes (and is tested) for both the old .*Name APIs and
.toTarget
Note that this PR primarily exists to be backported to `3.5.x` and I will immediately follow it with a PR turning these accesses into errors on `master`.
Note that this deprecation and ultimate removal was contemplated in https://github.com/chipsalliance/chisel3/pull/1616. I am finally doing it now in preparation for removing all reflective naming in Chisel 3.6.
- code cleanup
This deprecates accessing the name (via `.instanceName` and related APIs as well as via `.toTarget`) of non-hardware `Data` (ie. unbound `Data` objects). These names do not correspond to anything in the FIRRTL and are thus very misleading.
No impact
- Squash …
> Deprecate accessing the name of non-hardware Data

- plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
- src/test/scala/chiselTests/VerificationSpec.scala
- src/test/scala/chiselTests/naming/NamePluginSpec.scala
- src/test/scala/chiselTests/naming/PrefixSpec.scala
Previously, verification statements (assert, assume, cover, and printf)
were only named via reflection.
- bug fix   
Verification statements are now named in the same way as normal hardware components. 
In rare cases, some signals may get a new prefix based on the name of a verification statement, but this should only occur in cases where the statement is returned from a function/block and assigned to a val, eg.
```scala
val foo = {
val wire = Wire(UInt(8.W))
wire := ...
assert(wire =/= 123.U)
}
```
In this case, `wire` will now be named `foo_wire`.
- Squash
Handle naming and prefixing of verification statements in the same way as `Data` and `Mems`. This primarily affects the names used by annotations but also will now cause …
> Support VerificationStatement in the naming plugin

- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/Error.scala
- src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselCli.scala
- src/main/scala/chisel3/stage/ChiselOptions.scala
- src/main/scala/chisel3/stage/package.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/test/scala/chiselTests/naming/ReflectiveNamingSpec.scala
This new argument (and associated annotation) will turn on a warning
whenever reflective naming changes the name of a signal. This is
provided to help migrate from Chisel 3.5 to 3.6 since reflective naming
is removed in Chisel 3.6.
I also factored `_computeName` out into a resuable function so that you can ask for the name of something given a `seed` and `prefix` without having to have a `HasId` with those fields set.
This mega-conflicts with @mwachs5's https://github.com/chipsalliance/chisel3/pull/2556
This adds a new CLI/annotation API to warn when some names will change between Chisel 3.5 and 3.6.
No impact
- Rebase
Add `--warn:reflective-naming` to enable a warning that indicates when the name of some value in the hardware will change in the migration from Chisel 3.5 …
> Add --warn:reflective-naming

- core/src/main/scala/chisel3/Bits.scala
- macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
- src/test/scala/chiselTests/SIntOps.scala
- src/test/scala/chiselTests/UIntOps.scala
This PR adds the `.extract` function discussed in #2534, but instead being for the purpose of reducing boilerplate code (e.g. assigning a literal to a val, then calling .apply).
Adds single argument `Bits.extract` functions which the existing `apply()` functions alias to
No impact
Add `Bits.extract` and alias single-argument `.apply()` functions to it
This is to make deprecation of the literal bit extract pattern easier by removing the need for lots of boilerplate.
> Add single argument Bits.extract

- macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Include the function being called in the suggestion.
A very minor enhancement to the warning. Given:
```scala
val out = IO(Output(UInt(8.W)))
out := 12.U(8)
```
Old suggestion:
```
[warn] If you do want bit extraction, use .extract(8) instead
[warn]   out := 12.U(8)
[warn]              ^
```
New suggestion:
```
[warn] If you do want bit extraction, use .U.extract(8) instead.
[warn]   out := 12.U(8)
[warn]              ^
```
- documentation (warning suggestion)
No impact
No impact
- Squash
> Enhance suggestion in literal extract warning

- core/src/main/scala/chisel3/CompileOptions.scala
- core/src/main/scala/chisel3/Module.scala
- src/test/scala/chiselTests/MigrateCompileOptionsSpec.scala
I didn't add more comprehensive ScalaDoc. I will add that once we add migration options for all the compilation options.
Adds another optional field to CompileOptions to migrate inferModuleReset.
Squash
Added an optional field to CompileOptions to help users migrate the inferModuleReset compile option.
> Added migration for inferModuleReset

- src/main/scala/chisel3/testers/TesterDriver.scala
- src/test/scala/chisel3/testers/TreadleBackend.scala
Captures default output in TesterDriver with a ProcessLogger using the
Logger from FIRRTL to suppress output from Verilator when running tests.
This will change behavior for any users of the TesterDriver because the
standard out of Verilator compilation and execution is suppressed by default.
Users can create their own ProcessLogger to restore the previous
behavior, eg.
```scala
import scala.sys.process.ProcessLogger
val echoLogger = ProcessLogger(Console.out.println, Console.err.println)
```
- code cleanup 
This is binary incompatible. It could be made compatible but I don't care enough to do so, this is just for CI.
No impact
- Squash
Add `ProcessLogger` argument to `TesterDriver.execute`. By default, stdout and stderr are now sent to a `logger.Logger` object instead of echoing to the …
> Add ProcessLogger to TesterDriver for less test noise

- src/main/scala/chisel3/util/BitPat.scala
BitPat.rawString is called a lot when decoding and is used for certain
BitPat operations. We should use it less but this is at least a bandaid.
@sequencer, have you noticed issues with this?
No impact, this should be source and binary compatible
None
Squash
Micro-optimize and memoize BitPat.rawString to speed up decoding APIs
> Micro-optimize and memoize BitPat.rawString

- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- src/test/scala/chiselTests/MigrateCompileOptionsSpec.scala
- code cleanup  
Adds a new trait `ImplicitInvalidate`, which when mixed with a Module mimics the behavior when the compiler option has `explicitInvalidate=false`.
The best way to migrate would be to set the compiler option `explicitInvalidate=true`, then for all modules where the FIRRTL compilation errors, add back in the `ImplicitInvalidate` trait.
- Squash: The PR will be squashed and merged (choose this if you have no preference
Adds a new trait `ImplicitInvalidate`, which when mixed with a Module mimics the behavior when the compiler option has `explicitInvalidate=false`.
> Add ImplicitInvalidate, to help migrate the explicitInvalidate compiler option

- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/experimental/dataview/package.scala
- core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- docs/src/explanations/naming.md
- plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
- src/test/scala/chiselTests/naming/NamePluginSpec.scala
- src/test/scala/chiselTests/naming/PrefixSpec.scala
Note, I've rendered the updated docs [here](https://gist.github.com/jackkoenig/5777f77ba7c1a66c574d6f566bc31724).
Chisel and FIRRTL have long used signals with names beginning with an
underscore as an API to specify that the name does not really matter.
Tools like Verilator follow a similar convention and exclude signals
with underscore names from waveform dumps by default. With the
introduction of compiler-plugin prefixing in Chisel 3.4, the convention
remained but was hard for users to use unless the unnnamed signal
existed outside of any prefix domain. Notably, unnamed signals are most
useful when creating wires inside of utility methods which almost always
results in the signal ending up with a prefix.
With this commit, Chisel explicitly recognizes signals whos val names
start with an …
> Define leading '_' as API for creating temporaries

- docs/src/appendix/experimental-features.md
- docs/src/cookbooks/cookbook.md
> [docs] Document partial register reset

- plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
Previously, the plugin would crash with a useless internal error.
Fixes #2584
- bug fix 
Just a bug fix, no real impact
No impact
- Squash
Fix compiler plugin crash on varargs arguments to Bundle constructors.
> Handle varargs constructor arguments in Bundle plugin

- README.md
This PR makes the readme friendlier to beginners and also brings the description to the start of the page. Also adds some badges pointing to latest versions.
This is mostly a suggestion, we can cleanup or add more info as feedback arrives.
None
None
> Make readme friendlier to beginners

- core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
- new API 
- No impact - since the default value of this option is None - and the previous behavior should hold 
- Change is relative to the override name given for the external definition. Previously it used to pick only `definition.proto.name` - now it can hold a different value provided by the user. 
- Ideally the original issue of getting actual names of the external components in the final circuit can / should be solved more cleanly by making Prefixing a first class support within Chisel and/or having the concept of Namespaces within Firrtl. 
Squash
> Pass optional name in ImportDefinitionAnno used during Separate elaboration of definition and instance 

- core/src/main/scala/chisel3/Data.scala
- src/test/scala/chiselTests/experimental/DataMirrorSpec.scala
This extends the current DataMirror API.
Backend code generation is not changed.
Squash
Added `DataMirror` methods `isIO`, `isReg`, `isWire` for determining the binding of a Chisel type.
> Add DataMirror isIO, isReg, isWire

- docs/src/explanations/interfaces-and-connections.md
Links between markdown pages should not have any file extension to ensure they work on the website.
Fixes https://github.com/chipsalliance/chisel3/issues/2605
No impact
No impact
- Squash
> Fix broken link in interfaces-and-connections.md

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/Reg.scala
- src/test/scala/chiselTests/CompatibilitySpec.scala
- src/test/scala/chiselTests/LazyCloneSpec.scala
This change prevents unnecessary clones from happening where possible. Currently when creating a binding, the underlying Data object is always cloned. For example, elaborating this module creates 12 Foo objects.
```scala
class Foo extends Bundle {
val a = UInt(8.W)
}
class MyModule extends RawModule {
val io = IO(Flipped(new Bundle {
val foo = Output(new Foo)
val bar = Input(new Foo)
}))
}
```
Since the objects being passed to the binding functions are never used again they do not need to be copied. After this PR, only 2 Foo objects are created when elaborating MyModule.
This change improves elaboration time and memory usage. On two large designs, I saw the following improvements:
**Design 1**
| Metric               |   Default    |   Optimized cloning   |  Improvement  |
| --------- …
> Avoid making unnecessary clones during binding

- core/src/main/scala/chisel3/CompileOptions.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/internal/BiConnect.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
- bug fix                       
- code cleanup                       
- new feature/API            
This breaks out a specific field in `CompileOptions`, `emitStrictConnects`. Previously, this behavior was conditioned matching on `NotStrict` itself, which isn't right for users who may make their own `CompileOptions` variants.
This doesn't change anything except for users who may have been writing their own CompileOptions variants, who would now need to appropriately set this flag to `false` if they were manually making some sort of `NonStrict` variant. 
CompileOptions: add and use a emitStrictConnects flag.
> CompileOptions: add and use emitStrictConnects

- core/src/main/scala/chisel3/Annotation.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/NewAnnotationsSpec.scala
- new feature / API 
- 
- With the intent to ensure no existing code breaks / needs an update - a different variable (called newAnnotations) was used. Also wherever this is used a default value of Seq.empty was provided in the function argument list - again to avoid updating existing code. 
-  A new trait called `ChiselMultiAnnotaiton` was created with `toFirrtl` method - which returns a Seq of Annotations. 
@jackkoenig  this is based on our agreed upon strategy (creating a totally new trait as opposed to adding a new method in the existing one) 
No impact to current code. The current API is useful to generate annotations  containing information which will only be available after a module elaborates.  However this is limited since we can only generate a single annotation per call. In some …
> New enhanced API for  specifying Chisel to Firrtl Annotations

- core/src/main/scala/chisel3/experimental/package.scala
- macros/src/main/scala/chisel3/internal/naming/NamingAnnotations.scala
- src/main/scala/chisel3/util/Arbiter.scala
- src/main/scala/chisel3/util/CircuitMath.scala
- src/main/scala/chisel3/util/Counter.scala
- src/main/scala/chisel3/util/Decoupled.scala
- src/test/scala/chiselTests/StrongEnum.scala
This PR deprecates `@chiselName` and `NoChiselNamePrefix` in favor of the newly added `AffectsChiselPrefix` trait, and deletes all non-testing uses of them.
Needs to be backported so that a followup PR that removes both of these can be made
- code cleanup/refactoring
- deprecates chisellName and NoChiselNamePrefix
- no impact
- squash and merge
- Deprecate chiselName and associated NoChiselNamePrefix trait
> Deprecate chiselName and NoChiselNamePrefix trait

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/Module.scala
- src/test/scala/chiselTests/Direction.scala
In `Chisel._`, `IO` has an implicit output direction, and `Flipped` is used for two things:
1) Define relative direction of a field with respect to its parent bundle
2) To change the implicit output to an implicit input of IO
```scala
val io = IO(new Bundle { // implicit output
val x = Flipped(UInt()) // x is flipped relative to bundle, so it is an input
val y = UInt() // y is aligned relative to bundle, so it is an output
})
```
You can declare an input port using the (2) kind of Flipped:
```scala
val io = IO(Flipped(new Bundle { // implicit input
val x = Flipped(UInt()) // x is flipped relative to bundle, so it is an output
val y = UInt() // y is aligned relative to bundle, so it is an input
}))
```
In `chisel3`, `IO` does not have an implicit direction, but `Input` and `Output` are …
> Unify Chisel2 and chisel3 directionality

- src/main/scala/chisel3/util/Decoupled.scala
- src/main/scala/chisel3/util/util.scala
- src/test/scala/chiselTests/DecoupledSpec.scala
Addresses #1072: Implements a new utility for `Decoupled` which applies a function to its data.
- Adds `Decoupled.map` to apply a function to a `DecoupledIO` and return the new resulting `DecoupledIO`
- No change to verilog
- Squash and merge
Implement `DecoupledIO.map` to apply a function to `DecoupledIO.bits`
> Implement DecoupledIO.map utility

- build.sbt
Release automation tries to bump chiseltest which causes issues due to
SBT trying to resolve all dependencies (even for projects that will not
be published, like integrationTests).
- code cleanup   
None
No impact
- Squash
> Remove chiseltest from defaultVersions

- README.md
We no longer meet on Tuesdays, only Mondays.
Marked for backporting so this shows up on the website.
No impact
No impact
- Squash
> Remove Tuesday from Dev Meeting in README

- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/util/Decoupled.scala
A couple of `@chiselName` uses weren't covered by #2627 so this PR removes these as well.
- code cleanup
no impact
no impact
squash and merge
> Remove remaining chiselNames

- docs/src/explanations/chisel-type-vs-scala-type.md
Without this, we get some weirdly formatted sections / unevaluated mdoc blocks
- bug fix                
- documentation         
No Impact
No Impact
Fix formatting of Chisel Type vs Scala Type Article Section
> Fix formatting issue in  chisel-type-vs-scala-type.md

- integration-tests/src/test/scala/chisel3/std/BarrelShifter.scala
Just a minor folder issue fixed.
- code cleanup                      
non
non
> stdlibL: fix folders in test source

- core/src/main/scala/chisel3/StrongEnum.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- docs/src/explanations/chisel-enum.md
- src/test/scala/chiselTests/StrongEnum.scala
Casting a UInt to an Enum causes an unsuppressable warning. In some cases the designer can guarantee that the UInt is in fact a valid enum state (for example the UInt was created by casting an Enum value, or has been otherwise verified). In those cases it should be possible for the designer to suppress the warning. Sometimes a cast happens through another function like `asTypeOf`, so using `.safe` to avoid the warning is not practical.
This adds a new object for suppressing enum cast warnings.
No change.
Squash.
The `suppressEnumCastWarning` object can be used to prevent a block from generating enum cast warnings.
> Add ability to suppress enum cast warnings

- core/src/main/scala/chisel3/internal/Error.scala
- src/test/scala/chiselTests/WarningSpec.scala
Sometimes one line of source code can end up generating the same warning or error multiple times. With this change, multiple equivalent warnings/errors generated from the same source code location will only be shown once. This de-duplication uses the same approach as the de-duplication that currently exists for deprecation warnings.
Multiple equivalent warnings generated from the same location will now only be shown once.
No codegen change.
Squash
Multiple equivalent warnings generated from the same location will now only be shown once.
> Show equivalent warnings/errors only once

- core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/Error.scala
- src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
- src/main/scala/chisel3/stage/ChiselAnnotations.scala
- src/main/scala/chisel3/stage/ChiselCli.scala
- src/main/scala/chisel3/stage/ChiselOptions.scala
- src/main/scala/chisel3/stage/package.scala
- src/main/scala/chisel3/stage/phases/Elaborate.scala
- src/test/scala/chiselTests/WarningSpec.scala
Allows warnings to be treated as errors with `--warnings-as-errors`.
No change.
Squash
Allows warnings to be treated as errors with the `--warnings-as-errors` flag.
> Add option to treat warnings as errors

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/RecordSpec.scala
`OpaqueType` allows simplifying `Record` references when the `Record` subtypes have single map elements
- new feature/API               
New override for Records for single element types
If `Record.opaqueType` is overridden to `true`, the generated CHIRRTL will substitute name of the `Record` for that of the subfield, and substitute type of the subfield for type of the `Record`
Add new override in Record to support opaque types
> Add OpaqueType support to Records

- src/test/scala/chiselTests/naming/PrefixSpec.scala
Meant to compliment #2610: `AffectsChiselPrefix` was originally indirectly tested in `NamingAnnotationTest`, however most of these tests will be removed along with `@chiselName`. This PR adds the necessary code to directly test `AffectsChiselPrefix`'s behavior.
- code cleanup
No impact 
No impact
Adds `AffectsChiselPrefix` tests which were previously missing
> Add AffectsChiselPrefix test

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/ToTargetSpec.scala
Error messages from using `.toTarget` on a non-hardware type now provide the name of the value and the parent module. I will also open a separate version of this PR for 3.5.x that uses a deprecation warning instead of an error.
- code cleanup
Error messages for `.toTarget` now provide the name of the value and the parent module.
None
- Squash
Error messages from using `.toTarget` on a non-hardware type now provide the name of the value and the parent module.
> Provide a better error message for use of .toTarget on non-hardware value

- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/RecordSpec.scala
The `localName` field for `OpaqueSlot` led to invalid names for nested Records; this PR replaces it with override `name`
- bug fix
None
`toTarget` should emit the correct annotations
Bugfix: replace `OpaqueSlot`'s `localName` with overriding `name` function to correctly output `toTarget` for nested opaque type Records.
> Bugfix - OpaqueSlot replace invalid localName

- src/main/scala/chisel3/util/experimental/ForceNames.scala
- src/main/scala/chisel3/util/experimental/decode/decoder.scala
- src/test/scala/chiselTests/experimental/ForceNames.scala
This is a backport of #2700 for 3.5.x using deprecation warnings instead of errors.
> Backport of eager error messages for annotations (3.5.x) (#2700)

- .github/workflows/test.yml
Also make the specified version more human readable for easier bumping
in the future.
CI is broken due to https://github.com/chipsalliance/firrtl/pull/2543 in the current SNAPSHOT release of FIRRTL, we need to use newer CIRCT which supports FIRRTL version specifiers.
- bug fix     
No impact
No impact
- Squash
> Bump CIRCT to 1.14.0

- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/RecordSpec.scala
We need to ensure that contextual names stay contextual (ie. sensitive
to the module context which is important for naming ports).
This is a bug fix in a not-yet-released feature
- bug fix    
No impact, just a minor bug fix
No impact
- Squash
> Fix OpaqueSlot handling of contextual names

- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/WireSpec.scala
`implicit val noSourceInfo = UnlocatableSourceInfo` from `WireDefault#apply`
- Add test to show locators
- [-] Did you add Scaladoc to every public function/method?
- [-] Did you add appropriate documentation in `docs/src`?
- code cleanup
- wires in firrtl will now have source location information making it easier to find where they were declared
- Slightly changes the appearance of firrtl, adds some more characters to `Wire` 
- Should have no change in code functionality
- 
- Squash: The PR will be squashed and merged (choose this if you have no preference. -->
Source location information for `Wire`, `WireInit`, and `WireDefault` is now included in generated firrtl.
> Wires should have source location information in firrtl

- core/src/main/scala/chisel3/VerificationStatement.scala
Reverts chipsalliance/chisel3#2683
So it seems that in order for ScalaDoc grouping and prioritization to work, the `trait` has to be public. We could make the trait `sealed`, but then it would be a source incompatible change to ever change which objects extend it, so I think just leaving it public is fine.
I even tried putting the trait in package `chisel3.internal`, but because that package is excluded from ScalaDoc, that also broke the method grouping. Alas.
> Revert "Privatize trait VerifPrintMacros"

- core/src/main/scala/chisel3/Mem.scala
- src/test/scala/chiselTests/MultiClockSpec.scala
Mem.read is combinational and thus unaffected by the clock, and so it does not make sense to issue warnings about the current clock in this context.
- bug fix
None.
None.
Removed deprecation warning when reading a Mem when the current implicit clock differs from the implicit clock at time of definition.
> Remove incorrect clock warning on Mem.read

- core/src/main/scala/chisel3/BlackBox.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- project/build.properties
- src/test/scala/chiselTests/Module.scala
- src/test/scala/chiselTests/PortSpec.scala
- backend code generation
- 
Source locators are now on regularly define ports (not on automatically generated clock and reset).
This should not affect anything downstream
Source locators for ports will be included in generated verilog, but should have change any behavior
With this change firrtl and verilog will contain source locators for ports. This can be very helpful on figuring out where the ports were declared in deeply nested generated `IO`s
> Add source locators to ports

- core/src/main/scala/chisel3/Bits.scala
Fix chipsalliance/chisel3#2728
No function/method added
No API impact
No backend code generation impact
> Change SInt unary negation (expanding width) note

- .github/workflows/test.yml
- build.sbt
- build.sc
We should get this into 3.5.5.
- dependency bump
Enables Chisel users to use Scala versions 2.13.9 and 2.12.17
No impact
- Squash
Bump to Scala 2.13.9 and 2.12.17
> Bump to Scala 2.13.9 and 2.12.17

- src/main/scala/chisel3/internal/firrtl/Emitter.scala
This enables emission of modules that serialize to >2 GiB of .fir text.
See https://github.com/chipsalliance/firrtl/pull/2554.
This has no impact on performance for most designs, it slightly improves serialization performance for designs with very large modules (due to the cost of allocating large Strings--but the JVM is very good at this so the impact is small).
- bug fix 
- performance improvement  
No change
No impact
- Squash
Support serialization of Modules that require over 2 GiB of `.fir` text.
> Use new lazy serialization in FIRRTL

- .github/workflows/test.yml
- src/test/scala/chiselTests/DecoupledSpec.scala
Previously, failed jobs in the CI matrix would cause the sentinel job (all-tests-passed) to be skipped, which for purposes of Github Actions branch protection would count as "success". This allowed PRs with failing CI to be merged. This new approach which uses two sentinel jobs should not suffer from this same issue.
This approach was borrowed with love from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
- CI
No impact
No impact
- Squash
> Improve CI sentinel job for better branch protection

- .github/workflows/test.yml
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/Vec.scala
Replaces https://github.com/chipsalliance/chisel3/pull/2043
- ci improvement
No impact
No impact
- Squash
> Use Treadle (on pull requests only) to speed up CI

- .github/workflows/test.yml
Now that https://github.com/chipsalliance/chisel3/pull/2341 is merged, the Scala 2.12 CI takes 17 minutes and the 2.13 CI takes 12 minutes. The 2.12 CI runs documentation and formatting checks, so this splits those out to speed up the critical CI path by a ~3 minutes.
- ci
No impact
No impact
- Squash
> [ci] Split formatting and docs checks into separate task

- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Printable.scala
- core/src/main/scala/chisel3/Printf.scala
- core/src/main/scala/chisel3/VerificationStatement.scala
- src/test/scala/chiselTests/Assert.scala
- src/test/scala/chiselTests/Printf.scala
When passing a `Printable` to `assert`, `assume` or `printf`, the scope of where the `Printable` was constructed should be the same as where it is being referenced. This is currently not checked, which makes it possible to construct cases where invalid FIRRTL is generated. Specifically, if the `Printable` is constructed in an inner module and referenced from an outer module, the resulting FIRRTL can have references to objects like wires or temporaries that are local to the inner module. 
For example, the following snippet
```
class InnerPrintable extends Module {
val in = IO(Input(UInt(8.W)))
val out = IO(Output(UInt(8.W)))
val w = Wire(UInt(8.W))
w := 255.U
val p = p"$w"
out := in
}
ChiselStage.emitChirrtl { 
new Module {
val mod = Module(new InnerPrintable)
printf(mod.p)
}
}
```
outputs …
> Add lexical scope checks to Assert, Assume and Printf

- core/src/main/scala/chisel3/Printf.scala
- core/src/main/scala/chisel3/VerificationStatement.scala
- docs/src/explanations/printing.md
- src/test/scala/chiselTests/IntervalSpec.scala
- src/test/scala/chiselTests/Vec.scala
- src/test/scala/chiselTests/VecLiteralSpec.scala
This is to be backported to 3.5.x as a warning instead of an error
- updated feature/API      
Current `assert`, `assume` and `printf` APIs allow the Scala s-interpolator for formatting messages. This often leads to user errors where the Scala object is printed instead of the Chisel object, which leads to the messages being generally unhelpful.
After this update, using s-interpolators will throw an error about deprecation.
N/A
Using Scala s-interpolators now throws an error recommending a shift to the cf interpolator.
> Error on S-interpolator usage for assert, assume and printf

- core/src/main/scala/chisel3/experimental/Trace.scala
Change the type of modules that the traceName API can be used for from "Module" to "RawModule".  This fixes a bug where this API couldn't be used for RawModules even though it totally works.
> Fix traceName module type to RawModule

- core/src/main/scala/chisel3/experimental/Trace.scala
- src/test/scala/chiselTests/experimental/TraceSpec.scala
Change the behavior of the Trace API to not have "don't touch" behavior unconditionally.  Removing "don't touch" enables a finer granularity of functionality: if a user wants "don't touch" they can add a "don't touch".  However, they are not locked optimization blocking behavior which may be undesirable in certain situations.
> Remove "don't touch" behavior from Trace API

- .github/workflows/test.yml
- README.md
- build.sbt
- build.sc
2.13.9 [has a binary compatibility regression](https://github.com/scala/scala/releases/tag/v2.13.10) so should be avoided.
- bug fix
No impact
No impact
- Squash
Bump to Scala 2.13.10
> Bump to Scala 2.13.10

- README.md
Chisel 3.5.4 predates Scala 2.13.10 so the plugin is not published for 2.13.10.
> Fix scalaVersion in README

- core/src/main/scala/chisel3/Aggregate.scala
- plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
- src/main/scala/chisel3/util/MixedVec.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
There is a new trait, chisel3.experimental.AutoCloneType that is mixed in to Bundle and can optionally be mixed in to user-defined Records. The compiler plugin prints a deprecation warning on any user-defined implementation of cloneType, telling the user to mix in AutoCloneType before upgrading to 3.6.
This is intended to be backported to 3.5.x for release in 3.5.5. I have checked that this backports to 3.5.x [relatively] cleanly and is binary compatible (with the one caveat that MixedVec mixing in `AutoCloneType` changes the tyep of it's `cloneType` in a way that violates binary compatibility. It might be a false positive, but regardless I will revert that aspect of this PR on the backport).
I also intend to follow this PR with a version making cloneType generation mandatory for Records …
> Add opt-in AutoCloneType for Records

- core/src/main/scala/chisel3/experimental/Trace.scala
Add utilities to enable backwards compatibility of the Trace.traceName API to Chisel 3.5.x.  This adds a Trace.traceNameV2 utility which aliases to Trace.traceName.  This also removes the TraceNameAnnotation and renames it TraceAnnotation.  In 3.5.x, traceName will point at TraceNameAnnotation (which has don't touch behavior) and will be deprecated telling people to use traceNameV2 which will point at TraceAnnotation (which does not have don't touch behavior).  This will require fixups to the backport associated with this PR.
> Add traceNameV2 for backwards compat. of traceName

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/naming/PrefixSpec.scala
Changes `suggestName` so that it only updates the naming prefix when the first initial seed is suggested, but not on additional suggestion attempts.
- bug fix
No change
No impact
- Fix `suggestName` so that it doesn't tamper with prefixing when calling `suggestName` more than once
> Don't modify the Builder prefix if reinvoking suggestName on a Data

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/internal/BiConnect.scala
- core/src/main/scala/chisel3/internal/MonoConnect.scala
- src/test/scala/chiselTests/BulkConnectSpec.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
- bug fix                           
This will correctly get the direction of the `<-` right when there are `Input` or `Output` that coerce parts of compatibility mode Bundles that connect to Black Box IOs. (non BB or chisel3._ Ios would just emit `<=` properly, but if we were dropping into the field-by-field case the flip was wrong).
This doesnt change emitted verilog because the failing cases prevented generation of verilog
- Fix #2796, Correct directionality for <> to black box IO which contains Chisel.Bundle and coerced Input/Output subfields.
- Also minor improvement to getClassName especially useful in test case printf debugging
> Fix for <> to BlackBox.IO with Compatibility Bundles 

- core/src/main/scala/chisel3/experimental/dataview/DataView.scala
- core/src/main/scala/chisel3/experimental/dataview/package.scala
- docs/src/cookbooks/dataview.md
- src/test/scala/chiselTests/experimental/DataView.scala
This factory method makes it easy to create PartialDataViews from a Bundle type to its supertype. Because of the typing relationship, there is no need to provide a mapping between fields. The only thing necessary is to provide a function for constructing an instance of the supertype from an instance of the subtype.
- new feature/API        
New API
No impact
- Squash
Add PartialDataView.supertype for constructing PartialDataViews from a Bundle type to its supertype.
> Add PartialDataView.supertype

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/Trace.scala
- src/main/scala/chisel3/aop/Select.scala
- src/test/scala/chiselTests/RecordSpec.scala
This is a slightly omnibus PR but it was motivated by a bug discovered by @azidar.
If you create a `Record` with `def elements` (and those elements are not referring to vals in the `Record`), you get a `None.get` during binding. In debugging and fixing this issue, I noticed several things that I decided to fix in this PR. Please see the separate commits as they are technically each different things but all chain together well.
1. I added `Aggregates.elementsIterator` and micro-optimized a few functions. This should prevent lots of eager `Seq` constructions.
2. I realized `Aggregate.bind` is only called by `Records` so I moved it into `Record`. This is just a clean up
3. I extracted some logic from `Record.bind` and micro-optimized it.
4. I added a check for the original bug 😇 
For the …
> Improve Record.bind and Detect Records with unstable elements

- core/src/main/scala/chisel3/Module.scala
- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
- [NO] Did you delete any extraneous printlns/debugging code?
- [NO] Did you add appropriate documentation in `docs/src`?
- bug fix
- unit tests that fail on backport branches to be fixed further there
This ensures that Definition/Instance will work well when there are IOs where we need to assume directionality
This also adds unit test for MixedVec scenarios that are allowd on master but should fail more gracefully on the backport.
This only changes generated verilog for D/I case
Fix an issue with connecting to ports on Instances of Modules where directionality must be inferred
> Add unit tests and fix for #2794 , add unit tests for #2773 

- src/test/scala/chiselTests/RecordSpec.scala
Same fix noticed in backport https://github.com/chipsalliance/chisel3/pull/2836
- bug fix 
No impact
No impact
- Squash
> Fix cloneType in RecordSpec

- build.sbt
- core/src/main/scala/chisel3/Printf.scala
- core/src/main/scala/chisel3/VerificationStatement.scala
- docs/src/explanations/printing.md
- src/test/scala/chiselTests/IntervalSpec.scala
- src/test/scala/chiselTests/Vec.scala
- src/test/scala/chiselTests/VecLiteralSpec.scala
Backport of #2751, change errors to warnings for usages of s-interpolators
>  Warn on S-interpolator usage for assert, assume and printf (backport #2751)

- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
Use the resulting Vector to build the underlying Component's commands and then use those instead of copying the original ArrayBuffer when iterating on commands. Previously, the Component was using a List to hold the commands which is particularly memory inefficient, especially for large modules.
- performance improvement 
No impact
No impact
- Squash
Optimize Module internals
> Change RawModule._commands to a VectorBuilder

- src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
- code cleanup        
Fix misleading comments about tests that dont' pass on 3.5.x because they actually do pass (for 3.5.5)
> Remove Misleading comments from CompatibilityInteroperabilitySpec.scala

- core/src/main/scala/chisel3/Data.scala
- src/test/scala/chiselTests/RecordSpec.scala
- bug fix                  
Fixes https://github.com/chipsalliance/chisel3/issues/2844, corrects the string IO names from fullModulePorts.
Unless verilog was being generated by reflecting upon DataMirror.fullModulePorts returned values, no changes to emitted verilog.
> fullModulePorts + Opaque Types Fix and Test

- core/src/main/scala/chisel3/Bits.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/internal/Builder.scala
- core/src/main/scala/chisel3/internal/Error.scala
- core/src/main/scala/chisel3/package.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
This updates `Builder.error` and `Builder.warning` to take an implicit `SourceInfo` argument. 
`SourceInfo` of type `SourceLine` provides error messages with relative paths to the source file of the error as opposed to just the file basename, in addition to the column of the error occurrence.
If the `SourceInfo` is of type `NoSourceInfo`, the `ErrorLog` code falls back to the old behavior of looking up the source location via stack trace.
Furthermore, the deprecated `ErrorLog.info` method has been removed and the error message generating code has been simplified, removing the `LogEntry` class hierarchy which duplicated the error message tagging code found in `ErrorLog`.
One consequence of the changes is the removal of the `in class <class-name>` suffix in errors and warnings. `SourceLine` …
> Use SourceInfo in Builder error messages when available

- core/src/main/scala/chisel3/SeqUtils.scala
- src/test/scala/chiselTests/util/PipeSpec.scala
- src/test/scala/chiselTests/util/PriorityMuxSpec.scala
It used to be implemented with recursion, now it's implemented with a stack safe reverse and foldLeft.
Also there were no tests for PriorityMux so I added one which helps prove the change is functionally correct.
- performance improvement  
No impact
No impact
- Squash
`PriorityMux` is now stack-safe and will not require users to increase their JVM's stack size when called with large inputs.
> Make PriorityMux stack safe

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chisel3/internal/NamespaceSpec.scala
The namespace disambiguates requests for the same name with _<idx>. Rather than storing every disambiguated name in the underlying HashMap, it now only stores the base along with the "next available" index. This makes the logic for checking if a name is already contained in the namespace slightly more sophisticated because users can name things in a way that will collide with disambiguated names from a common substring.
For example, in naming the sequence "foo", "foo", "foo_1", the 2nd "foo" takes the name "foo_1" so the following "foo_1" gets disambiguated to "foo_1_1". But since we compressed that original "foo_1" into the same HashMap entry as just "foo", we have to do a form of "prefix checking" whenever naming something that ends in `_<idx>`.
In practice, the saved memory allocations …
> Implement compressed Namespace

- core/src/main/scala/chisel3/IO.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/package.scala
- code refactoring          
`chisel3.experimental.IO` will be deprecated and replaced by `chisel3.IO`
N/A
The `IO` from `chisel3.experimental.IO` been deprecated in favor of `chisel3.IO`.
> Unify BaseModule.IO and chisel3.experimental.IO into chisel3.IO

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/Data.scala
- core/src/main/scala/chisel3/Element.scala
- core/src/main/scala/chisel3/Module.scala
- core/src/main/scala/chisel3/experimental/Analog.scala
- core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala
- src/test/scala/chiselTests/experimental/ModuleDataProductSpec.scala
Only add Data to _ids when the binding is constrained. ConstrainedBinding means that the bound Data is scoped to a module. Since _ids are used for naming of signals within a module, there is no reason to add Unconstrained Data to the _ids of the Module they were constructed during. Unconstrained Data include things like literals and children of Aggregates (which sort of are constrained to a Module but only via their parent, they are not directly named by the module).
Note that this cannot be backported because it breaks the naming of unnamed things which is deprecated in 3.5 (but still works).
I measured this for a balanced, large design and it reduced minimum memory use from ~8000 MiB to ~7500 MiB (~6.25%). It did not have a measurable impact on wall-clock performance, but does reduce …
> Optimize _ids

- build.sc
The release automation uses regex to find these `defaultVersions` maps and they need to be consistent between `build.sbt` and `build.sc`. We can revisit this logic after the release of 3.6 but I'd rather wait till we collapse the many repositories before attempting any large changes to the release flow.
- bug fix   
No impact
No impact
- Squash
> [mill] Restore defaultVersions for release automation

- build.sbt
This allows build tools to warn users about possiblity binary incompatibilty issues when using dependencies that rely on binary incompatible versions of Chisel.
- infrastructure
No impact
No impact
- Squash
Chisel now publishes with `versionScheme` in the POM which should allow build tools (SBT and Mill) to warn users when library dependencies rely on binary incompatible versions of Chisel.
> Add versionScheme (PVP) to SBT publish settings

- core/src/main/scala/chisel3/Bits.scala
- core/src/main/scala/chisel3/package.scala
Deprecate Fixed Point types and Interval types.
This is the first of several PRs that are implementing the [Chisel Roadmap](https://github.com/chipsalliance/chisel3/blob/master/ROADMAP.md) plan to migrate to the MLIR-based FIRRTL Compiler. For more information, please see the referenced roadmap.
> Deprecate Fixed Point and Intervals

- core/src/main/scala/chisel3/connectable/Connectable.scala
- src/test/scala/chiselTests/ConnectableSpec.scala
This updates the `Connectable.squeeze*` functions to handle opaque types. Before, squeezing an opaque type would not affect it's underlying element. Now, squeezing an opaque type will squeeze it's underlying element.
- new feature/API improvement
Using `squeeze` with `OpaqueType` members will squeeze their underlying elements, as opposed to not affecting them.
None
> Take into account opaque members in squeeze functions

- plugin/src/main/scala/chisel3/internal/plugin/DeprecateSFCComponent.scala
For users using Scala 2.12.10 (and other versions), this enables defaulting to the old warning mechanism in the plugin. @jackkoenig tried it out by publishLocal on 2.12.8 and showing it compiles with chisel-template project.
- bug fix
> Added extension to work with users on 2.12.10 (and other 2.12 versions)

- src/test/scala/chiselTests/experimental/FlatIOSpec.scala
- bug fix                           
No impact, test code only.
No impact, test code only.
Fix the FlatIOSpec test case for Analog (previously it was not actually using FlatIO).
> FlatIOSpec: make sure the Analog test is using FlatIO

- core/src/main/scala/chisel3/Bits.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
IntervalLit, IntervalRange, and BinaryPoint have been deprecated
No immediate code generation impact
IntervalLit, IntervalRange, and BinaryPoint have been deprecated. This is cleanup of the deprecation of Interval and FixedPoint
> deprecate IntervalRange, IntervalLit, and BinaryPoint

- core/src/main/scala/chisel3/connectable/Alignment.scala
- core/src/main/scala/chisel3/connectable/Connection.scala
Minor change to enable a clearer mismatched widths error message.
- code cleanup 
> Clarify mismatched width error message

- core/src/main/scala/chisel3/Data.scala
- src/test/scala/chiselTests/Direction.scala
In cases when Flipped needs to clone, it was using the specified direction of the clone. Since cloneType does not propagate specifiedDirection, it was essentially always flipping an unspecified direction even if the direction had been specified.
This bug was introduced by the optimizations in https://github.com/chipsalliance/chisel3/pull/2611 so it only applies to 3.6.
- bug fix
No impact
No impact
- Squash
Fix bug where `Flipped` would not actually flip when the argument is assigned to a val before being passed to `Flipped`.
> Fix bug where Flipped did not properly flip

- core/src/main/scala/chisel3/Aggregate.scala
- core/src/main/scala/chisel3/Data.scala
- src/test/scala/chiselTests/AutoClonetypeSpec.scala
- src/test/scala/chiselTests/LazyCloneSpec.scala
Follow on to https://github.com/chipsalliance/chisel3/pull/2919. Fixes a couple of minor bugs and enhances the implementation from https://github.com/chipsalliance/chisel3/pull/2611.
This fixes 2 bugs:
* Lazy clone checking for external references must include Records
* Lazy clone checking for Records must be recursive.
The simple fix for the 2nd bug has a large negative impact on the utility of the lazy cloning, so this also tweaked the implementation to require more storage per Record, but identify more cases where cloning is not necessary.
Also see the description for the PR changing the lazy cloning algorithm:
Change mustClone calculation to use _minId
Previously it used a calculation of whether a given Record (or Bundle)
contained an "external reference", defined as any element with …
> Fix lazy cloning and apply the optimization in more cases

- core/src/main/scala/chisel3/StrongEnum.scala
- core/src/main/scala/chisel3/internal/Builder.scala
ChiselEnums check if they should create annotations every time an instance of them is bound. Because so many annotations would be created, they check to see if an equivalent annotation has already been added to the annotations. Previously, this used a linear search of the annotations, now it uses a HashSet.
I noticed this inefficiency glancing at a Flamegraph of a very large design. In that case, just eyeballing where this is obviously showing up, it's at least 18% of the runtime. As with all things that are fundamentally `O(n*m)`, the benefits from this change will be greatest in large designs with lots of annotations (`n`) and lots of `ChiselEnum`s (`m`).
No impact
No impact
- Squash
Improve …
> Improve performance of ChiselEnum annotations

- core/src/main/scala/chisel3/internal/Builder.scala
- src/test/scala/chiselTests/VecToTargetSpec.scala
- code cleanup
The only effect on the current API should be that existing usages that threw errors should now throw a more precise and helpful error.
This has no impact on code generation.
- Squash
Improved error message when targeting Vec subaccess
> Check for Vec subaccess in NamedComponent and throw a nicer error.

- src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
- src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
Make TruthTable implement structural equality
We had implemented equals, but not hashCode. This PR also changes the implemental of equals to just use the underlying values instead of wasting the compute calling .toString.
Also, delete sort, it is unused. I will deprecate it on the backport.
- bug fix 
This removes the public sort method from `TruthTable`, it was not functional but does need to be deprecated in 3.5.x.
No impact.
- Squash
Implement TruthTable.hashCode so that caching will now work. Also delete TruthTable.sort which was unused.
> TruthTable improvements: structural equality and delete sort

- core/src/main/scala/chisel3/Bits.scala
- core/src/main/scala/chisel3/internal/firrtl/IR.scala
- src/test/scala/chiselTests/ChiselSpec.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
- src/test/scala/chiselTests/SIntOps.scala
- src/test/scala/chiselTests/UIntOps.scala
- src/test/scala/chiselTests/WidthSpec.scala
These are in the FIRRTL language specification now and supported by both SFC + MFC.
If integer literal width is specified, support zero-width (`0.U(0.W)`), otherwise at least 1-bit (`0.U`), for compatibility with existing code.
Modified `assertKnownWidth`/`assertInferredWidth` to allow checking for width of zero, avoid attempting to use `-1S(0.W)`.  Used these to check basic zero-width behavior of wires/regs being initialized with zero-width integer literals.
Add a few tests to ensure zero-width literals and a few operations/constructs work as expected, and that their behavior is preserved.
Add support for zero-width integer literals, which must be explicitly requested (`0.U(0.W)`), for compatibility reasons `0.U` will still …
> Support zero-width integer literals.

- .github/workflows/test.yml
- ci
No impact
No impact, this only affects CI (but users copying the version from CI will see substantial changes
- Squash
> [CI] Bump firtool to 1.28.0

- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/internal/firrtl/Converter.scala
- src/test/scala/chiselTests/Direction.scala
- src/test/scala/chiselTests/RecordSpec.scala
I noticed that `OpaqueTypes` do not get the proper direction in the output FIRRTL. When debugging why this was the case, I realized that it's the same fundamental issue as my nemesis bug...
The bug that will never die, see https://github.com/chipsalliance/chisel3/pull/945, https://github.com/chipsalliance/chisel3/issues/1063, https://github.com/chipsalliance/chisel3/issues/1192, and https://github.com/chipsalliance/chisel3/pull/1196 (I would not be surprised if there are more that my quick search missed).
For years, Chisel always seemed to have bugs around whether you put direction operators inside or outside of a Vec, `Output(Vec(2, ...))` vs. `Vec(2, Output(...))`. Our fixes to this in the past were piecemeal, never addressing the true root cause, and it turns out... **it's still …
> Fix FIRRTL direction calculations for Vec and OpaqueType

- .github/workflows/test.yml
- website/project/Contributors.scala
Things seem to randomly fail when looking up the contributors. This will provide more information when that occurs and also fix what I suspect to be the cause (we had the token environment variable wrong).
- bug fix 
No impact
No impact
- Squash
> [website] Make Contributors fetching more robust

- ROADMAP.md
Remove loadMemoryFromFile (and implicitly loadMemoryFromFileInline) from the non-exhaustive list of deprecated things in the Roadmap.  This is now planned to be supported by MFC (https://github.com/llvm/circt/pull/4622).
> Remove loadMemoryFromFile from Deprecated Roadmap, NFC

- src/main/scala/circt/stage/phases/CIRCT.scala
There already exists a `logger` invocation to get at this data if it is necessary. By using an unconditional println we cannot suppress this log.
> Remove unconditional log

- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
Deprecate implementation details related to the loadMemoryFromFile API. Specifically, deprecate the Chisel-level annotation and the SFC transform while preserving the Chisel APIs.  The Annotation will, after Chisel 3.6 be made private and the transform will be deleted.
I'm planning to remove these from the `chisel5-slice-n-dice` branch and wanted to get these in as deprecated in Chisel 3.6.
> Deprecate loadMemoryFromFile SFC Details

- src/main/scala/chisel3/util/experimental/ForceNames.scala
- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
Deprecate forceName APIs on components.  These are only supported on modules/instances in the MFC.  (This could be revived in the future if desired.)
Deprecate the ForceNamesTransform.  This doesn't need to be public given that the forceName Chisel API is available to users.
This PR is stacked on #2986.
> Deprecate forceName Component APIs, Transform

- src/main/scala/chisel3/util/experimental/ForceNames.scala
- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
- src/test/scala/chiselTests/experimental/ForceNames.scala
Change the ForceNamesSpec, a test of the forceName Chisel API, to use the MFC instead of the SFC.  This requires deleting all tests forcing component names as this is not supported by the MFC.
This PR is stacked on https://github.com/chipsalliance/chisel3/pull/2987 which deprecates the APIs whose tests are removed here.
> Convert ForceNamesSpec to use MFC

- src/main/scala/chisel3/util/experimental/ForceNames.scala
- src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
- src/test/scala/chiselTests/AnnotationNoDedup.scala
- src/test/scala/chiselTests/experimental/ForceNames.scala
Convert the AnnotationNoDedup test to use the MFC.
This is a stacked PR as it's easier to manage the `chisel5` branch this way.
> Move AnnotationNoDedup Test to MFC

- src/main/scala/circt/stage/phases/CIRCT.scala
Remove an incorrect code path in the CIRCT phase that would convert a "ReplSeqMemAnnotation" into a "-blackbox" argument.  This option has existed for a long time and this would just cause "firtool" to error. Users will need to use the dedicated "-repl-seq-mem" options to "firtool" going forward (which is exactly what they have to do now).
> [CIRCT] Remove wrong ReplSeqMemAnno to bbox arg

- core/src/main/scala/chisel3/Num.scala
- core/src/main/scala/chisel3/RawModule.scala
- core/src/main/scala/chisel3/connectable/Connection.scala
- core/src/main/scala/chisel3/experimental/Attach.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
- core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
- core/src/main/scala/chisel3/internal/Error.scala
- core/src/main/scala/chisel3/package.scala
- src/main/scala/chisel3/aop/Select.scala
- src/main/scala/chisel3/compatibility.scala
- src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
- src/main/scala/chisel3/util/experimental/ForceNames.scala
- src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
- src/test/scala/chiselTests/ChiselEnum.scala
- src/test/scala/chiselTests/InstanceNameSpec.scala
- src/test/scala/chiselTests/LiteralToTargetSpec.scala
- src/test/scala/chiselTests/MultiAssign.scala
- src/test/scala/chiselTests/OneHotMuxSpec.scala
- src/test/scala/chiselTests/RawModuleSpec.scala
- src/test/scala/chiselTests/ToTargetSpec.scala
- src/test/scala/chiselTests/stage/ChiselMainSpec.scala
It was previously aliased from chisel3.internal which is bad for ScalaDoc.
- code cleanup
ChiselException has moved, this is binary incompatible but source compatible because there is a deprecated alias in package chisel3.internal
No impact
- Squash
Move Chisel exception from package chisel3.internal to package chisel3. It had been aliased in package chisel3 but moving it allows it to show up in the ScalaDoc.
> Promote ChiselException to package chisel3

- src/main/scala/circt/stage/phases/CIRCT.scala
Change the CIRCT phase to no longer drop the CombinationalPath annotation.  This dropping behavior was done to enable an SFC->MFC handoff where the SFC can produce this annotation.  Chisel can never produce this annotation, so it is safe to have MFC error if it sees it.
This is done in preparation to drop this annotation on the `chisel5` branch.
> [CIRCT] Remove CombinationalPath Anno Dropping

- src/main/scala/circt/stage/phases/CIRCT.scala
Remove dropping of RunFirrtlTransformAnnotation.  This isn't necessary to drop as firtool will drop these if it sees them.  There is utility in _not_ dropping these as it removes a dependency from the "circt" package on transforms that will be removed from the "firrtl" package on the chisel5 branch.
> [circt] Stop dropping RunFirrtlTransformAnnotation
