core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/package.scala
`WireInit` will now show up in ScalaDoc, no functional change.
- 
`WireInit` is now an actual object instead of just an alias, this is a source and binary compatible change.
No impact
- Squash
Tweak definition of `WireInit` so that it now shows up in API docs.
=> Change WireInit from val to object for ScalaDoc

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
This allows users to see what name Chisel plans to give a Data. This name is NOT guaranteed and the docs warn heavily about that.
This has been requested for debugging purposes--it's not an API I'd recommend using but that's why it's in `DataMirror` with a bit of an obnoxious name 😇 
API expansion
No impact
- Squash
Add `DataMirror.queryNameGuess` for getting some information about what Chisel might name a `Data`. This should not be relied upon and often will not match the name in the output Verilog, see API docs.
=> Add DataMirror.queryNameGuess

src/main/scala/circt/stage/ChiselStage.scala, src/main/scala/circt/stage/phases/CIRCT.scala
Simplify the dependency specification for CIRCT stage/phase infra to enable removal of some FIRRTL phases on the chisel5 branch.
This is primarily to remove the dependency on `AddImplicitEmitter`.
=> [circt] Remove reliance on some FIRRTL Phases

docs/src/cookbooks/hierarchy.md, src/main/scala/chisel3/stage/ChiselStage.scala, src/main/scala/chisel3/stage/package.scala
Deprecate existing ChiselStage class and object as this will be removed in Chisel 5.  Add a message telling people to switch to the equivalent circt class/object.
I'm preparing to remove this on the `chisel5` branch, hence the deprecation. This would be ideal to get this into Chisel 3.6.
=> Deprecate chisel3.stage.ChiselStage

src/main/scala/chisel3/util/experimental/group.scala
Deprecated chisel3.util.experimental.group since Chisel 3.6 as this is an API unsupported by the MFC.
=> Deprecate group API

src/main/scala/circt/stage/Annotations.scala, src/main/scala/circt/stage/CIRCTStage.scala, src/main/scala/circt/stage/ChiselStage.scala, src/main/scala/circt/stage/phases/CIRCT.scala, src/test/scala/chiselTests/Printf.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Remove the dependency of circt.stage.ChiselStage on chisel3.stage.ChiselStage.  Remove the internal call to ChiselStage and instead directly construct a PhaseManager that uses the target phases of ChiselStage directly.
Add a new argument type to the existing "--target" option of circt.stage.ChiselStage, "chirrtl", to indicate that specification FIRRTL (in the specification textual format and not MLIR) should be produced.
Use this new option to migrate two methods of ChiselStage$, emitCHIRRTL and convert, away from using a call to chisel3.stage.ChiselStage.
Add tests of the new option, emitCHIRRTL, and convert.
=> Decouple {circt, chisel3}.stage.ChiselStage

src/main/scala/circt/stage/phases/CIRCT.scala
Cause the ChiselCircuitAnnotation (which is Unserializable and will be dropped) to be passed through the CIRCT phase.  This is necessary to enable certain D/I use cases where an ImportDefinitionAnnotation is constructed from a ChiselCircuitAnnotation returned from a prior ChiselStage invocation.
=> Pass ChiselCircuitAnnotation through CIRCT phase

core/src/main/scala/chisel3/connectable/Connectable.scala, src/test/scala/chiselTests/ConnectableSpec.scala
Also switch ConnectableSpec to use circt.stage.ChiselStage.
This is a somewhat subtle issue, so here's a Scastie showing it: https://scastie.scala-lang.org/mDkIjDF5TBSTHJ20f5m9og
Basically and OpaqueType of a Flipped element should function the same as a Bundle of 1 flipped element, and it does in almost every case except for `:<>=` of two wires of the type, this fixes that.
- bug fix 
No changes
No change
- Squash
Fix `:<>=` connection of two opaque types of flipped elements
=> Fix Connectable connections between wires of OpaqueTypes of flipped elements

src/test/scala/circtTests/stage/ChiselStageSpec.scala
Copy relevant tests about chisel3.stage.ChiselStageSpec into circt.stage.ChiselStageSpec.  This covers cases related to exception handling and error reporting.  All other tests are already duplicated.
This is done in preparation to remove chisel3.stage.ChiselStage on the chisel5 branch. (!!!)
=> Copy chisel3.stage.ChiselStageSpec tests for CIRCT

src/main/scala/chisel3/compatibility.scala, src/test/scala/chisel3/testers/TestUtils.scala, src/test/scala/chiselTests/AnnotatingDiamondSpec.scala, src/test/scala/chiselTests/ChiselEnum.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/ConnectableSpec.scala, src/test/scala/chiselTests/InvalidateAPISpec.scala, src/test/scala/chiselTests/NewAnnotationsSpec.scala, src/test/scala/chiselTests/WarningSpec.scala, src/test/scala/chiselTests/experimental/SerializableModuleGeneratorSpec.scala, src/test/scala/chiselTests/experimental/TraceSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala, src/test/scala/chiselTests/util/SizeOfSpec.scala
Modify tests, other than ChiselStageSpec, to all use circt.stage.ChiselStage and not chisel3.stage.ChiselStage.  This paves the way for the deletion of the latter in Chisel 5.
Note: there is one bug in the Trace API resulting in a commented out test.  This is tracked with this CIRCT issue:
- https://github.com/llvm/circt/issues/4661
=> Convert tests to circt.stage.ChiselStage

src/main/scala/chisel3/stage/ChiselAnnotations.scala
Deprecate this Annotation/Option which is only used by chisel3.stage.ChiselStage.  An equivalent effect can be had with the emitCHIRRTL method of the ChiselStage$ object or using the "--target chirrtl" option of the ChiselStage class.
=> Deprecate NoRunFirrtlCompilerAnnotation

src/main/scala/circt/stage/CIRCTStage.scala
Remove an unnecessary optionalPrerequisite of CIRCTStage on the SFC Compiler phase.  This is entirely unnecessary given that there is no longer an SFC -> MFC handoff path within CIRCT-based Chisel compilation flows.
=> [circt] Remove CIRCTStage optional prereq on SFC

src/main/scala/circt/stage/CIRCTStage.scala
Deprecate CIRCTStage and CIRCTMain.  These are stage-based wrappers around just running firtool that are roughly equivalent to FirrtlStage and FirrtlMain that did this for the SFC.  These do not have users and it is unclear why these should persist given that
circt.stage.ChiselStage subsumes almost all use cases (going Chisel to Verilog or Chisel to CHIRRTL and then using the build system to go from CHIRRTL to Verilog).
=> Deprecate CIRCTStage (firtool wrapper)

src/main/scala/circt/stage/Annotations.scala, src/main/scala/circt/stage/CIRCTOptions.scala, src/main/scala/circt/stage/CIRCTStage.scala, src/main/scala/circt/stage/phases/CIRCT.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Add an option to "circt.stage.ChiselStage", "--split-verilog", which replaces the janky "firrt.EmitAllModulesAnnotation" method of generating one-file-per-module output and output file splitting in "firtool". Leave in the old behavior as a run-time warning until this gets removed sometime after the Chisel 5 release.
=> Add "--split-verilog" circt.*.ChiselStage option

src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
Remove a bunch of unnecessary code that depends on SFC features from the AnnotatingDiamondSpec.
=> Remove SFC Dependencies in AnnotatingDiamondSpec

src/main/scala/circt/stage/CIRCTStage.scala
Remove an unnecessary "currentState" argument when constructing the internal PhaseManager of CIRCTStage.  This is no longer necessary given that CIRCTState doesn't have to interoperate with SFC in any way.
This enables removal of this phase on the chisel5 branch.
=> Remove a FIRRTL phase CIRCTStage "currentState"

src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
Deprecate ProtoBufFileFormat and warn if a user is doing Protobuf emission.  This will be ripped out in Chisel 5.
=> Deprecate Protobuf Emission

src/main/scala/circt/stage/package.scala, src/test/scala/chiselTests/BlackBoxImpl.scala, src/test/scala/chiselTests/ExtModuleImpl.scala, src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala, src/test/scala/chiselTests/experimental/TraceSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Fix a bug where "--split-verilog" was not properly passed into the CIRCTOptions struct.  Add a test to lock in the correct behavior.
Also, move _all_ tests over to use "--split-verilog".
=> Fix bug in "--split-verilog" output

build.sbt, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/main/scala/circt/stage/phases/CIRCT.scala
Fixed up two final warnings.
In BoringUtils replace deprecated SyncVar with BuilderContextCache
In stage.phases.CIRCT fixed possible not exhaustive match
Number of warnings in 2.13 == 0
=> Cleanup warnings final

plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala, src/test/scala/chiselTests/AutoClonetypeSpec.scala
- code refactoring                  
Using private default constructors for bundles will issue an error
N/A
Private default bundle constructors now error during evaluation
=> Catch private default constructors for Bundles and Records

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/Error.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselCli.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/CIRCTStage.scala, src/main/scala/circt/stage/phases/CIRCT.scala, src/test/resources/chisel3/sourceroot1/Foo, src/test/resources/chisel3/sourceroot2/Foo, src/test/scala/chiselTests/stage/ChiselMainSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
This includes new command-line option --source-root which allows the user of Chisel to point to the root directory for source files. The default value is "." which should work for typical SBT and Mill projects.
- new feature/API 
New command-line, annotation API into Chisel, but no other API impact.
No impact
- Squash
Improve error reporting with source line and caret pointing to column. This requires knowing the root directory of source files which can be provided with `--source-root <dir>`. It will default to `.` which is the directory in which the Chisel elaboration process is invoked which should be correct for typical projects.
=> Give a source line and caret for errors when possible

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
We [can't use 1.32.0](https://github.com/chipsalliance/chisel3/pull/3040#issuecomment-1447238681) so just bump to 1.31.0 for Chisel 3.6.0-RC2.
=> Bump firtool to 1.31.0

.github/workflows/test.yml, build.sbt, website/build.sbt
Setup initial Chisel 5 SNAPSHOT publishing
~This _almost works_, but I think `sbt-ci-release` only publishes the plugin and not the new `unipublish` project so I need to get that working before we can merge.~ This is now ready to go.
No impact
No impact
- Squash
Change published artifact from edu.berkeley.cs::chisel3 to org.chipsalliance::chisel. Set up automated publishing for 5.0-SNAPSHOT (to s01.oss.sonatype.org because Chips Alliance is a relatively new Sonatype organization). Merge old `firrtl`, `chisel3-macros`, `chisel3-core`, and `chisel3` artifacts into a single artifact: `chisel`.
=> Chisel5 publishing

docs/src/cookbooks/verilog-vs-chisel.md, integration-tests/src/test/scala/chiselTest/LFSRSpec.scala, src/main/scala/chisel3/Cat.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/util/util.scala, src/test/scala/chiselTests/CatSpec.scala
Move Cat function to chisel3 package from chisel3.util
Supercedes PR #3051 
- code cleanup
- 
Cat import has moved to chisel3. util.Cat is deprecated
No changes
The Cat operator has been moved to the chisel3 package. The util.Cat operator has been deprecated
=> Move the Cat object to chisel3 package

.github/workflows/test.yml, build.sbt
Pushes to main will now have SNAPSHOTs based on `git describe --tag`. Also run CI workflow (which includes publishing) on push to any tag and enable workflow_dispatch.
Earlier today, I pushed `v5.0.0-M1` (https://github.com/chipsalliance/chisel/releases/tag/v5.0.0-M1) which gives us a tag in the history to use for deriving versions.
Using this commit and an extra dummy commit, Maven artifact ordering does appear to be correct for the versions given by SBT dynver.
For example,
```scala
import org.apache.maven.artifact.versioning.ComparableVersion
val x = new ComparableVersion("5.0.0-M1+1-c3a34983-SNAPSHOT")
val y = new ComparableVersion("5.0.0-M1+2-c345858d-SNAPSHOT")
x.compareTo(y) // -1
y.compareTo(x) // 1
```
See Scastie: https://scastie.scala-lang.org/l13ZLA0DSOu8hw63fSCuAA
See API …
=> Let sbt-dynver control the SBT version

.github/workflows/test.yml
We accidentally published such SNAPSHOTs as `0.0.0+1-2ebb8670-SNAPSHOT` 😬
=> [CI] Do full unshallow clone for publish job

build.sbt
Now if you try to publish from a shallow clone, it will error. This check would've helped detect https://github.com/chipsalliance/chisel/pull/3069.
=> Require unshallow clone to publish in SBT

src/main/scala/chisel3/util/Mux.scala, src/test/scala/chiselTests/MuxSpec.scala
adds `chisel3.util.MuxLookup.fromEnum`
none
Squash
add `chisel3.util.MuxLookup.fromEnum`
=> add MuxLookup.fromEnum

.github/workflows/test.yml
Also remove deploy_website job as we only want to deploy the website from main.
- ci fix
No impact
No impact
- Squash
=> Enable CI on push to 3.6.x

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/main/scala/chisel3/internal/firrtl/Emitter.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Now emitting [FIRRTL version 1.2.0](https://github.com/chipsalliance/firrtl-spec/releases/tag/v1.2.0).
This fixes `.fir` serialization to include the FIRRTL spec version. It was previously working just for `chisel3.stage.ChiselStage.emitChirrtl` (which no longer exists but does on 3.6.x and 3.5.x branches), but it didn't work for anything using the `CircuitSerializationAnnotation` (which uses the `Emitter`).
The backport does not include the spec version bump (since the spec version is specified in SFC on older branches), just the fix.
- bug fix
Now emitting FIRRTL 1.2.0 and in more cases. This will be rejected by versions of SFC older than v1.5.5 and firtool older than 1.12.0.
This bumps the version in the emitted `.fir` and ensures we always emit a version in the `.fir`.
- Squash
Fix …
=> Fix FIRRTL spec emission and bump to spec 1.2.0

src/main/scala/circt/stage/phases/CIRCT.scala
Change CIRCT to turn on read-write inference by default. Re
move the ability to disable inter-module constant propagation (IMCP) when
running with CIRCT.  These options were removed in:
https://github.com/llvm/circt/commit/9620d656f8a59998cc38472a60f83bfdcb6a8549
=> Remove deprecated CIRCT Options

docs/src/cookbooks/verilog-vs-chisel.md, integration-tests/src/test/scala/chiselTest/LFSRSpec.scala, src/main/scala/chisel3/util/Cat.scala, src/test/scala/chiselTests/util/CatSpec.scala
It is a very painful change for users with marginal benefit. We plan to change the package to chisel in the not-so-distant future--that's a much better opportunity to make this change.
FYI @sequencer @chick 
See https://github.com/chipsalliance/chisel/pull/3075 for relevant discussion about the original change, this is a manual revert of https://github.com/chipsalliance/chisel/pull/3062
Restore the Chisel 3.6.0-RC2 API
No impact
- Squash
Restore `Cat` to package `chisel3.util`, remove it from package `chisel3`.
=> Undo move of Cat from chisel3.util to chisel3

macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala, src/main/scala/chisel3/util/Mux.scala
It seems that deprecations on methods that are macro expanded away do not actually trigger a deprecation warning. Instead, we will just accept no source locator on the deprecated API (no released version of Chisel has the source locator).
This is needed before we can crack another 3.6 release.
- bug fix
Removes a macro definition that has never been released and should not be used by users anyway.
No impact
- Squash
=> Fix MuxLookup old API deprecation

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
Directly subclassing Iterable is lazy-ish, but if you call any operation on the resulting value (eg. map or ++) it will evaluate the Iterable and return a List.
Forward port of https://github.com/chipsalliance/firrtl/pull/2627, no need to backport because the fix is on the firrtl repo for 3.6.x and before.
No impact
No impact
- Squash
Reduce peak memory usage during .fir serialization by using lazy intermediate data structures.
=> Make return value of Serializer.lazily lazy

.devcontainer/Dockerfile
While the first iteration of the Dockerfile was great for browsing chisel source code, it wasn't actually sufficient for building and testing Chisel. This PR adds the following improvements to make in-container Development viable:
- Switch to Java11 to avoid deprecation errors
- Install Firtool
(@jackkoenig to review?)
=> More VSCode Devcontainer Improvements

build.sbt
I missed this is review of https://github.com/chipsalliance/chisel/pull/3121
- bug fix
svsim will now be in the published jars
No impact
- Squash
=> Fix svsim to publish as part of unipublish

src/main/scala/chisel3/simulator/PeekPokeAPI.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala, svsim/README.md, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala, svsim/src/test/scala/BackendSpec.scala
New feature/API
Added a `Simulator` class which provides the glue code to use Chisel modules with `svsim`.
Next steps: Create an interface designed for unit tests and port `ChiselRunner` to use that interface.
This is all new API, though I have renamed `SvsimCompilationSettings` to `svsim.CommonCompilationSettings` which I think is clearer.
None
- Added `chisel3.simulator.Simulator` for simulating Chisel modules with `svsim`
=> Add `Simulator` class for simulating Chisel modules with `svsim`

.devcontainer/Dockerfile
I just added a "full sources" release artifact to CIRCT: https://github.com/llvm/circt/pull/4901
This PR changes the devcontainer to use this artifact instead of `git clone` for significantly faster startup. It should also be a bit "safer" than just using the top of main.
Developer QOL improvement
=> [devcontainer] Use CIRCT full source bundle instead of git

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, firrtl/src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala, firrtl/src/test/scala/firrtlTests/stage/phases/ChecksSpec.scala, src/main/scala/chisel3/stage/phases/Convert.scala, src/test/scala/chisel3/testers/TestUtils.scala, src/test/scala/chiselTests/AnnotatingDiamondSpec.scala, src/test/scala/chiselTests/ChiselEnum.scala, src/test/scala/chiselTests/NewAnnotationsSpec.scala, src/test/scala/chiselTests/stage/phases/ConvertSpec.scala, src/test/scala/chiselTests/util/SizeOfSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala, src/test/scala/circtTests/stage/phases/AddImplicitOutputFileSpec.scala
Change FIRRTL Circuit conversion/serialization to place ChiselAnnotations (converted to FIRRTL Annotations) inside the FIRRTL Circuit and to serialize this using the "%[[]]" inline JSON format that is present in the FIRRTL spec.  This does not remove _all_ annotations passed via the annotation file, but it is the first step towards that.
=> Use %[[]] format for ChsielAnnotations

src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/PeekPokeAPI.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chiselTests/simulator/EphemeraSimulatorSpec.scala, src/test/scala/chiselTests/simulator/GCD.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala, svsim/src/main/resources/simulation-driver.cpp
Introduce `chisel3.simulator.EphemeralSimulator` for ephemeral scenarios (such as scala-cli).
This PR also adds `stepUntil` to PeekPokeAPI. This is effectively just svsim's `TICK` but is generally useful (for example in the GCD module used in the tests).
New feature/API
- Introduce `chisel3.simulator.EphemeralSimulator` for ephemeral scenarios (such as scala-cli)
=> Add EphemeralSimulator API

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/config/release-notes.json, .github/workflows/release-notes.yml, .github/workflows/require-label.yml, CONTRIBUTING.md
Add new workflow to generate release notes. This workflow can be run manually via workflow dispatch, but will also run automatically upon creating a release. The workflow dispatch can be used for testing, previewing release notes for a potential release, or for generating release notes for past releases for when the automation has a bug or didn't exist.
No impact
No impact
- Squash
=> [CI] Add Release Notes Automation

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/connectable/Alignment.scala, core/src/main/scala/chisel3/connectable/Connectable.scala, core/src/main/scala/chisel3/connectable/Connection.scala, docs/src/explanations/connectable.md, src/test/scala/chiselTests/ConnectableSpec.scala
Added a `.exclude` mechanism to `Connectable`, allowing fields to always be ignored by any connectable operator.
This is useful for omitting all `Analog` types from a bundle, prior to connecting it. I believe we should then make the directioned operators (`:=`, `:#=`, `:<>=` etc.) just error if it encounters an `Analog` type, but that can be a future PR.
This also jives with #3088 as probe types should also be omitted, as they have their own "connection-like" API called `define`.
Added `.exclude` mechanism on `Connectable` to enable never connecting to/from the marked fields using any connectable operator.
=> Added .exclude to Connectable

src/main/scala/circt/Convention.scala, src/test/scala/circtTests/ConventionSpec.scala
This annotation is being handled in mfc via:
https://github.com/llvm/circt/pull/4665
The convention lets users define how ports with aggregate types are lowered to verilog.
=> Add an annotation for specifying module port conventions

build.sbt
Remove deprecated "sonatypeRepo" from firrtl compilation unit.  This is unnecessary given that the firrtl compilation unit uses "commonSettings" which already include the non-deprecated versions of the Sonatype Repositories.
=> Remove unnecessary sonatype resolvers for firrtl

README.md, SETUP.md
-  docs cleanup
No impact
No impact
- Squash
=> Update README.md for Chisel 5

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/Clock.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/experimental/Analog.scala, src/test/scala/chisel3/TypeEquivalenceSpec.scala
This utility provides a way to check different versions of type equivalence in Chisel internals and generates error messages for when mismatches are found. Specifically, it handles structural vs. nominal typing as well as strict vs. non-strict width checking.
This helps fix (but does not actually include the fix) https://github.com/chipsalliance/chisel/issues/3200.
- Squash
=> Add Data.findFirstTypeMismatch for better type checking

build.sbt
This makes it much easier to automate checking new versions as they are released.
- Squash
We can now simply append versions as they are released to `project/previous-versions.txt` on relevant release branches. `build.sbt` also now contains instructions are how to waive binary compatibility breakages.
=> Read previousVersions for bincompat checking from a file

src/main/scala/chisel3/interface/Interface.scala, src/test/scala/chiselTests/interface/Drivers.scala, src/test/scala/chiselTests/interface/InterfaceSpec.scala, src/test/scala/chiselTests/interface/ParametricInterfaceSpec.scala
Migrate work from [seldridge/chisel-separable](https://github.com/seldridge/chisel-separable) on separate compilation into upstream Chisel.  This defines an Interface and a Conformance.  An Interface is a Singleton Object that maps to a FIRRTL external module with pre-defined IO.  A Conformance is a type-class whose implementations define how a Chisel module aligns itself to the Interface.  Used together, these enable separate compilation of a client that uses an Interface from a component that implements the Interface.
This originally came from https://github.com/seldridge/chisel-separable/. We've used this internally in non-load-bearing ways and it's becoming unwieldy to continue to maintain out-of-tree.
This API may change rapidly in the future.
Add Interface/ConformsTo APIs for …
=> [Feature] Add Interface, ConformsTo for Separate Compilation

core/src/main/scala/chisel3/connectable/Connection.scala, core/src/main/scala/chisel3/internal/BiConnect.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala/chiselTests/Vec.scala
Fixes #3200 
- Bugfix
- Squash
=> Revert checks for size 0 Vecs in connections

core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala, src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Instantiate was released in 3.6.0 and 5.0.0-RC1
- Bugfix
- Squash
Instantiate previously erased type information for case classes and case objects which could result in incorrect behavior.
=> Fix Instantiate for Product parameters

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/experimental/Analog.scala, core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala, core/src/main/scala/chisel3/experimental/prefix.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/naming/PrefixSpec.scala
This is a more complete implementation of #3167 , but rather than delaying closing of a module, adds a special area where ports and connections can be added to a module, post-closing. This second phase is closed when calling `.toDefinition` or reflecting on the ports (e.g. with `DataMirror`). 
A longer term plan is to fix some internals (e.g. when closing happens) so that we can unify these phases more gracefully.
For handling the D/I case, we can consider https://github.com/chipsalliance/chisel/pull/3173 as one approach.
- Squash: The PR will be squashed and merged (choose this if you have no preference.)
Added a new BoringUtils.bore that is performed during Chisel elaboration, not via Annotations+CIRCT. Punched ports are accessible to the user via DataMirror. …
=> Handle BoringUtils in Chisel, rather than in FIRRTL compiler

src/main/scala/chisel3/interface/Interface.scala, src/test/scala/chiselTests/interface/InterfaceSpec.scala, src/test/scala/chiselTests/interface/ParametricInterfaceSpec.scala
Change an abstract def to a val when specifying the ports of an Interface.  This improves the static nature of the Interface and prevents abuse as leaving this a s a def (a function) makes it a generator.
h/t @azidar
=> Change ports in Interface to be a val

src/main/scala/chisel3/util/circt/ClockGate.scala, src/test/scala/chiselTests/util/BitPatSpec.scala, src/test/scala/chiselTests/util/BitSetSpec.scala, src/test/scala/chiselTests/util/BitwiseSpec.scala, src/test/scala/chiselTests/util/CatSpec.scala, src/test/scala/chiselTests/util/PipeSpec.scala, src/test/scala/chiselTests/util/PriorityMuxSpec.scala, src/test/scala/chiselTests/util/RegSpec.scala, src/test/scala/chiselTests/util/circt/ClockGate.scala, src/test/scala/chiselTests/util/circt/IsXSpec.scala, src/test/scala/chiselTests/util/circt/PlusArgsTestSpec.scala, src/test/scala/chiselTests/util/circt/PlusArgsValueSpec.scala, src/test/scala/chiselTests/util/circt/SizeOfSpec.scala
Add the `circt.clock_gate` intrinsic. This is not yet used anywhere and has no impact on existing code. Also move CIRCT-specific tests into a `circt` subpackage of `chiselTests.util` to reflect the main package structure.
- New API
- Squash
Add support for the `circt.clock_gate` intrinsic.
=> Add ClockGate intrinsic

src/main/scala/chisel3/interface/Interface.scala, src/test/scala/chiselTests/interface/InterfaceSpec.scala
Fix a bug where the name of the Stub module (a module auto-generated from an Interface without an implementation available) would be called "Stub" as opposed to the name of the Interface.  This could create a linker error if the Stub was used.  Fix this by correctly setting the "desiredName". Add a test that this works.
=> [interface] Fix Wrapper.Stub Name

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
Bump firtool version to get parsing of new connect/invalidate statements.
Bump firtool from 1.38.0 to 1.40.0. See the following release notes for more information:
- [1.39.0 Release Notes](https://github.com/llvm/circt/releases/tag/firtool-1.39.0)
- [1.40.0 Release Notes](https://github.com/llvm/circt/releases/tag/firtool-1.40.0)
=> Bump firtool version to 1.40.0

core/src/main/scala/chisel3/Mem.scala, src/test/scala/chiselTests/Mem.scala
#3221 removed the usage of a temporary wire in `SyncReadMem.read` that, at first glance, appears to be redundant; however it turns out that this wire is important for helping SFC and firtool infer the correct address values for the port. This PR undoes that specific change and additionally adds an integration test to both document the behavior and test against it.
- Bugfix
=> Undo removal of address intermediate wire in `SyncReadMem.read`, `SyncReadMem.readWrite`

.github/workflows/enable-bincompat-checking.yml
I developed this on a little mini repo, I'm pretty sure it works: https://github.com/jackkoenig/test-on-release
Now whenever a release is created, this action will automatically open PRs to check binary compatibility on any stable branches that include the particular tag. This does include main which can be useful for using main as a major release branch.
- Squash
=> Add workflow to automatically update binary compatibility checks

.github/workflows/enable-bincompat-checking.yml
The new Chisel Bot https://github.com/chiselbot will be responsible for opening automated PRs so that:
1. CI will run when they are opened, see https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs, and
2. I will be able to approve the PRs (if I used a personal token, then it would open PRs as me).
=> Use Chisel Bot Token for automated PRs

.github/workflows/backport-fixup.yml
The Mergify-generated backports do not currently include the information needed by the release notes generation automation. This new workflow will copy such information over to backport PRs.
- Squash
Improve backport automation so that release notes generation from backport PRs works properly.
=> Add new workflow to fixup backports for release notes

core/src/main/scala/chisel3/experimental/dataview/package.scala, src/test/scala/chiselTests/experimental/DataView.scala
Change what DataView allows in its type checking to enable Reset to be viewed as either a UInt<1> or an AsyncReset.  This enables more flexible DataViews which match already allowable Chisel and FIRRTL connection semantics.
Change what DataView allows in its type checking to enable Reset to be viewed as either a UInt<1> or an AsyncReset.  This enables more flexible DataViews which match already allowable Chisel and FIRRTL connection semantics.
=> Allow DataView of Reset <=> [UInt<1>, AsyncReset]

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
Fix a bug in the new BoringUtils.bore API where this would generate invalid FIRRTL if the user did boring which created a path that went up to an LCA and then down.  Change the internal leastCommonAncestor utility to also return the LCA module as this avoids a second call to compute the LCA.
Fixes #3239.
Skipping release notes on this as the new BoringUtils API is not in a release.
=> [bugfix] Fix BoringUtils up--down bug

core/src/main/scala/chisel3/naming/Identifier.scala, src/test/scala/chiselTests/naming/IdentifierProposerSpec.scala
Fix a bug in naming where a Module that took a Unit parameter could cause naming to crash.  This is, admittedly, a very weird pattern, but can occur if you have a type-parametric module where certain type parameterizations can be Unit.
Fix #3245.
Fix bag where a Module with a Unit parameter crashes.
=> [bugfix] Fix naming module with Unit parameter

core/src/main/scala/chisel3/experimental/dataview/DataView.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, src/test/scala/chiselTests/experimental/DataView.scala
- fix a nondeterminism error in DataView noticeable on error reporting
- Bugfix
* Allow .viewAsSupertype to work on Records, with additional tests.
* Ensure that errors in DataView show the problematic fields in a deterministic order.
=> Enable .viewAsSupertype to work on Records

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
This does not seem to be required by Scala, but it is required by newer versions of SemanticDB (and thus to use Scala Metals).
Workaround for https://github.com/scalameta/scalameta/issues/3122.
- Squash
=> SemanticDB requires private fields of case class to use "val"

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/util/RegSpec.scala
Change FIRRTL emission to use a simpler syntax for registers without a reset.  Previously, this used a self-reset with a zero reset signal. Simplify this to emit a register without a reset.
Skip register emission in Chisel for reset-less registers.
=> [codegen] Simpler FIRRTL Code for Reg w/o Reset

core/src/main/scala/chisel3/RawModule.scala, integration-tests/src/test/scala/chiselTest/util/experimental/TapSpec.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
Add writable tap (`rwTap`) API to BoringUtils, which drills writable probe ports downwards only.
=> BoringUtils writable tap (rwTap) API

src/main/scala/chisel3/util/BitPat.scala, src/test/scala/chiselTests/util/BitSetSpec.scala
I also added some focused tests.
I am making this change because I noticed slow performance for a `TruthTable` that has 65k entries. The performance of just `==` on that `TruthTable` was pretty bad. Note that `==` for `BitSet` uses `cover`, so I first optimized that, then went ahead and also optimized `equals`, and then `overlap` was free so did that too. See benchmark for equality of two copies of a `TruthTable` with 65k entries:
| Change | Runtime | Speedup over Baseline |
| --- | --- | --- |
| Baseline | 68 ms | -  |
| Optimize cover | 3.9 ms | 17x |
| Optimize equals | 1.3 ms | 52x |
There are other improvements to be made, but this is pretty good and constrained.
=> Optimize BitPat equals, overlap, and cover

core/src/main/scala/chisel3/Module.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala
Fix a bug in BoringUtils (and secret IO APIs) where APIs would return a Data.  This could create problems if the BoringUtils APIs were used directly in operations, e.g., the following could cause a problem:
val a = b & BoringUtils.bore(c)
This requires some casting of DontCare as it is unfortunately not a proper "bottom" type.
No test is added as the test is that Scala passes type checking.
This has no release notes as this is a bugfix for a feature that is in 6.0.
=> [bugfix] Don't return Data from BoringUtils APIs

svsim/src/main/scala/Simulation.scala, svsim/src/test/scala/BackendSpec.scala
- Bugfix
- Fixed an issue where throwing an `assert` from an `svsim` simulation run may kill the simulated process before it can finish writing a waveform.
=> Make svsim shutdown gracefully when the test throws an exception

svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala, svsim/src/test/scala/BackendSpec.scala
- Allow users of chisel to specify their own `svsim.Backend` implementations outside of Chisel. This is useful since in-tree backends may not support all versions of the specified backend (and we don't necessarily want them to).
=> Allow out-of-package svsim backend implementations

core/src/main/scala/chisel3/Mem.scala
Fixes a bug where calling `SyncReadMem.readWrite` with an explicit `Clock` that is different from the memory's clock raises an implicit clock warning anyways, when this shouldn't be the case.
- Bugfix
- Squash
=> Don't emit implicit clock warnings for `SyncReadMem.readWrite` when explicit clocks are used

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/Vec.scala, src/test/scala/chiselTests/VecToTargetSpec.scala
This reduces the amount of work that both Chisel and firtool have to do.
=> Convert Vec dynamic index with a literal to static index

core/src/main/scala/chisel3/Aggregate.scala, docs/src/cookbooks/cookbook.md, src/test/scala/chiselTests/Vec.scala
Follow on to https://github.com/chipsalliance/chisel/pull/3033, applying the same change to Vec dynamic indices (previously it was just dynamic bit selection for UInts).
- Squash
=> Warn on incorrect widths for Vec dynamic indexing

build.sbt
This enables Chisel users to use these newer Scala versions.
- Squash
=> Add Scala 2.13.11 and 2.12.18 to plugin cross versions

core/src/main/scala/chisel3/internal/Error.scala
This is really hard to test. See Release Notes below for user-facing API and limitations.
I would like to test this but it can't be done in ScalaTest nor really even with SBT, you need to publishLocal and then use scala-cli and then some way of processing the output for correctness.
- Squash
* Chisel will now detect when it should print warnings, errors, and deprecations in color. 
* Color can be controlled with environment variable `CHISEL_USE_COLOR`. Set to `true` to force Chisel to use color and `false` to disable it.
* Due to how the JVM works, detection requires interactive stdout, stderr, **and** stdin. Build tools like SBT virtualize stdin and thus color will be disabled by default when running a Chisel main with SBT.  Detection also requires environment …
=> Fix color emission to check for interactive terminal

core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Fixes https://github.com/chipsalliance/chisel/issues/1089
- Bugfix
- Squash
Chisel will to report multiple errors, but this can be cut short by any thrown Exception which would then take precedence over the previously encountered errors. Now Chisel will prioritize reporting errors even if an Exception is thrown.
=> Report Builder errors even when exception is thrown

core/src/main/scala/chisel3/Bits.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
With https://github.com/chipsalliance/chisel/pull/3321, it becomes very important that users can extract zero bits. While the `(-1, 0)` looks a little funny, it is the correct API for parameterized code.
Motivating example:
```scala
import chisel3.util.log2Ceil
import circt.stage.ChiselStage.emitCHIRRTL
class Example(size: Int) extends Module {
val vec  = IO(Input(Vec(size, UInt(8.W))))
// Say we have a value we will use as an index but its width is unrelated to the Vec
val addr  = IO(Input(UInt(8.W)))
val out   = IO(Output(UInt(8.W)))
// Chisel warns on mismatched widths so we bit extract
val safeIdx = addr(log2Ceil(size) - 1, 0)
out := vec(safeIdx)
}
// Normal sizes work great!
emitCHIRRTL(new Example(8))
// What happens with the size of the Vec is 1?
emitCHIRRTL(new …
```
=> Add support for zero-width bit extraction

.devcontainer/Dockerfile, .gitignore
- Internal
- VSCode devcontainer now follows CIRCT top-of-tree rather than latest release
=> Make devcontainer point to CIRCT top-of-tree instead of latest release

src/test/scala/chiselTests/interface/InterfaceSpec.scala
=> Add test demonstrating a ref to an aggregate member

src/main/scala/chisel3/util/SRAM.scala
This PR adds a new String parameter to `SRAM.apply` which loads the contents of a binary file from the filesystem into the memory (invokes `loadMemoryFromFileInline` on the inner `SyncReadMem`.)
- Feature
- Squash and merge
`SRAM.apply` and `SRAM.masked` now take a `contents` parameter, by default a `None`, which is a string path to a binary file on the filesystem which the SRAM should be initialized with.
=> SRAM API: Add a parameter to initialize the memory 

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
Change the FIRRTL serializer to use literal identifiers if any identifiers begin with a leading digit.  This is a FIRRTL 3.0.0 feature that simplifies parsing.
This enables literal identifier emission anywhere.  However, this code path is only reachable via MixedVec due to mangling of numeric names to add a leading underscore in all other circumstances.  In the future, this commit will enable removing this restriction and switching to literal identifiers when this happens.
No changes are made to annotation targets.  E.g., the literal identifier, "wire `42`" in circuit "Foo" and module "Bar" is still referred to by a local target "~Foo|Bar>42".  This is intentional (for now).  Targets don't have parsing ambiguity like FIRRTL text and the name of this wire is still "42" not "`42`".  It …
=> [codegen] Emit literal identifiers for numeric ids

firrtl/src/main/scala/firrtl/passes/CheckTypes.scala, src/test/scala/chiselTests/ConstSpec.scala
This currently just ignores constness when determining if a bulk connect is valid, leaving const-checking to the firrtl compiler. I can add that checking here too, but I wasn't sure what our policy is on redundant checks between the two stages.
=> Support bulk connection for const types

src/main/scala/chisel3/util/Math.scala
* log2 functions
* unsignedBitLength
- Bugfix
- Squash
(The below might look weird but it'll make the release notes generation work better)
* log2 functions
* unsignedBitLength
=> Add messages to require statements in Math

core/src/main/scala/chisel3/experimental/dataview/package.scala, src/test/scala/chiselTests/experimental/DataView.scala
The best example of why this is useful is the test showing some possible uses with `Valid`:
```scala
object ValidExtensions {
implicit def view[T <: Data] = DataView[T, Valid[T]](
x => Valid(x.cloneType), // Valid will strip direction with `Output(...)` anyway
_ -> _.bits,
(_, v) => true.B -> v.valid
)
}
```
This enables you to box any `T` as a `Valid[T]` where the `valid` bit is the literal true:
```scala
import ValidExtensions._
class MyModule extends Module {
val in = IO(Input(UInt(8.W)))
val out= IO(Output(Valid(UInt(8.W))))
out := in.viewAs[Valid[UInt]]
}
```
- Squash
=> Support literals and DontCare in DataView targets

firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/ConstSpec.scala
- Bugfix
Multiple consecutive 'const' modifiers are no longer emitted when emitting a const vector of const elements.
=> Avoid emitting 'const const' for const vecs of const elements

core/src/main/scala/chisel3/experimental/dataview/package.scala
This is not a functional bug. The recursive form of reify for Element would use the .topBinding from the wrong argument, so it would recurse an extra time, but it would ultimately converge to the right value.
This is really subtle and I don't think it's even possible to write a test for it (other than by adding a side effect to reify but that would be insane).
It is a very slight, probably unmeasurable, performance improvement.
The way I convinced myself that the problem happened and was fixed was with the following example code:
```scala
import chisel3.experimental.dataview._
import circt.stage.ChiselStage
class Foo(val foo: UInt) extends Bundle
class Bar(val bar: UInt) extends Bundle
object Views {
implicit val foo2bar = DataView[Foo, Bar](f => new Bar(f.foo.cloneType), …
```
=> Fix issue where reify would do the same lookup twice

core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/experimental/DataView.scala
It's an error in most cases already, and in the cases it isn't, make it a warning. Also fix a crash that could occur when viewing a non-Data containing non-hardware Data.
I will immediately follow this PR with one turning it into an error, but I want to fix the crash in Chisel 5 and 3.6 because the errors are super opaque.
- Squash
Also fix a crash that could occur when viewing a non-Data containing non-hardware Data.
=> Deprecate calling .viewAs on non-hardware

core/src/main/scala/chisel3/experimental/dataview/DataView.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/experimental/DataView.scala
Based on https://github.com/chipsalliance/chisel/pull/3395 and should be merged afterward
- Squash
=> Error when calling .viewAs on non-hardware

src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/Mem.scala
It is sometimes desirable to instantiate a memory with ports clocked with different clocks (e.g. clock domain crossing). This PR adds additional APIs to `SRAM` which allow users to drive ports using a sequence of clocks:
```
// Create a multi-clocked 3R, 2W SRAM
val mem = SRAM(
1024, 
UInt(8.W), 
Seq(clock1, clock2, clock3), // Memory read port clocks
Seq(clock4, clock5),         // Memory write port clocks
Seq.empty                    // Memory read-write port clocks
)
```
Squash
Add new `SRAM` APIs that take three `Clock` sequences as parameters instead of the number of read/write/read-write ports. This will sequentially instantiate a memory port for each clock in the `Clock` sequence and drive them accordingly.
=> SRAM API: Add multiple-clocked port API

svsim/src/main/scala/Simulation.scala
By default, `stderr` is redirected to `PIPE`, which has a limited buffer size. Once that buffer is filled, the OS will block writes until data is read from the buffer. Since `svsim` never reads data from that buffer, this could result in the simulation hanging. Instead, we have the simulation inherit it's `stderr` from the parent process.
- Bugfix
- Fixes an issue where simulations that logged to `stderr` could hang
=> [svsim] Don't redirect simulation stderr to a pipe

.devcontainer/Dockerfile, firrtl/src/main/scala/firrtl/options/Shell.scala
The additional-commandline-arguments functionality in Chisel does not work with the way Metals works for VSCode's TestExplorer UI, and as a result we have not been able to use VSCode's Test Explorer prior to this fix, which creates an environment variable to disable the command line argument extension functionality.
- VSCode's Metal's Test Explorer UI can now run tests when the `CHISEL_ARGUMENT_EXTENSIONS` environment variable is set to `DISABLE`
=> Disable argument extensions when in devcontainer

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/PrintableSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/Examples.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
This moves name sanitation a little earlier and ensures that the sanitized names are use more consistently throughout Chisel internals.
This fixes a bug in D/I where unsanitary names would lead to a crash.
- Bugfix
- Squash
Fixes a bug in D/I where unsanitary names would lead to a crash. It also makes the Printable output for Bundles and Records use the sanitary names which makes them better match the FIRRTL.
=> Sanitize Record._elements

core/src/main/scala/chisel3/Bits.scala, src/test/scala/chiselTests/UIntOps.scala
Add a new `take` method on Bits that returns the requested number of low order bits as a `UInt`
Add a simple test that `take(0)` return a zero width `UInt`
Adds to API a `take` method on `Bits`, can return a zeroWidth UInt if argument is zero
`take` will accept an argument of zero and will return a zero-length UInt
=> Add a new `take` method on `Bits` that returns the requested number

build.sbt, src/main/scala/chisel3/util/experimental/BoringUtils.scala
Simply deprecates the old BoringUtils `bore(source, sinks)`, `addSource`, `addSink` in favor of the new API.
Squash
`BoringUtils.bore(source, sinks)`, `BoringUtils.addSource` and `BoringUtils.addSink` are now deprecated in favor of the new BoringUtils APIs: `BoringUtils.bore(source)`, `BoringUtils.tap(source)` ...
=> Deprecate old BoringUtils API

core/src/main/scala/chisel3/probe/package.scala, src/test/scala/chiselTests/ProbeSpec.scala
- Bugfix
Properly extend forced values in `probe.force` and `probe.forceInitial` methods. Error out on unknown widths.
=> Extend constants in `probe.force` and `probe.forceInitial` methods.

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/experimental/SourceInfo.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/Error.scala, core/src/main/scala/chisel3/internal/Warning.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/package.scala, docs/src/explanations/explanations.md, docs/src/explanations/warnings.md, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/ChiselStage.scala, src/test/scala/chisel3/testers/TestUtils.scala, src/test/scala/chiselTests/ConstSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala, website/docs/src/main/resources/microsite/data/menu.yml
Currently opened as a draft but I would like to get the ball rolling on this.
This is heavily inspired by [configurable warnings in Scala](https://www.scala-lang.org/2021/01/12/configuring-and-suppressing-warnings.html), but is a little more limited.
The commit text gives a pretty good overview:
```
Add support for configurable warnings
Warnings have been assigned unique integers to use as identifiers for
purposes of documentation and configuration.
New CLI option --warn-conf accepts a comma-separated sequence of
<filter>:<action> pairs for customizing warnings.
Supported filters are:
* any          - matches all warnings
* id=<integer> - matches warnings with the integer id
* src=<glob>   - matches warnings where <glob> matches the warning
source file
id and src filters can be combined …
```
=> Add support for configurable warnings

core/src/main/scala/chisel3/experimental/SourceInfo.scala, core/src/main/scala/chisel3/internal/Error.scala, core/src/main/scala/chisel3/internal/Warning.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
It causes issues in downstream codebases and really adding it just isn't worth the pain.
Removes an API added in https://github.com/chipsalliance/chisel/pull/3414
Will need to be included in #3430 and #3431.
No release notes
- BugFix
(Modification of an API that is not-yet-released)
- Squash
Tweak emission of source locators in error messages to match format in emitting FIRRTL (removed the `:` between filename and line number).
=> Remove SourceLineNoCol

src/main/scala/circt/stage/Annotations.scala, src/main/scala/circt/stage/CIRCTOptions.scala, src/main/scala/circt/stage/ChiselStage.scala, src/main/scala/circt/stage/package.scala, src/main/scala/circt/stage/phases/CIRCT.scala
In certain environments, such as when running tests via `bloop`, it may be difficult to influence which `firtool` CIRCT uses via the PATH environment variable (the only method currently available). This allows us to replace the version of `firtool` that is used at runtime (or point Chisel to the correct firtool binary in scenarios where it isn't on your PATH).
This will also be helpful if we want to package firtool in the Chisel jar @jackkoenig, since we will probably be extracting it to a temporary directory and not in the PATH.
- Add `FirtoolBinaryPathOption` to select a different `firtool` binary at runtime.
=> Add FirtoolBinaryPath option

firrtl/src/main/scala/firrtl/ir/IR.scala, src/test/scala/chiselTests/SourceLocatorSpec.scala
Speeds up serialization a little bit, for a very large design (~ 11 GB of .fir) it speeds up serialization from ~200 s to ~160 s.
- Squash
Only escape/unescape source locators that need it, avoids a String copy in the common case.
=> Optimize source locator escaping when emitting FIRRTL

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala
MonoConnect.elemConnect is updated to accept any BaseType, so its checks can be re-used for any source and sink BaseType that are already known to be compatible.
=> Move more Data methods to BaseType and base connection checks on BaseType.

src/main/scala/circt/stage/Annotations.scala, src/main/scala/circt/stage/CIRCTOptions.scala, src/main/scala/circt/stage/ChiselStage.scala, src/main/scala/circt/stage/package.scala, src/main/scala/circt/stage/phases/CIRCT.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
As usual, a 20 min hack had a bit of scope creep but I think this is a nice improvement
I'm open to a better name for the argument, but I think the functionality is pretty handy
@fabianschuiki FYI
- Rebase
This option will dump the .fir before invoking firtool.
* Additional changes:
* Use os.lib for invoking firtool
* Use lazy serialization to avoid holding the entire FIRRTL in memory.
* Mix NoStackTrace into FirtoolNotFound
* Fix detection of no firtool
=> Add --dump-fir option to ChiselStage

.github/workflows/build-scala-cli-template/action.yml, .github/workflows/install-circt/action.yml, .github/workflows/test.yml
Add support for grabbing the latest nightly version of `firtool` to the
install-circt action.  This requires passing the "github.token" so that
the GitHub API can be used.  Note that the token is marked as "required",
however, it is only actually needed when using a nightly build.
=> [ci] Add "nightly" option to install-circt action

.github/workflows/ci.yml, .github/workflows/test.yml
Change test.yml to be a reusable workflow so that this can be called with different inputs (different matrix arguments) for different test scenarios.  One PR scenario is testing PRs, branches, and releases.  This is added in the ci.yml workflow.  The other, future scenario is nightly testing with CIRCT.
This PR is stacked on #3457.
=> [ci] Make test.yml a reusable workflow

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/RawModuleSpec.scala
This adds a new API to invoke generators late, within the scope of a Module that has just been elaborated. It is intended as a power user API, and should not normally be needed. However, it does unlock new functionality in some cases where it would otherwise be impossible.
=> Add hook to invoke hardware generators at the end of elaboration.

.github/workflows/ci-circt-nightly.yml
Adds a skeleton of a nightly CI job so that I can test workflow_dispatch.
=> [ci] Add skeleton of nightly CIRCT CI job

.github/workflows/build-scala-cli-template.yml, .github/workflows/ci.yml, .github/workflows/install-circt/action.yml, .github/workflows/test.yml
Change how the CIRCT version is specified for non-nightly flows to a single environment variable in the ci.yml script.  This makes things easier for either: (1) a human to update this or (2) a machine to update this in a CD flow.
=> [ci] Change CIRCT version to exist in one place  

.github/workflows/build-scala-cli-template.yml, .github/workflows/ci.yml, .github/workflows/install-circt/action.yml
Make it such that using "Install CIRCT" does not require specifying a CIRCT version, instead using the string 'default' as a way to pick the "default version". The "default version" is the version that Chisel is tested and released against.
This fixes "Generate Scala CLI Template" which does not care to specify a CIRCT version.
Make it such that using "Install CIRCT" does not require specifying a CIRCT version, instead using the string 'default' as a way to pick the "default version". The "default version" is the version that Chisel is tested and released …
=> [ci] Use 'default' as version string for typical CIRCT version

.github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/test.yml
Add nightly testing of Chisel "main" branch with the nighlty published
"firtool" binary.  This testing will also be run on PRs targeting the
staging branch, "ci/ci-circt-nightly".
---
This runs nightly testing using the published `firtool` binary made available through this action on CIRCT: https://github.com/llvm/circt/actions/workflows/uploadFirrtlReleaseArtifacts.yml. The Chisel action (that this PR introduces) is setup to run one hour after the CIRCT one starts.
The nightly testing relies on a staging branch, `ci/ci-circt-nightly`, to deal with changes that are necessary for the nightly to pass. Nightly testing will try to update this branch (via rebase) onto the `main` branch before it builds.
Patches can be included in the `ci/ci-circt-nightly` branch by either manually updating it …
=> [ci] Add CIRCT nightly CI

core/src/main/scala/chisel3/properties/Property.scala, core/src/main/scala/chisel3/properties/package.scala, docs/src/explanations/explanations.md, docs/src/explanations/properties.md, src/test/scala/chiselTests/properties/PropertySpec.scala, website/docs/src/main/resources/microsite/data/menu.yml
=> Initial properties package and Property type.

src/test/scala/chiselTests/experimental/TraceSpec.scala
Upstream firtool fixed a bug in its lowering of traces.  Update the tests in Chisel to now be correct. (Previously, the tests were wrong.)
This is targeted at the `ci/ci-circt-nightly` branch as this is the staging area for the next CIRCT bump.
=> Stage changes for firtool Trace API fixes

.github/workflows/install-circt/action.yml, etc/README.md, etc/circt.json
Change the way that the current CIRCT version is specified.  Previously, this was code inside a GitHub Action.  Now this is data inside a JSON file.  This is done to enable other GitHub actions to update the JSON without having to have permissions to update workflows.
=> [ci] Move CIRCT version to JSON file

.github/workflows/install-circt/action.yml
Remove caching of the `firtool` binary.  Caching empirically provides no measurable benefit over downloading the binary from a GitHub Release every time.
This has the effect of avoiding a bug where the "default" old version would incorrectly hit when the `firtool` version is updated via a change to the `./etc/circt.json` file.
=> [ci] Remove caching of firtool

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This includes the API, Chisel IR, Converter, FIRRTL IR, and Serializer support for Property connections.
It also includes moving `requireVisible` from `Data` to `BaseType`, which is required but was omitted from #3442.
Property assignment is defined in FIRRTL spec version 3.1.0: https://github.com/chipsalliance/firrtl-spec/releases/tag/v3.1.0.
=> Support connecting Properties.

core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This includes the API, Chisel IR, Converter, FIRRTL IR, and Serializer support for Seqs of Properties (and Property of Seq). This includes support for values are Seqs of Properties which themselves may or may not be literals.
- Squash
=> Add support for sequences of Properties, including values.

core/src/main/scala/chisel3/IO.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Object.scala, core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala, src/test/scala/chiselTests/Module.scala, src/test/scala/chiselTests/properties/ClassSpec.scala, src/test/scala/chiselTests/properties/ObjectSpec.scala
Sending a draft now, thought it isn't quite ready.
- Bugfix
=> Add support for Class and Object on top of Properties.

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/MultiClock.scala, src/test/scala/chiselTests/ModuleSpec.scala, src/test/scala/chiselTests/MultiClockSpec.scala
This is in preparation for the new LTL operators defaulting to using the current in scope clock (needs `Option[Clock]`) and making it easy to disable clock for a region of assertions.
- Squash
* withClock, withReset, and withClockAndReset now have forms that take Option[Clock] and Option[Reset]
* Module.clockOption and Module.resetOption return Option[Clock] and Option[Reset]
=> Support Optionality of implicit clock and reset

core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/Disable.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/internal/Builder.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala, src/test/scala/chiselTests/DisableSpec.scala
~Does not actually depend on https://github.com/chipsalliance/chisel/pull/3496, but I developed them together and they conflict so will rebase once that is merged.~ Done.
Disable will be used by a following PR which will make the new LTL properties use `Disable` instead of `Bool`.
I was really struggling with how to make the user API for this reasonable, and huge h/t to @azidar for the idea to make the disable setting API (`withDisable`) a _function_ of the current reset. I originally was thinking it would be its own value but this could lead to some really strange behavior like simulation-only ports getting added to modules (for feeding into assertions) and changing the reset not affecting the disable. I think this is a much better design point than I originally had in mind--the API is …
=> Add Disable, a new API for disabling simulation constructs

src/main/scala/chisel3/ltl/LTL.scala, src/test/scala/chiselTests/LTLSpec.scala
Built on top of https://github.com/chipsalliance/chisel/pull/3497 so currently PR-ed against it, will be rebased on main once #3497 is merged.
- Squash
Properties in package chisel3.ltl will now be clocked and disabled by default (if there is an implicit clock and disable). Default disable is not hasBeenReset of the current implicit reset (if one exists). The clock and disable can be removed by setting them to None via withClock, withReset, and withDisable APIs.
=> Make LTL properties use Clock and Disable by default

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Object.scala, core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This PR changes the `Property.apply` from `def apply[T: PropertyType](): Property[T]` to `def apply[T]()(implicit tpe: PropertyType[T]): Property[tpe.Type]`. This lets implicit resolution resolve the result type, instead of having to add different apply methods for all the combinations of `T` and `Property[T]` alternatives - `Seq[Property[T]]`/`Seq[T]`, `Map[String, Property[T]]`/`Map[String, T]`, `(Property[A], Property[B])`/`(A, B)` etc.
=> Add Map properties

core/src/main/scala/chisel3/Module.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Fix ExtModules to not silently drop Property IO.
This is half of #3509.
Fix bug where Property types on ExtModules would be silently dropped.
=> Allow properties on ExtModule IO

core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Adds `DoublePropertyValue`, `DoublePropertyType`, and a `PropertyType[Double]` instance
=> add Double property type

core/src/main/scala/chisel3/properties/PathType.scala, core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Adds new public `PathType` class that represents a path to a hardware instance or member. Adds `PathPropertyType`/`PathPropertyLiteral` and `PropertyType` instances for module/data/mem.
=> add Path property type

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/BundleLiteralSpec.scala, src/test/scala/chiselTests/VecLiteralSpec.scala
This should be fairly innocuous change that was originally blocked by firtool's lack of `const` parsing support. This is a prerequisite for the more extensive `const` updates I've been working on.
Aggregate literals now materialize `const` wires. This will facilitate further support for `const` in operations and the type system in the future.
=> Aggregate literals now materialize const wires

core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Previously they only used Strings as keys.
- Squash
=> Map Properties now support Properties as the key

core/src/main/scala/chisel3/properties/Path.scala, core/src/main/scala/chisel3/properties/Property.scala, project/Boilerplate.scala
This makes `PropertyType` and its companion object public and adds a factory method to construct a `Path` from an `IsMember` target.
=> make PropertyType public, add Path factory method

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
While this doesn't exist, some of the property-related features in-tree don't exist in the claimed 3.1.0.
Bump FIRRTL version to unreleased 3.2.0 to cover experimental features emitted.
=> firrtl: Emit under 3.2.0 (not released) to cover property features.

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Object.scala, core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, project/Boilerplate.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
this adds `AnyClassType`, which cannot be instantiated and can be used to create properties of type `AnyRef` e.g.
```scala
val io: PropertyType[ClassType] = IO(Input(Property[AnyClassType]()))
// emits "input io : AnyRef"
```
This also changes the signature of `PropertyType.getPropertyType` to take no arguments instead of `Option[T]`. Previously creating a `Property[ClassType]` that wasn't backed by a `Some(ClassType)` value would result in a None.get error during serialization. This change makes it so that it is always possible to serialize the type, and also makes it so that it is no longer possible to do `Property[ClassType]()`. Now, to create a `Property[ClassType]` you must do one of the following
```scala
// AnyRef property
val io: …
```
=> Add `AnyRef` type and rework `PropertyType.getPropertyType`

docs/src/cookbooks/cookbook.md, docs/src/explanations/warnings.md, website/Makefile
Done by adding a named anchor to the Cookbook to make linking easier. Also fix a minor issue with the website Makefile where stale markdown files could be left around and would not be overwritten when using the common alias cp alias `cp -i`.
- Squash
=> [website] Fix link from Warnings to Cookbook

docs/src/cookbooks/naming.md
`HasTypeName` was written instead of `HasTypeAlias` (this is not the name of the trait that was added by #3445). Also changes the wording of some of the related cookbook docs to fit the rest of the naming doc.
- Squash
=> Fix HasTypeAlias cookbook typos

build.sbt
This is just adding 2.13.12 to plugin cross-compilation, also useful in older versions so users can bump their Scala without having to bump to newest Chisel major version.
- Squash
=> Add support for Scala 2.13.12 to the compiler plugin

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/experimental/DataView.scala
For the reviewers benefit, the error messages in the tests before this change are:
```
Exception in thread "main" chisel3.package$ChiselException: Connection between sink (_$$View$$_.view: [SInt<8>]) and source (Top.in: IO[UInt<8>]) failed @: Sink (SInt<8>) and Source (UInt<8>) have different types.
```
and
```
[error] src/main/scala/Jack.scala 18:31: Connection between sink (_$$View$$_.view_4._2: [SInt<8>]) and source (_$$View$$_.view__view_4._2: [UInt<8>]) failed @: Sink (SInt<8>) and Source (UInt<8>) have different types.
[error]   ((fizz, buzz).viewAs: Data) :#= ((foo, bar).viewAs: Data)
[error]                               ^
[error] src/main/scala/Jack.scala 18:31: Connection between sink (_$$View$$_.view_4._1: [SInt<8>]) and source (_$$View$$_.view__view_4._1: [UInt<8>]) failed @: …
```
=> Improve error messages involving views

core/src/main/scala/chisel3/experimental/package.scala, src/test/scala/chiselTests/experimental/FlatIOSpec.scala
Change `FlatIO` to work for any `Data` as opposed to just for `Record`. For non-`Record`, have this behave the same as `IO`.  I.e., there is no prefix stripping.
Change `FlatIO` to work for any `Data` as opposed to just for `Record`. For non-`Record`, have this behave the same as `IO`.  I.e., there is no prefix stripping.
=> Make FlatIO work (as IO) for non-Record Data

integration-tests/src/test/scala/chiselTest/MixedVecIntegrationSpec.scala, src/main/scala/chisel3/util/MixedVec.scala, src/test/scala/chiselTests/MixedVecSpec.scala
In the change to scala 2.13, collection.IndexedSeq is not enough to be considered a Seq
Change MixedVec to inherit from collection.immutable.IndexedSeq, so that it can work for Seq[Data].
=> MixedVec subclasses immutable.IndexedSeq

core/src/main/scala/chisel3/IO.scala, core/src/main/scala/chisel3/Module.scala, src/main/scala/chisel3/PolymorphicIOModule.scala
Add a `private[chisel3]` ability to block further IO creation in a
`BaseModule`.  This is intended for advanced, in-tree APIs that need to
disallow the creation of further IO by a user.  This API has mutable state
to track if more IO is allowed to be created, a method to get the
value, and a method to set the module to disallow further IO creation.
This one-way setting (h/t @jackkoenig) tries to keep this as locked down
as possible.
Add a new module hierarchy that promotes the type of the IO of that module
to a type parameter.  This module hierarchy includes:
1. PolymorphicIOBaseModule
2. PolymorphicIORawModule
3. PolymorphicIOBlackBox
Both (2) and (3) inherit from (1).  These modules are all polymorphic in
their type of IO.  It follows that no more IO are allowed to be created
other than …
=> Add PolymorphicIOModule, PolymorphicIOBlackBox

src/test/scala/chiselTests/BoringUtilsTapSpec.scala
=> Add unit test demonstrating BoringUtils.tap with D/I

binder/src/main/scala/PanamaCIRCT.scala, binder/src/main/scala/PanamaCIRCTConverter.scala, common.sc
~If the current position is under a `when` context, insert `chirrtl.memoryport` before the `whenBegin`, and leave `chirrtl.memoryport.access` inside the `when` branch.~
If the current position is under a `when` context, insert `chirrtl.memoryport` before the root `whenBegin`, and leave `chirrtl.memoryport.access` inside the `when` branch.
If not, insert `chirrtl.memoryport` directly and followed by a `chirrtl.memoryport.access`.
=> [Binder] Corrent `chirrtl.memoryport` position

docs/src/explanations/muxes-and-input-selection.md
`MuxLookup(idx, default)(Array(0.U -> a, 1.U -> b, ...))` was deprecated in 3.6 and now it uses `MuxLookup(idx, default)(Seq(0.U -> a, 1.U -> b, ...))`. However explanation in documentation still uses an Array. This PR fixes this.
=> Changed Array to Seq in MuxLookup explantation

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
See https://github.com/chipsalliance/rocket-chip/pull/3476
This has been a lingering issue, about time we fixed it.
I'm going to try backporting this but it may or may not be binary compatible.
- Bugfix
- Squash
=> Fix DataMirror.internal.chiselTypeClone to preserve Scala type

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
- Bugfix
Coerces tapAndRead to punch stripped-direction flips when punching downwards with Inward non-probe ports, Fixes #3556
=> Partial fix for probe and Decoupled interaction + demo of workaround

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Change the reported version of Chisel-emitted FIRRTL to 3.3.0.  Version 3.2.0 includes groups and Chisel is currently emitting things that are not in a spec version yet, e.g., property lists.
=> Bump emitted FIRRTL to 3.3.0

core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/experimental/HasAutoTypename.scala, core/src/main/scala/chisel3/util/Naming.scala, plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala, src/main/scala/chisel3/util/Decoupled.scala, src/main/scala/chisel3/util/Valid.scala
Replaces instances of `getClass.getSimpleName` in `typeName`, which is problematic in Java 8, with a common utility function (which just bundles the default `Module.desiredName` logic). Also disallows mixing `HasAutoTypename` into an anonymous Record, which is prone to generating `Malformed class name` errors.
Compiler plugin change was validated by attempting to compile anonymous `Bundle with HasAutoTypename` classes, with positive erroring.
- Bugfix
Squash
- Introduce a `simpleClassName` utility object that emulates a `getClass.getSimpleName` call without throwing `Malformed class name` exceptions when Java 8 is used. `typeName` and all related implementations use this function now instead of `getClass.getSimpleName`.
- `HasAutoTypename` can no longer be mixed into an anonymous …
=> Fix 'Malformed class name' errors in typeName and related implementations

core/src/main/scala/chisel3/Group.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/util/GroupSpec.scala
Add optional groups.
Chisel:
```scala
object A extends group.Declaration(group.Convention.Bind) {
object B extends group.Declaration(group.Convention.Bind)
}
class Foo extends RawModule {
val a = IO(Input(Bool()))
group(A) {
val w = WireInit(a)
dontTouch(w)
group(A.B) {
val x = WireInit(w)
dontTouch(x)
}
}
}
```
Output FIRRTL:
```
FIRRTL version 3.2.0
circuit Foo :%[[
{
"class":"firrtl.transforms.DontTouchAnnotation",
"target":"~Foo|Foo>w"
},
{
"class":"firrtl.transforms.DontTouchAnnotation",
"target":"~Foo|Foo>x"
}
]]
declgroup A, bind :
declgroup B, bind :
module Foo :
input a : UInt<1>
group A:
wire w : UInt<1>
connect w, a
group B:
wire x : UInt<1>
connect x, w
```
Output Verilog:
```verilog
// Generated by CIRCT firtool-1.56.1-32-g4da6a4d83
module Foo_A_B(
input _w
);
wire x = _w; …
```
=> Add optional group API

core/src/main/scala/chisel3/Group.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/util/GroupSpec.scala
Change the Builder to record the Root Optional Group in its Group Stack.
This is done to later enable error checking that group definitions are
nested correctly.
Add a requirement check that Optional Group definitions are nested in the
same way that their declarations are.
=> Check that Optional Groups are Correctly Nested

core/src/main/scala/chisel3/ChiselEnum.scala, src/test/scala/chiselTests/ProbeSpec.scala
Don't add enum annotations to probes of enum.
- Bugfix
Fix probe of ChiselEnum.
=> Fix and test probe of ChiselEnum.

src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Fix a port order change in BoringUtilsTapSpec.  Port order in firtool 1.57.0 is done in the exact order as the FIRRTL/HW modules and no re-ordering and grouping of inputs and outputs is done.  This change to the test has no effect.
=> Fix port order in test for firtool 1.57.0

website/docs/src/main/tut/api/chisel/5.0/index.md, website/docs/src/main/tut/api/chisel/6.0/index.md, website/docs/src/main/tut/api/chisel/latest/index.md, website/docs/src/main/tut/api/chisel3/3.5/index.md, website/docs/src/main/tut/api/chisel3/3.6/index.md
javadoc.io has been down for 2 days: https://github.com/maxcellent/javadoc.io/issues/180#issuecomment-1749281890
- Squash
=> [docs] Switch API docs hosting from javadoc.io to sonatype

core/src/main/scala/chisel3/Annotation.scala, core/src/main/scala/chisel3/BlackBox.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala, src/main/scala/circt/stage/ChiselStage.scala, src/test/scala/chiselTests/DedupSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Add `DedupGroupAnnotation` phase that generates deduplication groups based on module `desiredNames`
=> Add DedupGroupAnnotation phase

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
=> Fix BoringUtils.bore can not bore from a Probe

src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala, src/test/scala/chiselTests/util/experimental/DecoderTableSpec.scala
- bug fix for decoderbundle not being able to be lhs op
- add default field for DecodeField for DecodeTable non X case
=> Fix Decodetable

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/connectable/Connection.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, docs/src/explanations/connectable.md, src/test/scala/chiselTests/ProbeSpec.scala
- Enable mono/ `:=`connects for probes, which will emit a ProbeDefine.
- Also enables the fancier connect forms
- A "Probe<Bundle>" will be connected at the root
Co-authored-by: Will Dietz <will.dietz@sifive.com>
- Enable mono/ `:=`connects for probes, which will emit a ProbeDefine.
- Also enables the fancier connect forms
- A "Probe<Bundle>" will be connected at the root
=> Support probe-define in monoconnects

.github/workflows/ci.yml, .github/workflows/test.yml
Switch from install-circt v1.0.0 to v1.1.1.  There is no major change to
functionality other than this switches to using a shell script instead of
scripting in a GitHub composite action.  This also fixes a bug related to the
action not working in a container environment.  (This is not a problem for
Chisel.)
=> [ci] Bump install-circt to v1.1.1

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chisel3/internal/NameCollisionSpec.scala, src/test/scala/chiselTests/ToTargetSpec.scala, src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
The first commit contains some internal refactoring of how ids get named in a RawModule, which was required for the new API. The ids generated normally are named, then any `atModuleBodyEnd` blocks are evaluated and the RawModule is closed, and finally any ids generated by `atModuleBodyEnd` blocks are named. This allows the new `toRelativeTarget` to be called within an `atModuleBodyEnd` block for the root RawModule.
The second commit actually adds the new APIs.
The new toRelativeTarget API augments the existing toAbsoluteTarget API, to provide a mechanism to get hierarchical paths to a NamedComponent relative to a known root.
=> Add new target API to get a target relative to a specific BaseModule.

.github/workflows/ci-circt-nightly.yml
Running the nightly test here: https://github.com/chipsalliance/chisel/actions/runs/6584516409
I haven't tested the behavior of merging to the `ci/ci-circt-nightly` branch. However, this change is almost entirely mechanical.
=> [ci] Switch to upstream circt/update-staging-branch

core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chisel3/internal/NamespaceSpec.scala
When naming `foo`, then `foo_`, the calculation for the prefix of `foo_` is incorrect. It should not have a prefix, but instead thinks the entire `foo_` is the prefix. When the prefix is stripped to find the index, you get a `java.lang.NumberFormatException: For input string: ""`, as it tries to convert the empty string to an `Int`.
This bugfix checks the case where a prefix is calculated, but would return an empty string if stripped.
- Bugfix
Naming `foo` and then `foo_` will no longer trigger an error.
=> Bugfix: foo and foo_ names cause incorrect prefix calculation

src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala, src/test/scala/chiselTests/DedupSpec.scala
- Bugfix
Class definition components cannot have any annotations.
=> Don't add DedupGroupAnnotation to classes.

core/src/main/scala/chisel3/probe/package.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/chiselTests/interface/TappedInterfaceSpec.scala
Remove `clock` and `cond` from probe `force` and `release` methods.
=> remove clock and cond from probe force/release API

core/src/main/scala/chisel3/properties/Path.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
- Bugfix
This includes two changes to how Path property target types are serialized:
* For ModuleTargets, use the OMInstanceTarget target type, like for InstanceTargets
* Add a new API to request "member" target types
=> Updated Path property target type serialization.

core/src/main/scala/chisel3/probe/package.scala
- Bugfix
For `Vec`s, also set the `probeInfo` of their `sample_element`, which is used to determine its element type.
=> set sample_element's probeInfo for Vecs

core/src/main/scala/chisel3/connectable/Alignment.scala, core/src/main/scala/chisel3/connectable/Connection.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala
No non-internal existing functionality intended to be changed.
"Alignment" interface (internal) does change.
DataMirror methods implemented in terms of Alignment no longer require the Data to be hardware, allowing walking (bare) Chisel types and their alignments.
This will be used in a follow-on PR.
- This PR is meant to only refactor while supporting existing behavior.  New functionality will follow.
DataMirror methods relating to alignment such as `collectAlignedDeep`) no longer require Data to be Hardware and may be used on bare Chisel types.
=> Alignment: Don't require a Connectable base, split.

docs/src/explanations/explanations.md, docs/src/explanations/optional-groups.md, website/docs/src/main/resources/microsite/data/menu.yml
Add documentation for groups.
This is expected to fail until `firtool-1.57.0` is used in Chisel.
=> [nfc] Add documentation of optional groups

macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
This is needed by users of Chisel using Scala 2.13.12
- Bugfix
- Squash
This fixes Scala compiler warnings in Scala 2.13.12 requiring type ascriptions on public implicit definitions.
=> Add type ascription to implicits from instantiable

core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/ToTargetSpec.scala
We have recently reworked when HasIds are named within a module so they can be named before atModuleBodyEnd executes, and then get referenced within atModuleBodyEnd. However, the component is still not set when they are referenced, so in this case use the local name.
=> Support instanceName on HasId without a component by using localName.

build.sbt, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/internal/SourceInfoFileResolver.scala, core/src/main/scala/chisel3/internal/SourceInfoMacro.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselUtils.scala, plugin/src/main/scala/chisel3/internal/sourceinfo/SourceInfoFileResolver.scala, src/test/scala/chiselTests/IntrinsicModule.scala, src/test/scala/chiselTests/SourceLocatorSpec.scala, src/test/scala/chiselTests/util/circt/ClockGate.scala, src/test/scala/chiselTests/util/circt/IsXSpec.scala, src/test/scala/chiselTests/util/circt/PlusArgsTestSpec.scala, src/test/scala/chiselTests/util/circt/PlusArgsValueSpec.scala, src/test/scala/chiselTests/util/circt/SizeOfSpec.scala, src/test/scala/chiselTests/util/circt/Synthesis.scala
This is implemented using the compiler plugin so that:
1. The source locator points to the first character of the class name.
2. Users don't accept implicit sourceInfos as arguments to their module classes (this would override all source locators in the body of the class).
- Squash
The source locators point to the name of the class extends Module, RawModule, BlackBox, ExtModule, or Class. They are included in the output FIRRTL.
=> Add source locators to all subclasses of BaseModule

integration-tests/src/test/scala/chiselTest/util/SparseVecSpec.scala, src/main/scala/chisel3/util/SparseVec.scala
Add a new utility, SparseVec.  This exposes a normal Vec-like dynamic access API.  However, the dynamic access is implemented one of three ways:
1. Using a binary decoder
2. Using a one-hot decoder
3. Using when statements
This is added to better support a design pattern ("vec--decoder pattern") where a large, sparse vector is used to describe a decoder.  This pattern, if unchecked and used in a parametric generator, can cause the vector to grow extremely large and cause backend tools to complain.
Specifically, Cadence tooling is known to set limits on the addressable range of a "memory" and will error if these are exceeded.  This vec--decoder pattern can easily exceed this if designers are not careful.
Add `SparseVec` API.
=> Add SparseVec

src/main/scala/circt/stage/phases/CIRCT.scala
Remove the deprecated -dedup option.  This was deprecated in firtool 1.57.0 and is planned to be removed soon.  This option has no effect. Deduplication always runs.
See: https://github.com/llvm/circt/pull/6191
=> [circt] Remove deprecated dedup option

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala
- Bugfix
Property types never actually called the helper that was factored out of MonoConnect specifically for them. Upon adding this, it turned out that they never had assignCompatDir called either, and this was leaving directions unspecified in aggregates. Both of these have probably lingered since Property types were made subclasses of Data again. This addresses both omissions, leading to earlier error checking for Property type connections.
=> Enable checkConnect for Property types in MonoConnect.

core/src/main/scala/chisel3/Bits.scala, src/test/scala/chiselTests/LTLSpec.scala, src/test/scala/chiselTests/UIntOps.scala, src/test/scala/chiselTests/VerificationSpec.scala
- Squash
This results in a slight improvement to emitted FIRRTL quality
=> Don't emit nodes when calling .asBool on a Bool

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Add new DataMirror.isFullyAligned for checking if all members are aligned w.r.t. the given base.
=> DataMirror.isFullyAligned: add method to check data is all aligned.

docs/src/index.md, website/Makefile, website/docusaurus.config.js, website/src/pages/index.js
* Rename docs/introduction.md to docs/index.md so that now the main link is just /docs.
* Add redirects for some common links from the old sbt microsites website.
- Squash
=> [website] docs/introduction => docs/index, add redirects

.gitignore, build.sbt, project/Releases.scala, website/.gitignore, website/Makefile, website/docusaurus.config.js, website/src/pages/api/chisel3/latest.js
- Squash
This should enable them to be indexed and thus searchable as part of the website (both by Algolia and by Google).
=> [website] Self-host latest [stable] API docs

core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/internal/BiConnect.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/properties/Property.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This is the right place in the Chisel type hierarchy for Property as it exists today. Property types can be used in Aggregates, and are not themselves Aggregates in their current form. Making Property extend Element allows much of Chisel's internal reflection to work as expected when Property types are used in Aggregates.
=> Make Property an Element.

core/src/main/scala/chisel3/experimental/Trace.scala, src/test/scala/chiselTests/experimental/TraceSpec.scala
Change the behavior of the Trace API to only trace leaves.  This aligns with recent changes to CIRCT which error if annotations are applied to aggregates which are then mandatorily split due to FIRRTL ABIs.  This should have no practical effect on use of the Trace API only that downstream consumers will need to work at the level of leaf types and not on aggregates.
=> Change Trace API to only trace leaves

project/Releases.scala, project/Version.scala
=> [docs] Fix release ordering and make RC count as latest

.github/workflows/build-scala-cli-template.yml, .github/workflows/ci.yml, .github/workflows/test.yml, build.sbt, build.sc, common.sc, project/FirtoolVersion.scala, project/plugins.sbt, src/main/scala/circt/stage/phases/CIRCT.scala, src/main/scala/circt/stage/phases/ScribeInterop.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
This uses https://github.com/jackkoenig/firtool-resolver which I will transfer to be an actual chipsalliance repo once this is merged.
- Squash
Whereas in the past, the user was expected to provide the firtool binary
on the PATH, Chisel will now manage the firtool binary automatically.
Chisel users the following 3-step process for determining which binary
to use:
1. If environment variable FIRTOOL_PATH is set, it will check for
firtool in that directory
2. It will check the classpath for firtool provided by
chipsalliance/llvm-firtool
3. It will download a default version of chipsalliance/llvm-firtool
Both (2) and (3) will store the firtool binary in a sensible location
depending on the user's operating system. See dirs-dev/directories-jvm
for more information. The user …
=> Switch to firtool-resolver

binder/includeFunctions.txt, binder/src/main/scala/PanamaCIRCT.scala, binder/src/main/scala/PanamaCIRCTConverter.scala, binder/src/test/scala/BinderSpec.scala
Some fixes for binder:
- Truncate for aggregate connection.
- Set `inner_sym` only when needed.
=> [binder] Truncate for aggregate connection, fix inner_sym

build.sbt
This is sort of an BugFix to an unreleased API (added after 6.0.0-RC1), see the Release Notes for how this changes the behavior of `FIRTOOL_PATH` in a desirable way.
- Bugfix
- Squash
The logic for 
* If FIRTOOL_PATH is set, the --version regex failing no longer will return fail, instead it will set version to `<unknown>`.
* If FIRTOOL_PATH is set and something fails (firtool not found or cannot execute the binary), then the error will be returned rather than firtool-resolver falling back to fetching the default version.
* Errors from running firtool will be logged and returned rather than unconditionally turned into "Firtool binary not on FIRTOOL_PATH".
=> Bump firtool-resolver to 1.1.0

.github/workflows/test.yml, build.sbt
- Squash
* Use Java 17 to build documentation in CI
* Exclude docs project from Unidoc
=> [CI] Fix flaky CI and remove VerilogMdocModifier from API docs

src/main/scala/circt/stage/phases/CIRCT.scala
Legacy `--print-ir-after-all` has been replaced by this new argument.
- Bugfix
Fix the `--mlir-print-ir-after-all` option.
=> Fix the `--mlir-print-ir-after-all` option.

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala
When creating large numbers of Definitions, copying the globalNamespace back and forth becomes a performance bottleneck.
=> Share the globalNamespace in the DynamicContext used for Definition.

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/choice/package.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/package.scala, docs/src/explanations/instchoice.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala, src/main/scala/chisel3/choice/ModuleChoice.scala, src/main/scala/chisel3/util/experimental/decode/TruthTable.scala, src/test/scala/chiselTests/ModuleChoiceSpec.scala
- Squash
Added support for the post-generation configuration of designs. Instance choices allow multiple, option-dependent targets to be specified for a single option, picking an implementation in the downstream flow.
=> Add ModuleChoice and Groups

.github/workflows/build-scala-cli-template.yml, .github/workflows/test.yml, build.sbt, build.sc, src/test/scala/circtTests/stage/ChiselStageSpec.scala
This would be an API modification but no Chisel has yet been released using firtool-resolver
- Squash
To override which firtool is used by Chisel, users can set environment variable `CHISEL_FIRTOOL_PATH`.
=> Bump firtool-resolver to 1.3.0

binder/src/main/scala/PanamaCIRCT.scala, binder/src/main/scala/PanamaCIRCTConverter.scala, binder/src/main/scala/PanamaCIRCTOM.scala
- Flush the buffer at the end of `Writable` streams
It fixes the output stream doesn't write out results completely.
- Keep original integer types from foreign API
It fixes some constant literals that bigger than the range of `Int` are not handled correctly, they should be passed as `BigInt` in Scala and as `Long` (Scala type) passed to C API.
=> [binder] Flush the buffer at the end of `Writable` streams, keep original integer types from foreign API

core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Status: instance names are colliding, [causing the new tests 11.3 and 11.4 to fail](https://github.com/chipsalliance/chisel3/actions/runs/3680952208/jobs/6227099986#step:8:1289). Need to figure that out and fix it.
This supersedes #2414, which I think is abandoned. Resolves #2366.
Adds `suggestName` API for hierarchy instances.
Allows users to control Verilog module instance names.
Adds `suggestName` API for hierarchy instances.
=> Add Instance.suggestName

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
Chisel creates new contexts whenever you're constructing a Definition. Previously, if you had a Definition in the parent context, the actual object would not be available in the child context (because it's a new context, `Builder.components` is cleared when you go to a new context). Now, we keep track of definitions explicitly _including definitions from parent/outer scopes_. This is implemented using a nested `List` for efficiency of constructing the datastructure while still allowing for efficient iteration.
- Performance improvement - but probably not measurable
- Bugfix
- Squash
Fixes #3708
=> Fix using Definitions as arguments to Definitions

.github/workflows/backport-fixup.yml, .github/workflows/build-scala-cli-template.yml, .github/workflows/cd-circt.yml, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/enable-bincompat-checking.yml, .github/workflows/release-notes.yml, .github/workflows/require-label.yml, .github/workflows/scala-cli-template.yml, .github/workflows/test.yml, project/build.properties
It seems that some change to SBT requires bumping libc, thus bumping the ubuntu runners to 22.04 fixes this.
- Squash
=> Bump SBT to 1.9.8 and update Ubuntu runners

core/src/main/scala/chisel3/internal/Binding.scala
- Squash
* Make already deprecated APIs package private
* Add deprecation warnings to a few that we missed
=> Clean up Bindings deprecations

binder/includeFunctions.txt, binder/src/main/scala/PanamaCIRCT.scala, binder/src/main/scala/PanamaCIRCTConverter.scala, binder/src/test/scala/BinderSpec.scala
Based on the merged PR in upstream CIRCT: llvm/circt#6577
Unsolved issue: #3735
CC @sequencer
=> [binder] Fix emission of `firrtl.invalidvalue`

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/DataEqualitySpec.scala
=> Support === on empty Aggregates

.github/workflows/config/release-notes.json, .github/workflows/release-notes.yml
- Squash
* Bump `mikepenz/release-changelog-builder-action` to v4.1.1
* It now tabs every line included in the Release Notes section of the PR template
=> Enhance release notes automation

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Users are now able to check whether a Data is visible from the current context via `chisel.reflect.DataMirror.isVisible`.
=> Support checking isVisible with reflect.DataMirror

core/src/main/scala/chisel3/Width.scala, src/test/scala/chiselTests/UIntOps.scala
=>  Shift right produce at least 1 width result

build.sc, common.sc, flake.nix, lit/tests/CompilerPlugin/WithCompilerPlugin.sc, lit/tests/CompilerPlugin/WithoutCompilerPlugin.sc, lit/tests/lit.cfg.py, lit/tests/lit.site.cfg.py.in, lit/utility/src/package.scala, nix/scala-cli.nix, nix/sources.json, overlay.nix, tests.sc
I wanna use #3596 to subsume #3410, see [this](https://github.com/chipsalliance/chisel/blob/ec94af02c13d9222baac943e8a3b437303a00d47/filecheck/tests/EmptyModule.sc) simple test:
```scala
//> RUN: scala-cli $THIS | firtool -format=fir
import circt.stage.ChiselStage
class EmptyModule extends Module
println(ChiselStage.emitCHIRRTL(new EmptyModule))
```
In the build system, it will be processed into:
```scala
//>using scala "2.13.12"
//> using jars /home/sequencer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar /home/sequencer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.12/scala-reflect-2.13.12.jar /home/sequencer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/os-l …
```
=> a Pure LLVM Lit test framework

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/probe/Probe.scala, core/src/main/scala/chisel3/probe/package.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala
This adds Layer Colors to Probe types.
This is an existing part of the FIRRTL 3.2.0 "groups" feature which is being expanded/clarified in FIRRTL 4.0.0. This enables a probe to be associated/colored with a layer.  This enables a layerblock to define probes of the same color.
This feature is used to construct simple interfaces of probes whose defines require complicated logic that does not exist inside the interface. Consider a situation where you have a simple single-cycle microprocessor. You'd like to expose a simple commit trace that is the last four instructions. However, the microprocessor does not actually record the last four instructions. It only keeps track of the current instruction. What do you do? If you put the logic outside the microprocessor, then your interface has changed. …
=> Add Layer Colors to Probe Types

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Add a utility to reflect on the optional color of a layer.  This will be used by libraries that need to know if they need to put generated logic in a layerblock or not.
Add `DataMirror.getLayerColor` API to return the optional layer color of a `Data`.
=> Add DataMirror.getLayerColor

core/src/main/scala/chisel3/Mem.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/MultiClock.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/package.scala, docs/src/cookbooks/cookbook.md, src/test/scala/chiselTests/ClockSpec.scala, src/test/scala/chiselTests/ResetSpec.scala
This also deleted a long-deprecated protected method that didn't do anything.
- Squash
These traits implement the functionality formerly only implemented in Module such that they can now be used by RawModules. They also define new protected virtual methods `implicitClock` and `implicitReset` that can be overridden within `Module` to change what values are used as the implicit clock and implicit reset respectively.
=> Provide ImplicitClock and ImplicitReset

core/src/main/scala/chisel3/Reg.scala, src/test/scala/chiselTests/ClockSpec.scala
Previously, it was not calling .ref. It was thus not properly:
1. Checking that the clock is bound hardware
2. Checking that the clock is visible in the current scope
3. Reifying the clock if its a view
Note that RegInit() was already correctly calling .ref.
h/t @nandor for noticing this, pretty crazy such a fundamental bug has been lingering without being noticed.
- Bugfix
- Squash
* Clocks are now properly supported by `DataView` (including `FlatIO`)
* Users will also received better error messages when providing invalid clocks to `Reg()`
=> Fix `Reg()` to properly handle clocks as rvalues

core/src/main/scala/chisel3/properties/Property.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Since we override litOption to always be None, we need to override isLit to check the Binding.
=> Support isLit for Property types.

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
This adds an API to DataMirror to query if a Data is a Property.
=> Support isProperty query in DataMirror.

core/src/main/scala/chisel3/RawModule.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
This adds support for BoringUtils.bore to bore and connect Property ports.
=> Support Property in BoringUtils.

docs/src/cookbooks/cookbook.md, docs/src/cookbooks/dataview.md, docs/src/cookbooks/hierarchy.md, docs/src/cookbooks/naming.md, docs/src/cookbooks/serialization.md, website/src/css/custom.css
Also put cookbooks in a better order for new users.
Figuring out this CSS was annoying, many thanks to @richardxia for help.
Before:
After:
I do kind of like how we didn't have the "group" bullets as links, but this is sooooo much easier to maintain.
We can also then decide to have more interesting ToC styling, but I at least wanted to make sure we could replicate the styling exactly (or at least, very very close).
- Squash
=> [docs] Generate ToC for Cookbooks

core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Object.scala, src/test/scala/chiselTests/properties/ObjectSpec.scala
This is in addition to the existing support in Definition.apply. Sometimes it is not possible to use Definition.apply, for example, if you plan to bore ports through the Class being constructed. The new DynamicObject.apply method supports this, and creates a DynamicObject from the newly elaborated Class.
=> Add a new DynamicObject.apply method to create Class instances.

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/package.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, firrtl/src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala, src/main/scala/chisel3/aop/injecting/InjectingPhase.scala, src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/circtTests/stage/phases/AddImplicitOutputFileSpec.scala
Add a function that allows the layer to be "enabled" within the current module scope.  This has the effect of emitting the module with the "enablelayer <layer>" FIRRTL format.  This is not currently in the FIRRTL spec---it is being prototyped inside CIRCT and is expected to land in the spec soon.
This is done to allow for the use case of a Test Harness needing to enable one or more layers (more than one layer is the union of several layers) inside a DUT in order to drive it properly.  The specific use case is to get access to an expensive core trace inside a microprocessor that is hidden behind a layer.
This was originally written using an API where the layer provided a trait that enabled the layer.  This runs afoul of Scala's restriction on inheriting the same trait multiple times.
FYI: …
=> Allow modules to globally enable layers

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Bump emission to use FIRRTL 4.0.0.  Since Chisel is now emitting layer-colored probes and the work-in-progress "enablelayer" keyword, Chisel needs to emit a version of FIRRTL that compilers will accept.
The only change to the output (other than the stated version) is "groups" are now changed to "layers".
Note: FIRRTL 4.0.0 is not finalized yet.
=> Bump to FIRRTL 4.0.0

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/When.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala/chiselTests/WhenSpec.scala
Not really a bugfix but that seemed closest
- Bugfix
- Squash
=> Report source locator in when scoping error messages

core/src/main/scala/chisel3/Public.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/package.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, firrtl/src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala, src/main/scala/chisel3/aop/injecting/InjectingPhase.scala, src/test/scala/chiselTests/PublicModuleSpec.scala, src/test/scala/circtTests/stage/phases/AddImplicitOutputFileSpec.scala
Add a new trait, `Public`, which can be used to emit FIRRTL modules which have the public keyword.  This is a weak form of "public modules" that we want to support for FIRRTL 4.0.0.  This does not allow for multiple, disjoint instance graphs to be contained in a circuit, nor does it remove the "main module" from the circuit.  However, it provides a mechanism for plucking modules out of a circuit later and working with them.
This is self-typed on `RawModule` to prevent mix-in to an external module.
For the included test Chisel:
```scala
class Baz extends RawModule
class Bar extends RawModule with Public {
val baz = Module(new Baz)
}
class Foo extends RawModule {
val bar = Module(new Bar)
}
```
This produces the following FIRRTL. Note the `public` keyword:
```
FIRRTL version 4.0.0
circuit …
```
=> Add Public trait to create public FIRRTL modules

src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Fix a BoringUtils test that was checking for the name of a define produce by CIRCT.  This was changed slightly in FIRRTL 4.0.  Align the test with the new Verilog macro name.
=> Update BoringUtils test for FIRRTL 4.0

core/src/main/scala/chisel3/Width.scala, src/test/scala/chiselTests/UIntOps.scala
Revert changes to the width of static shift right.  Originally, Chisel would return a 0-bit value.  However, this violated the FIRRTL spec which mandated that this return a 1-bit value.  FIRRTL compilers would then clean this up, however, if a user looks at the Chisel-determined width they would get the wrong answer.
Commit 1634320ce299775307aafa4ffbffe8e18022e81f made Chisel align with FIRRTL.  After additional discussion, it was decided that the best course of action was to make FIRRTL _align with Chisel_ for UInt, but not for SInt.  Specifically, the following behaviors are what we want to move towards:
1. The smallest width of a UInt shifted right is 0-bit
2. The smallest width of an SInt shifted right is 1-bit
This will then be handled with changes to the FIRRTL spec and by FIRRTL …
=> Revert "Shift right produce at least 1 bit width result (#3752)"

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/internal/Binding.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
A latent issue with how Binding and lexical scope checking (aka visiblity) works in Chisel is that it is assumes a single "location" for a given Data. Aggregate Views can have multiple locations so this logic needs to be generalized. I started doing that work but it's a much larger overhaul than I was willing to commit to for a bug fix, so I ditched that idea and did something more focused. We do need to make that change eventually though.
- Bugfix
- Squash
`DataMirror.isVisible` and other things checking visibility now work properly for views.
=> Fix visibility for views

src/main/scala/chisel3/util/SRAM.scala
- Feature
`memSize`, `dataType`, `numReadPorts`, `numWritePorts`, `numReadwritePorts`, `masked` parameters are now visible for `SRAMInterface`.
=> Make `SRAMInterface` parameters publicly available

svsim/src/main/scala/verilator/Backend.scala
=> [svsim] Better error message when verilator not on PATH

core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/Width.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/ChiselStage.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
This requires a recent change to CIRCT (https://github.com/llvm/circt/pull/6698).
Once firtool is released with the linked change, bumped in this repository, and this PR is merged, I think we should crack 7.0.0-M1 as it will serve as a useful milestone for dealing with this semantic change.
I also added a CLI option to emulate the old behavior: `--legacy-shift-right-width`. I'm not wedded to the name so if anyone has a better name for it, please suggest it.
Instructions on using this option will be in the release notes but we should probably also add a page to the website about migrating from Chisel 6 to Chisel 7 that calls this out.
- Rebase
* A UInt shifted right by a static amount >= its width will now result
in a 0-bit UInt
* An SInt shifted right by a static amount …
=> Change the width of static shift right

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/PublicModuleSpec.scala
Drop an argument from the Builder.build method which is only used to
change behavior when building Definitions.  Instead, rely on the
`inDefinition` variable made available by the DynamicContext.
Fix a bug where a Definition's root module would be incorrectly marked
public.  Definitions currently create a separate Circuit for each
Definition.  The logic to control marking the main module public relied on
marking the last module in the circuit public.  However, this incorrectly
assumed that there was one Circuit when, in actuality, there are
multiple.  (This commit ignores questions of whether or not it should work
this way.)
Instead, use the DyanmicContext `inDefinition` variable to execute this
code path to set the main module public when the Builder is not working
with a Definition. …
=> Fix bug where Definitions are incorrectly public

src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/Mem.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
=> Remove extra bit from `SRAMInterface` address width

core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This allows Properties to be used to build up expressions in terms of input Properties and literals.
=> Add Property expressions, starting with addition.

core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This adds an API for integer Property multiplication.
=> Add Property expression for integer multiplication.

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, panamaconverter/src/PanamaCIRCTConverter.scala
This supports format strings for assert and assume statements as proposed in https://github.com/chipsalliance/firrtl-spec/pull/166. This change might break existing code if message contains `%`.
=> Add format strings to assert and assume

core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This adds an API for integer Property shift right.
=> Add Property expression for integer shift right.

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/probe/package.scala, src/test/scala/chiselTests/LayerSpec.scala
Change the checking logic for the legality of a probe define destination to align with FIRRTL specification language introduced recently [1]. Specifically, this enforces the following sentence:
> An operation that "writes" to a probe must be in a region whose layer color is enabled when the probe's layer color is enabled.
Previously, Chisel was more restrictive and would only allow writing to a probe whose color was the same as the layer block you are currently in. However, as has been worked out in CIRCT and elsewhere, it is fine to drive a probe from any region that is enabled when the probe is also enabled.
Practically, this gets some Chisel code passing that was legal by a FIRRTL compiler, but Chisel was refusing to generate it.
CC: @rwy7
[1]: …
=> Relax legality of defines, align with FIRRTL spec

core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, src/test/scala/chiselTests/experimental/DataView.scala
=> Add DataProduct for Iterables and primitive types

.github/workflows/install-jextract/action.yml
Some unexpected CI failures occurred in PR #3842, logs https://github.com/chipsalliance/chisel/actions/runs/8029630555
- Updates the `jextract` download URL, the previous one is no longer accessible.
=> [ci] Update `jextract` download URL

src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
Public modules can't have inferred widths or abstract reset, fix tests to emit spec-compliant FIRRTL 4.0.
Main module are "public" (#3813, soon mandatory) which means they cannot have inferred widths or abstract resets.  Code relying on old behavior will presently encounter an error in `firtool`.
=> Fix tests to avoid inferred width ports on public modules.

core/src/main/scala/chisel3/properties/Class.scala, src/test/scala/chiselTests/properties/ClassSpec.scala
This allows users to get a ClassType for use in other Property types, which is especially useful when constructing aggregate Property types of a specific Class.
=> Add getClassType API to Definition[T <: Class].

core/src/main/scala/chisel3/VerificationStatement.scala, src/test/scala/chiselTests/VerificationSpec.scala
- Backend Code Generation
chisel3.Assume now directly emits a FIRRTL `assume` with the specified format message.
Previously a `when not(predicate): printf(...)` was emitted followed by a message-less `assume`.
The resulting SystemVerilog will change, more aligned with `assert` output but specifically uses `$error(..)` instead of a printf guarded by the usual printf guards.
-----
Example output before/after:
Before:
```
FIRRTL version 4.0.0
circuit SimpleTest :
public module SimpleTest : @[src/test/scala/chiselTests/VerificationSpec.scala 11:7]
input clock : Clock @[src/test/scala/chiselTests/VerificationSpec.scala 11:7]
input reset : UInt<1> @[src/test/scala/chiselTests/VerificationSpec.scala 11:7] …
```
=> Assume: Use plain FIRRTL assume + format string instead of printf + assume.

core/src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
`HasTarget` trait now also exposes `suggestName` method of a `NamedComponent`.
=> Add `suggestName` method to `HasTarget`

svsim/src/main/scala/verilator/Backend.scala
When I update to verilator v5.022, the svsim test will fail (someone has already raised an [issue](https://github.com/chipsalliance/chisel/issues/3836)). I found out this was because verilator added a [check](https://github.com/verilator/verilator/commit/e3e5f30ba1b02a202aff32e10c95e824e855a6df) for the c++14 standard. 
- Bugfix
Change ChiselSim to requires a C++14 compiler.
=> Use c++14 to pass the verilator check

docs/src/explanations/properties.md
=> Add explanation for Class and Object, with examples.

core/src/main/scala/chisel3/VerificationStatement.scala, src/test/scala/chiselTests/Stop.scala
- Bugfix
The message passed to `stop` is no longer ignored. The construct was extended to accept Printable.
=> Print the optional Printable passed to stop ops

src/main/scala/chisel3/simulator/package.scala
Fix an incorrect assumption in ChiselSim that a 'filelist.f' will exist that includes all modules, _including blackboxes_, in the design.  Change this to try to also copy files from the black box filelist.  This makes ChiselSim work with CIRCT 1.66 and earlier (which put everything in 'filelist.f') and CIRCT 1.66+ (which does not include blackboxes in 'filelist.f').
Note that this is intended as a temporary solution until FIRRTL has a rock solid ABI that is implemented by CIRCT where all modules can be discovered under an arbitrary public module.
See CIRCT changes here: https://github.com/llvm/circt/pull/6729
Change ChiselSim to also move blackboxes as indicated by the default black box filelist.  This fixes issues with ChiselSim and CIRCT 1.67.0 introduced in …
=> Get ChiselSim working with CIRCT 1.66+

src/main/scala/chisel3/simulator/package.scala
Change the way ChiselSim moves files to track and not move files which may be duplicated in both the default black box filelist and in the main CIRCT-produced filelist.  Previously, this was working because a java.nio exception was being ignored.  However, this may have been hiding bugs where the filelist was actually pointing at a file that did not exist.
=> [chiselsim] Better fix for CIRCT 1.66- and 1.66+

firrtl/src/main/scala/logger/LoggerAnnotations.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Change logger annotations to mix-in the Unserializable trait so that they will not emitted by a stage.  These annotations are not intended to be seen by CIRCT and these should be stripped from the output FIRRTL text.
Change all logger annotations to be unserializable. This avoids a bug where these could be seen by CIRCT (which rightly does not understand them) and cause it to reject the FIRRTL it sees.
=> Make logger annotations unserializable

firrtl/src/main/scala/firrtl/annotations/JsonProtocol.scala, firrtl/src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala, firrtl/src/test/scala/firrtl/JsonProtocolSpec.scala
This probably also improves performance and reduces memory since creating a large String is expensive.
- Bugfix
- Squash
=> Support serializing large (> 2 GiB) annotation files

core/src/main/scala/chisel3/BlackBox.scala, core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/VerificationStatement.scala, core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/test/scala/chiselTests/VerificationSpec.scala, src/test/scala/chiselTests/naming/NamePluginSpec.scala, src/test/scala/chiselTests/naming/PrefixSpec.scala
* Replaced printf-encoded assertion with ifElseFatal intrinsics[0]. Currently the intrinsic is a private object of core since we don't want to expose it other than chisel3.assert. 
* Removed outdated comments regarding verification statements. 
* Added a new case class `PrintableParam` for lazily constructing a string parameter for format string. 
[0] https://github.com/llvm/circt/blob/main/docs/Dialects/FIRRTL/FIRRTLIntrinsics.md#circtchisel_ifelsefatal
Support `circt_chisel_ifelsefatal` intrinsics and use it for chisel3.assert emission.
=> Add ifElseFatal intrinsics; use it for chisel3.assert emission

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Extends BorginUtils.bore (and related) to work where the source is a probe.  Currently, if a user tries to do this, they will get an error about being unable to probe a probe because the old code would unconditionally wrap whatever the source was in `Probe`/`RWProbe`.  Change this to not wrap if the source is already a probe.
Allow boring from a source which is already a probe.
=> Allow BoringUtils.bore to work on probes

core/src/main/scala/chisel3/VerificationStatement.scala, core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala, src/test/scala/chiselTests/VerificationSpec.scala
This is a follow-up to #3825.
MFC has attached a laebl "chisel3_builtin" to every ifElseFatal assertion. Usually a label on ifElseFatal is just ignored but the label is emitted when compiled with `-emit-chisel-asserts-as-sva`. So labels on assertions converted from ifElseFatal disappear due to #3825. This PR restores labels to preserve the old behavior.
Add a label "chisel3_builtin" to ifElseFatal intrinsic.
=> Add a label "chisel3_builtin" to ifElseFatal intrinsic

overlay.nix
The `nix flake` setup, as added in #3050, overlaid `jextract` to `jdk21` branch without specifing a commit. With upstream updates, it won't build now as SHA-256 hash have changed, and with updates in `nixpkgs` it is not needed anymore.
- Bugfix
=> remove outdated jextract in nix overlay

core/src/main/scala/chisel3/Num.scala, src/test/scala/chiselTests/LiteralExtractorSpec.scala
This very minor PR fixes a bug in `Num.toBigInt(x: BigDecimal, binaryPoint: Int)`. 
The current function gives the impression to round the input BigDecimal:
```scala
val result = (x * multiplier).rounded.toBigInt
```
However:
```scala
BigDecimal(1.4).rounded.toBigInt // : BigInt = 1
BigDecimal(1.5).rounded.toBigInt // : BigInt = 1
BigDecimal(1.6).rounded.toBigInt // : BigInt = 1
```
I'm assuming this is not the intended behaviour. 
The underlying issue is with the `rounded` function which uses the BigDecimal's `MathContext`. I changed this to use `setScale(0)` instead.
I added a testcase for rounding positive numbers. I would've added a testcase for negative ones, but as far as I know there is no `RoundingMode` that replicates the rounding of Doubles there (round half to positive …
=> toBigInt should round identically for Double and BigDecimal

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/reflect/CheckTypeEquivalenceSpec.scala
Fix embarrassing bug introduced in https://github.com/chipsalliance/chisel/pull/3201. Basically, `DataMirror.checkTypeEquivalence` is only checking the first element of Bundles 🙈 
Fixes https://github.com/chipsalliance/chisel/issues/3922
- Bugfix
- Squash
Fixes `DataMirror.checkTypeEquivalence` to actually check all fields of Bundles and Records. This may expose latent bugs in user code.
=> Fix Data.findFirstTypeMismatch to check all elements of Bundles

core/src/main/scala/chisel3/properties/Path.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Sometimes a generator wants to emit a Path that targets some Data, but that Data isn't always produced by the generator. The DeletedPath can be used to represent the presence of a Path, but the absence of a Data in this case.
=> Add DeletedPath for targets that no longer exist.

panamaconverter/src/PanamaCIRCTConverter.scala, panamalib/src/PanamaCIRCT.scala, panamaom/src/PanamaCIRCTOM.scala
- Add method for reading mlirbc in `PanamaCIRCTConverter`
- Construct `MlirStringRef` manually for `Array[Byte]`
`Array[Byte]` may not end with `'\0'`, so constructing a `MlirStringRef` with `Array[Byte]` via `mlirStringRefCreateFromCString` can sometimes cause a crash in CIRCT.
- Fix infinite recursion for displaying `PanamaCIRCTOMEvaluatorValuePath`
=> Some fixes related to OM

website/Makefile
Modifies the Makefile in the `website/` subdirectory so that you can run it on an alternate port:
`$ make serve PORT=8001`
=> Add PORT option to `make serve` in website/ subdir.

docs/src/appendix/experimental-features.md, docs/src/cookbooks/cookbook.md, docs/src/explanations/connectable.md, docs/src/explanations/memories.md, docs/src/explanations/warnings.md, docs/src/resources/faqs.md, website/docusaurus.config.js, website/package.json
The website build has started failing for an unknown reason, but there was a warning about the Algolia integration and bumping Docusaurus seems to fix the issue. Docusaurus 3.1.1 introduces checks for broken anchors which is also fixed in this PR. One of the broken anchors was to a section on FixedPoint, as FixedPoint was removed, this section was deleted.
- Squash
=> [website] Bump Docusaurus to 3.1.1 and fix broken anchors

src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Fixes https://github.com/chipsalliance/chisel/issues/3932
This adds the support in `Chiselsim` to configure the workspace with additional args for `firtool` (#3932). The user can specify how the sv circuit is compiled for simulation (i.e. including debug information `-g`).
=> Make firtool options for `elaborateGeneratedModule` in `workspace` parametric

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/SramTarget.scala, core/src/main/scala/chisel3/experimental/Analog.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/main/scala/chisel3/aop/Select.scala, src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/Mem.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
`SRAM`s updated to directly emit FIRRTL memories (as opposed to creating `SyncReadMem`s.
=> Make SRAMs directly emit FIRRTL memories

core/src/main/scala/chisel3/RawModule.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
This API allows users to bore to a sink they plan to drive, which complements the existing API to bore from a source to read.
=> Add a new BoringUtils.drive API for boring to drive a sink.

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Element.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/experimental/DataView.scala
This also fixes a bug with the rename map for non 1-1 views of literals.
Arguably a Feature or Bugfix, but I lean bugfix.
- Bugfix
- Squash
View of literals will now themselves be literals. This also fixes an internal bug related to views of literals.
=> Support literals in DataView

core/src/main/scala/chisel3/dontTouch.scala, core/src/main/scala/chisel3/experimental/package.scala, core/src/main/scala/chisel3/package.scala, src/main/scala/chisel3/util/experimental/decode/decoder.scala, src/test/scala/chiselTests/DontTouchSpec.scala
- Squash
This gives much better error messages when accidentally dontTouching a literal
=> Add requireIsAnnotatable for better errors when annotating literals

circtpanamabinding/includeFunctions.txt, panamaconverter/src/PanamaCIRCTConverter.scala, panamalib/src/PanamaCIRCT.scala
Fixes #3963, upstream PR: llvm/circt#6893
This PR fixes the first problem in the issue mentioned above, for the second one, it seems to be just the style of output from CIRCT that doesn't affect the final result and there's nothing we can do about it from Chisel side.
=> [binder] Support constructing integers larger than 64 bits

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/DataEqualitySpec.scala
- Bugfix
- Squash
Previously, the function would infinitely recurse resulting in a stack overflow.
=> Fix === for abstract Reset types

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/probe/Probe.scala, src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala
Fix a bug where a layer definition would only be added to Builder state if it was used in a layer block.  Also add these layers to the Builder state if they are used by a layer-colored probe type or by a module's enable layer.
Fixes #3983.
Fix a bug where illegal FIRRTL (that was missing a layer) unless a layer block using that layer was provided.
=> Add layers for colored probe types or enablelayer

src/main/scala/chisel3/simulator/package.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Simulation.scala, svsim/src/main/scala/Workspace.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala
- Changed `TraceStyle.Vcd` to include a trace file name
- Added `OptimizationStyle.OptimizeForSimulationSpeed` and associated verilator flags to achieve simulation speed.
- "--x-assign ast" and "--x-initial fast" flags should not really affect behaviour of most Chisel/CIRCT generated code and seem to give some performance boost, but it's open for feedback.
- added "-j 0" flag to verilator arguments to enable arallelism for uses all available CPU cores for verilate and build jobs
- added a "ShutdownHook" to kill the simulation process in case of Ctrl+C etc. Tested on macOS only, but seems to be working.
- Rebase: You will rebase the PR onto master and it will be …
=> [svsim] Expose further verilator options for trace file name and simulation speed optimization

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/connectable/Connection.scala, core/src/main/scala/chisel3/connectable/package.scala, src/test/scala/chiselTests/ConnectableSpec.scala
The user can override these methods to customize how their Data applies waive, squeeze, and exclude in its Connectable.
=> Add extension points on Data for customizing Connectable behavior.

src/main/scala/chisel3/util/BitPat.scala, src/test/scala/chiselTests/util/BitPatSpec.scala
Benchmarked using https://github.com/chipsalliance/chisel/pull/3987,
For `BitPat(0xdeadbeefL.U)` 72x speedup:
```
Benchmark                           Mode  Cnt   Score   Error   Units
ChiselBenchmark.BitPatFromUInt     thrpt   10  42.105 ± 1.364  ops/us
ChiselBenchmark.BitPatFromUIntOld  thrpt   10   0.582 ± 0.005  ops/us
```
For `BitPat(3.U)` 7x speedup:
```
Benchmark                           Mode  Cnt   Score   Error   Units
ChiselBenchmark.BitPatFromUInt     thrpt    3  44.501 ± 7.054  ops/us
ChiselBenchmark.BitPatFromUIntOld  thrpt   10   5.819 ± 0.049  ops/us
```
For real design, reduced amount of time in `BitPat.apply` from 116 seconds to 12.5 seconds (9x speedup)
- Squash
Speeds up conversion of UInt literals to BitPat by ~9x in practice, ~70x for large …
=> Optimize BitPat factory from UInt literals

src/main/scala/chisel3/util/BitPat.scala, src/main/scala/chisel3/util/experimental/decode/TruthTable.scala, src/test/scala/chisel3/util/BitPatSpec.scala, src/test/scala/chisel3/util/experimental/decode/TruthTableSpec.scala
I'm collecting numbers, but it should be pretty obvious that not essentially doing a deep copy of every TruthTable both before and after running espresso minimization in the common case where the default value is uniform (i.e. all ones, all zeros, or, most commonly, all dont care) will speed things up.
To implement this, I also added some useful methods to BitPat that you can see the tests for.
Doing split and merge on the `TruthTable` from `TruthTableSpec`:
```scala
val table = TruthTable(
Map(
// BitPat("b000") -> BitPat("b0"),
BitPat("b001") -> BitPat("b?"),
BitPat("b010") -> BitPat("b?"),
// BitPat("b011") -> BitPat("b0"),
BitPat("b100") -> BitPat("b1"),
BitPat("b101") -> BitPat("b1"),
// BitPat("b110") -> BitPat("b0"),
BitPat("b111") -> BitPat("b1")
),
BitPat("b0")
)
```
Before this …
=> Optimize truth table merge

core/src/main/scala/chisel3/Intrinsic.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, docs/src/explanations/intrinsics.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, src/test/scala/chiselTests/IntrinsicSpec.scala
Intrinsic expressions and statements are now supported, streamlining their use.  These should be preferred over intrinsicModule's, which in the future will be deprecated and removed.
=> Add support for generic intrinsic expressions and statements.

core/src/main/scala/chisel3/Width.scala, src/test/scala/chiselTests/UIntOps.scala
=> Provide require message for negative widths

.github/workflows/backport-fixup.yml
This action formerly copied over the PR body but it seems Mergify does that itself now.
- Squash
=> [ci] Stop copying body over to backports in backport-fixup

src/main/scala/chisel3/util/circt/ClockGate.scala, src/main/scala/chisel3/util/circt/IsX.scala, src/main/scala/chisel3/util/circt/PlusArgsTest.scala, src/main/scala/chisel3/util/circt/PlusArgsValue.scala, src/main/scala/chisel3/util/circt/SizeOf.scala, src/main/scala/chisel3/util/circt/Synthesis.scala, src/test/scala/chiselTests/util/circt/ClockGate.scala, src/test/scala/chiselTests/util/circt/IsXSpec.scala, src/test/scala/chiselTests/util/circt/PlusArgsTestSpec.scala, src/test/scala/chiselTests/util/circt/PlusArgsValueSpec.scala, src/test/scala/chiselTests/util/circt/SizeOfSpec.scala, src/test/scala/chiselTests/util/circt/Synthesis.scala
This builds on #3986 , moving most of the current intrinsics to the new intrinsic expressions.
The LTL intrinsics are not migrated in this PR.
Change intrinsic wrappers to use intrinsic expressions instead of intrinsic modules.
`PlusArgsTest(x, str)` is now deprecated as first argument is unused.  Use `PlusArgsTest(str)`.
=> Use intrinsic expressions for most intrinsics

core/src/main/scala/chisel3/experimental/SerializableModuleGenerator.scala, src/test/scala/chiselTests/experimental/SerializableModuleGeneratorSpec.scala
- **implement the instantiable SerializableModule**
- **add test**
- Bugfix
=> make SerializableModuleGenerator work with D/I

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/BuilderContextCache.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
When Instantiate a instantiable module, if it has other instantiable modules inside it, inner module will miss cache.
- Bugfix
- Squash
Fix Nested Instantiate
=> Fix Nested Instantiate

core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala, src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Dep on #4018 
This issue is designed for the use case of OM, but also apply to the future linking flow.
The type of `Class` should always be deduped at chisel elaboration time, since for each elaboration, newly generated `Class` has a different type to previous one.
Thus we need to force user to pass `Definition` from top to down though hierarchy. I think is a bad user experience. :( 
Generally, all OM `Class` are cacheable since it only containing simple value or no values. This makes cache always work.
Thus user only need to use `Instanitate.definition(new SomeOM)` to elaborate `SomeOM` or fetch `SomeOM` from builder cache if possible.
=> Add Instanitate.definition to get Definition from cache.

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
=> Fix Typo in ExtractFromVecSizeZero warning message

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
The DataMirror API allows users who know what they're doing to access a module's ports before it is closed.
=> Add private Module API and internal DataMirror API for moduleIOs.

build.sbt
Bump to using 2.13.14 is separate as this change should be backported but that probably won't be.
- Squash
=> Add Scala 2.13.14 to cross-build

lit/tests/Property/DocExample.sc, lit/tests/Property/Good.sc, panamaom/src/PanamaCIRCTOM.scala
If the instantiation is failed, method returns `None` rather than assertion failure.
CC @sequencer
=> OM evaluator instantiate method returns Option

src/main/scala/chisel3/ltl/LTL.scala
Companion to https://github.com/chipsalliance/chisel/pull/4058
- Squash
It should never have been a public API.
=> Deprecate AssertPropertyLike.createIntrinsic

src/main/scala/chisel3/util/circt/LTLIntrinsics.scala, src/test/scala/chiselTests/LTLSpec.scala
- Bugfix
Fix LTL verif statements.
=> [LTL] Fix verif_* -- these are statements not expressions, no ret value.

build.sbt, core/src/main/scala/chisel3/experimental/IntrinsicModule.scala, docs/src/explanations/intrinsics.md
IntrinsicModule has been replaced by Intrinsic and IntrinsicExpr .
=> IntrinsicModule: deprecate in favor of intrinsic expressions.

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/experimental/DataView.scala
This requires https://github.com/chipsalliance/chisel/pull/4070 for the tests to pass
- Bugfix
- Squash
Previously, a view of an empty aggregate would incorrectly always have a litValue of `0`.
=> Fix literal handling for views of empty Aggregates

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Added `modulePorts` and `fullModulePorts` methods in `DataMirror` that returns all ports on an `Instance` of a module.
=> Add modulePorts and fullModulePorts in DataMirror for Instance

core/src/main/scala/chisel3/VerificationStatement.scala, src/test/scala/chiselTests/Assert.scala, src/test/scala/chiselTests/VerificationSpec.scala
I'm waffling on whether to call this an API Modification or a Backend code generation. It sort of toes that line. I decided to keep the `Assertion failed:` prefix (at least for now) even when there is a user-provided message just because I know that that String is often used for determining when an assertion fires. Removing that is something we should probably do (when the user provides a String), but I'll leave that as a separate change that should be marked as an API modification.
This change feels very... late lol. This feels like the sort of thing in Chisel before 3.0 yet it has lingered for a very long time. Capturing the user's line has a lot of negative consequences, like including comments. It's also very ugly.
- Squash
Also remove line and column when a …
=> Remove line contents from assertion messages

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/package.scala, firrtl/src/main/scala/firrtl/annotations/Target.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/chiselTests/ToTargetSpec.scala
Add .toRelativeTargetToHierarchy for getting .toRelativeTarget functionality when the root is a Definition or Instance.
=> Add .toRelativeTargetToHierarchy

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/experimental/DataView.scala
Fixes https://github.com/chipsalliance/chisel/issues/4079. This will result in some wires that may not be necessary which is particularly inelegant for Probes, but it makes certain things work that didn't use to and can be improved further as necessary.
- Bugfix
- Squash
Fix muxing and probing of views of Aggregates
=> Materialize wires for .ref of Aggregate views

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, src/test/scala/chiselTests/BundleLiteralSpec.scala, src/test/scala/chiselTests/ConnectableSpec.scala, src/test/scala/chiselTests/VecLiteralSpec.scala
- Bugfix
- Squash
Previously, the user-specified (or unspecified minimum width) of the literal would be used in some operations like concatenation. For literal values that are too-wide, they will now truncate to the correct width. This will become a warning (then later an error) in newer major versions of Chisel.
=> Fix widths for literal values in Bundle literals

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
This should always return the same type/alignment regardless of where the original resides, so if the expectation is a fully aligned result then create one if needed.
- Bugfix
Always return fully aligned result from tapAndRead, even if no boring performed.
=> BoringUtils: Fix tapAndRead to return same type even when not boring.

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/internal/Warning.scala, docs/src/explanations/warnings.md, src/test/scala/chiselTests/BundleLiteralSpec.scala, src/test/scala/chiselTests/VecLiteralSpec.scala
Follow on to https://github.com/chipsalliance/chisel/pull/4082 to make too wide of Bundle literal values be a warning (Chisel warnings are elevated to errors by many users).
- Squash
=> Make it a warning to have too-wide literal values in Bundle Literals

core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Expected result is fully aligned, which is what happens when reading from a probe.
When the source is already at the LCA (from parent) there's no probe and the secret connections only support a few commands.
For lack of a way to do, e.g., `:#=` here,
use `read(probe(x))` to get the fully aligned result that's expected and bored down to the child.
This isn't ideal but fixes this using only the sorts of expressions and commands that we've already committed to supporting.
Fixes #3557.
- Bugfix
Fix tapping mix-alignment signal from parent.
=> Fix boring tap of non-passive source from parent.

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/BundleLiteralSpec.scala
Having to add this special-case is a shame, but worthwhile. Basically, if a user writes something like:
```scala
(new MyBundle).Lit(_.field1 -> whatever, _.field2 -> (some * complex / expression).U)
```
We should not warn if `field2` is 0-bit and that expression evaluates to `0`, it's way too onerous to expect the user to handle passing `0.W` to `.U` in this case. I think a similar thing will come up when we start warning/removing implicit truncation. It's a special-case, but it's pragmatic.
The best fix would be for `0.U` to start being zero-width, but that has a ton of knock on effects and should be considered a breaking change and handled as such.
- Bugfix
- Squash
=> Don't warn when 0.U used as value for 0-bit BundleLit field

core/src/main/scala/chisel3/experimental/dataview/package.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Fixes https://github.com/chipsalliance/chisel/issues/4106
- Bugfix
- Squash
Also fix reifySingleData to return the Data itself if it is not a view.
=> Support views of ports in ChiselSim

core/src/main/scala/chisel3/internal/Error.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
I'm not sure if this is a feature, bugfix, or documentation 😂. In any case, it's a nice little improvement IMO as the `...` at the top is misleading if the exception was thrown by user code.
- Bugfix
- Squash
=> Don't ... top of stack trace if it isn't actually trimmed

core/src/main/scala/chisel3/internal/Error.scala, src/main/scala/chisel3/simulator/PeekPokeAPI.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Fixes #4128. (cc @jackkoenig)
Some notes:
* b3fca5e adds the `SourceInfo` collection and reporting in the exception.
* I haven't tried stack trace collection. Other than simply not getting to it yet, I don't think I have a rigorous enough setup (or a large enough testcase, which I have a working build going for) to meaningfully assess the performance cost.
* Minor API design question: do we ever expect `testableData.expect` (with `expected`, `encode` and `buildMessage` arguments) to be called by a test user directly? If not, I have a slight preference for making the `sourceInfo` argument non-implicit there, and only having it implicit in the user-facing calls on `SimulationData`.
* 2d58c7e adds a baseline testcase that `expect()` actually does anything. This isn't specific to this work.
* …
=> PeekPokeAPI: include source location on failed expect() calls.

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Bits.scala, src/test/scala/chiselTests/BundleLiteralSpec.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala, src/test/scala/chiselTests/VecLiteralSpec.scala
Also working on supporting preserving literals across `.asTypeOf`, but this is the first step.
- Squash
This is mostly useful for initial values for async reset registers and for constructing literal values in testing contexts (e.g. ChiselSim). It also should slightly reduce memory use and `.fir` size.
=> Preserve literals across .asUInt

core/src/main/scala/chisel3/Bits.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
Note that `.asSInt` is only defined on `Bits`, if you want to cast to `SInt` from Bundles or Vecs you already gotta go through `UInt`.
- Squash
=> Preserve literal value across .asSInt and .zext

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/DataPrint.scala
- Bugfix
- Squash
This makes `.toString` behavior better outside of Chisel elaboration contexts.
=> Suppress exception throwing in Data.toString

src/test/scala/chiselTests/ChiselEnum.scala
Enshrine the behavior of #4159 - this test will be useful for backporting and then showing the change when we fix it.
- Squash
=> Add a test for issue 4159

src/test/scala/chiselTests/AsTypeOfTester.scala
This includes changing AsTypeOfSpec to be FunSpec instead of FlatSpec so that the tests can have more structure.
I'm working on making it possible to preserve literals across `.asTypeOf` casts (which will help with unit testing and is much more convenient for async reset). In doing so, I found the existing tests extremely lacking so I decided to lay out the existing behavior exhaustively. Please do not review this PR based on what you think _should_ happen[^1], rather, treat this as documenting the existing behavior so that at least changes that _should_ be functionally equivalent will be and we can be intentional in changing the behavior going forward. 
I marked this as documentation since, at least for development purposes, it is documenting the behavior.
Marked for backporting to 6.x …
=> Add more exhaustive tests for .asTypeOf

core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/probe/package.scala, src/test/scala/chiselTests/ProbeSpec.scala
- Bugfix
- Squash
This is already an error caught in firtool, now Chisel will error earlier.
=> Error when calling define targeting a child of a probe

src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala
This PR speeds up the intensive usage of `DecodeTable`, T1 uses it to construct the `DecodeBundle`, to avoid each table instantiating overhead(QMC or espresso calling), this PR makes it lazy to speed up.
make TruthTable in DecodeTable lazy to speed up decoding.
=> make TruthTable in DecodeTable lazy

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Element.scala, core/src/main/scala/chisel3/Intrinsic.scala, core/src/main/scala/chisel3/Mem.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/Reg.scala, core/src/main/scala/chisel3/connectable/Alignment.scala, core/src/main/scala/chisel3/experimental/Analog.scala, core/src/main/scala/chisel3/experimental/OpaqueType.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/internal/BiConnect.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/probe/ProbeValue.scala, core/src/main/scala/chisel3/probe/package.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Object.scala, core/src/main/scala/chisel3/properties/Property.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/main/scala/chisel3/choice/ModuleChoice.scala, src/main/scala/chisel3/util/SRAM.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala
This is done by adding a new package private object "binding" within
which all bindings live. This required changing imports in lots of files
but it makes it much easier to not accidentally create a public binding
in the future.
- Merge
These `chisel3.internal` APIs should never have been public in the first place.
=> Make "deprecated public" binding APIs private

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Element.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/internal/BiConnect.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chisel3/experimental/dataview/ReifySpec.scala, src/test/scala/chiselTests/BulkConnectSpec.scala
This is a minor overhaul of DataViews internals that make the various use cases of what were previously referred to as "1-1 views" more clear. This incidentally fixes an issue with bulk connections and views.
While for users this is just a bug fix, this has larger implications for developers. This replaces `reifySingleData` with two more precise functions:
* `reifyIdentityView` - Fast, used for things like Probe legality (which by having pointer semantics, only really works with identity views).
* `reifySingleTarget` - Slow, used for legacy annotation support which was, and remains, iffy for views.
A subtle but critical aspect of this PR is that `reifyIdentityView` works in cases when the `reifySingleData` did not. It is properly hierarchical: e.g. if you have an Aggregate that is a child …
=> Distinguish identity views from single-target views

core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/When.scala, core/src/main/scala/chisel3/internal/CIRCTConverter.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/main/scala/chisel3/aop/Select.scala
Change the internal representation of `When` in Chisel to be region based as opposed to token-based.  Concretely, change `WhenContext` to not push token commands indicating when the region starts/stops, has an alternative, etc.  Instead, use a single object that has an "if" and an "else" region where commands can be pushed.
CC: @sequencer, @SpriteOvO: I didn't fixup the bindings here.
=> Rework When IR to be Region-based

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala
Add a Region operation to Chisel IR.  This is a command which is a container of other commands.  This is intended to provide an "insertion point" that can be added to the command buffer which can then be referenced later to add more commands.  This avoids the problem of the command buffer being append only while _not_ going fully in the direction of using a datastructure which allows arbitrary insertion (i.e., a linked list).
This is stacked on #4184.
=> Add Region to Chisel IR

core/src/main/scala/chisel3/internal/firrtl/IR.scala, panamaconverter/src/PanamaCIRCTConverter.scala
Remove an unused Chisel IR feature.
Commentary: this is a pretty rare deletion!  This IR features dates _to the first commit_ in the repo.
=> Remove ConnectInit

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Element.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/internal/BiConnect.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/probe/package.scala, core/src/main/scala/chisel3/properties/Property.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chisel3/experimental/dataview/ReifySpec.scala, src/test/scala/chiselTests/ReadOnlySpec.scala
Also add internal support for marking things as "deprecated read only". This will promptly be used to mark the return value of `.asTypeOf` as "deprecated read only" in 6.x in preparation of https://github.com/chipsalliance/chisel/pull/4168.
I implemented this as part of the view binding for the following reasons:
1. While one could mutate the underlying Data, there are use cases where an API may want to return a read-only reference/view of their underlying Data while reserving the right to connect to it themselves (I intend to do this in proprietary code)
2. We could implement this as a separate Binding (i.e. not part of the existing Views) or as an Arg. Either approach could certainly work, but it would need to compose with views _anyway_. Consider some of the tests. Given some Data that …
=> Add support for marking things as readOnly

core/src/main/scala/chisel3/internal/Builder.scala
Chisel includes logic to trim NonFatal stack traces. OutOfMemoryErrors (e.g. from running out of heap or stack) can cause weird issues where because the JVM is out of memory, scala.util.control.NonFatal cannot be loaded to compare to and then the JVM masks the real OutOfMemoryError by throwing a LinkageError.
- Bugfix
- Squash
=> Initialize scala.util.control.NonFatal in Builder

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/internal/Warning.scala, docs/src/explanations/warnings.md, src/test/scala/chiselTests/Vec.scala, src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
Users will now get a deprecation warning if they connect to the result of .asTypeOf.
Marked for backporting to 6.x so that we can change this in 7.0.
- Squash
Previously, `.asTypeOf` would return a `Wire`. To get the old behavior, wrap the `.asTypeOf` call in `WireInit(...)`.
=> Mark return value of .asTypeOf as "deprecated read-only"

core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
We should also support non-identity views, that involves creating more secret commands (e.g. materializing a wire). This is more of a patch fix that is made important because of https://github.com/chipsalliance/chisel/pull/4198 which results in a lot more identity views (the return value of `.asTypeOf`).
- Bugfix
- Squash
=> Fix BoringUtils for identity views

src/main/scala/chisel3/FixedIOModule.scala, src/test/scala/chiselTests/FixedIOModuleSpec.scala
Since `io` inside `FixedIOBaseModule` is final, we cannot override or add `@public` Scala annotation to it. This PR add `@public` annotation to `FixedIOBaseModule.io`, making `FixedIOBaseModule` compatible w/ D/I API. 
- Bugfix
make FixedIOModule work with D/I
=> make FixedIOBaseModule.io public

core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/Vec.scala, src/test/scala/chiselTests/naming/NamePluginSpec.scala
I'm calling this a bugfix because it fixes an issue exacerbated by https://github.com/chipsalliance/chisel/pull/4198, but it's also sort of a feature. The crux of the motivation for this change is visible in the change to `VecSpec`. Basically, if the user returns a view in lieu of the underlying target Data, the actual Data does not currently get named. This PR fixes it by having identity views forward their naming on to the underlying target. This PR is made much more important by https://github.com/chipsalliance/chisel/pull/4198 because this now comes up quite a bit in user code, `VecSpec` showing an example.
Future work is handling non-identity views because it is reasonable to forward naming in those cases as well, but perhaps with additional prefixing based on the "local" name of the …
=> Name the targets of identity views

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, src/test/scala/chiselTests/WhenSpec.scala
Fix minor side effect of https://github.com/chipsalliance/chisel/pull/4184. No release notes because there's been no release with these elses.
- Bugfix
- Squash
=> Elide else skip in FIRRTL for whens with no otherwise

core/src/main/scala/chisel3/experimental/dataview/package.scala, src/test/scala/chiselTests/UIntOps.scala
Contemplating views in naming (https://github.com/chipsalliance/chisel/pull/4222) exposed a longstanding bug that I patched out recently in https://github.com/chipsalliance/chisel/pull/4147. Basically `isView` does not work outside of Builder contexts. Now it is safe.
We do have lots of tests for things like literals outside of Builder contexts, but they didn't trigger this because `ViewParent` is a `lazy val` and thus if _any_ Chisel elaboration has occurred on the same thread, then the problem doesn't manifest. Thus this "test" looks very strange, but by virtue of defining a literal assigned to a val first thing in a ScalaTest spec, it ensures no Chisel elaboration has run before when this line executes, and the naming plugin + #4222 ensures that this value is checked if it's a view.
- …
=> Make isView safe outside of Builder context

src/main/scala/circt/stage/ChiselStage.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
- Squash
Emits a file without returning the serialized object which is more memory efficient and supports > 2 GiB of serialized FIRRTL text.
=> Add ChiselStage.emitCHIRRTLFile

core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala/chiselTests/BulkConnectSpec.scala
Fixes https://github.com/chipsalliance/chisel/issues/4218
One can question the need for this, as it's just making `<>` not error in a few more cases. The main motivation is that https://github.com/chipsalliance/chisel/pull/4205 causes some existing uses of `<>` that used to work no longer work. It's an unnecessary breakage that is fixed by this change.
- Bugfix
- Squash
=> Emit FIRRTL bulk connects even for "input" wires

core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/Shell.scala, src/test/scala/chiselTests/ChiselEnum.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
This is primarily a bug fix, but it changes widths in a way that could silently break user code so I'm framing this as an API Modification that has instructions for users when bumping Chisel. In https://github.com/chipsalliance/chisel/pull/3824 we added `--use-legacy-shift-right-width` to help users migrate to the fixed width semantics for shift-right. I have renamed that option `--use-legacy-width` and added this width behavior change to the option.
`--use-legacy-width` is purely a code migration option, this behavior will only be "optionally preserved" for migrating code to Chisel 7, it will be removed in Chisel 8.
- Bugfix
- Squash
Fixes https://github.com/chipsalliance/chisel/issues/4159.
Previously, the width reported by Chisel under `.getWidth` was inconsistent …
=> Fix width of ChiselEnum values in emitted FIRRTL

core/src/main/scala/chisel3/Aggregate.scala
It's hard to measure the benefit from this, but I used the following little snippet of Chisel to make a bundle of Bundles:
```scala
// _root_ disambiguates from package chisel3.util.circt if user imports chisel3.util._
import _root_.circt.stage.ChiselStage
class MyBundle extends Bundle {
val a, b, c, d, e, f, g = UInt(8.W)
}
class Foo(n: Int) extends Module {
val in = IO(Input(Vec(n, new MyBundle)))
val out = IO(Output(Vec(n, new MyBundle)))
out :#= in
}
object Main extends App {
val n = args(0).toInt
ChiselStage
.emitCHIRRTLFile(
gen = new Foo(n)
)
.toSeq
}
```
Then I built a fat assembly jar with Mill, and checked the heap size with `find_heap_bound`:
```
./firrtl/benchmark/scripts/find_heap_bound.py -vvv --start-size 4G --min-step 100M --context 2 -- -cp assembly.jar …
```
=> Share ChildBinding objects between siblings

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Bits.scala, core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/Clock.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/experimental/Analog.scala, core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/warnings.md, src/test/scala/chiselTests/AsTypeOfTester.scala, src/test/scala/chiselTests/BundleLiteralSpec.scala, src/test/scala/chiselTests/ChiselEnum.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala, src/test/scala/chiselTests/Vec.scala, src/test/scala/chiselTests/VecLiteralSpec.scala, src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
Built on top of https://github.com/chipsalliance/chisel/pull/4160 so should merge this one after that one (might need rebase but git seems smarter about cherry-picks these days).
This is very valuable for ChiselSim-style testing because it means that you can much more easily construct literals in tests.
- Squash
Casting a literal (of any type) to another type with .asTypeOf will result in a literal of the new type. For non-literals, the FIRRTL representation will now be a little bit more efficient.
=> Preserve literals across .asTypeOf

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chisel3/TypeEquivalenceSpec.scala
Make Add a contextual message to Data.requireTypeEquivalent and expose a public API in DataMirror.requireTypeEquivalent, to make it easier for user code to have good error messages when requiring type equivalence between two chisel Datas
=> Make requireTypeEquivalent public and add context message

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/Vec.scala
This is a more focused fix for the issue hit by @sequencer in [[1]](https://github.com/chipsalliance/chisel/pull/4198#issuecomment-2182917012), credit to @mwachs5 for coming up with this solution.
- Bugfix
- Squash
Previously, VecInit would try to "intelligently" select := or <> depending on if the type is bidirectional. :<>= has the desirable behavior here for both passive and bidirectional types. It also has the advantage over <> of handling internal wires.
=> Use :<>= in VecInit methods instead of := or <>

src/main/scala/chisel3/util/Valid.scala, src/test/scala/chiselTests/ValidSpec.scala
Modeled after https://github.com/chipsalliance/chisel/pull/2646.
Squash
Users can now apply a function `f` to the `bits` field of a `Valid` instance with the new `Valid.map(f)` method.
=> Add map method for Valid

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/internal/Builder.scala
- Squash
* This removes a 4-byte field (8-bytes with heap > 32 GB) from all Data
=> Move circuitVar from HasId to BaseModule

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala
This almost entirely API compatible, but due to `ActualDirection.Bidirectional` being a case class, this change breaks things like the copy method. This is mostly a performance improvement
- Rebase (merge commit)
* Specified and actual direction information are each now stored as single bytes rather than references.
* This reduces the memory use of a typical bound UInt from 72 bytes shallow, 128 bytes retained to 64 bytes shallow, 120 bytes retained.
* The change is mostly source compatible, but ActualDirection.Bidirectional, has changed slightly to memoize its two possibilities (`Bidirectional.Default` and `Bidirectional.Flipped`). There are deprecations for the typical APIs
=> Micro-optimize Direction

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/RecordSpec.scala
The code is a little janky, but it is a massive reduction in memory use.
For a typical Bundle with 7 UInt fields, this reduces the memory footprint from 1992 bytes to 1552 bytes (the duplicate VectorMap of only 7 elements is 440 bytes!), a 22% reduction. Combined with my other recent performance improvement PRs (#4251, #4252, #4253 but **excluding** #4242), this 1992 bytes is reduced to 1424 for a total reduction of 28.5% memory use for this typical Bundle with 7 UInt fields.
I suspect we can do better by getting rid of any Map here at all and instead just use an `Array[Data]` (where the String names of the fields are stored in the children Data themselves as they are already stored there). Whereas the VectorMap of 7 elements is 440 bytes, an Array of 7 elements is 48 bytes.
That being …
=> Optimize Record._elements to not duplicate VectorMap if possible

core/src/main/scala/chisel3/internal/firrtl/IR.scala, src/test/scala/chiselTests/DataPrint.scala
We should turn on warnings for unused variables 🙃 
- Bugfix
- Squash
=> Fix .toString for dynamic indexing

core/src/main/scala/chisel3/probe/package.scala, src/test/scala/chiselTests/ProbeSpec.scala
Add more information to the error message when attempting to `probe.define` to a mismatched chisel type.
=> Add more information when probe types don't match

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/LayerSpec.scala
- Feature
Feature: Add user-specified output directories to layer declarations
=> Add output directory support to layer declarations

src/main/scala/chisel3/util/circt/DPI.scala, src/test/scala/chiselTests/DPISpec.scala
This PR adds DPI intrinsic support and API to define DPI functions declaratively. The test passes locally but requires a new version of firtool. 
=> Add DPI intrinsics and API 

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/properties/Object.scala
Similar to https://github.com/chipsalliance/chisel/pull/4238 (and reflecting our redundant representation--binding and ref)
- Squash
This reduces memory use by n - 1 times 16-bytes for an Aggregate with n elements.
=> Share Node objects between siblings

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/ReadOnlySpec.scala
Views can be a bit expensive, so make fewer of them with the `.readOnly` API.
- Squash
=> Optimize .readOnly to only create views when necessary

core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/main/scala/chisel3/aop/Select.scala, src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/DataPrint.scala, src/test/scala/chiselTests/Vec.scala
Built on top of https://github.com/chipsalliance/chisel/pull/4259 (so this should be merged after it)
The benefit comes from not boxing static indices in ILits (and BigInts although those are memoized). Each ILit is 16-bytes, not to mention at least 2 memory loads to get the index when using it.
- Squash
This saves 16-bytes per Vec element.
=> Specialize Index for literal indices with LitIndex 

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/Vec.scala
https://github.com/chipsalliance/chisel/pull/4268 introduced a subtle bug for when dynamically indexing Vecs of size 0. This is currently deprecated but obviously we need to emit legal FIRRTL until it becomes an error.
- Bugfix (but no release notes because this bug isn't released)
- Squash
=> Fix emitted FIRRTL for dynamic index of size 0 Vec

core/src/main/scala/chisel3/experimental/package.scala, core/src/main/scala/chisel3/internal/Builder.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala, src/test/scala/chiselTests/naming/NamePluginSpec.scala
Adds new trait `AffectsChiselName` that adds support for naming user-defined types
=> Add AffectsChiselName

src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
- Bugfix
Milestone is 7.0 because the fixed code does not exist on 6.x
- Squash
=> Properly handle OpaqueTypes in SRAM mask

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
Fix a bug where smem/cmem did not emit commas which are now mandatory in the FIRRTL spec.
h/t @dtzSiFive for identifying the problem/fix
=> [firrtl] Emit commas for smem/cmem

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, src/test/scala/chiselTests/LayerSpec.scala
Fix a bug in D/I where layers created by a Definition were not added to the layers of the `Builder`.  Change this by correctly copying these layers over.
Fixes #4299.
Fix bug where layers were not added to the circuit if used in a `Definition`.
=> Emit Layers when using D/I

src/test/scala/chiselTests/LayerSpec.scala
Move some tests around in LayerSpec to coalesce common tests of working functionality from common tests of non-working functionality.
=> Cleanup LayerSpec tests, NFC

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala
Change Chisel IR for `layer.block` operations to be region based instead
of token based.  This is a similar refactor that was done for when blocks
previously.
Remove complexity from the Chisel IR Converter which only existed to
facilitate converting token-based IR structures like WhenBegin/WhenEnd and
LayerBlockBegin/LayerBlockEnd.  Now that all of these structures have been
removed, there is no need for the added complexity.
Change the name of a function internal to the Chisel IR/FIRRTL IR
converter.
This is structured as logical commits that may be reviewed independently.
=> Use Region for Layer Blocks

core/src/main/scala/chisel3/Layer.scala, src/test/scala/chiselTests/LayerSpec.scala
Change `chisel3.layer.block` to create parent layers on demand and only error if the layer of the current layer block is not an ancestor of the desired layer.  This is a relaxation of the previous requirement that the current layer must be the parent of the desired layer.
The reason for this relaxation is to make future APIs easier to write. E.g., there is a desire to put asserts under layers automatically.  Part of such an API will need to automatically create layer blocks if the user wants to put all assertions in a layer that is not a child of the root layer.  Ergo, an API like what `block` was modified to be is necessary either for `block` or in this new assertion code.  It seemed better to make this available to all users and library authors.
Note: this is narrowly an API extension …
=> Create layer blocks on demand

integration-tests/src/test/scala/chiselTest/LFSRSpec.scala, src/test/scala/chiselTests/AnalogIntegrationSpec.scala, src/test/scala/chiselTests/AnalogSpec.scala, src/test/scala/chiselTests/BlackBox.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/ExtModule.scala, src/test/scala/chiselTests/MultiClockSpec.scala, src/test/scala/chiselTests/aop/InjectionSpec.scala, src/test/scala/examples/SimpleVendingMachine.scala
Remove annotations arguments to ChiselSpec methods, e.g., runTester. This argument was not actually used for anything.
Update all tests that were passing annotations to no longer pass annotations.
=> Remove annotations from ChiselSpec methods

src/main/scala/chisel3/simulator/package.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala
Change Chisel's simulator to enable all layers that exist in the circuit.
Do this by copying over the layer bind files and including them in
compilation.
In terms of implementation, this works by copying over all files in the filelist (as before) and then copying over all ABI-specified `layers_` files. All files copied over are included in the compilation (which turns on all the layers). In order for `` `include `` directives to be properly evaluated, this adds include directories to common compilation options. These include directories map to the same option in either Verilator or VCS: `+incdir`.
Enable all layers during simulation. Previously, all layers were disabled.
=> [simulator] Enable all layers for simulation

core/src/main/scala/chisel3/properties/Property.scala, src/test/scala/chiselTests/experimental/DataView.scala
Partial fix for https://github.com/chipsalliance/chisel/pull/4291
- Bugfix
- Squash
This fixes an issue with views of List of Property.
=> Remove unnecessary overrides of lref and ref in Property

core/src/main/scala/chisel3/probe/package.scala, src/test/scala/chiselTests/experimental/DataView.scala
Partial fix for https://github.com/chipsalliance/chisel/pull/4291
- Bugfix
- Squash
=> Handle define on views of Probes

src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/LayerControl.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/simulator/EphemeraSimulatorSpec.scala, src/test/scala/chiselTests/simulator/LayerControlSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala
Add some infrastructure for controlling which layers are enabled by
Chisel's simulator.  This is not currently exposed to the user, yet.  This
makes no changes to the existing behavior of all layers being enabled.
Add a function argument that can be used to choose (filter) which Verilog
files should be include in the build.  This is a _very_ low level API that
is being added to allow a user to enable bind convention layers when
writing a test.
Add the ability for the user of the EphemeralSimulator to control which
layers are enabled.
This is broken into logical commits that can be reviewed independently.
=> [simulator] Add LayerControl infra

svsim/src/main/scala/Workspace.scala
This fixes two bugs in https://github.com/chipsalliance/chisel/pull/4286
* VCS seems to be unhappy with `initTestBenchScope;` so replace it with `initTestBenchScope();`. 
* `getBitWidth` exported DPI functions are used both for gettable/settable ports but #4286 only added DPI decl for getter so this PR fixes by removing a filter. 
- Bugfix
=> Fix svsim DPI function template

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/probe/Probe.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Checks.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/Shell.scala, src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Add a new annotation/option to Chisel, `RemapLayer`, which is intended to
be used to allow a Chisel compilation to change which layers are used by
an upstream project's libraries in a downstream project.  The motivation
here is to fix mismatches between upstream and downstream when they have
different layers.
Add the ability for ChiselStage to globally remap a layer to another
layer.  This is intended to be used as a Chisel-level mechanism for a
downstream project to change the layers of all upstream projects.  This
may be necessary in order to produce compatible FIRRTL designs where the
upstream project and downstream project have different layers, but the
upstream project has put certain constructs (e.g., asserts) into
specific layers.
Add --remap-layers ChiselStage option for changing …
=> Add --remap-layers to ChiselStage

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala, src/test/scala/chiselTests/BundleElementsSpec.scala
Fixes #4223. Straighten out the reversing of bundle elements by removing sorting. Add reversals to fix ordering and fix tests
- API Modification
All `Bundle` elements will be ordered by the order of their declaration, including by inheritance.
=> Bundle elements ordering fix

src/main/scala/chisel3/layers/Layers.scala, src/main/scala/chisel3/layers/package.scala
Add the common layers that all Chisel projects are expected to use.  These layers will, in later commits, be used for in-tree Chisel generators to put hardware in.  I.e., it is expected that asserts will not be put under their corresponding layer.
CC: @SandeepRajendran 
Add Chisel-approved layers. These are intended to be used by downstream projects (Chisel users) to define their layer collateral and, in the future, by Chisel's libraries which generate verification collateral, e.g., assertions.
=> Add common layers to Chisel

core/src/main/scala/chisel3/Layer.scala, src/test/scala/chiselTests/LayerSpec.scala
Add an argument to `layer.block` which can be used to prevent a layer block from being created if the current builder state indicates that we are already inside a layer block.  This API is intended to be used for library writers to provide a way to _maybe_ put an operation into a layer block.  Specifically, this is intended for verification statements which should go into a default layer block (e.g., `Verification.Assert`), but should not do this if the Chisel user is already in another layer block.
Add `skipIfAlreadyInLayerBlock: Boolean` parameter to `layer.block`. This is a more advanced API for a library writer to write an API where hardware is, by default, created in a layer block. However, if the user wraps the API in a layer block, then the layer block the API would create is …
=> Add skipIfAlreadyInBlock arg to layer.block

.github/scripts/check-maven-for-llvm-firtool-version.sh, .github/workflows/cd-circt.yml
- Squash
Now CIRCT bumping CD will wait for the repackaging of firtool as a Maven dependency for use with firtool-resolver.
=> [cd] Guard cd-circt PR on llvm-firtool publish to Maven

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/MuxSpec.scala
I'm not sure what the best category for this is, not really a feature nor a bug fix, so maybe Documentation?
Before:
```
can't create Mux with non-equivalent types MuxBetween.in0: IO[MyBundle$1] and MuxBetween.in1: IO[MyBundle$1]
```
After:
```
can't create Mux with non-equivalent types _.foo: Left (MuxBetween.in1.foo: IO[UInt<16>]) and Right (MuxBetween.in0.foo: IO[UInt<8>]) have different widths.
```
- Squash
=> Improve the error message for mismatched types in Mux

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, docs/src/explanations/layers.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chisel3/TypeEquivalenceSpec.scala, src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala, src/test/scala/chiselTests/simulator/EphemeraSimulatorSpec.scala, src/test/scala/chiselTests/simulator/LayerControlSpec.scala, src/test/scala/chiselTests/simulator/SimulatorSpec.scala, src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Add inline-layers, a kind of Layer that lowers to macro ifdefs, inline, in the resulting verilog.
- Rename the "bind layers" concept to "extract layers".
- An inline-layer, in contrast to extract-layers, do not have output directories. When determining the output directory of an extract-layer, skip over and ignore any parent 
- Deprecate the concept of a layer's convention in favour of two `Layer` configuration types: `LayerConfig.Extract` and `LayerConfig.Inline`. Update all code inspecting the convention of a layer to instead match against the configuration.
Layer API has changed from convention as argument to constructing specific layer kind directly.
=> Layers: Add support for inline convention.

core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
This ensures boring from an OpaqueType that wraps a Property uses the correct connection operator in the IR.
=> Support BoringUtils.bore on OpaqueType wrapping a Property.

src/main/scala/chisel3/aop/Select.scala
Fix a bug introduced when converting layer blocks to be region based [1] where methods in the `aop.Select` object were not updated to walk into the regions of layer blocks.
[1]: b166cfa064426a06d7d68207406a0cabf5194c3b
Fix a bug in `aop.Select` where `layer.block`s would not be visited.
=> Visit layerblocks in aop.Select methods

core/src/main/scala/chisel3/Layer.scala, src/test/scala/chiselTests/LayerSpec.scala
Add a second control parameter to `layer.block` that will cause no layer to be created if the current module has any layers enabled.  This is intended as a safe default for library writers that are putting operations into layer blocks.  Certain verification operations do not work well with other verification operations (e.g., force and assert) due to interactions where layers may result in the creation of multiple always blocks.  This option allows operations to be placed in the body of a testbench (the likely module that has layers enabled) and avoid any of the interactions of disjoint always blocks.
Add `skipIfLayersEnabled` parameter to `layer.block` which will elide the block if any layers are currently enabled.  This is an advanced library-writer API that only comes up when a library …
=> Add skipIfLayersEnabled param to layer.block

core/src/main/scala/chisel3/VerificationStatement.scala, src/main/scala/chisel3/ltl/LTL.scala, src/test/scala/chiselTests/DataEqualitySpec.scala, src/test/scala/chiselTests/LTLSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Put verification operations into layer blocks.
Put verification operations (asserts, assumes, covers, and stop) into Chisel-defined layers by default. Assertions are placed in `Verification.Assert`, assumptions are placed in `Verification.Assume`, covers are placed in `Verification.Cover`, and stop is placed in `Verification`. For users of ChiselSim/svsim, all layers are enabled by default, so no changes are necessary. For users that previously relied on these operations being enabled by default, either enable in-CIRCT specialization with `-enable-layers=Verification,Verification::Assert,Verification::Assume,Verification::Cover` or follow the FIRRTL ABI and include bind files for the layers that should be enabled.
=> Add layer specification to LTL, verification ops

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/LayerSpec.scala
Add an API, `chisel3.layer.elideBlocks` that will cause any calls to create a layer block inside its thunk to _not_ be created.  This is an advanced API intended to be used in situations where a library has to avoid additional layer block creation.
This is specifically being added because we have an API, backed by an in-tree CIRCT transforms, which can create bound modules and does so _after_ layers are converted to modules.  While this API is intended to be replaced with layers, initially it needs to have a way to prevent layers from being added to the design to prevent creation of a bind-under-bind in the output.
I expect this API to be short lived...
Add `chisel3.layer.elideBlocks` API that can be used to prevent the creation of additional layer blocks. This is an advanced, library …
=> Add layer.elideBlocks API

core/src/main/scala/chisel3/Layer.scala, src/test/scala/chiselTests/LayerSpec.scala
Make the `chisel3.layer.addLayer` API public.  This is useful if a user wants to guarantee that a layer will show up in CHIRRTL even if no layer block refers to this layer.
This solves a problem where downstream build flows want to expect that certain layers will always exist.  However, without this API, there is no way to do this other than to create dummy layer blocks.  This is slightly cleaner without the empty layer block trick.  Additionally, there is no real harm to having this API public.
Add `chisel3.layer.addLayer` API.  This can be used to cause a layer to be emitted in FIRRTL even if it has no layer block users.  This API is added (it was private before) so that users can make their custom layers always be there.  This is important for downstream build flows which may want to …
=> Make layer.addLayer API public

core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/layers/package.scala, docs/src/explanations/layers.md, src/test/scala/chiselTests/LayerSpec.scala
Add "default layers" that are always emitted in CHIRRTL.  These layers are the built-in Chisel layers:
- Verification
- Verification.Assert
- Verification.Assume
- Verification.Cover
This is done to create uniformity of CHIRRTL emitted by Chisel. Downstream build flows can count on these layers _always_ existing and can then know to expect them (either using them or specializing them away).
Cause default Chisel layers (Verification, Verification.Assert, Verification.Assume, and Verification.Cover) to always be emitted in FIRRTL.  This is done to improve the predictability of Chisel designs---these layers will always exist and downstream flows can choose how to handle them without the unpredictability of them only being emitted if they have user layer blocks.
=> Add default layers that are always emitted

docs/src/explanations/layers.md, src/test/scala/chiselTests/LayerSpec.scala
Add a test and update documentation that shows how a layer can be declared with a custom parent.  This is particularly useful for the case of creating user-defined layers which nest under built-in layers.
=> Add test, docs of layer reparenting, NFC

src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala, src/test/scala/circtTests/stage/ChiselMainSpec.scala
Dramatically increase the power of the '--module' argument to 'circt.stage.ChiselMain'.  This adds support for constructing modules with parameters using reflection as demonstrated elsewhere [[1]].
This is long missing support that I intended to add when both the original reflective construction was added [[2]] and turned on [[3]].  At the time, I didn't know how to do reflective construction of arbitrary modules and left that feature unfinished for the next 5 years.
This is done to move 'ChiselMain' more in the direction of being a command line utility for running Chisel generators.  This is related to the discussions of a hypothetical 'chisel-cli' that has been discussed on #4351.
This commit changes the API such that any class constructed this way must take a trailing '()'.  Anything …
=> Make '--module' support arguments

core/src/main/scala/chisel3/internal/firrtl/IR.scala, src/test/scala/chiselTests/ProbeSpec.scala
- Bugfix
Names for probe Args will be the default `toString`. For example, if you use `DataMirror` to get the `earlyName` of a probe (derived from `Arg.name`), you will see this default `toString`.
```scala
import chisel3.probe._
import chisel3.reflect.DataMirror
import chisel3.util.experimental.BoringUtils
import circt.stage.ChiselStage
class ProbedClockedData[D <: Data](gen: => D) extends Bundle {
val dataProbe = Probe(gen)
def data      = probe.read(dataProbe)
val clockProbe = Probe(Clock())
def clock      = probe.read(clockProbe)
val resetProbe = Probe(Reset())
def reset      = probe.read(resetProbe)
def tapAndConnect(ref: D, clock: Clock, reset: Reset) = {
dataProbe  := BoringUtils.tap(ref)
clockProbe := BoringUtils.tap(clock)
resetProbe := BoringUtils.tap(reset)
}
} …
```
=> Fix Arg.name and earlyLocalName for probes

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/Direction.scala
In https://github.com/chipsalliance/chisel/pull/2634, we unified the Chisel 2 and Chisel 3 direction semantics, making it legal to have Records where the directionality of elements is mixed (some may be specified, some may be not). The implementation is mostly right, but there was a corner case I came across in https://github.com/chipsalliance/chisel/issues/4204.
Previously, ActualDirection.fromSpecified would return Unspecified for either Unspecified or Flipped input. This in turn resulted in Bundles mixing Unspecified and Outputs as being "bidirectional" despite the fact that they are actually unidirectional (or passive), and similarly for Bundles mixing Flipped with Input.
Now, Unspecified maps to Output and Flip maps to Input. This change makes the direction calculation more …
=> Fix ActualDirection calculation from SpecifiedDirection

core/src/main/scala/chisel3/properties/Path.scala, src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/properties/PropertySpec.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
This PR adds Property support for `SRAMInterface`, instantiating the `SRAMOM` when using `SRAMInterface`. In our flow this is intend to replace the repl-sram and provide a unified Verilog for both synthesis tool and simulation tools.
add property to SRAMInterface
=> Add property support to SRAMInterface-based SRAM

core/src/main/scala/chisel3/properties/Path.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Chisel will now reject attempts to create a Path within a Module that is not a direct ancestor of the target. Note that such paths are already rejected by firtool.
I'm marking this as API Modification since it is a pretty big behavioral change but I don't think the change is actually observable by users unless they are doing things with the paths in the `.fir`.
- Squash
=> Change Path to emit relative targets

docs-target/src/main/scala/chisel3/docs/package.scala, docs/src/appendix/experimental-features.md, docs/src/cookbooks/cookbook.md, docs/src/cookbooks/dataview.md, docs/src/cookbooks/hierarchy.md, docs/src/cookbooks/naming.md, docs/src/explanations/bundles-and-vecs.md, docs/src/explanations/chisel-enum.md, docs/src/explanations/chisel-type-vs-scala-type.md, docs/src/explanations/connectable.md, docs/src/explanations/connection-operators.md, docs/src/explanations/dataview.md, docs/src/explanations/interfaces-and-connections.md, docs/src/explanations/layers.md, docs/src/explanations/naming.md, docs/src/explanations/polymorphism-and-parameterization.md, docs/src/explanations/ports.md, docs/src/explanations/warnings.md
And deploy this utility, replacing most uses of ChiselStage with chisel3.docs.emitSystemVerilog.
h/t @keithdr93 for pointing this out on gitter
- Squash
This cleans up a lot of boilerplate and removes the default layer emission in all of the uses.
=> Add utility for pretty Verilog emission in mdoc

.github/workflows/build-scala-cli-example/chisel-example.scala
I would've just pushed to main on this, but I want CI to run first.
=> Add -default-layer-specialization=enable to Scala CLI example

src/main/scala/chisel3/simulator/LayerControl.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala/chiselTests/simulator/LayerControlSpec.scala
The Layer filename ABI changed in FIRRTL [[1]].  This will show up in CIRCT 1.85.0.  This commit gets Chisel working with this new ABI.
[1]: https://github.com/chipsalliance/firrtl-spec/commit/d35f2bb5f460d5c866cb9021ad7d45d8f0430ec1
Update Chisel to support new Layer filename ABI. This requires CIRCT 1.85.0+.  CIRCT versions before this will not work.
=> [simulator] Switch ChiselSim to use new Layer ABI

src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
See https://github.com/chipsalliance/chisel/issues/4379, there are issues in firtool with creating Path values at the moment. Will restore in the future once that is resolved.
Marked "No Release Notes" because SRAMDescription is not yet released.
- Bugfix
- Squash
=> Remove Path from SRAMDescription as it isn't fully functional

firrtl/src/main/scala/firrtl/AttributeAnnotation.scala, firrtl/src/test/scala/firrtlTests/annotationTests/AttributeAnnotationSpec.scala, src/main/scala/chisel3/util/AttributeAnnotation.scala
Bugfix
Squash: The PR will be squashed and merged (choose this if you have no preference).
Add AttributeAnnotation back to in-tree firrtl
=> Add Attribute annotation back to chisel in-tree firrtl

core/src/main/scala/chisel3/SeqUtils.scala, src/test/scala/chiselTests/OneHotMuxSpec.scala, src/test/scala/chiselTests/util/PriorityMuxSpec.scala
=> Improve error messages for empty Mux1H and PriorityMux

core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Fix BoringUtils (see tests) placement of connection commands so that they are added to the current command buffer.
Flush staged commands before changing regions to avoid needing multiple "staging" buffer lists.
Alternatively the current list could be saved and restored.
Tests from #4108 are included and finished, with this change two of them now pass (the ones encountered in practice, FWIW). The third is included but marked "ignore" as future work.
This is a bit of a change regarding "staged" commands, as now before the module is closed they are no longer "secret" since they are added to the normal command buffers.
They are still staged (deferred) which appears to be useful to ensure they appear after what's currently being constructed (specifically, not before).
- Bugfix
- Internal or …
=> Flush staged commands before/after enter/exit regions.

src/main/scala/chisel3/experimental/util/SerializableModuleElaborator.scala, src/test/scala/chiselTests/experimental/SerializableModuleElaboratorSpec.scala
This PR implements the SerializableModuleElaborator trait, which is used to create elaborators for SerializableModule. In t1, we compile all the Scala code into a jar file and specify different main classes to elaborate different modules. 
The config API is used to guarantee the type safety of the parameters, and the design API actually produces the circuit, which is used this way:
```scala
@main
def config(
@arg(name = "parameter") parameter:  GCDParameterMain,
@arg(name = "target-dir") targetDir: os.Path = os.pwd
) =
os.write.over(targetDir / s"${topName}.json", configImpl(parameter.convert))
@main
def design(
@arg(name = "parameter") parameter:  os.Path,
@arg(name = "target-dir") targetDir: os.Path = os.pwd
) = {
val (firrtl, annos) = designImpl[GCD, …
```
=> feat: implement SerializableModuleElaborator

build.sbt
Bump to using Scala 2.13.15 (and mill update) is separate as this is intended to be backported but we will not backport the more complete version bump.
- Squash
Add support for Scala 2.13.15
=> Add Scala 2.13.15 to compiler plugin cross-build

build.sbt, core/src/main/scala/chisel3/ModuleAspect.scala, src/main/scala/chisel3/aop/injecting/InjectStatement.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/aop/injecting/InjectingPhase.scala, src/main/scala/chisel3/stage/phases/MaybeInjectingPhase.scala
Deprecate injecting aspect code as of Chisel 6.6.0.  These were planned to be deprecated some time ago (see ROADMAP.md).  However, these had a long user in @sequencer.  He is now off of these and there is nothing blocking their removal.
I will follow this with a commit to remove these from `main` for Chisel 7.
For similar, verification-focused functionality can be selectively added to the circuit, use layers.
Deprecate injecting aspects as of Chisel 6.6.0 and plan for removal in Chisel 7.
=> Deprecate all Injecting Aspect Code

build.sbt, core/src/main/scala/chisel3/aop/Aspect.scala, src/main/scala/chisel3/aop/AspectLibrary.scala, src/main/scala/chisel3/aop/inspecting/InspectingAspect.scala, src/main/scala/chisel3/stage/phases/AspectPhase.scala, src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
Deprecate the remaining parts of Aspects that were missed in earlier commits.  After this, the only non-deprecated part of the `aop` library are the `Select` utilities.
Deprecate everything in `aop` package except `Select` library.
=> Deprecate more Aspect parts

build.sc, firrtl/src/test/scala/firrtlTests/FileUtilsSpec.scala
Add missing ScalafmtModule mix-in to all test objects.  This adds a `_.reformat` build target to all of them, i.e., they can now be run through Scalafmt.
=> [mill] Add ScalafmtModule to all tests

src/test/scala/chiselTests/aop/SelectSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala, src/test/scala/chiselTests/naming/NamePluginSpec.scala, src/test/scala/chiselTests/naming/PrefixSpec.scala
Rework internal users of aspects to use alternatives. Concretely, this is changing Select tests to directly test those APIs and changing naming tests to use string-based matching. This is generally beneficial for making these tests more directly test their respective features. However, the primary motivation is to prepare Chisel 7 to drop aspects.
=> Make aspects non-load bearing

src/main/scala/chisel3/ltl/LTL.scala, src/test/scala/chiselTests/LTLSpec.scala
This PR is based on #4436 and fixes #4429.
Fix LTL intrinsics are generated outside the verification layer block
=> fix: wrap all intrinsics in layerblocks

core/src/main/scala/chisel3/BitsImpl.scala, src/test/scala/chiselTests/UIntOps.scala
=> Make it legal to extract zero bits from a zero-width UInt

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Previous behavior would always put the new probe expression in the instance's module body, but this is incompatible with instances built with Instantiate.
Given FIRRTL now supports this, we can improve this API.
Additionally, added a few more D/I + BoringUtils tests
- Bugfix
BoringUtils.rwTap can now works on a port of an `instance: Instance[..]`
=> Fix Boring.rwTap on instance ports

src/test/scala/chiselTests/BoringUtilsTapSpec.scala
=> BoringUtilsTapSpec: remove debugging print

src/main/scala/chisel3/aop/Select.scala, src/test/scala/chiselTests/aop/SelectSpec.scala
Previously it would always fail to find anything.
Working on the Mill build, I was lazy in setting up scalacOptions and applied `-Xlint:infer-any` to everything which caught this. Unfortuantely, `Iterable.contains` is not type safe but if you screw up the type, this lint will catch it inferring `Any` (or `Object`).
- Bugfix
- Squash
=> Fix Select.attachedTo

core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/probe/PackageImpl.scala, src/test/scala/chiselTests/LayerSpec.scala
Drop test specifically checking this incorrect behavior.
Add tests checking don't need to be under a layer block to define a probe with more colors, and that enabled layers don't change what is allowed to be defined.
- Bugfix
Fix checking of layer-color probes to avoid rejecting valid uses and to detect actual problems that would otherwise be caught by CIRCT.
=> Layers: color check all not any and don't consider enabled layers.

build.sbt, core/src/main/scala/chisel3/Annotation.scala, core/src/main/scala/chisel3/BitsImpl.scala, core/src/main/scala/chisel3/DataImpl.scala, core/src/main/scala/chisel3/IO.scala, core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/Width.scala, core/src/main/scala/chisel3/connectable/Alignment.scala, core/src/main/scala/chisel3/dontTouch.scala, core/src/main/scala/chisel3/experimental/HasTypeAlias.scala, core/src/main/scala/chisel3/experimental/Trace.scala, core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Property.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala
Part of the larger work of preparing for Scala3 support
Adds -Xsource:3 to core in preparation of Scala3 migration. Add stricter type ascriptions for Scala3:
* ResetType.litOption return type changed from `None` to `Option[BigInt]`
* AsyncReset.litOption return type changed from `None` to `Option[BigInt]`
* RequireAsyncReset.resetType type changed from `ResetType.Type` to `Asynchronous.type`
* RequireAsyncReset.resetType type changed from `ResetType.Type` to `Synchronous.type`
* CrossModuleBinding.location return type changed from `None.type` to `Option[BaseModule]`
=> [Scala3] Add core -Xsource:3 for Scala3 cross compilation support

build.sc, core/src/main/scala/chisel3/AggregateImpl.scala, core/src/main/scala/chisel3/connectable/Connection.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, src/main/scala/chisel3/aop/Select.scala, src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala, src/main/scala/circt/stage/phases/CIRCT.scala
We hit an internal error and it isn't useful because of missing String interpolators. Fix that
- Bugfix
- Squash
=> Fix missing string interpolators, add -Xlint:missing-interpolator

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
The new metadata like SRAMDescription is useful, but there are some composition issues with various CIRCT transforms that are not yet resolved. Since this stuff is new (not yet released), I argue we should guard it under a CLI option (`--include-util-metadata`) for the time being. Ultimately, I expect we will want to include it by default, but I think we need the support to mature a bit first.
The only metadata at the moment is `SRAMDescription`, but we probably should do similar things with `Queue` and possibly other utils so I added a generic CLI option to guard them all.
We could also make it possible to elide metadata on an API call by API call basis. I thought about doing that for SRAM but due to the fact that default arguments cause binary compatibility issues, we keep increasing …
=> Elide metadata by default, add --include-util-metadata

core/src/main/scala/chisel3/DataImpl.scala, src/test/scala/chisel3/TypeEquivalenceSpec.scala, src/test/scala/chiselTests/DataPrint.scala, src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala
- Bugfix
Probe chisel types now include the kind of probe and layer in their `.toString` method
=> Add Probes to .toString Data methods

core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/experimental/hierarchy/Annotations.scala, src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/Examples.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
I also changed HasTarget to only wrap SramTarget rather than any NamedComponent which I explain in the comments:
```
This is only currently used for SRAM to hide the underlying Memory but still let users annotate it.
Rather than generalizing this, it's more likely that we'll just delete it (and the use in SRAM) in favor of Path Properties.
```
- Squash
=> Implement Lookupable for HasTarget (used by SRAM)

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
- Bugfix
When trying to drill a port, it doesn't matter if the module is closed. We do not need to construct new hardware and can just use the existing port.
=> Allow BoringUtils to use existing port in a closed module

core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, src/test/scala/chiselTests/experimental/hierarchy/Examples.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
An oft-overlooked primitive type but an important one nonetheless!
- Squash
=> Implement Lookupable for Unit

core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/RawModuleSpec.scala
Add the `afterModuleBuilt` hook to `RawModule`, similar to the existing `atModuleBodyEnd`. This hook is called after a module has been fully constructed and its resulting component definition has been added to the builder. Thus code inside the body of `afterModuleBuilt` can get the definition of the surrounding module and instantiate it, which is interesting for generating additional collateral like unit tests alongside a module.
The new `afterModuleBuilt` hook can be used to schedule code to be executed once a module has been fully generated and its definition is available. This allows further collateral such as unit tests to be generated alongside a module.
=> [Module] Add afterModuleBuilt hook

core/src/main/scala-2/chisel3/experimental/hierarchy/Instantiate.scala, core/src/main/scala/chisel3/MemImpl.scala, core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala, core/src/main/scala/chisel3/internal/Builder.scala, docs/src/explanations.md, docs/src/explanations/moduleprefix.md, src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/PrefixSpec.scala
Introduces a new API `withModulePrefix`.
Example:
```scala
class Submod extends RawModule {
// ...
}
class Top extends RawModule {
val noprefix_inst = Module(new Submod)
withModulePrefix("Foo") {
val foo_inst = Module(new Submod)
}
withModulePrefix("Bar") {
val bar_inst = Module(new Submod)
}
}
```
This will result in the definition of the following modules:
```firrtl
module Submod :
skip
module Foo_Submod :
skip
module Bar_Submod : 
skip
public module Top :
inst noprefix_inst of Submod
inst foo_inst of Foo_Submod
inst bar_inst of Bar_Submod
```
Only module definitions are prefixed. Other circuit components, such as wires and registers, are unaffected.
Module prefixes nest, where `Foo_Bar_Submod` indicating that a prefix `Foo` exists in the grantparent or higher of the instance of …
=> Add `withModulePrefix`

core/src/main/scala-2/chisel3/PrintfMacros.scala, src/test/scala/chiselTests/Printf.scala
Change the emission of printfs to emit these under the `Verification` layerblock.  This is done as part of replacing the `firtool` extract-test-code feature with layers and the "advanced layer sink" `firtool` feature.
The extract-test-code feature will extract asserts _and_ printfs together. This is technically a deviation from this behavior.  However, it seems better to not lump these in with asserts.  Nonetheless, this is a backwards compatible change from the perspective of extract-test-code because the `Verification` layer is always loaded if the `Assert` layer is present.  (Prints will always show up if you turn on assertions.)
In the future, we probably want to add a `Debug` layer under the `Verification` layer where these will live.  I would like to hold off on making this change …
=> Wrap printfs in the Verification layerblock

core/src/main/scala/chisel3/layers/Layers.scala, src/test/scala/chiselTests/LayerSpec.scala
Change directories for default layers to use lowercase output directories. While this is independently likely a better choice, it is a somewhat pragmatic, as these directory names match the legacy names of `firtool`'s extract-test-code feature (which was a custom SiFive pass for the SFC before being open-sourced in `firtool`).  This will help us land an extract-test-code replacement without having to disturb build flows. Secondarily, and independently, lower case directories are likely better.
There are two alternative changes which were rejected:
1. The layers could be renamed to be lowercase.  Generally, it's better to have objects and classes be uppercase.
2. The automatic directory names could be mangled to be lowercase as opposed to the exact layer names.
Change directories for …
=> Change default layers to use lowercase directories

build.sc
They were accidentally dropped in https://github.com/chipsalliance/chisel/pull/4492
- Squash
=> Restore common scalacOptions to project chisel

src/main/scala/chisel3/util/experimental/Inline.scala, src/test/scala/chiselTests/InlineSpec.scala
The InlineInstance trait can be attached to a module, to cause firtool to inline instance of that module. The inline annotation is tricky to wield because, if an inline module dedups with another module, we will inline all instances of both modules.
To make InlineInstance easier to use, whenever we mark a module as inline, we also mark it as "no dedup".
This of course does not work well when we have a module which we want to inline AND dedup. So, this PR adds a new InlineAllInstances trait which allows a module to be marked inline without blocking dedup.
=> Add new InlineAllInstances trait

build.sc
Trait HasScala2Plugin and HasScala2MacroAnno extending CrossSbtModule will override the mill sources with SBT's folder layout and it will break the modules with mill's default source layout like LitUtility and PanamaConverter.
- Bugfix
=> fix: fix wrong mill source layout

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
FIRRTL spec version 4.0.0 was released.  Chisel is currently emitting things _beyond_ this and it should now mark the emitted FIRRTL as being 4.1.0.
Bump emitted FIRRTL version to 4.1.0.
=> Bump emitted FIRRTL to 4.1.0

build.sbt, build.sc, core/src/main/scala/chisel3/experimental/hierarchy/core/IsInstantiable.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/experimental/hierarchy/package.scala, docs/src/cookbooks/hierarchy.md, src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala, src/test/scala/chiselTests/experimental/hierarchy/Examples.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
See Release Notes for description.
- Squash
Historically, the Lookupable API is able to change the type of fields looked up from Definitions or Instances. This enabled Module fields to be looked up as Instances, as well as user-defined types to opt-in to this same Instance-boxing behavior.
This path-dependent type changing behavior is now deprecated. Looking up Modules is also deprecated, instead, the user should cast them Instances (via `.toInstance`). It is also deprecated to mark user-defined types as `@instantiable`. Instead, users should define Lookupable for their types using the new Lookupable.product[1-5] factory methods. See the Chisel website for more details.
* Deprecate user-extension of trait Lookupable.
* Deprecate …
=> Refactor Lookupable

.github/workflows/release-notes.yml, .github/workflows/scala-cli-example.yml
These actions failed for v6.6.0, Github now requires explicit permissions to push to releases, see https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions.
- Squash
Also bump softprops/action-gh-release to v2.1.0.
=> Update CD permissions for uploading release artifacts

core/src/main/scala/chisel3/ModuleImpl.scala, docs/src/explanations/moduleprefix.md, src/test/scala/chiselTests/ModulePrefixSpec.scala
Labeling `No Release Notes` because the API this is modifying has not yet been released.
The slightly more concise `localPrefixAppliesToSelf` does not add value and may imply to users that it modifies more things than just `localModulePrefix`. So I decided to make it more verbose and clear.
- Squash
=> Rename localPrefixAppliesToSelf to localModulePrefixAppliesToSelf

core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala, core/src/main/scala/chisel3/internal/Builder.scala, docs/src/explanations/moduleprefix.md, src/test/scala/chiselTests/ModulePrefixSpec.scala
- Squash
* `withModulePrefix` now optionally takes a 2nd parameter `includeSeparator` (passing `false` will omit separator).
* Overriding `localModulePrefixUseSeparator` in a Module to false will omit separator for local prefix applied by overriding `localModulePrefix` in that Module.
=> Add APIs to omit module prefix separator

docs/src/explanations/interfaces-and-connections.md
=> The linked PDF at UCB is now behind a login wall. So dropping it.

core/src/main/scala/chisel3/experimental/SerializableModuleGenerator.scala, core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Do-apply pattern for Definition/Instance apply methods was removed
=> Remove do-apply pattern from Definition and Instance

core/src/main/scala/chisel3/ModuleImpl.scala, src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala, src/test/scala/chiselTests/ModulePrefixSpec.scala
- Bugfix
- Squash
Also fix logic for naming PseudoModules which should ignore the prefix.
=> Fix auto generated DedupGroups to be sensitive to module prefix

.github/workflows/install-filecheck/action.yml, .github/workflows/test.yml, SETUP.md, src/test/scala/chiselTests/ChiselEnum.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/DecoupledSpec.scala
Draft to see if the process works end-to-end
- Squash
=> Add FileCheck for unit testing

src/test/scala/chiselTests/LayerSpec.scala
Convert `chiselTests.LayerSpec` to use FileCheck.  This is much stricter testing as the ordering of matches is now guaranteed.
=> [test] Convert LayerSpec to use FileCheck, NFC

src/test/scala/chiselTests/LayerSpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
Add an integration test of SystemVerilog generation for inline layers. This relies on new support in firtool 1.97.0 which adds support for compiling this feature.  Previous versions of firtool could parse inline layers, but error when compiling them.
=> [test] Add Verilog test of inline emission, NFC

core/src/main/scala/chisel3/properties/Path.scala, src/test/scala/chiselTests/ToTargetSpec.scala
At the moment `toTarget` does not work properly with the D/I system, seeing that we cannot get the instanceName of a module when evaluating it, and even if we call `toTarget` in `atModuleBodyEnd` we will get the wrong circuit name since the definition of the module's parent is still in construction.
In order to construct `Path` properly, we need to defer the evaluation of `target` to the IR generation time in the `isMember` constructor, just as the other constructors already do.
- Bugfix
=> fix: evaluate target lazily in Path

src/test/scala/chiselTests/LayerSpec.scala
Change `LayerSpec` to use the new inline layer ABI.  This uses '$' as a delimiter instead of '_' in order to avoid ambiguity related to layer names which may contain '_'.
=> [test] Switch to new inline layer ABI

src/test/scala/chiselTests/LayerSpec.scala
Fix the tests again for the even newer inline layer ABI.  This includes the public module name (circuit name for now) and a "layer_" prefix.
=> [test] Update tests for newer inline layer ABI

src/main/scala-2/chisel3/util/circt/LTLIntrinsics.scala, src/test/scala/chiselTests/LTLSpec.scala
- Bugfix
Some nodes created by LTL properties had `suggestName` called on them, potentially leading to name collisions with user code.
=> Fix potential name collision caused by LTL properties

core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, src/main/scala-2/chisel3/simulator/EphemeralSimulator.scala, src/main/scala-2/chisel3/simulator/LayerControl.scala, src/main/scala-2/chisel3/simulator/Simulator.scala, src/main/scala-2/chisel3/simulator/package.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/aop/SelectSpec.scala, src/test/scala/chiselTests/experimental/TraceSpec.scala, src/test/scala/chiselTests/simulator/EphemeraSimulatorSpec.scala
Add support for ChiselSim to turn on inline layers.  This requires a different approach than how this worked for extract layers in order to continue to support the ability to "enable all" layers.  For extract layers, this was straightforward: all files which looked like layer files could be included.  However, for inline layers, to enable all layers requires knowledge of the layers that exist because Verilog preprocessor defines must be hand-crafted.
The first part of this patch adds support for layer ABIs.  After that, the `DesignAnnotation` is widened to include information about what layers were elaborated.  Finally, ChiselSim and svsim classes/functions are untangled to make it possible to add information to the compiler options after elaborating the circuit.
There are stubs in here …
=> [ChiselSim] Add Inline Layer Control

src/main/scala-2/chisel3/simulator/EphemeralSimulator.scala, src/main/scala-2/chisel3/simulator/LayerControl.scala, src/main/scala-2/chisel3/simulator/Simulator.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/simulator/LayerControlSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala
Provide initial work that better handles the problem of needing to filter
files in order to enable specific layers.  This adds a new member
function, `shouldIncludeFile` which returns a `PartialFunction` that is
defined only if the file being examined is a layer file (as defined in the
FIRRTL ABI for extract layers) and returns true if that layer file should
be included in order to enable the requested layers.
Change both ChiselSim and svsim to no longer use the `filter` function of
`LayerControl`.  Migrate both to use `shouldIncludeFile` partial function.
The latter is a much better API as it reserves the handling of files that
are outside the domain of the filter to ChiselSim and svsim.
Remove `LayerControl`'s filter as this is no longer load-bearing.
=> [ChiselSim][svsim] Switch to shouldIncludeFile

svsim/src/main/scala/Backend.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala, svsim/src/test/scala/BackendSpec.scala
Add an abstract function to `svsim.Backend` which can be used to control how define key and values will be escaped.  Add escaping for '$' for VCS only.
This is done to work around what I think is a difference in how VCS and Verilator handle the `+define+key=value` command line argument.  In svsim, we call both like the following (this is a key only, no value):
<tool> '+define+Foo$Bar'
While Verilator will accept this, VCS will not and instead wants:
<tool> '+define+Foo\$Bar'
As far as I can tell, the problem seems to be the single quotes not being respected by VCS.  This is _likely_ due to the fact that the VCS entrypoint is shell and may have some oddities in how it is handling command line options.  (This is speculation.)
I expect that this could have manifested for anything that was …
=> [svsim] Escape '$' in defines for VCS only

docs/src/explanations/layers.md
Add documentation for inline layers.  Additionally, greatly expand on everything in the layers documentation.
There are still holes in this explanation.  Notably, layer colored probes are not discussed nor is directory control.
=> [docs] Document inline layers

docs/src/explanations/layers.md
Add a section to the layer docs about layer coloring.  This covers both
layer-colored probes and wires as well as enabling layers for a module.
=> [docs] Document layer coloring

core/src/main/scala/chisel3/properties/Property.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
- Bugfix
- Squash
This technically breaks backwards compatibility for `firrtl.ir.StringPropertyLiteral` but `firrtl.ir` is considered an internal API.
=> Escape special characters in Property String literals

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
Fix a bug in BoringUtils where it could create input probes when tapping a probe.
Fixes #4576.
Fix a bug where `BoringUtils` methods could create input probes when tapping a probe type.
=> Fix BoringUtils input probe creation

lit/tests/Property/Good.sc, lit/tests/SmokeTest.sc, panamaconverter/src/PanamaCIRCTConverter.scala
Follow up the upstream PR llvm/circt#7734.
=> CIRCT converter: rename `portSyms` to `portSymbols`

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
FIRRTL spec version 4.1.0 was just released [[1]] with support for inline layers.  The non-spec things that Chisel is emitting requires bumping the version to 4.2.0.
[1]: https://github.com/chipsalliance/firrtl-spec/releases/tag/v4.1.0
Change emitted FIRRTL version from 4.1.0 to 4.2.0.
=> Bump FIRRTL version to 4.2.0

core/src/main/scala/chisel3/BitsImpl.scala, core/src/main/scala/chisel3/ChiselEnumImpl.scala, core/src/main/scala/chisel3/DataImpl.scala, core/src/main/scala/chisel3/MemImpl.scala, core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/When.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/properties/Class.scala, core/src/main/scala/chisel3/properties/Property.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/test/scala/chiselTests/WhenSpec.scala
I am making changes that are tripping scope issues and it was very annoying. I did this work to help myself so it probably belongs in upstream!
- Squash
* Errors are aggregated by default and all reported at the end whereas exceptions throw immediately. This allows users to fix multiple scope violations at the same time.
* `Printable.unpack` now takes an implicit `SourceInfo`
* `PropertyType.convertUnderlying` now takes an explicit `SourceInfo`
=> Error rather than throw on scope violations

core/src/main/scala-3/chisel3/probe/Probe.scala
The Probe.apply API is supposed to take a second argument of type `Layer`. However, this was incorrectly taking an argument of type `Option[Layer]`. Revert to the former.
=> [scala3] Fix Scala3 difference in Probe API

core/src/main/scala-3/chisel3/probe/Probe.scala, integration-tests/src/test/scala/chiselTest/QueueSpec.scala, src/main/scala/chisel3/util/Queue.scala
Add a method to the `Queue$` object that can be used to create a `Queue` and include a second queue that contains some data which will be tracked alongside the first `Queue`, but this will be kept in a layer.
This is added to help address a use case where design verification wants to track some extra, sidecar data that should be added to some data pipeline.  However, this sidecar data is expected to be removed from the design.  This would normally be addressed with a generator-time parameter. However, the generator-time parameter prevents removal of the sidecar data unless the design is re-elaborated.
E.g., below, this can be used to create a shadow queue outside the module which contains a queue. The shadow queue will operate in lockstep with the original queue:
``` scala
class Bar …
```
=> [util] Add a withShadowLayer Queue

core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
Note that simply using the "current ports" in Lookupable is totally fine. It's not possible to see BoringUtils introduced ports via `@public` so their visibility in the ports seen by Lookupable is irrelevant.
I waffled on if I think this should be legal or not. What eventually convinced me was the following: One of the main reasons `.toInstance` exists is to write generators that work with both normal `Modules` and with D/I `Instances`. What is the purpose of such parameterization in a generator? Obviously, this exists because the user may want to do things that only Modules can do (i.e., that don't work on Instances). One of the most common things in this category is boring, which you can do to Modules but obviously cannot do to Instances. Thus we should make sure it's allowed. I will …
=> Support boring on original Module after .toInstance call

docs/src/cookbooks/cookbook.md
=> [docs] Add Cookbook entry for Verilog case equality (IsX)

macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala, src/main/scala-2/chisel3/util/Mux.scala, src/main/scala-3/chisel3/util/Mux.scala, src/main/scala/chisel3/util/MuxImpl.scala, src/test/scala/chiselTests/OneHotMuxSpec.scala, src/test/scala/chiselTests/util/PriorityMuxSpec.scala
All I wanted to do was aggregate errors, but in for a penny, in for a pound.
- API Modification
- Squash
* This requires adding source locators to PriorityMux and Mux1H which requires SourceInfoTransform macros in Scala 2 and thus splitting the Scala 2 / Scala 3 public interfaces.
* Because macro applications do not support named arguments in Scala 2, this is an API change.
=> Aggregate PriorityMux and Mux1H Seq size errors

docs/src/developers/lit-test.md
=> update documentation for lit test

core/src/main/scala-3/chisel3/Aggregate.scala, core/src/main/scala-3/chisel3/Bits.scala, core/src/main/scala-3/chisel3/ChiselEnum.scala, core/src/main/scala-3/chisel3/Clock.scala, core/src/main/scala-3/chisel3/Data.scala, core/src/main/scala-3/chisel3/Disable.scala, core/src/main/scala-3/chisel3/Mem.scala, core/src/main/scala-3/chisel3/Mux.scala, core/src/main/scala-3/chisel3/Printf.scala, core/src/main/scala-3/chisel3/PrintfMacros.scala, core/src/main/scala-3/chisel3/VerificationStatementMacros.scala, core/src/main/scala-3/chisel3/probe/Probe.scala, core/src/main/scala-3/chisel3/probe/ProbeValue.scala, core/src/main/scala-3/chisel3/probe/package.scala, src/main/scala-3/chisel3/choice/ModuleChoice.scala, src/main/scala-3/chisel3/util/BitPat.scala, src/main/scala-3/chisel3/util/Bitwise.scala, src/main/scala-3/chisel3/util/Cat.scala, src/main/scala-3/chisel3/util/Mux.scala, src/main/scala-3/chisel3/util/Reg.scala
They are not needed and add unnecessary noise to public APIs.
- Squash
Only affects Scala 3 APIs which are not yet published
=> [scala3] Remove names from context parameters

core/src/main/scala/chisel3/FormalTest.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/RawModuleSpec.scala
The FIRRTL spec defines a `formal` construct to indicate that a module should be executed as a formal test. Currently, there is no way to emit this construct from Chisel.
This PR adds a user-facing `FormalTest` class that can be used to mark a module as to be executed as a formal test. This would commonly be used inside a test harness module to mark the surrounding module as a test. For example:
class TestHarness extends RawModule {
new FormalTest(this)
}
The formal test can be given an optional name and a map of parameters. The parameters are distinct from blackbox modules in that they do not map to Verilog parameters, but instead allow for any recursive nesting of integers, doubles, strings, arrays, and maps, as prescribed by the FIRRTL spec. Multiple formal test markers may be added to …
=> Add FormalTest marker

macros/package.mill
This fixes use of Scala Metals with Chisel.
- Squash
=> [mill] Guard scalaReflect under not Scala 3 in macros

core/src/main/scala/chisel3/Placeholder.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, src/main/scala-2/chisel3/aop/Select.scala, src/test/scala/chisel3/PlaceholderSpec.scala, src/test/scala/chisel3/SelectSpec.scala
Add an advanced Chisel API which allows for generation of hardware at a remembered point in the design.  This API allows a user to create an object of `class Placeholder` which, if used later via its `append` method, will create hardware at the location where the `Placeholder` object was created.
This is intended to be used to support certain generator patterns where hardware must be created _before_ some other hardware, but only after the other hardware has been built.  E.g., this can be used to support creating and defining layer-colored probes after constructing a layer block.
=> [core] Add Placeholder API

src/main/scala/chisel3/UnitTest.scala, src/main/scala/chisel3/UnitTestMain.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/UnitTestMainSpec.scala
Add the `UnitTest` trait as a marker for classes and objects that should be automatically discovered and constructed/executed as unit tests for hardware written in Chisel.
Also add a new `chisel3.UnitTests` main which discovers all unit tests in the classpath and generates the FIRRTL output for them. The discovery mechanism is roughly the same as implemented in ScalaTest, which scans the classpath for JAR files and directories and then tries to guess class names based on the encountered file structure. This feels pretty brittle, but has been working reliably for ScalaTest for a long time, so chances are this will work for Chisel too.
The utility offers a few options to list all available unit tests, or filter them according to inclusion or exclusion regular expressions. This allows unit …
=> Add UnitTest marker and test discovery utility

core/src/main/scala/chisel3/internal/Builder.scala
Remove some Builder methods which have no users.  These methods may be useful, however, they can be added back if necessary.
=> Remove unused Builder methods

svsim/src/main/scala/Workspace.scala
Avoid problems with VCS xprop (either xmerge or tmerge) when using svsim due to these features (seemingly) introducing spurious clock transitions when enabled.
The change introduced in ab7c417 changes the behavior of svsim such that the simulation body would run after all initial blocks.  Before this, the simulation body ran during the testbench's initial block which would race with other initial blocks.  However, after this change, VCS xprop simulations started failing.  As far as I can tell, this is due to xprop introducing a clock transition for the clock variable in the testbench after initial blocks, but before the simulation body.  This would then cause a number of assertions to evaluate and fail the simulation.
Fix this by initializing the variables used to drive inputs to the DUT …
=> [svsim] Initialize ports to zero

build.mill, integration-tests/package.mill
See docs: https://mill-build.org/mill/javalib/testing.html#_test_grouping
We could possibly do something more intelligent, but this speeds things up quite a bit on my MBP (~7.5 min to run `chisel[].test.test` vs. 15 min without this change), should speed up CI a bit too.
I tried using ScalaTest's parallelism (by overriding [def test](https://github.com/com-lihaoyi/mill/blob/07da626f5516b574586592f6083e872ead7d9752/scalalib/src/mill/scalalib/TestModule.scala#L70) passing `-P<nprocs>`) but it was slower.
I also tried `.grouped(1)` but that was much slower. `.grouped(8)` at least seems to speed things up a bit. It would be nice if the parallelism could be dynamically scheduled (the grouping is basically a static separating out tests to JVM forks so you really want to avoid putting all of the …
=> [ci] Speed up tests with testForkGrouping

core/src/main/scala/chisel3/ModuleImpl.scala
Change code for building a `Module` from using one-off state save/restore code to use new, common code for this.  This uses `Builder.State` methods which were developed for the `Placeholder` API, but were observed by @jackkoenig to be reusable here.
=> [internal] Use State.guard in ModuleImpl

src/main/scala-2/chisel3/simulator/DefaultSimulator.scala, src/test/scala/chiselTests/simulator/DefaultSimulatorSpec.scala
Add a new simulator, DefaultSimulator, to Chiselsim.  This fills a major, long-standing hole in this API by adding a simulator that does not delete all the files that it creates after a test runs.
This uses a type class, `HasTestingDirectory`, to allow for control over where the directory is created.  A default implementation is provided which uses a nanosecond resolution timestamp to differentiate the tests. E.g., example output from running the new test included in this commit multiple times is:
test_run_dir/
└── DefaultSimulator
├── 2025-02-05T16-58-02.175175
├── 2025-02-05T16-58-11.941263
└── 2025-02-05T16-58-17.721776
Note: a Scalatest-based type class implementation is intentionally _not_ provided as part of this PR.  This will be provided in a follow-on in such a way that Chiselsim …
=> [chiselsim] Add Default (non-Ephemeral) Simulator

.github/workflows/test.yml, circtpanamabinding/package.mill, panamaconverter/package.mill, panamalib/package.mill, panamaom/package.mill, plugin/package.mill
Reverts chipsalliance/chisel#4661
Breaks publishing CI so revert for now, @unlsycn and @sequencer to fix and re-PR.
=> Revert "Add publish flow for panama modules"

.gitignore, build.mill, build.sbt, release.mill, src/main/scala-2/chisel3/simulator/scalatest/WithTestingDirectory.scala, src/test/scala/chiselTests/simulator/scalatest/WithTestingDirectorySpec.scala
Add a trait, `WithTestingDirectory`, that will automatically create a test directory structure based on Scalatest information.  This provides a type class implementation of `HasTestingDirectory`, but with better Scalatest-specific directories as opposed to generic timestamp-based ones.
This necessarily introduces a provided ("compile only" to Mill) dependency on Scalatest for Chisel.  This prevents making all of Chisel pull in Scalatest and relies on the user to load it.
E.g., the included test will create the following directory structure:
```
build
└── WithTestingDirectorySpec
└── A-test-suite-mixing-in-WithTestingDirectory
├── should-generate-a-directory-structure-derived-from-the-suite-and-test-name
├── should-generate-another-directory,-too
├── should-handle-CJK-characters,-e.g.,-好猫咪 …
```
=> [Chiselsim] Add WithTestingDirectory

src/main/scala-2/chisel3/simulator/EphemeralSimulator.scala, src/main/scala-2/chisel3/simulator/HasTestingDirectory.scala
Context: I'm working towards developing a common simulator API. Part of the problem right now is that the `DefaultSimulator` and `EphemeralSimulator` are different enough that they can't be easily unified.
Unify the `DefaultSimulator` and `EphemeralSimulator` by rewriting the latter using the former. This is done by writing a new `HasTestingDirectory` type class implementation generator called `temporary` which will do all the work of what the `EphemeralSimulator` was previously doing.
- Add `chisel3.simulator.HasTestingDirectory.temporary` type class implementation generator for control of temporary directory creation (with optional auto-deletion).
=> [chiselsim] Rewrite EphemeralSimulator in terms of DefaultSimulator

src/main/scala-2/chisel3/simulator/DefaultSimulator.scala, src/main/scala-2/chisel3/simulator/HasTestingDirectory.scala, src/main/scala-2/chisel3/simulator/scalatest/WithTestingDirectory.scala, src/test/scala/chiselTests/simulator/DefaultSimulatorSpec.scala
Remove an argument from the `getDirectory` method of the `HasTestingDirectory` type class.  This was intended to capture the name of the class.  However, this didn't actually work.  Remove this as it is both: (1) not necessary as if users of this are likely using the Scalatest type class implementation which does support this and (2) it simplifies downstream methods as this doesn't need to be routed around.
This is changing a public method that was never in a release. Hence, there are no release notes.
=> [chiselsim] Remove test class name from directory

src/main/scala/chisel3/simulator/DefaultSimulator.scala, src/main/scala/chisel3/simulator/HasSimulator.scala, src/test/scala-2/chiselTests/simulator/DefaultSimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/HasSimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/WithTestingDirectorySpec.scala
Add a new type class, `HasSimulator`, which provides a method to get a
simulator.  Provide two implementations: one for Verilator and one for
VCS.  Additionally, provide a low-priority default that maps to Verilator.
This is working towards refactoring Chiselsim to improve the
customizability of its APIs while not dramatically changing how a user
interacts with it.  Additionally, this is trying to work towards providing
Scalatest-specific implementations of `HasSimulator` which allow the
simulator to be chosen on the command line.  Much of the code for this is
currently sequestered in either ChiselSpec (part of the tests which are
not published) or in internal code.
Refactor the Chiselsim's `DefaultSimulator` to no longer create an
instance of a private Verilator simulator class. …
=> [chiselsim] Add, use HasSimulator type class

firrtl/src/main/scala/firrtl/options/StageUtils.scala, src/main/scala/circt/stage/phases/CIRCT.scala
Factor out a utility for constructing distinctive messages from the CIRCT phase and into the firrtl package.  This was always the plan, however, I forgot about it for years.
This is being moved and made public so that I can use it when constructing Chiselsim error messages.
- Add `firrtl.options.StageUtils.dramaticMessage` utility for constructing distinctive error messages that do not print to stdout.
=> [firrtl] Add, use dramaticMessage

src/main/scala/chisel3/simulator/DefaultSimulator.scala, src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala
Add a new `SimulatorAPI` trait which provides methods for running
simulations.  This will submsume the existing `DefaultSimulator.simulate`
method and extends it with an "ABI" for how to startup simulations of
Chisel-generated Verilog.
This API includes two methods:
1. simulateRaw -- This is only usable with `RawModule`s where there is
no information about the clock and reset.  This is the same as
`DefaultSimulator.simulate`.
2. simulate -- This is only usable with `Module`s where there is a
defined clock and reset.  This is the method which implements an "ABI"
startup sequence which avoids problems with simulators, time zero
behavior, and race conditions.
Remove all methods from `DefaultSimulator` and replace them with methods
provided by the `SimulatorAPI`.  This is change to the …
=> [chiselsim] Add SimulatorAPI, reduce DefaultSimulator to nothing

src/main/scala/chisel3/simulator/package.scala, src/main/scala/chisel3/simulator/scalatest/package.scala
Add two flavors of APIs for working with `ChiselSim`. This provides both the "trait mix-in" pattern and the "wildcard object import" pattern.
- Add `ChiselSim` APIs. This as the main entry points to `ChiselSim` and should be used in favor of the `EphemeralSimulator`.
=> [chiselsim] Add ChiselSim APIs

core/src/main/scala/chisel3/ElaboratedCircuit.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, docs/src/cookbooks/hierarchy.md, docs/src/explanations/chisel-type-vs-scala-type.md, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala, src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala, src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala, src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala, src/main/scala/chisel3/stage/phases/Convert.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/chisel3/stage/phases/Emitter.scala, src/main/scala/chisel3/testers/TesterDriver.scala, src/main/scala/circt/stage/ChiselStage.scala, src/test/scala-2/chisel3/stage/ChiselOptionsViewSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala, src/test/scala-2/chiselTests/stage/phases/AddSerializationAnnotationsSpec.scala, src/test/scala-2/chiselTests/stage/phases/ElaborateSpec.scala, src/test/scala-2/circtTests/stage/ChiselStageSpec.scala
When I tried out https://github.com/chipsalliance/chisel/pull/4643 internally at SiFive, I realized that despite `chisel3.internal.firrtl.ir` being a package private object, `ir.Circuit` still leaks out via `ChiselCircuitAnnotation` and it can be used freely. This leaks full access to the Chisel internal IR in a way that makes it really hard to change things.
This is my attempt to "spackle" that leak by providing the new `ElaboratedCircuit` API as the intended public interface to give to users to let them do what they want to do, while letting us muck with the internals. I think we should feel free to add and deprecate then remove APIs from `ElaboratedCircuit` as long as we take care to keep the actual internals private.
Before merging this, I intend to test it internally and redo …
=> Add ElaboratedCircuit and deprecate use of internal ir Circuit

src/main/scala/chisel3/simulator/PeekPokeAPI.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/test/scala-2/chiselTests/simulator/DefaultSimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/EphemeralSimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala, svsim/src/test/scala/BackendSpec.scala
Fix longstanding problems in Chiselsim where the result of a failing simulation (e.g., an assertion firing) would result in an obtuse `UnexpectedEndOfMessages` assertion.  This then forces any Chiselsim user to catch this and then figure out what went wrong.  See the unpublished ChiselSpec for an example.
Fix this with an abstract method for the Backend that forces it to describe (via a RegEx) how to find interesting parts of the log file which indicate certain failures (the aforementioned assertion failures).  This then allows for the default simulate method to substitute a _better_ assertion where possible.
This is not as good as a more advanced alternative which actually hooks into the simulation to do something when an assertion fires.  However, this is a larger effort that requires …
=> [chiselsim] Improve error behavior

svsim/src/main/resources/simulation-driver.cpp, svsim/src/main/scala/Workspace.scala, svsim/src/test/resources/Finish.sv, svsim/src/test/scala/BackendSpec.scala, svsim/src/test/scala/Resources.scala
Fix a bug in how Verilator simulations work in svsim where the simulation would _not_ terminate when a `$finish` was called.  This seems to be a bug in Verilator where it will not terminate the simulation (as mandated by the Verilog spec) unless you are running with time delays.
Fixes #4700.
Fix an svsim bug, which could manifest in Chiselsim, where when a simulation calls `$finish` that it does not immediately exit for Verilator backends.
=> [svsim] End Verilator simulation on $finish

src/main/scala/chisel3/simulator/LayerControl.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/test/scala-2/chiselTests/ChiselSpec.scala, src/test/scala-2/chiselTests/simulator/LayerControlSpec.scala, src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala
Only compile what is needed for extract layers. Previously, all files would be compiled and the layer would be enabled using the ABI bind file. Change this to, for extract layers, only visit directories which the layer says it is writing to.
Note: this can cause problems if the user is using weird combinations of layer directory control and module-level control. However, if a user is doing this, they should know what they are doing and the limitations of the tooling.
Fixes #4676. Individual commits should be reviewed separately.
Stop compiling all extract layer collateral. Instead, only compile what is specified from those directories. This avoids a problem where LTL constructs (unsupported by Verilator) would cause compilation failure even though they would never be bound in.
=> [svsim][chiselsim] Do not compile extract layery directories

src/main/scala-2/chisel3/ltl/LTL.scala, src/main/scala-2/chisel3/util/circt/LTLIntrinsics.scala, src/test/scala-2/chiselTests/LTLSpec.scala
Add support for CIRCT's `circt_verif_require` and `circt_verif_ensure` intrinsics. These interact with the formal contracts implemented in CIRCT and translate to asserts or assumes depending on whether the contract is checked or applied. They lower to asserts if used outside of a contract.
Chisel itself has no support for contracts yet, such that these two additions behave like `AssertProperty` in practice. As soon as contracts are added to Chisel though, they can be used to formulate the pre- and post-conditions of those contracts.
=> Add RequireProperty and EnsureProperty

.github/workflows/test.yml
Add `-oF` to CI runs. I think I broke something with https://github.com/chipsalliance/chisel/commit/36e49577cfd46041cf70a82dbddfe7ccd10da1ae and am having difficulty debugging it.
I was originally only going to use this for testing. However, this would be useful to have generally on all CI runs.
=> [ci] Add -oF to tests

svsim/src/main/resources/simulation-driver.cpp, svsim/src/main/scala/Simulation.scala, svsim/src/main/scala/Workspace.scala, svsim/src/test/resources/Finish.sv, svsim/src/test/scala/BackendSpec.scala, svsim/src/test/scala/Resources.scala
Re-land #4702.
The commit to fix this looks like a brittle fix as it narrowly handles the observed exception. (See: https://github.com/chipsalliance/chisel/actions/runs/13418015449/job/37483578519#step:11:1377) However, I think this is actually correct. The details are in the commit message and copied below:
Fix an issue that can occur now that the simulation will aggressively try
to shut themselves down when they see a `$finish`.  The problem occurs
because svsim is assuming that it can check if the simulation process is
alive and then shut it down.  However, this occurs in a critical region.
Just because the process is alive when checked, doesn't mean it _will_ be
alive when you try to shut it down.
I considered an alternative solutoin here which would put the simulation
into a "finish" …
=> Re-land #4702

src/main/scala/chisel3/simulator/ChiselSettings.scala, src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Change SimulatorAPI methods to use the ChiselSettings class instead of
directly communicating layerControl.  This will enable us to lump together
more options that all are associated with Chisel/FIRRTL/the Verilog ABI.
Extend ChiselSettings with three macros which were currently being set by
ChiselRunners:
- ASSERT_VERBOSE_COND
- PRINTF_COND
- STOP_COND
Make this work in such a way that the user can specify a function that
will return the _signal_ that they want to use to set this macro in one of
several predefined ways.
This is working towards replacing this part of ChiselSpec: https://github.com/chipsalliance/chisel/blob/main/src/test/scala-2/chiselTests/ChiselSpec.scala#L60
- Add FIRRTL/Verilog ABI macro control to Chiselsim.
=> [chiselsim] Add FIRRTL macro control

src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/stimulus/RunUntilFinished.scala, src/main/scala/chisel3/simulator/stimulus/Stimulus.scala, src/test/scala-2/chiselTests/Assert.scala, src/test/scala-2/chiselTests/BoringUtilsSpec.scala, src/test/scala-2/chiselTests/ProbeSpec.scala
Add timeout exception and `runUntilFinished`. Use this to replace some usages of `ChiselSpec`.
This is stacked on #4699. This PR is intended to show where I am going with this and to get buy-in on how tests will look before rolling this out everywhere (to replace more widely used `ChiselSpec` methods like `assertTesterPasses` and `assertTesterFails`.
Add `Stimulus` object to `SimulatorAPI` which is intended to contain basic, common stimulus that should be applied to a circuit.  These can be chained together in series if desired. For now, only add `runUntilFinished` which is stimulus that runs for a number of cycles and then throws an exception if the simulation doesn't finish before the timeout.
=> [Chiselsim] Replace Chiselspec w/ ChiselSim

svsim/src/main/scala/Simulation.scala
Attempt to workaround an observed CI failure [1] where calling `exitValue` on a process throws an exception.  Require that `waitFor` is called after the process is destroyed so that it will block until it _is_ destroyed.
[1]: https://github.com/chipsalliance/chisel/actions/runs/13476120281/job/37655532844
Fix a possible `IllegalThreadStateException` that could be raised during `svsim.Simulation.run`.
=> [svsim] Wait after destroying simulator process

integration-tests/src/test/scala-2/chiselTest/MixedVecIntegrationSpec.scala, src/test/scala-2/chiselTests/ChiselSpec.scala
Migrate MixedVecIntegrationSpec from ChiselSpec to ChiselSim.
Factor out the Scalacheck / property utilities from `ChiselPropSpec` into
a separate trait.  As ChiselSpec is deprecated, this wil make it easier to
move things off of the `Chisel*Spec` abstract classes.
=> [test] Move MixedVecIntegrationSpec to ChiselSim

core/src/main/scala/chisel3/Annotation.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
Now depends on https://github.com/chipsalliance/chisel/pull/4717.
Because views may not map 1-1 to FIRRTL targets and that annotations are so heavily exposed to the user (esp. via Stage/Phase), we have to generate a RenameMap for any views that are annotated. Previously, we couldn't know what views might be annotated (the `.toTarget` call is after Chisel elaboration) so we had to conservatively generate a `RenameMap` for all views that don't map 1-1. This is **ludicriously** expensive.
With #4643, we now require that annotations report what Data will be annotated up front, so now we only need to rename views that are actually annotated. Much more elegant and efficient at the cost of a minor API change.
I guess technically we shouldn't merge this until the deprecated APIs are removed... 🙈 …
=> Selective view renaming

src/main/scala/chisel3/testers/BasicTester.scala, src/test/scala-2/chiselTests/TesterDriverSpec.scala
Fix what appears to be a longstanding bug where `BasicTester.finish` never did anything unless used with the `BackendCompilationUtilities` trait. This trait has been deprecated for four years before being made private.
I plan to deprecate and remove `BasicTester`, as it has no value over a straight `Module`. However, this is an intermediate step that is necessary to port its associated test to `ChiselSim`. (This test wasn't actually working before and would assert and finish on the same cycle without applying the body of the `finish`.)
Port the associated test to ChiselSim.
I'm breaking this out from the other porting effort as this may break something.
Fix a bug where the `BasicTester.finish` would never be called.
=> [testers] Fix BasicTester `finish`, port to ChiselSim

svsim/src/main/resources/simulation-driver.cpp, svsim/src/main/scala/Workspace.scala
Fix an incorrect function signatures for the VCS implementation of `run_simulation`.  This is a task which has inputs and outputs.  This needs to be declared as having an `int *` argument for the output in C and have the input/outputs declared in Verilog.
This should fix an internal error when bumping Chisel w/ VCS-based tests (I haven't tested this, though. 😬)
=> [svsim] Fix VCS run_simulation function

src/test/scala-2/examples/VendingMachineGenerator.scala
Fix an out-of-bounds vector access that was possible in the vending machine example.  This would cause the vending machine example to fail whenever there was a "vend" on the last cycle.  I'm not sure _why_ this was working before as this bug seems like it was always possible to hit.
This fixes the broken `main` branch. 🥲
=> [test] Fix Vending Machine check

src/test/scala-2/chisel3/internal/NameCollisionSpec.scala, src/test/scala-2/chiselTests/AnalogSpec.scala, src/test/scala-2/chiselTests/AutoClonetypeSpec.scala, src/test/scala-2/chiselTests/BundleSpec.scala, src/test/scala-2/chiselTests/ChiselSpec.scala, src/test/scala-2/chiselTests/Direction.scala, src/test/scala-2/chiselTests/IOCompatibility.scala, src/test/scala-2/chiselTests/IllegalRefSpec.scala, src/test/scala-2/chiselTests/InvalidateAPISpec.scala, src/test/scala-2/chiselTests/MixedVecSpec.scala, src/test/scala-2/chiselTests/ModuleSpec.scala, src/test/scala-2/chiselTests/PrintableSpec.scala, src/test/scala-2/chiselTests/RebindingSpec.scala, src/test/scala-2/chiselTests/ResetSpec.scala, src/test/scala-2/chiselTests/SwitchSpec.scala, src/test/scala-2/chiselTests/ToTargetSpec.scala, src/test/scala-2/chiselTests/TypeAliasSpec.scala, src/test/scala-2/chiselTests/Vec.scala, src/test/scala-2/chiselTests/VecToTargetSpec.scala, src/test/scala-2/chiselTests/WarningSpec.scala, src/test/scala-2/chiselTests/experimental/OpaqueTypeSpec.scala, src/test/scala-2/chiselTests/experimental/ProgrammaticPortsSpec.scala
Remove `ExitException` and `extractCause` utilities. This hits a lot of tests and I want to bounce it off CI.
=> [test] Batched cleanups

src/test/scala-2/chiselTests/ChiselSpec.scala, src/test/scala-2/chiselTests/experimental/DataViewTargetSpec.scala, src/test/scala-2/chiselTests/experimental/ExtensionMethods.scala, src/test/scala-2/chiselTests/experimental/ModuleDataProductSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/DefinitionSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/Utils.scala
Move the last method provided by `ChiselRunners` into an extension method scoped to the testing package that needs it. Delete `ChiselRunners` after that.
=> [test] Delete ChiselRunners

src/test/scala-2/chiselTests/ChiselSpec.scala, src/test/scala-2/chiselTests/PortSpec.scala
Delete ChiselFreeSpec. Refactor PortsSpec to use AnyFlatSpec and FileCheck. This exposed a problem with what the test was checking, so I am opting to lock in the existing behavior.
=> [test] Delete ChiselFreeSpec

src/main/scala/chisel3/testers/BasicTester.scala, src/main/scala/chisel3/testers/TesterDriver.scala, src/test/scala-2/chiselTests/TesterDriverSpec.scala
Deprecate `BasicTester` and `TesterDriver`.  These have been fully replaced with ChiselSim.
Deprecate `chisel3.testers.{BasicTester, TesterDriver}`. The former can be replaced with a `Module`. If you are relying on the latter, please switch to ChiselSim.
=> [testers] Deprecate everything the testers package

src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/HasSimulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/main/scala/chisel3/simulator/scalatest/package.scala, src/main/scala/chisel3/testing/HasTestingDirectory.scala, src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala, src/test/scala-2/chiselTests/simulator/DefaultSimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/HasSimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/TestingDirectorySpec.scala, src/test/scala-2/chiselTests/testing/scalatest/TestingDirectorySpec.scala
Create a new package, `chisel3.testing`, and move
`simulator.HasTestingDirectory` and the scalatest implementation of it to the new package.  This is done because the ability to get a testing directory is really a general property of "testing" and not "simulation".
This also builds towards moving the FileCheck utility out of `ChiselSpec` (i.e., only being available for tests) and into a proper home in `testing`.  It also makes sense for FileCheck to use the `HasTestingDirectory` type class as it has the same problem of needing to be given a "testing directory".
=> [testing] Testing package w/ HasTestingDirectory

src/main/scala/chisel3/testing/FileCheck.scala, src/main/scala/chisel3/testing/scalatest/package.scala, src/test/scala-2/chiselTests/testing/FileCheckSpec.scala
Add an extension-method based FileCheck API.  This builds off of @jackkoenig's original FileCheck trait inside ChiselSpec and repackages it for publishing.
This makes a number of deviations from the original version:
1. This opts for extension methods.
2. This does not add helpers for running Chisel.
3. This throws dedicated assertions on failures.
Taking (1) and (2) together, this is intended to _not_ duplicate methods which are already availble via ChiselStage.  Specifically, I am intending the API to be used like:
ChiselStage.emitSystemVerilgo(new Foo).fileCheck()("CHECK: module Foo")
Things are done this way to try to make the APIs as orthogonal as possible without too many redundant ways to accomplish the same thing.
(3): is added for convenience of testing.  On failure, this …
=> [testing] Add FileCheck API

core/src/main/scala/chisel3/internal/Builder.scala, firrtl/src/test/scala/firrtl/testutils/FirrtlSpec.scala, firrtl/src/test/scala/firrtlTests/StringSpec.scala, firrtl/src/test/scala/firrtlTests/options/phases/GetIncludesSpec.scala, src/test/scala-2/chiselTests/InvalidateAPISpec.scala, src/test/scala-2/chiselTests/experimental/TraceSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
This is prerequisite work for deprecating and removing `BackendCompilationUtilities`. The only real usages of this are related to getting a test directory. This is fully replaced with the `HasTestingDirectory` type class and its Scalatest-integrated implementation `chisel3.testing.scalatest.TestingDirectory`.
=> [test] Remove usages of BackendCompilationUtilities

firrtl/src/main/scala/firrtl/FileUtils.scala, firrtl/src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala, firrtl/src/main/scala/firrtl/util/BackendCompilationUtilities.scala, firrtl/src/test/scala/firrtlTests/FileUtilsSpec.scala, src/test/scala-2/chiselTests/Harness.scala
Mass deprecation of APIs that we would like to delete in Chisel 7.
- Deprecate `FileUtils`
- Deprecate `BlackBoxResourceFileNameAnno`
- Deprecate `BlackBoxSourceHelper`
- Deprecate `BackendCompilationUtilities`
=> Mass deprecations, to be removed in Chisel 7

docs/src/appendix/migrating-from-chiseltest.md, docs/src/explanations/testing.md
Add an explanation about testing in Chisel.  This discusses both the modern ChiselSim APIs and FileCheck APIs.  Both are discussed as they represent complementary testing strategies for users.
As the formal and inlinen testing comes online, this documentation is expected to be enhanced to include those.
FYI: @fabianschuiki, @tmckay-sifive
=> [docs] Add ChiselSim, FileCheck documentation

src/test/scala-2/chiselTests/WidthSpec.scala
Avoid dumping FIRRTL to see if this will help with #4761.
=> [test] Don't dump FIRRTL in WidthSpec method

core/src/main/scala/chisel3/ElaboratedCircuit.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/main/scala/circt/stage/phases/CIRCT.scala, src/test/scala-2/chiselTests/BlackBox.scala, src/test/scala-2/chiselTests/Direction.scala, src/test/scala-2/chiselTests/InstanceNameSpec.scala, src/test/scala-2/chiselTests/LiteralToTargetSpec.scala, src/test/scala-2/chiselTests/Mem.scala, src/test/scala-2/chiselTests/WhenSpec.scala
Future work TODO:
- Squash
This reduces peak memory use when serializing to `.fir`. It heavily depends on the design, but for designs with a single very large module, we have measured 20-25% reductions in peak memory use. For most cases, the reduction will likely be more modest.
=> Add Serializer for ChiselIR

core/src/main/scala/chisel3/package.scala, macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Fixes https://github.com/chipsalliance/chisel/issues/4733
Unfortunately, this is really hard to write a unit test for, but I did manually check it works (and it's using the same approach as we have been using for `.U` and `.S`). I'm also not sure that this is the _best_ fix for 4733, but it works.
FYI @tymcauley 
- Squash
The user probably forgot .W. Apply the same technique as used for .U|.S.
=> Warn on <literal>.asUInt|.asSInt(_: Int)

core/src/main/scala-2/chisel3/FormalContractIntf.scala, core/src/main/scala-3/chisel3/FormalContractIntf.scala, core/src/main/scala/chisel3/FormalContract.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, src/test/scala/chiselTests/FormalContractSpec.scala
Add the `Contract` API which allows users to express the pre and post-conditions of a piece of hardware. These can be used during formal verification to prove that the hardware upholds the conditions laid out in the contract. Additionally, contracts may be used to implement a divide-and-conquer strategy to simplify larger proofs since they act like a cutpoint and an assume-guarantee substitution.
=> Add formal contracts

svsim/src/main/resources/simulation-driver.cpp
Minor cleanup of simulation-driver.cpp:
1. Move all global mutable state into a single static struct.
2. Mark everything that is only used internally to the module as `static`.
I'm not crazy about the solution of (1). However, the order of calls necessitates something like this. What is going on:
1. `main` runs and sets up global mutable state.
2. `main` calls `simulation_main`.
3. `simulation_main` runs, dropping into Verilog.
4. Verilog calls `simulation_body` via DPI.
5. `simulation_body` needs access to things created by (1).
I'd much rather have a way to _not_ have global mutable state.
This is stacked on #4765.
=> [svsim] Cleanup simulation-driver.cpp

src/main/scala/chisel3/testing/HasTestingDirectory.scala, src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala, src/test/scala-2/chiselTests/testing/scalatest/TestingDirectorySpec.scala
Change the default directory that `HasTestingDirectory` uses from
`test_run_dir/chiselsim` to `build/chiselsim`.  Generally, `test_run_dir/`
is an older style and `build/` is both newer (for Chisel) and more
standard (generally).
Change the return type of the abstract method `buildDir` to be `Path`
instead of `String`.  This is better as it avoids problems with separators
which could plague Windows users.
Change the directory that Scalatest tests use from being rooted at
`build/` to being rooted at `build/chiselsim/`.  The former can have a lot
of contention with many output files and it would be better to add this
additional level.  Also, this aligns this with the new default behavior of
the non-Scalatest WithTestingDirectory.
This does not need to get release notes as these APIs have …
=> [testing] Cleanup default and Scalatest directory structure

src/main/scala/chisel3/simulator/scalatest/package.scala, src/main/scala/chisel3/testing/scalatest/HasConfigMap.scala, src/test/scala-2/chiselTests/testing/scalatest/HasConfigMapSpec.scala
This is three commits that should be reviewed independently.  This builds towards and then adds a `HasConfigMap` trait which allows for `-D<key>=<value>` options to be exposed to `chisel3.simulator.scalatest.ChiselTest`. In order to do this, and without starting to add functionality directly to `ChiselSim`, the existing `TestingDirectory` trait is refactored to be made stackable.
Add the ability for users to pass command-line options, via `-D<key>=<value>`, to any `chisel3.simulator.scalatest.ChiselTest` test for them to customize the execution of the test.
=> [chiselsim] Allow command line options to be passed to ChiselSim tests

src/main/scala/chisel3/testing/scalatest/HasClilSimulator.scala
Add a new trait, `HasCliSimulator`, that builds on `HasConfigMap` to provide a standardized way to get a simulator that the user can choose at scalatest test time via a `-Dsimulator=<simulator-name>` argument.
Note: this is difficult to test, however, I've tested it manually.
CC: @andrew-gouldey-sifive: I'm planning to get this into the open source and then use it internally. We will customize the simulator used internally slightly for the different Verilator or VCS default options that we use.
Add `HasCliSimulator` which can be used, along with `HasConfigMap`, to allow for tests to choose their simulator at test time via a `-D` command line option. This is added to avoid fragmentation of command line options around choosing which simulator to run.
=> [scalatest] Add HasCliSimulator

core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
- Bugfix
Fix multiple instantiation of imported Definitions.
=> Fix extmodule emission when instantiating an imported Definition multiple times

core/src/main/scala/chisel3/AggregateImpl.scala, core/src/main/scala/chisel3/BitsImpl.scala, core/src/main/scala/chisel3/ChiselEnumImpl.scala, core/src/main/scala/chisel3/ClockImpl.scala, core/src/main/scala/chisel3/DataImpl.scala, core/src/main/scala/chisel3/experimental/Analog.scala, core/src/main/scala/chisel3/properties/Property.scala, src/test/scala-2/chiselTests/RecordSpec.scala
@tymcauley this should work for https://github.com/ucb-bar/fixedpoint/pull/11. I tried it out and it seemed to work, but there are new compile errors to resolve due to the removal of `BasicTester`. I'll comment on that PR with an example of how to fix
- Squash
This enables external libraries like FixedPoint to override it. This is not an ideal API, but it works until we have a better way to do this.
=> Change Data._fromUInt to protected

src/main/scala/chisel3/simulator/ControlAPI.scala, src/main/scala/chisel3/simulator/package.scala, src/main/scala/chisel3/simulator/scalatest/package.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Add a missing ChiselSim ControlAPI.  This currently only includes APIs to
enable and disalbe waveforms.  This API was previously inaccessible
because you would need to get at an svsim Controller to use it.
Note: the enable/disable waveform APIs will have no effect unless the
simulator is compiled with waveform support.
Add `ControlAPI` to ChiselSim. This adds `enableWaves` and `disableWaves` functions. These functions _require_ compiling a simulator with waveform support.
=> [chiselsim] Add ControlAPI w/ Waveform Enable/Disable Support

src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/main/scala/chisel3/simulator/stimulus/ResetProcedure.scala
Factor the reset initialization procedure out of `SimulatorAPI.simulate` and into a separate, re-usable stimulus.
Add `stimulus.ResetProcedure` that encapsulates a simple circuit initialization procedure. This is customizable for non-`Module`s by specifying a clock and reset.
=> [ChiselSim] Factor reset procedure out of SimulatorAPI and into stimulus

core/src/main/scala/chisel3/internal/firrtl/IR.scala, src/test/scala-2/chiselTests/SIntOps.scala
Found by @tymcauley https://github.com/ucb-bar/fixedpoint/pull/11#issuecomment-2715634001
This bug was introduced 2 years ago when we added support for zero-width literals: https://github.com/chipsalliance/chisel/pull/2932
The problem is that `BigInt.bitlength` excludes the sign bit, so we need to add 1 to it for SInts (which is what we originally did), BUT we need special case support for zero-width SInts (only when specified).
- Bugfix
- Squash
For users attempting to reinterpret raw 2s complement values as SInts, use `.U.asSInt`.
=> Fix SInt literals to reject too small of widths

src/main/scala/chisel3/simulator/HasSimulator.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/test/scala/BackendSpec.scala
Fix the logic for grabbing environment variables for the replay Makefile when running VCS tests.  The VCS manual says that you grab the Synopsys-specific license file (SNPSLMD_LICENSE_FILE) first and only use the generic license file (LM_LICENSE_FILE) if that fails.  The existing code was wrong in that it only grabbed the latter.  There is no requirement that the latter is available and that is only a fallback if the former doesn't exist.
Also, add some lightweight infrastructure to cleanup the representation of VCS license files.
I tested this internally and all the tests passed.  (I had to change the test to queue for licenses, though...)
Fixes #4785.
CC: @tymcauley 
In svsim, use Synopsys-specific license if available. Otherwise, fallback to the default, generic license file. This is …
=> [svsim] Use SNPS-specific license in VCS

svsim/src/main/scala/vcs/Backend.scala, svsim/src/test/scala/BackendSpec.scala
Add VCS backend options to enable coverage collection.  The options for this are taken directly from our internal flow.  I don't think that all these options need to be turned on (e.g., @girishpai indicated that `USE_UNR_ONLY_CONSTRAINTS` isn't load bearing).  However, I'd rather migrate things wholesale and then refactor later.
This includes a very simple test that a coverage database directory is created.  This database is not created if coverage is turned off.
CC: @andrew-gouldey-sifive
Add options to svsim VCS backend to allow for coverage collection.
=> [svsim] Add coverage collection to VCS backend

src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/main/scala/chisel3/simulator/package.scala, src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
Modify ChiselSim simulate methods to allow for Chsiel and firtool options to be passed to the `simulate` methods.  This is done to allow for things like `--throw-on-first-error` to be passed.
For more context, we have a number of CLI options internally for working around the fact that ChiselSim doesn't support passing the Chisel/firtool compilation options to ChiselStage.  This seems wrong to me as I want to have the SimulatorAPI methods be richer externsions of what you can do with ChiselStage.  Ergo, because ChiselStage can control Chisel and firtool options, so should the SimulatorAPI.
The only slightly sharp edge here is that certain Chisel options may be illegal.  The Simulator APIs are already going to compile your module to SystemVerilog.  If you were to try to use `--target …
=> [chiselsim] Chisel/firtool Options on SimulatorAPI

.github/workflows/build-scala-cli-example.yml, .github/workflows/cd-circt.yml, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/enable-bincompat-checking.yml, .github/workflows/release-notes.yml, .github/workflows/scala-cli-example.yml, .github/workflows/test.yml
Try not to be too paranoid, but in light of the recent compromise of a popular action `tj-actions/changed-files` [[1]](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised) (that we weren't using, but still). It's probably best to pin to specific commits of Actions. I think leaving the core Github Actions alone is _okay_ because if Github is compromised then we are toast anyway, and I expect them to have better security as an organization--but I am open to imposing the same policy on those actions as well.
- Squash
=> Use commit hashes for actions not owned by Github

src/main/scala/chisel3/simulator/ChiselSettings.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala, svsim/src/test/resources/PlusArg.sv, svsim/src/test/scala/BackendSpec.scala, svsim/src/test/scala/Resources.scala
Add the ability to set `$value$plusarg` and `$test$plusargs` directly from
ChiselSim simulate APIs.  These can be specified using the lower level
options to the simulator or via the implicit common/backend-specific
options.  However, this new API is the intended way that these should be
set by the user going forward.
Add the ability to pass plusargs to svsim simulations.
Note: there is some ugliness here in that simulation options are passed to functions that are doing "compilation".  This is a software architecture problem in svsim as evidenced by backend compilation options including runtime options (for VCS).  This all needs to be cleaned up separately.
Add support for Verilog `$value$plusargs` and `$test$plusargs` to svsim and ChiselSim.
=> [svsim][chiselsim] Add plusarg support

src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala, svsim/src/main/scala/Backend.scala
Change the existing VCD waveform CLI API to _also_ enable waves. There was enough infrastructure there to do this and this is actually a way better API.
Add FSDB and VPD CLI emission. These require VCS and will throw an `IllegalArgumentException` if you try to use them with Verilator.
- Add ChiselSim traits which can be used to add Scalatest CLI support for compiling in FSDB and VPD waveform support into a test.
- Modify existing Scalatest CLI traits to both compile _and enable_ waves. These can be accessed with `-DemitVcd=1`, `-DemitVpd=1`, and `-DemitFsdb=1`.
=> [chiselsim] Add CLI FSDB, VPD support, enable waves (VCD, too)

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/SeqUtils.scala, core/src/main/scala/chisel3/internal/plugin/package.scala, core/src/main/scala/chisel3/package.scala, docs/src/explanations/naming.md, plugin/src/main/scala-2/chisel3/internal/plugin/ChiselComponent.scala, src/main/scala-2/chisel3/util/SRAM.scala, src/test/scala-2/chiselTests/naming/NamePluginSpec.scala
`chisel3.internal.plugin.autoNameRecursively` has always felt like a bit of a mouthful to me, especially in stack traces as it is _everywhere_ since it is inserted by the naming plugin. So in celebration of Chisel 7.0, I think it's time to simply the name to just `chisel3.withName`. This API also is pretty reasonable for users to go ahead and use, and I suspect in the near future we should start encouraging (or requiring?) it over `.suggestName`--but that is potentially more controversial so I'll leave that to a future PR (that will also need docs).
I've left `chisel3.internal.plugin.autoNameRecursively` around but deprecated so that people won't get weird linkage errors if they use an older version of the plugin--but they will get lots of deprecation warnings which should encourage them …
=> Replace autoNameRecursively with chisel3.withName

src/main/scala/chisel3/testing/HasTestingDirectory.scala, src/test/scala-2/chiselTests/testing/HasTestingDirectorySpec.scala
Fix a bug in the timestamp and temporary implementations of the `HasTestingDirectory` type class.  These need to, for a given type class implementation, always return the same date/time used when constructing a temporary directory.
This fixes a bug if a user is trying to get the current directory, e.g., via an `implicitly[HasTestingDirectory]` call.
Fix a bug in timestamp and default `HasTestingDirectory` type class implementations where this could return a different directory every time.
=> [testing] Fix testing dir date/time stability

src/main/scala/chisel3/simulator/ChiselSettings.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Add an option to ChiselSim settings to enable waves at time zero.  While this is now the _fourth_ way that this can be done (enableWaves, svsim.CommonCompilationSettings, and via modifications type classes to CommonCompilationSettings/via the CLI), this is useful/necessary to have a place that waves can be turned on from inside a test that still works with the `simulate` API and its reset procedure.
Add `enableWavesAtTimeZero` to ChiselSim settings.  This allows for turning on waves at time zero if you don't have full control over the stimulus, e.g., when using `SimulatorAPI.simulate` which applies a reset procedure.
=> [chiselsim] Add waves at time zero to settings

src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/Settings.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Rename the main settings class for configuring ChiselSim from "ChiselSettings" to "Settings".  The latter was somewhat confusing as these are really "simulator" settings.  Keep this terse because this is already prefixed with an appropriate package (`chisel3.simulator`).
This has never been in a release so this does not have release notes.
=> [chiselsim] Rename ChiselSettings to Settings

core/src/main/scala-2/chisel3/MemIntf.scala, core/src/main/scala-3/chisel3/MemIntf.scala, core/src/main/scala/chisel3/Mem.scala, src/main/scala-2/chisel3/util/SRAM.scala
Hard to test for this but easy to validate which I did.
- Squash
The old error was `Cannot prove that chisel3.UInt <:< chisel3.Vec[_]`, the new error is `Masked write requires that the data type is a Vec, got chisel3.UInt`.
=> Provide custom error for Mem masked write wrong data type

src/main/scala/chisel3/simulator/scalatest/package.scala
Add the `HasCliOptions` and `Cli.EmitVcd` traits to the Scalatest ChiselSim trait. This provides a saner default for end users:
1. Command line options are not allowed to sneak in through Scalatest's ConfigMap and must go through normal option parsing paths.
2. The default ChiselSim environment will always have `-DemitVcd=true` as an available option.
- Change the `scalatest.ChiselSim` trait to require that any command line options are passed using the `addOption` method. Users will no longer be able to use Scalatest's ConfigMap directly. This is done for safety reasons. If users would like different behavior, they can construct their own `ChiselSim` trait from the traits they would prefer.
- Add `-DemitVcd=true` option to `scalatest.ChiselSim`. Users can now run any simulation and turn …
=> [chiselsim] HasCliOptions, EmitVcd for ChiselSim

src/main/scala/chisel3/simulator/OptionsModifications.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/main/scala/chisel3/simulator/scalatest/Cli.scala, src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Add more type classes that can be used to modify the Chisel and `firtool` options of ChiselSim's `SimulatorAPI` methods.
While the number of type classes here is getting comical, these are being added to fill two remaining gaps.  We need the ability to control, via command line arguments, certain options.  With Scalatest, the only way to do this is via `-D` options.  However, the way to use `-D` options is via the `HasCliOptions` API which is implemented via this type class pattern.
Provide infrastructure for allowing modifications to Chisel and `firtool` command line arguments when running ChiselSim tests, e.g., via the Scalatest command line.
=> [chiselsim] Chisel/firtool update type classes

svsim/src/main/scala/vcs/Backend.scala
Add some missing compile and simulation time options for the VCS backend.
Add support for `-cm_dir` and `-cm_name` to svsim VCS backend.
=> [svsim] Add Coverage Directory and Name to VCS Backend

src/main/scala/chisel3/simulator/EphemeralSimulator.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Rename the parameter to some functions from "chiselSettings" to "settings".  The type of the parameter had already been changed, but not the parameter name.
Change the `chiselSettings` parameter of some ChiselSim functions to be called `settings`.
=> [chiselsim] Change chiselSettings to settings

build.mill
This probably improves performance, but the main reason I want to do it is to make user-code stacktraces a lot less miserable.
Consider the following:
```scala
class Child extends Module {
val foo, bar = IO(Input(UInt(8.W)))
val out = IO(Output(UInt(8.W)))
out := foo + bar
???
}
class Foo extends Module {
val foo, bar = IO(Input(UInt(8.W)))
val out = IO(Output(UInt(8.W)))
val c = Module(new Child)
c.foo := foo
c.bar := bar
out := c.out
}
```
If I build this with head of main, the stack trace I get is:
```
Exception in thread "main" scala.NotImplementedError: an implementation is missing
at ... ()
at Child.$anonfun$out$2(chisel-example.scala:16)
at chisel3.experimental.prefix$.apply(prefix.scala:50)
at Child.$anonfun$out$1(chisel-example.scala:13)
at …
```
=> Enable inlining in Scalac options

src/main/scala/chisel3/simulator/SimulatorAPI.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Add a subdirectory parameter to `simulate` and `simulateRaw` methods. This is intended for a bit of a corner case where a user wants to run simulate multiple times within a single test or they want to customize the test directory based on Cli arguments.
Add `subdirectory` parameters to ChiselSim `simulate` and `simulateRaw` APIs. These complement the existing `HasTestingDirectory.withSubdirectory` API which is slightly cumbersome to use in Scala 2 due to implicit resolution rules.
=> [chiselsim] Add subdirectory to SimulatorAPI fns

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, docs/src/cookbooks/hierarchy.md, docs/src/explanations/chisel-type-vs-scala-type.md, integration-tests/src/test/scala-2/chiselTest/util/SparseVecSpec.scala, src/main/scala/circt/stage/ChiselStage.scala, src/test/scala-2/chisel3/experimental/dataview/ReifySpec.scala, src/test/scala-2/chiselTests/CloneModuleSpec.scala, src/test/scala-2/chiselTests/DataEqualitySpec.scala, src/test/scala-2/chiselTests/LayerSpec.scala, src/test/scala-2/chiselTests/ReadOnlySpec.scala, src/test/scala-2/chiselTests/experimental/ExtensionMethods.scala, src/test/scala-2/chiselTests/experimental/hierarchy/DefinitionSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/InstantiateSpec.scala, src/test/scala-2/circtTests/stage/ChiselStageSpec.scala
I would like for the Convert phase to stop converting the IR (it will then only convert annotations) so that standard ChiselStage APIs will stop converting the IR. To do this though, I first need to be able to remove `ChiselStage.convert` which I will deprecate in 6.8.0 and remove on main.
- Squash
Also add `name` to `Definition[BaseModule]`.
=> Deprecate ChiselStage.convert, replace with elaborate

src/main/scala/chisel3/simulator/stimulus/RunUntilFinished.scala, src/main/scala/chisel3/simulator/stimulus/RunUntilSuccess.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Add new stimulus, `RunUntilSuccess`, which can be used to run a simulation until a user-specified "success" port asserts.  This is added as a complementary testing approach to `RunUntilFinished` whish is needed for some environments where the test harness cannot terminate on its own or the test harness is re-used in a separate, non-ChiselSim testing context where it cannot terminate on its own.
Add `RunUntilSuccess` stimulus for ChiselSim. This works like `RunUntilFinished` except that it is checking for a user-specified "success" port to assert.
=> [chiselsim] Add RunUntilSuccess stimulus

core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, core/src/main/scala/chisel3/package.scala, docs/src/explanations/printing.md, src/test/scala-2/chiselTests/PrintableSpec.scala, src/test/scala-2/chiselTests/Printf.scala
Despite the firrtl spec not mentioning `%m`, it is passed through to Verilog by firtool so #yolo.
- Squash
=> Add support for printing hierarchical names in Verilog (%m)

core/src/main/scala-2/chisel3/BitsIntf.scala, core/src/main/scala-3/chisel3/BitsIntf.scala
Fixing a ScalaDoc inconsistency noted on Element.
Note that unary operators are only allowed to be single characters, `-`, `!`, `~` and `+`, so `unary_-%` has always been invalid to call as a unary operator, you have to call it as `myUInt.unary_-%` which is just pointless and silly.
- Squash
Deprecate invalid unary operator unary_-%.
=> Fix UInt unary negation ScalaDoc

src/main/scala/chisel3/simulator/Randomization.scala, src/main/scala/chisel3/simulator/Settings.scala, src/test/scala-2/chiselTests/RecordSpec.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Add the ability to control the existing FIRRTL randomization settings via an additional parameter to `chisel3.simulator.Settings`.  Set the default behavior for this to always randomize.  This is a reasonable default for Verilator or any other 2-state simulator.  For 4-state simulators, users may want to deviate and use the provided `uniniitialized` randomization.
This commit intentionally does not try to struggle with setting per-simulator settings that are different from each other.  While I think this could make sense (you would like to use randomization for Verilator and uninitialized w/ x-prop for VCS), I think that the logic necessary to handling this is going to be too opaque for most users.  I would rather keep this as a single setting on simulate and any simulator you use will …
=> [chiselsim] Add randomization to settings

core/src/main/scala/chisel3/internal/Builder.scala, src/test/scala-2/chiselTests/LayerSpec.scala
Fix a bug where use of the `layer.enable` API would incorrect cause a propagation of layers being enabled to all subsequent modules.  This was due to a bug in how the state save/restore logic worked.
Fixes #4839.
Fix a bug where `layer.enable` would apply to all later modules.
=> Fix layer.enable applying to all later modules

svsim/src/main/resources/simulation-driver.cpp, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/vcs/Backend.scala
For the internal installation of VCS and RHEL, our simulations do not work due to VCS' save/restore functionality which will launch a simulation, detect if ASLR is present, and then kill the simulation and relaunch it with ASLR disabled.  The workaround employed here has been empirically shown to be problematic for at least one user (#4837).  Drop the ASLR workaround and add the runtime option `-no_save` which turns off VCS save/restore functionality.  svsim doesn't support this and it's ill advised to use non-standard workarounds.
Fix problems for some users when using svsim with VCS where a simulation would fail to start due to non-standard ASLR workarounds employed. Change svsim to run VCS simulations with the `-no_save` option to avoid VCS simulation relaunches on machines with ASLR …
=> [svsim] Use -no_save instead of ASLR workarounds

src/test/scala-2/chiselTests/RecordSpec.scala
Revert a small change in dd04d997d which was done to workaround CIRCT producing width warnings with Verilator.  This will be fixed in CIRCT 1.111.0.
I'm re-opening this as the nightly CI didn't seem to be kicking in.
=> [test] Revert to original RecordSpec, NFC

firrtl/src/main/scala/firrtl/annotations/JsonProtocol.scala, firrtl/src/test/scala/firrtlTests/annotationTests/UnrecognizedAnnotationSpec.scala
Change the way that `Named` is serialized into JSON to have this serialize as a `Target`.  This prevents a legacy serialization from ever showing up without actually removing `Named`.
This is done to free up the ability for us to change the serialization of `Target` to drop the circuit name without introducing a collision with the `Named` syntax.
E.g., I want to change the syntax for a target from:
~Foo|Foo
To:
Foo
However, this aliases with a `CircuitName` of `Foo`.  However, by ensuring that everything is funneled through `Target`, this can then be changed on a FIRRTL version bumpd without worrying about backwards compatibiliy with `Named`.
Serialize annotations which use `Named` instead of `Target` using `Target` syntax. This has no effect (as long as users are using the CIRCT …
=> [FIRRTL] Serialize Named as Target

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala-2/chiselTests/BoringUtilsSpec.scala
Remove BoringUtils APIs that were deprecated in Chisel 6.  This is done in preparation for the Chisel 7 release.  This is secondarily done to remove a user of the Named APIs.
Remove BoringUtils APIs deprecated in Chisel 6.
=> Remove deprecated BoringUtils APIs

core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, core/src/main/scala/chisel3/package.scala, docs/src/explanations/printing.md, src/test/scala-2/chiselTests/PrintableSpec.scala, src/test/scala-2/chiselTests/Printf.scala
- Squash
This includes modifiers defined in the SystemVerilog spec like minimum width (e.g. `%0d`) and set width (e.g. `%8d`). It does **not** include non-standard extensions like left-justification and zero-padding for decimal.
=> Add support for modifiers to format specifiers in printing

core/src/main/scala-2/chisel3/probe/Probe.scala, core/src/main/scala-3/chisel3/probe/Probe.scala, src/test/scala-2/chiselTests/ProbeSpec.scala
- Add API for creating layer-colored writable probes
=> Add API to create layer-colored RWProbes

core/src/main/scala-2/chisel3/VerificationStatementMacros.scala, core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, core/src/main/scala/chisel3/package.scala, src/test/scala-2/chiselTests/PrintableSpec.scala, src/test/scala-2/chiselTests/VerificationSpec.scala
The old version conflated the concerns of lowering to FIRRTL format Strings with what should simply be the inverse operation of Printable.pack. Specifically, Name and FullName are not represented in FIRRTL so must be "erased" before lowering to FIRRTL. This removal requires use of internal Chisel types (Component) so was always weird to have on a public API. Rather than doing this in .unpack, we instead treat that as a separate operation.
This does delete an API (`FirrtlFormat.unpack` replaced by `Printable.unpack`) but it's one I just added in https://github.com/chipsalliance/chisel/pull/4821.
This isn't really an important PR from a feature perspective, but it fixes a wart with `Printable.unpack` that has bothered me since we first added Printable many years ago.
- …
=> Deprecate Printable.unpack and .unpackArgs, replace with new version

firrtl/src/main/scala/firrtl/RenameMap.scala, firrtl/src/main/scala/firrtl/annotations/AnnotationUtils.scala, firrtl/src/main/scala/firrtl/annotations/LoadMemoryAnnotation.scala, firrtl/src/main/scala/firrtl/annotations/Target.scala, src/test/scala-2/chiselTests/CloneModuleSpec.scala
- Remove the ability to serialize a `Named`.
- Drop a private factory for the `RenameMap` that has no users.
- Remove `Named.serialize` API. If for whatever crazy reason you are using this, please use `Named.toTarget.serialize`.
- Remove `firrtl.annotation.AnnotationUtils.{toNamed, toSubComponents}`
=> [firrtl] Remove serialize and miscellaneous APIs

docs/src/explanations/layers.md
Document the fact that layer blocks can return layer colored wires if the return type is a subtype of `Data`.
=> [docs] Document layer block return values

docs/src/cookbooks/testing.md, docs/src/explanations/testing.md
Add a discussion of stimulus and the canned stimulus provided. Add information about the testing directory, how to change the base directory, and about how to use the command line features that ChiselSim + Scalatest provide.
=> [docs] Expand documentation of Testing

docs/src/explanations.md, docs/src/explanations/probes.md
Add documentation of probes.  This includes light documentation of `BoringUtils` which is closely related.
=> [docs] Add Probe Documentation

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/InlineTestIncluder.scala, src/main/scala/chisel3/experimental/inlinetest/InlineTest.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/Shell.scala, src/test/scala/chiselTests/experimental/InlineTestSpec.scala
- Provide control over when inline tests are elaborated
- Add `--include-tests-module` command line argument to enable inline test elaboration for modules matching a glob
- Add `--include-tests-name` command line argument to enable inline test elaboration for tests matching a glob
- Add `HasTests.elaborateTests` to dynamically enable test elaboration for a module (dynamic per-test elaboration can be done by wrapping calls to `test` in a conditional block)
=> Add command line options to control elaboration of inline tests

core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/package.scala, docs/src/explanations/printing.md, src/test/scala-2/chiselTests/PrintableSpec.scala, src/test/scala-2/chiselTests/Printf.scala
- Squash
Unlike `%t` in Verilog, SimulationTime (`%T`) does not take an argument.
=> Add SimulationTime (%T) format specifier

firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
Bump the version of serialized FIRRTL to version 5.1.0.  This was
mistakenly not bumped when the version was updated in Chisel.
=> [firrtl] Bump serializer version to 5.1.0

docs/src/explanations/testing.md, src/main/scala/chisel3/simulator/scalatest/Cli.scala, src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala
Add another factory for creating options that is intended to be used for
creating "flag"-style options.  This exists to unify this pattern as
opposed to forcing users to invent their own when they need it.
As can be seen, this unifies a number of existing flag-like options
relating to waveform emission.
CC: @andrew-gouldey-sifive: This will be available in the next internal
Chisel release for your use.
Add `CliOption.flag` to facilitate the creation of ChiselSim Scalatest flag-like options.
=> [chiselsim] Add a "flag" CLI option factory

src/main/scala/chisel3/experimental/inlinetest/InlineTest.scala, src/test/scala/chiselTests/experimental/InlineTestSpec.scala
- Refactor `HasTests` to track tests in buffer before elaborating
- The use case for this is to support capturing metadata about the tests that belong to a `HasTests` module. At the moment, `testName` is the only public member of the `TestParameters`, but this may be expanded in the future.
=> Track tests in HasTests to support metadata needs

src/main/scala/circt/stage/Shell.scala, src/test/scala-2/circtTests/stage/ChiselStageSpec.scala
Resolves #4893.
Users can use the `--chisel-output-file` argument to `ChiselStage` to customize the output file name.
=> Support customizing output CHIRRTL file name

.github/workflows/backport-fixup.yml, .github/workflows/build-scala-cli-example.yml, .github/workflows/cd-circt.yml, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/enable-bincompat-checking.yml, .github/workflows/release-notes.yml, .github/workflows/require-label.yml, .github/workflows/scala-cli-example.yml, .github/workflows/test.yml
Change all actions from 22.04 to 24.04.  This requires newer artifacts published from llvm/circt also using 24.04.
=> [ci] Bump all actions to Ubuntu 24.04

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/SimLog.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, docs/src/explanations/printing.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, src/test/scala-2/chiselTests/SimLogSpec.scala
This requires not-yet-released firtool 1.114.0 to be able to emit Verilog.
Related CIRCT PR: https://github.com/llvm/circt/pull/8419
- Squash
You can use Printables in SimLog filenames, e.g. `val log = SimLog.file(cf"logfile_$idx%0d.log")`
=> Support Printable SimLog filenames

core/src/main/scala/chisel3/SimLog.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, docs/src/explanations/printing.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, src/test/scala-2/chiselTests/SimLogSpec.scala
Staged on top of https://github.com/chipsalliance/chisel/pull/4892
- Squash
`SimLog` objects now support `.flush()`. You can flush stderr with `SimLog.StdErr.flush()`.
=> Add Simlog.flush

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/experimental/package.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala-2/chiselTests/DontTouchSpec.scala, src/test/scala-2/chiselTests/Vec.scala
This is done by adding DynamicIndexBinding so that Chisel can more precisely track when a Data is part of a dynamic index.
Erroring eagerly is only possible since making breaking changes to the annotation API a couple of months ago: https://github.com/chipsalliance/chisel/pull/4717.
- Bugfix
- Squash
Fixes a longstanding wart by at least giving a more useful error message at the site of the problematic user code.
=> Error eagerly when attempting to annotate dynamic indices

src/main/scala/chisel3/util/Arbiter.scala
The default behavior remains the same: don't initialize the `lastGrant` register in `LockingRRArbiter`. See #267 for previous discussions on this.
As noted in that old PR, this register is frequently in the control path of a design, where X-propagation can lead to simulation errors. There are nice ways to work around this uninitialized register in RTL simulations (namely the `RANDOMIZE_REG_INIT` text macro in the emitted SystemVerilog). However I've run into issues with non-resettable registers in the control path during gate-level simulations, where it's a bit harder to control the random initialization of registers. Having the option to resolve that problem with an RTL change would be very useful.
A few other notes about this PR:
- I chose an API where a `Boolean` lets the user opt in …
=> Support reset-initializing the lastGrant register in RRArbiter

core/src/main/scala/chisel3/properties/Property.scala, src/test/scala-2/chiselTests/properties/PropertySpec.scala
=> Support concatenating Properties of Seq subtypes

docs/src/developers/style.md
The parameter name is `entries` not `depth`.
Documentation or website-related
Squash
=> fix: queue depth parameter name

src/main/scala/chisel3/simulator/Simulator.scala
Set `+incdir` for every primary source directory.  Previously, only the
root primary source directory would be set.
This change is done to allow for the FIRRTL ABI related to bind layers to
be changed to _not_ use an FIRRTL compiler output directory-relative path
for `` `include `` [[1]].  This is necessary because some flows are
rearranging the directory structure of Chisel-generated Verilog, which
includes layers, and paths relative to the root will break.
This is a compromise between complexity of the build system, ABI
simplicitly, and ease of directory manipulation.  This has the effect of
users with custom build flows will need to recognize that they need to set
the `+incdir` recursively based on all output directories that were
created.  Practically, this is easy to do.
[1]: …
=> [chiselsim] Set +incdir on all primary sources

src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
Directories created with `[;<>]` are problematic for Makefiles and/or
Verilator.  Drop these if we see them.  This fixes issues where tests,
converted to ChiselSim, will fail to compile through Verilator due to
observed use of semicolons in test scopes or serialization of Chisel
types, e.g., `UInt<16>`.
Note: the continued patching of this indicates that we should setup an
allowlist of legal characters as opposed to continuing to exlcude
characters.
Drop `;`, `<`, and `>` if they show up in a ChiselSim Scalatest scope name.  This fixes a bug where Verilator (or the generated Makefile for ChiselSim) could fail to compile if it sees directories with these characters.
=> [testing] Mangle more directories

core/src/main/scala-2/chisel3/BitsIntf.scala, src/test/scala-2/chiselTests/BoolSpec.scala
Add a metho to Bool for logical implication.  Use a prose method
name ("implies") as opposed to a terse operator to avoid
problems/confusion that was brought up in original PR review.
Fixes #1500.
Add `implies` method to `Bool` for logical implication.
=> [core] Add Bool "implies" method

svsim/src/main/scala/verilator/Backend.scala
- Squash
Added extra option Verilator Backend for Timing option. User now has choice to either add `--timing` or `--no-timing` or nothing for this parameter, in the Verilator Args Seq
- [x ] Did you review?
=> Add timing parameter support to Verilator backend

src/main/scala/chisel3/simulator/PeekPokeAPI.scala, src/main/scala/chisel3/simulator/Simulator.scala, src/main/scala/chisel3/simulator/stimulus/ResetProcedure.scala, src/main/scala/chisel3/simulator/stimulus/RunUntilFinished.scala, src/main/scala/chisel3/simulator/stimulus/RunUntilSuccess.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala, svsim/src/main/scala/Backend.scala, svsim/src/main/scala/Workspace.scala, svsim/src/main/scala/vcs/Backend.scala, svsim/src/main/scala/verilator/Backend.scala, svsim/src/test/scala/BackendSpec.scala
Add the ability to better control the frequency of a simulation in
ChiselSim stimulus.  Previously, this was left up to the simulator to
define and could result in some weird behaviors: Verilator defaults to
`1ps/1ps` (which would cause simulations to seemingly simulate very fast)
and VCS defaults to `1s/1s` (which would cause simulations to seemingly
simulate very slowly).
Change the default behavior to simulate at 1GHz (by using a default
timescale of `1ns/100ps` and making the clock period 10 precision units).
Additionally, make the first two steps of the reset procedure longer to
keep things nicely aligned in waveforms.
Due to how Verilator and non-Verilator (e.g., VCS) simulators are handled
differently by svsim, this requires some changes to align the two
implementations of the …
=> [chiselsim] Add frequency control to stimulus

plugin/src/main/scala-2/chisel3/internal/plugin/ChiselComponent.scala, src/test/scala-2/chiselTests/naming/NamePluginSpec.scala
`AffectsChiselName` is new in 7.0 so no reason to backport.
- Bugfix
- Squash
Previously, naming support on unapply only worked for subtypes of Data, but now it works for all namable types, including user-extensible AffectsChiselName as well as non-Data Chisel built-in types: Mem, VerificationStatement, properties.DynamicObject, and Disable.
=> Fix naming plugin support for unapply

build.mill
- Squash
Also bump mdoc to 2.7.1 (but this isn't visible to users).
Note that we are not yet bumping os-lib to 0.11 because it will raise the minimum supported JVM to 11. Similarly we are not bumping upickle to 4.0 because it does not support Scala 3.3 which is our target for Scala 3 support (because 3.3 is LTS).
=> Bump os-lib to 0.10.7

src/main/scala/chisel3/simulator/package.scala
Change the logic used for determining which files to incldue from a
blocklist to an allowlist.  The blocklist approach is problematic as
sometimes users will generate odd files (e.g., '.graphml') and these need
to be excluded from the build.  It is easier to just include reasonable
files which is all Verilog and C++ files.
This is an imperfect solution and should be changed in the future to
either: (1) allow customization of this, (2) split the Chisel build
directory from the FIRRTL build directory, or (3) use CIRCT tooling to
query the MLIR to get the full list of files that should be included.
- Switch to a Verilog and C++ allowlist for ChiselSim build directory includes. This makes Chisel compatible with CIRCT 1.25.0+.
=> [chiselsim] Use allowlist for compilation includes

src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala, src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala, src/test/scala-2/chiselTests/testing/scalatest/TestingDirectorySpec.scala
Change the way that test directory names are mangled to be much more
conservative.  Mangle ny character which isn't a letter, number, or
underscore/dash.
This was empirically observed to be needed for Verilator v5.038 by
@ngraybeal.
- Change `scalatest.TestingDirectory` directory name mangling to be very conservative. Now, mangle anything not a letter, number, underscore, or dash. This is overly conservative, but avoids a whack-a-mole problem with Verilator. This has been empirically needed for Verilator v5.038.
=> [scalatest] More conservative testdir mangling

src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
Fix an inconsistency in the SimulatorSpec where, if you convert it to run
with VCS, this will then have FIRRTL randomization occurr at time 1.  The
test starts before this and several tests will then fail.
Fixes #4980.
=> [test] Test after randomization in SimulatorSpec

.github/scripts/publish.sh, .github/workflows/ci.yml, build.mill, plugin/package.mill, release.mill
Remove custom publishing logic, use upstream flow instead.
This involves generating the list of plugin versions we publish. Once we start publishing Scala 3 versions we can remove this logic.
I tried doing this programmatically in Mill code, if you look at the individual commits you can see how unwieldy this got and I'm not super keen on maintaining that code. I think this approach is the least bad option.
Draft PR for now so I can test the Github Actions flow.
- Squash
Users can access these SNAPSHOTs using the Maven Central Snapshots repository: https://central.sonatype.com/repository/maven-snapshots/
=> Publish snapshots

core/src/main/scala/chisel3/BlackBox.scala, core/src/main/scala/chisel3/Layer.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/experimental/IntrinsicModule.scala, core/src/main/scala/chisel3/experimental/hierarchy/DefinitionClone.scala, core/src/main/scala/chisel3/experimental/hierarchy/InstanceClone.scala, core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/firrtl/Serializer.scala, core/src/main/scala/chisel3/properties/Class.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, firrtl/src/test/scala/firrtlTests/SerializerSpec.scala, src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala, src/test/scala-2/chiselTests/BlackBox.scala, src/test/scala-2/chiselTests/LayerSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
Add an API to add `knownlayer` specifications to FIRRTL `extmodule`s.
This is a mechanism to declare that an external module was compiled with
support for specific layers.  This then allows a FIRRTL comopiler compiler
to know that it should automatically enable these layers if needed.
Add `knownLayers` API to `BlackBox` and `ExternalModule`. This allows for external modules to declare that they will contain layers, e.g., that they contain debug collateral. This allows a FIRRTL compiler using them to know that they _should_ enable these layers in concert with the parent circuit.
=> [core] Add knownLayers API to BlackBox, ExtModule

core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, src/test/scala-2/chiselTests/aop/SelectSpec.scala
This is mostly used when constructing PseudoModules when looking up Instances within other Instances or Definitions. Previously, we would construct the PseudoModule then manually set the _parent field. The problem with this is that _parent is used during construction of the object and defaults to Builder.currentModule. Instead, we properly set the Builder state to hold the desired _parent and then construct the PseudoModule.
This also cleaned up tech debt in Module.do_pseudo_apply which duplicated logic from the standard Module.apply path in a way that had already gotten out of sync and likely would result in other very subtle bugs.
Fixes https://github.com/chipsalliance/chisel/issues/5011
- Bugfix
- Squash
This fixes subtle bugs where accessing children of an `Instance` (whether directly …
=> Fix construction of PseudoModules to have correct parent

svsim/src/main/scala/verilator/Backend.scala
Verilator 5.034 fails to compile c++ sources as it uses syntax for c++17 while the CFLAGS passed to it specify c++14.
Before this patch I got the following error when testing my design with:
``` scala
"UartTx should send" in {
simulate(new UartTx(8, None, StopBitsOne())) { dut => {} }
}  
```
```
[info] g++ -Os  -I. -Wall -Wextra -Wfloat-conversion -Wlogical-op -Werror -MMD -I/usr/share/verilator/include -I/usr/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable …
```
=> [svsim] Update c++ CFLAGS for verilator from c++14 to c++17

core/src/main/scala/chisel3/layers/Layers.scala, core/src/main/scala/chisel3/layers/package.scala, src/test/scala-2/chiselTests/LayerSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
Add a new `Temporal` inline layers that are nested under each of the
builtin Assert, Assume, and Cover layers.  These layers exist because we
have observed situations where assertions which _should_ be legal in all
designs are unsupported by specific tools, though they are legal
properties by the SystemVerilog spec.
E.g., `s_eventually` is entirely unsupported by Verilator and has only
limited support in VCS.  The motivation for this PR is to have a location
where we can put these assertions and guard them off with tools that do
not support them.
Because this is expected to be problematic for all of the existing builtin
layers, this is added to each of Assert, Assume, and Cover.  Additionally,
as users have user-defined layers, the pattern of creating this `Temporal`
layer is factored …
=> [core] Add Temporal inline layer, trait

src/main/scala/chisel3/simulator/scalatest/Cli.scala, src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala, src/test/scala-2/chiselTests/simulator/scalatest/HasCliOptionsSpec.scala
Disable Temporal layers (either internal or those that use the
`HasTemporalInlineLayer` trait) when use ChiselSim with Verilator via the
`Cli.Simulator` trait.
This required adding a number of additional functions to the `CliOption` class
that can be used to control what happens when an option is _not_ set.  This was
a big hole in this API as it created a discontinuity between arguments like
`-Dsimulator=verilator` which would run settings modification functions and the
absence of any simulator being specified which would _not_ run any settings
modifications.  If the settings modifications were non-identity, then this was
incongruous.
Closes #5023.
Disable Temporal layers (either internal or those that use the
`HasTemporalInlineLayer` trait) when use ChiselSim with Verilator via the …
=> [chiselsim] Drop Temporal layers for Verilator Cli

firrtl/src/main/scala/firrtl/options/Stage.scala
Fixes https://github.com/chipsalliance/chisel/issues/5022
- Bugfix
- Squash
Also deprecate the older forms using AnnotationSeq.
=> Overload Stage methods to use Seq[Annotation]

src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala
You can see the failures in https://github.com/chipsalliance/chisel/pull/5028
- Bugfix
Marked No Release Notes because this binary compatibility issue is not yet released.
- Squash
=> Fix binary compatibility for HasCliOptions.CliOption

core/src/main/scala-2/chisel3/experimental/SourceInfoIntf.scala, core/src/main/scala-3/chisel3/experimental/SourceInfoIntf.scala, core/src/main/scala/chisel3/experimental/SourceInfo.scala
It turns out there was a really easy solution: https://youtrack.jetbrains.com/issue/SCL-24377/Incorrect-No-implicits-found-for-code-using-Chisel-v7.0.0#focus=Comments-27-12709369.0-0
Fixes https://github.com/chipsalliance/chisel/issues/4929
- Bugfix
- Squash
This works around an issue in IntelliJ around using the macro to materialize SourceInfo.
=> Rename private[chisel3] SourceInfo$Intf to SourceInfoIntf

src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Fix a problem that could cause a failing test based on the Verilator
version.  Prior to Verilator 5.036, this test would report the assertion
at time 30.  After 5.036, this will report as time 40.  Just make the test
robust to accept any time here as the actual time isn't terribly
important.
=> [test] Make ChiselSim log test robust to Verilator

.github/scripts/chisel-example.scala, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/test.yml, CONTRIBUTING.md, build.mill, docs/src/cookbooks/testing.md, docs/src/installation.md, src/main/scala/chisel3/testing/scalatest/HasConfigMap.scala, src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
Suppress MurmurHash3.productHash deprecation until we can also bump Scala 3 to include the replacement API.
It's also not a problem at all, see comment in code.
- Squash
**Note:** Scala 2.13.17 has a new warning for inferred structural types as a Scala 3 compatibility issue. This warning applies to the common `val io = IO(new Bundle { ... })` pattern in Chisel. It is not actually a problem because Chisel uses [Programmatic Structural Types](https://docs.scala-lang.org/scala3/reference/changed-features/structural-types-spec.html) in Scala 3. You can suppress this warning in your build by adding`-Wconf:msg=will no longer have a structural type:s` to your scalacOptions. See [configurable warnings](https://www.scala-lang.org/2021/01/12/configuring-and-suppressing-warnings.h …
=> Bump to Scala 2.13.17
