chipsalliance/chisel

src/main/scala/Chisel/testers/BasicTester.scala, src/main/scala/Chisel/testers/TesterDriver.scala, src/test/scala/chiselTests/DeqIOSpec.scala, src/test/scala/chiselTests/TesterDriverSpec.scala
…subclass which allows tester to have clean up and other construction code executed after a user code executed during constructor of that subclass.
Created a spec file TesterDriverSpec that shows finish method being called
=> Chisel tester support

README.md
Based on https://github.com/jackkoenig/chisel3-skeleton, but without assuming any specific repository structure (like requiring a top-level project with chisel3 and firrtl submoduled).
=> README instructions for installing with Scala FIRRTL

.gitignore, build.sbt
Add necessary lines to build.sbt so that chisel3 will be an accessible sbt distribution on sonatype.org.
=> Distribution prep1

build.sbt, src/main/scala/Chisel/Driver.scala, src/main/scala/Chisel/Main.scala
I can't get this to work when Chisel 3 is installed as a submodule.
=> Remove scalastyle test hook

src/main/scala/Chisel/internal/firrtl/IR.scala
I'm getting this error and the message is awful.
=> Print a better message on constant width failures

README.md
This branch may be deleted when merged.
=> Add pointer to Chisel3 compatibility on Chisel2 README.

src/main/scala/Chisel/Aggregate.scala, src/main/scala/Chisel/CoreUtil.scala, src/main/scala/Chisel/Data.scala, src/main/scala/Chisel/Driver.scala, src/main/scala/Chisel/internal/Builder.scala, src/main/scala/Chisel/internal/firrtl/IR.scala, src/main/scala/Chisel/throwException.scala, src/main/scala/Chisel/util/Counter.scala
This branch may be deleted when merged.
=> Scalastyle fixes and "ignores". - No functional changes.

src/test/scala/chiselTests/BundleWire.scala, src/test/scala/chiselTests/Module.scala, src/test/scala/chiselTests/Padding.scala, src/test/scala/chiselTests/Risc.scala, src/test/scala/chiselTests/Stack.scala, src/test/scala/chiselTests/Tbl.scala, src/test/scala/chiselTests/Vec.scala
This branch may be deleted when merged.
=> Replace deprecated usage in tests. Issue #149

src/main/scala/Chisel/package.scala
This is more of a proof of concept and a strawman, so that we don't forget
about this discussion.  Not sure we want to merge this without further
discussion.
=> Support writing literals like 1.U or -1.S

src/main/scala/Chisel/Aggregate.scala, src/main/scala/Chisel/Data.scala, src/main/scala/Chisel/SeqUtils.scala, src/main/scala/Chisel/util/Bitwise.scala, src/main/scala/Chisel/util/Cat.scala, src/main/scala/Chisel/util/Mux.scala
=> Remove dependences from Chisel core on Chisel utils

build.sbt
Just converted the Seq to variatic argument list.
=> Fixed sbt error where the typechecker was complaining.

build.sbt
This is necessary for developers working on upstream chisel repo along with chisel3 to publish chisel3 locally
=> Add a hack to build.sbt to allow local publishing

build.sbt
This should have been part of PR #194.
=> Move more publishing definitions into commonSettings.

chiselFrontend/src/main/scala/chisel/internal/Builder.scala
Rather than using a global counter, memoize the last returned value for
colliding names to generate smaller sequence numbers.
=> Generate better node names when names collide

chiselFrontend/src/main/scala/chisel/core/BlackBox.scala
=> Fix BlackBox setRefs to correctly handle arbitrarily nested bundles as ports

src/main/scala/chisel3/util/BitPat.scala
=> bitpat should keep the width of uint

src/main/scala/chisel3/util/Counter.scala
Just was looking at this and noticed the current example doesn't work
=> counter(inc,n) example should reflect actual use

src/main/scala/chisel3/util/TransitName.scala
This was originally mixed in with #199, Add Assert Data.
=> TransitName comment change.

chiselFrontend/src/main/scala/chisel3/core/Data.scala, src/test/scala/chiselTests/ComplexAssign.scala
=> clone firrtlDirection when cloning - Issue #306

src/main/scala/chisel3/util/Decoupled.scala
=> Add a cloneType method to QueueIO

chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, chiselFrontend/src/main/scala/chisel3/core/Module.scala, chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
No more need for e.g.
new Bundle {
def foo(dummy: Int): Data
}
as now you can write
new Bundle {
def foo: Data
}
This also removes code duplication with Module.
h/t @sdtwigg
=> Refactor and fix field reflection

build.sbt
Since chisel now depends on firrtl, we need a way for super projects (i.e., rocket-chip) to control the actual firrtl package used by chisel.
=> Existence of unmanaged firrtl.jar, replaces sbt managed dependency.

chiselFrontend/src/main/scala/chisel3/core/Data.scala
=> Fix toBits() deprecation message (to match what it effectively does).

chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, chiselFrontend/src/main/scala/chisel3/core/Bits.scala, chiselFrontend/src/main/scala/chisel3/core/package.scala
=> Disallow chained apply

build.sbt, chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/package.scala, src/main/scala/chisel3/testers/TesterDriver.scala, src/main/scala/chisel3/util/ImplicitConversions.scala, src/main/scala/chisel3/util/Valid.scala
=> Add feature warnings to build, fix feature and documentation warnings

chiselFrontend/src/main/scala/chisel3/core/package.scala, src/test/scala/chiselTests/WidthSpec.scala
Fixes #388 
Also add sanity checks
=> Fix literal width

src/main/scala/chisel3/util/BitPat.scala, src/main/scala/chisel3/util/Bitwise.scala, src/main/scala/chisel3/util/Cat.scala, src/main/scala/chisel3/util/CircuitMath.scala
=> utils scaladoc examples for BitPat through CircuitMath

README.md
=> Update FIRRTL cloning instructions.

chiselFrontend/src/main/scala/chisel3/core/Bits.scala, chiselFrontend/src/main/scala/chisel3/core/package.scala, src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/FixedPointSpec.scala
In reference to ucb-bar/firrtl#389
=> Have FixedPoint use asFixedPoint in fromBits.

src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/AnnotatingDiamondSpec.scala, src/test/scala/chiselTests/AnnotationNoDedup.scala, src/test/scala/chiselTests/BlackBox.scala, src/test/scala/chiselTests/FixedPointSpec.scala, src/test/scala/chiselTests/FromBitsTester.scala
Moved interfaces into experimental package
Fix tests and other references to these constructs
=> Mark Annotation and FixedPoint as experimental

chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, chiselFrontend/src/main/scala/chisel3/core/BiConnect.scala, chiselFrontend/src/main/scala/chisel3/core/Binding.scala, chiselFrontend/src/main/scala/chisel3/core/CompileOptions.scala, chiselFrontend/src/main/scala/chisel3/core/Data.scala, chiselFrontend/src/main/scala/chisel3/core/Module.scala, chiselFrontend/src/main/scala/chisel3/core/MonoConnect.scala, chiselFrontend/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/BundleSpec.scala, src/test/scala/chiselTests/RecordSpec.scala
This proposal for programmatic bundles is to just use Bundle.apply to generate Bundles. I haven't thought through all of the implications so here is a PR to start discussion. I also need to write more tests, most of the ones I've added so far just check standard Bundles.
=> Add Record as superclass of Bundle for custom Aggregate types

src/main/scala/chisel3/util/Reg.scala, src/test/scala/chiselTests/Reg.scala
Open to discussion. It resets all registers in the shift to the same value. This is sufficient for my needs.
=> Add shift register with reset

chiselFrontend/src/main/scala/chisel3/core/Assert.scala, chiselFrontend/src/main/scala/chisel3/core/Mem.scala, chiselFrontend/src/main/scala/chisel3/core/Module.scala, chiselFrontend/src/main/scala/chisel3/core/MultiClock.scala, chiselFrontend/src/main/scala/chisel3/core/Printf.scala, chiselFrontend/src/main/scala/chisel3/core/Reg.scala, chiselFrontend/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/MultiClockSpec.scala
withClockAndReset allows multi-clock within a Module
At long last, multi-clock within a Module!
I had written a test that inspected the Firrtl but realized that was not nearly as good as execution tests.
=> Add support for clock and reset scoping

chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
Should supersede #456 @sdtwigg @ducky64
=> Builderreflectionfix

chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, chiselFrontend/src/main/scala/chisel3/internal/Builder.scala, src/test/scala/chiselTests/BetterNamingTests.scala, src/test/scala/chiselTests/NamingAnnotationTest.scala, src/test/scala/chiselTests/RecordSpec.scala
This incorporates the fixes from @terpstra and @mwachs5. I merged their commits because they kinda went together while I think the other 2 are separate. In particular, @ducky64, can you look at the first commit which changes and uses NamedModuleTester?
=> Digit record field

src/main/scala/chisel3/compatibility.scala
@ucbjrl does this fix the rocket builds?
=> Add single arg constructor back to compatibility reg

chiselFrontend/src/main/scala/chisel3/core/Module.scala, src/test/scala/chiselTests/RawModuleSpec.scala
Resolves #604, now with more tests.
That was an embarrassing bug...
=> Clear clock and reset scope for RawModule

chiselFrontend/src/main/scala/chisel3/core/MonoConnect.scala, src/test/scala/chiselTests/IntervalSpec.scala
@azidar not sure how this works for you, but I needed these fixes to run
=> Too small fixes that caused me problems testing the interval stuff

README.md
There was a lot of malformed markdown there, this makes it much more readable.
=> Fix syntax of README.md

src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/package.scala, src/main/scala/chisel3/util/BitPat.scala, src/main/scala/chisel3/util/Valid.scala, src/test/scala/chiselTests/CompileOptionsTest.scala
=> Address scalastyle issues, out of date comments, extraneous imports.

chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, chiselFrontend/src/main/scala/chisel3/core/Bits.scala, chiselFrontend/src/main/scala/chisel3/core/BlackBox.scala, chiselFrontend/src/main/scala/chisel3/core/Data.scala, chiselFrontend/src/main/scala/chisel3/core/Module.scala, chiselFrontend/src/main/scala/chisel3/core/UserModule.scala, chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/internal/firrtl/Emitter.scala
As suggested in a comment on commit aaee58d
=> Rename userDir -> specifiedDir

chiselFrontend/src/main/scala/chisel3/core/Assert.scala, chiselFrontend/src/main/scala/chisel3/core/Bits.scala, chiselFrontend/src/main/scala/chisel3/core/Module.scala, chiselFrontend/src/main/scala/chisel3/core/MultiClock.scala, chiselFrontend/src/main/scala/chisel3/core/Printf.scala, chiselFrontend/src/main/scala/chisel3/core/UserModule.scala, chiselFrontend/src/main/scala/chisel3/internal/Builder.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/testers/BasicTester.scala, src/test/scala/chiselTests/AsTypeOfTester.scala, src/test/scala/chiselTests/Assert.scala, src/test/scala/chiselTests/CompatibilitySpec.scala, src/test/scala/chiselTests/MultiClockSpec.scala
Bool implements Reset. Compatibility package includes an implicit
conversion from Reset to Bool.
=> Make Reset a trait

README.md
Incorporated suggestions from @edwardcwang
=> Another try of a smoother intro what Chisel is

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add issue and pull_request templates.

chiselFrontend/src/main/scala/chisel3/core/Bits.scala, src/test/scala/chiselTests/FixedPointSpec.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
=> Reject negative shift amounts; add tests

chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala, src/test/scala/chiselTests/Vec.scala
Fixes #482
* **Impact**
Add error message for <> of Vec and Seq of different lengths
=> Add error message for <> of Vec and Seq of different lengths

chiselFrontend/src/main/scala/chisel3/core/Mem.scala, coreMacros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala, src/test/scala/chiselTests/Mem.scala
Fix for #708
* **Impact**
Text from here to the end of the body will be considered for inclusion in the release notes for the version containing this pull request.
=> Add source info / compile options transforms to Mem accessors

build.sbt
Fixes #748
* **Impact**
Text from here to the end of the body will be considered for inclusion in the release notes for the version containing this pull request.
Resolve sbt 1.0.4 issues.
=> Remove (possibly) extraneous aggregate() line.

README.md
This addresses issue #756.
* **Impact**
=> Update README.md with release status and supported Verilator version.

src/test/scala/chiselTests/ComplexAssign.scala, src/test/scala/chiselTests/Decoder.scala, src/test/scala/chiselTests/MemorySearch.scala, src/test/scala/chiselTests/MulLookup.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/Tbl.scala, src/test/scala/chiselTests/Vec.scala, src/test/scala/cookbook/FSM.scala, src/test/scala/cookbook/RegOfVec.scala, src/test/scala/cookbook/UInt2VecOfBool.scala, src/test/scala/cookbook/VecOfBool2UInt.scala, src/test/scala/examples/SimpleVendingMachine.scala, src/test/scala/examples/VendingMachineGenerator.scala
Fixes deprecations in tests that were exposed by changes from #761 
Should be no functional changes. Can be merged independently of #761.
* **Impact**
=> Fix deprecations in tests

project/build.properties
* **Related issue**
There is an incremental recompilation issue exposed by #766 and preventing bumping chisel in rocket-chip https://github.com/freechipsproject/rocket-chip/pull/1232
* **Impact**
Bump sbt to 1.1.1 to get incremental recompilation bugfix https://github.com/sbt/zinc/pull/484
=> Bump sbt to 1.1.1

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Other enhancement
* **Impact**
no functional change
implementation
=> Remove checkboxes from issue/pr templates.

src/main/scala/chisel3/tester/BackendInterface.scala, src/main/scala/chisel3/tester/FirrterpreterBackend.scala, src/main/scala/chisel3/tester/Testers2.scala
Add support for options in new tester.
=> Add support for options.

src/main/scala/chisel3/tester/FirrterpreterBackend.scala
Add support for accessing `reset`.
=> Add reset to portNames.

src/test/scala/chiselTests/Mem.scala
**Related issue**: https://github.com/freechipsproject/firrtl/issues/757
**Type of change**: other enhancement (chisel test for bug fixed in firrtl)
=> Add test for zero-width Mems.

.gitignore
Add Scala IDE (Eclipse) project metadata to .gitignore
=> Ignore eclipse metadata

README.md
=> Update versions and links in README

README.md
**Type of change**:  other enhancement
=> Update latest release reference.

doc/style.md
Some minor tweaks/copyedits to the style guide (does not affect functionality).
=> Minor tweaks to the style guide

README.md
=> Bump version reference in README.md

README.md
=> Add CircleCI status badge to README

.circleci/config.yml
**Impact**: no functional changeon
This makes use of reusable executors and reusable commands to minimize boiler plate when describing CI jobs.
=> Convert to 2.1 .circleci/config.yml

README.md
**Impact**: no functional change 
Now that Chisel3 has been released, you only need local Chisel to use the `master` branch in a project.
=> Update description given that Chisel3 has been released

project/build.properties
=> Bump SBT from 1.2.6 to 1.2.7 to fix partial recompilation issue

README.md
Title is self-explanatory.
**Related issue**: Fixes #960 
=> Add Windows setup instructions to readme

src/LICENSE.txt
=> Bump copyright year

src/main/scala/chisel3/util/LFSR.scala, src/test/scala/chiselTests/LFSR16.scala
Update documentation for LSFR16
- Moved bulk of comments to object.
- Added an example
- Added functional test
- example based on section of test
=> Util doc lsfr

src/main/scala/chisel3/package.scala, src/test/scala/chiselTests/CloneModuleSpec.scala, src/test/scala/chiselTests/Module.scala, src/test/scala/chiselTests/MultiClockSpec.scala, src/test/scala/chiselTests/RawModuleSpec.scala
=> Mainline Chisel multi-clock functionality

README.md
**Type of change**:  documentation
=> Update README to reference the bootcamp

src/main/scala/chisel3/util/Mux.scala
=> ScalaDoc for Mux (examples added)

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
I propose that documentation should be a "type of issue" in our templates. Templates should promote the way we would like things to be, and I think we could emphasize documentation more.
=> Update templates to include documentation.

src/main/scala/chisel3/util/Lookup.scala
Document the beast that is ListLookup. It's something that seems to make a lot more sense with an example than can be described in words or implementation.
Additionally gives background for where this came from (chisel2, probably without much critical evaluation) and where this could go (deprecation).
**Related issue**: #411 
Scaladoc for ListLookup / Lookup.
=> Docs for ListLookup

doc/style.md
Fix a small typo in the style guide.
=> Fix typo in link

README.md
The _current release_ is static text in `README.md` and therefore usually incorrect. Replace it with a dynamic badge.
=> Replace textual release version with Shields SemVer badge.

chiselFrontend/src/main/scala/chisel3/core/Module.scala
=> Style nitpick

chiselFrontend/src/main/scala/chisel3/core/RawModule.scala, src/test/scala/chiselTests/Direction.scala
Create Chisel IR Port() in a way that Converter is happy with.
Also add more extensive test suite for future-proofing.
Close #1063
=> Fix wrong directionality for Vec(Flipped())

src/main/scala/chisel3/util/LFSR.scala
Change deprecation since for LFSR16 from 3.3 to 3.2.
=> Change LFSR16 deprecation from 3.3 -> 3.2

chiselFrontend/src/main/scala/chisel3/core/package.scala, chiselFrontend/src/main/scala/chisel3/package.scala, root-doc.txt
- add/move package descriptive text
- fix FixedPoint link (it's chisel3.experimental.FixedPoint)
=> Minor Scaladoc update

README.md
This includes comments related to my review of #1106 and an attempt to address feedback by @ducky64 and @edwardcwang.
=> Additional README.md updates

README.md
Only missing one is the cheatsheet.
=> Update website references to the new website

chiselFrontend/src/main/scala/chisel3/Data.scala
=> Refactor: remove redundant code

build.sbt, build.sc
Bump external library dependency versions.
=> Bump dependency versions

README.md
Fix cheatsheet url.
**Related issue**: Fixes #1169 
=> Add Chisel Cheatsheet Latest Release Link

README.md
The FIR filter should be a raw link and not a GitHub link. Also I botched the original link...
=> Use raw link for FIR filter

.circleci/config.yml, build.sbt, project/plugins.sbt
I have no idea what I'm doing with CircleCI, so some help would be appreciated @ucbjrl 
**Impact**: no functional change (actually enforces *no* API modification)
Binary compatibility is preserved for all releases in the 3.2.x family
=> Add MiMa and CI checks for binary compatibility

chiselFrontend/src/main/scala/chisel3/Aggregate.scala
=> Improve error message when assigning from Seq to Vec

README.md
Publicize CCC20 on the README.md so that this can get pulled in on the website.
**Type of change**: documentation | other enhancement
=> Add CCC20 Info at README top

README.md
**Type of change**: documentation | other enhancement
=> Update README to reflect CCC20 Extension

.mergify.yml
=> Remove Jenkins CI from .mergify.yml

src/main/scala/chisel3/compatibility.scala, src/test/scala/chiselTests/CompatibilitySpec.scala
Reverts freechipsproject/chisel3#1253
See discussion in the reverted PR.
=> Revert "Compat compile options macro"

src/main/scala/chisel3/compatibility.scala, src/test/scala/chiselTests/CompatibilitySpec.scala
Reverts freechipsproject/chisel3#1257
See discussion in https://github.com/freechipsproject/chisel3/pull/1253
=> Revert "Use macro to materialize CompileOptions in Chisel._ (bp #1253)"

src/main/scala/chisel3/stage/ChiselStage.scala
=> specifying type of targets field in ChiselStage

build.sbt, build.sc
=> 3.2.3 release

chiselFrontend/src/main/scala/chisel3/Printf.scala, src/test/scala/chiselTests/PrintableSpec.scala
Forward port of https://github.com/freechipsproject/chisel3/pull/1323
=> Printf: Add support for tabs, and give helpful error messages (#1323)

build.sbt, build.sc, project/build.properties, project/plugins.sbt
=> Bump sbt and tool/plugin dependencies.

build.sbt, build.sc
=> Restore SNAPSHOT version.

.mergify.yml
Copy of freechipsproject/firrtl#1429
=> Make mergify open backport PRs & signal on failed cherry-picks

build.sbt
Same concept as in https://github.com/freechipsproject/firrtl/pull/1443
=> Update MiMa check to include all 3.2.x releases

src/main/scala/chisel3/compatibility.scala, src/test/scala/chiselTests/CompatibilitySpec.scala
**Related issue**: Bitten by the fundamental issue discussed in https://github.com/freechipsproject/chisel3/pull/1253
Fix bug where custom user-defined compile options would be ignored by compatibility-mode Modules
=> Propagate user compile options for Chisel.Module

build.sbt
NOTE: The equivalent of this PR has been incorporated in 3.3-release (in order to publish the release).
=> Add publishSettings to subprojects.

build.sc
**Type of change**: bug report 
Fix bug introduced in #1384
=> fix mill build

README.md
None
**Development Phase**:   implementation
Add link to the website source so that it's easier to figure out how to help enhance the content
=> README: add link to website source

.circleci/config.yml, build.sbt, project/plugins.sbt
=> [3.3.x] Add binary compatibility checking to CI

project/plugins.sbt
Scala-steward fix #1432
other enhancement
no functional change
=> Scala steward+1432 - Update scalatest to 3.1.2

build.sbt, build.sc
=> Bump SNAPSHOT version.

.mergify.yml
=> Restore backporting to 3.2.x

build.sbt
=> Have defaultVersions specify complete ModuleIDs.

build.sbt
=> [3.3.x] Bump Mima check to 3.3.1

build.sbt
=> [3.2.x] Bump Mima check to 3.2.6

.scala-steward.conf
Add .scala-steward.conf to ignore firrtl updates and check other updates once a month.
=> Add .scala-steward.conf

README.md
=> Update Development Meetings Info

core/src/main/scala/chisel3/Annotation.scala
It was private and unused
There is no impact on any user code. This also enables https://github.com/freechipsproject/firrtl/pull/1833 to pass CI.
=> Remove ChiselLegacyAnnotation

build.sc
Fixes a problem where build.sc was not in agreement with build.sbt
Broke release scripts
Build release issue
=> fix build release problem

build.sbt
I'm ignoring the checklist on this one, pretty self-explanatory
=> Bump MiMa previous artifacts to 3.3.2

build.sbt
I'm ignoring the checklist on this one, pretty self-explanatory
=> Bump MiMa previous artifacts to 3.2.7

.mergify.yml
- automation
No impact
No impact
- Squash
None
=> Add 3.4.x to Mergify

.github/workflows/test.yml, build.sbt, project/plugins.sbt
This is a manual backport of pull request #1706 done by @jackkoenig 
---
Mergify failed to do the backport automatically for some reason 🤷
=> Automate publishing of SNAPSHOTS with sbt-ci-release (bp #1706)

.github/workflows/test.yml, build.sbt, build.sc
- code cleanup
Remove support to Scala 2.11
=> Farewell Scala 2.11

core/src/main/scala/chisel3/Aggregate.scala
This PR revert #1480, but keep the test.
- code cleanup
None
None
=> remove 2.11 dedicated code.

.github/workflows/test.yml, build.sbt, core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/BlackBox.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Element.scala, core/src/main/scala/chisel3/Mem.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/experimental/Analog.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, no-plugin-tests/src/test/scala/chisel3/testers/TestUtils.scala, no-plugin-tests/src/test/scala/chiselTests/ChiselSpec.scala, no-plugin-tests/src/test/scala/chiselTests/InstanceNameSpec.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala, src/test/scala/chiselTests/CompatibilitySpec.scala
This is a manual backport of pull request #1624 done by @jackkoenig.
=> Make Data GC-able (bp #1624)

core/src/main/scala/chisel3/Aggregate.scala
Not a Pokémon
documentation
None
None
Squash
Fix a typo in the Record example.
=> Aggregate: fix typo

docs/src/explanations/chisel-enum.md
This is needed for the page to show up on the website
No impact
No impact
- Squash
=> Add header for chisel-enum.md

build.sbt
Really need to automate this...
=> Bump previous version for binary compatibility checking

docs/src/appendix/appendix.md, docs/src/appendix/versioning.md, docs/src/explanations/modules.md, docs/src/resources/faqs.md
=> Update the FAQ and add doc on versioning

docs/src/appendix/experimental-features.md
Documentation
No impact
No impact
Squash: The PR will be squashed and merged
Fix formatting issue of links in the "Experimental Features" part of the docs/website
=> Fix formatting issue of links

.github/PULL_REQUEST_TEMPLATE.md
None
No impact
Update PR Template to reflect 3.4.x milestone
=> Update PULL_REQUEST_TEMPLATE.md for the 3.4.x milestone

docs/src/cookbooks/cookbook.md
No impact
No impact
Added "tieoff to 0" example to Cookbooks
=> Add "how to tie off to 0" to the Cookbook

.mergify.yml
Using https://github.com/ucb-bar/chisel-repo-tools/pull/31
No impact
No impact
- Squash
=> Improve Mergify labeling of backports

README.md
=> update CCC2021 info

src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/test/scala/chiselTests/aop/InjectionSpec.scala
- bug fix
No changes.
Should successfully generate code in cases where aspects are used to inject code into multiple instances of the same module; previously, this would fail.
Fix for `InjectingAspect` — injections into multiple instances of the same module should now work.
=> Fixing aspect injection context bug

README.md
- documentation      
None
None
- Squash
=> Fix Gitter link in README

docs/src/cookbooks/cookbook.md
No impact
No Impact
Cleanup Cookbook examples on the website
=> Cleanup some Cookbook Examples

docs/src/developers/developers.md
just a minor documentation fix
=> doc: link to developer style guide

build.sc
=> make mill support 2.13.

README.md
None
None
Update README to include information about Chisel Sub-Projects
=> explain sub-projects in README

README.md
=> Switch to Github Actions CI Badge

core/src/main/scala/chisel3/Num.scala
=> Correct typos in core/src/main/scala/chisel3/Num.scala

README.md
Provide some useful developer documentation
- documentation         
No impact
No impact
- Squash
=> Add link to Chisel Breakdown slides to README

README.md
=> CCC update

README.md
=> updated readme to mention verilator dependency 

.github/workflows/test.yml, build.sbt
This PR refactor CI container out of GitHub Action to reduce docker maintenance effort.
Borrow Verilator CI by @ekiwi from chiseltest
None
None
None
=> refactor github action

README.md
There are now more tool dependecies than just `verilator` to get the full test suite to pass. Also add instructions for running the tests without the compiler plugin,
- documentation  
No impact
No impact
Updated README to clarify dependencies for running the unit test suite, and added instructions for running the unit tests without the compiler plugin.
=> Clarify test dependencies in README, add noplugin

src/main/scala/chisel3/util/experimental/decode/EspressoMinimizer.scala
- code cleanup
NA
NA
- Squash: The PR will be squashed and merged.
Pass truth table to espresso using stdin instead of temp file
=> Pass truth table to espresso using stdin instead of temp file

.github/workflows/test.yml
This reverts commit 1e7829eb674eed85a4cd537896d9fd9ee0bc5ff4.
And start to debug CI:
Current issue:
Cache hit, download compiled Z3 successfully.
```yaml
- name: Cache Z3 ${{ matrix.z3 }}
uses: actions/cache@v2
id: cache-z3
with:
path: z3-z3-${{ matrix.z3 }}
key: ${{ matrix.system }}-z3-${{ matrix.z3 }}
- name: Compile Z3
```
make install trigger rebuild:
```yaml
- name: Install Z3 ${{ matrix.z3 }}
run: |
cd z3-z3-${{ matrix.z3 }}/build
sudo make install
z3 --version
```
Basically, dependency check of make is based on timestamp.
This PR make these changes:
1. switch use ninja backend for CMake, which is much faster(~30mins -> ~15mins).
2. upgrade action@cache to 2.2.6, timestamp bug seems to be fixed in actions/cache#397
=> Z3 CI debug

.github/PULL_REQUEST_TEMPLATE.md
This the clearest thing I could come up with, not perfect though.
=> Add backport policy to PR Template

README.md
- bug fix 
No impact
No Impact
Fix firrtl spelling error in README versioning section
=> FIx firrtl typo in README versioning section

SETUP.md
The bintray reference is dead.
=> Update sbt installation instructions

plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala, src/test/scala/chiselTests/AutoClonetypeSpec.scala
Fixes https://github.com/chipsalliance/chisel3/issues/1893
- [N/A] Did you specify the code generation impact?
- bug fix
Makes autoclonetype work in all cases (that we know of). We expect this change should enable us to require the compiler plugins.
=> Fix higher-kinded types for autoclonetype

docs/src/explanations/functional-abstraction.md, docs/src/explanations/modules.md
Fixes #2138
- Squash
Fix typos in documentation
=> Fix typos in documentation

build.sbt
It can be set as default 2.13 build version later.
=> Add scala 2.13.7 to plugin build list

CONTRIBUTING.md
No impact
No change
Update contributor documentation to explain what branch to open PRs against.
=> Update CONTRIBUTING.md to explain what branch to PR to

src/main/scala/chisel3/util/Decoupled.scala, src/main/scala/chisel3/util/Valid.scala, src/main/scala/chisel3/util/random/PRNG.scala
Documentation
Unknown Impact
No impact
Squash
Improved documentation for DecoupledIO and other subclasses of Bundle
=> Add field grouping ScalaDoc for other subclasses of Bundle 

src/main/scala/chisel3/util/Decoupled.scala
- Did you add at least one test demonstrating the PR?
bug fix
Unknown impact
Unknown impact
Squash
Fix merge conflicts
=> Fix merge conflicts

.github/workflows/test.yml
=> ci: use official action to install oss cad tools

core/src/main/scala/chisel3/Bits.scala, src/main/scala/chisel3/compatibility.scala, src/test/scala/chiselTests/CompatibilitySpec.scala
=> Remove toBools

src/main/scala/chisel3/util/experimental/decode/EspressoMinimizer.scala, src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
private a non-user API: `chisel3.util.experimental.decode.EspressoMinimizer.espresso`(my bad to expose it.)
None
None
=> Add some documentation to decoder

src/main/scala/chisel3/Driver.scala, src/main/scala/chisel3/compatibility.scala, src/main/scala/chisel3/stage/package.scala, src/test/scala/chiselTests/Harness.scala
Also remove as many deprecated APIs as possible by inlining
implementations of old deprecated/removed code from firrtl
I hate this and would rather delete it but it wasn't deprecated soooo here we are. 
Fixes breakage from merging https://github.com/chipsalliance/firrtl/pull/2419 and anticipates **some** (but not all) breackage from https://github.com/chipsalliance/firrtl/pull/2423 and https://github.com/chipsalliance/firrtl/pull/2422.
=> Deprecate chisel3.BackendCompilationUtilities

docs/src/cookbooks/cookbook.md
=> [docs] add minimizing output bits recipe

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala/chiselTests/ConnectSpec.scala, src/test/scala/chiselTests/InvalidateAPISpec.scala
Better error messages for MonoConnect connection errors. Fixes #2061 
- performance improvement      
None
None
=> Better MonoConnect error messages

core/src/main/scala/chisel3/Aggregate.scala, src/test/scala/chiselTests/experimental/DataView.scala
This is the first step in supporting dynamic indexing on view Vecs. This initial work only supports views that are identity views of a target Vec, but it's a first step.
My next step is to support dynamic indexing when there is a Vec that is a piece of a larger view, but still corresponds 1:1 to a target Vec. This will be enough to make `FlatIO` work decently well and is enough for 3.5.0-RC2 I think.
The 3rd step is the generalization, supporting any type viewed as a Vec. This is a bit harder but important as well, hoping to finish it for 3.5.0
Partial implementation of a missing API
No impact on Verilog
- Squash
Support dynamic indexing for Vec identity views (eg. dynamic indexing on `val vecView = …
=> Add support for dynamic indexing on Vec identity views

core/src/main/scala/chisel3/internal/firrtl/IR.scala
- code cleanup
Stuff that should not have been part of the public API in IR.scala was made package private.
None
Classes in IR.scala were made package private and removed from the public API.
=> Make stuff in IR.scala package private

integration-tests/src/test/scala/chiselTests/util/experimental/DecoderSpec.scala, integration-tests/src/test/scala/chiselTests/util/experimental/minimizer/MinimizerSpec.scala, src/main/scala/chisel3/util/BitPat.scala, src/main/scala/chisel3/util/experimental/decode/EspressoMinimizer.scala, src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala, src/main/scala/chisel3/util/experimental/decode/TruthTable.scala, src/main/scala/chisel3/util/experimental/decode/decoder.scala, src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
In current TruthTable implementation, unordered Map will introduce non-deduped circuit.
This PR refactor TruthTable to use Seq instead of Map to produce a reproducible behavior in decoder.
After this PR:
https://scastie.scala-lang.org/Ee26d2aTTKqN6sFA6EJ6GQ
will return true.
=> Refactor TruthTable to use Seq.

core/src/main/scala/chisel3/internal/firrtl/IR.scala
This reverts commit 21e324727e99f0bc124aaddea7fe294b4111c23a.
Note that I am keeping the change making Arg sealed.
Fixes https://github.com/chipsalliance/chisel3/issues/2307
NA because this fixes something that was not released
- bug fix      
Restores some deleted APIs that need to go through deprecation schedule
No impact
- Squash
=> Revert "Make stuff in IR.scala package private (#2274)"

README.md
=> Update README shield to include RCs

.github/configs/mergify_config.yml, .mergify.yml
Fixes https://github.com/chipsalliance/chisel3/issues/2331
This is needed for any PRs to be merged. I'm updating this with the intent of adding an action similar to https://github.com/chipsalliance/firrtl/blob/master/.github/workflows/update_mergify.yml although that's not strictly necessary.
I don't think this needs to be backported because I _think_ mergify uses the default branch configuration but we can backport later if necessary.
- mergify/automation fix
No impact
No impact
- Squash
=> Update mergify queue action

.github/PULL_REQUEST_TEMPLATE.md, README.md
- documentation     
No impact
No impact
- Squash
=> Update README for 3.5.0 release

core/src/main/scala/chisel3/BlackBox.scala, core/src/main/scala/chisel3/RawModule.scala, src/test/scala/chiselTests/CompatibilitySpec.scala
The new reflection based IO autowrapping for compatibility mode Modules
would previously throw a NullPointerExceptions if any hardware were
constructed in the Module before "val io" was initialized. The logic is
now more robust for this case.
This was a doozy, but it fixes https://github.com/chipsalliance/chisel3/issues/1802 and https://github.com/chipsalliance/rocket-chip/pull/2932.
Note this only affects 3.5.x because the buggy logic is new in 3.5.0.
- bug fix   
No impact
No impact
- Squash
Fix bug where a NullPointerException would be thrown in any compatibility mode Module that constructs hardware before `val io` is initialized.
=> Fix Compatibility Module io wrapping

build.sc
1. add integration-tests to mill, which has already been added in sbt.
2. use object v to record ivy dependencies for simplicity.
3. remove deprecated testFrameworks API in mill.
None
None
None
None
=> Improve mill build

project/build.properties
This reverts commit 4097d179d03dc5e080d722d60fd125fbc75f9258.
This upgrade breaks the publish CI: https://github.com/chipsalliance/chisel3/runs/4974953775
=> Revert "Update sbt to 1.6.1 (#2369)"

core/src/main/scala/chisel3/Mem.scala
Use Builder.deprecated instead of Builder.warning so that the warnings
are aggregated by source locator to prevent spamming the screen with
duplicated warnings.
This turns ~40 lines of warnings into 6 for my designs.
It would be marginally faster to thread the source locator through on the 2 call sites that for some reason don't have source locators, doing that in a binary compatible way might be a bit of a pain and I want this in so I can release 3.5.1 so this is a patch solution that works. Note that if you don't pass a source locator to `Builder.deprecated` it uses a stack trace to find one and it works pretty well.
Tweak to unreleased feature, no …
=> Tweak new mem port clock warnings

core/src/main/scala/chisel3/internal/Builder.scala
- bug fix/code cleanup
I'm honestly unsure of the impact of this change, but I figure this typo should be fixed, or `dyanmicContext` should be replaced with an explicit ignore (`_`).
None
Unknown
Rebase
=> Fix variable-name typo

CONTRIBUTING.md
- [N/A] Did you delete any extraneous printlns/debugging code?
No impact
No impact
- Squash: The PR will be squashed and merged (choose this if you have no preference
Add instructions on how to run scalafmt
=> Update CONTRIBUTING.md with scalafmt instructions

build.sbt
SBT warns about deprecation of `in` for scoping keys starting 1.1.0 as detailed here: https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
- code cleanup
=> Migrate build.sbt to slash syntax

core/src/main/scala/chisel3/Printable.scala
To me this example is a little confusing, since the point of the `p` is to "reduce" to the case without the p, so update the example to clarify
No impact
No impact
Update scaladoc example for Printable
=> Clarify example in Printable

src/main/scala/chisel3/util/BlackBoxUtils.scala, src/main/scala/chisel3/util/ExtModuleUtils.scala
Remove an unused, deprecated import.
=> rm unused/deprecated BlackBoxResourceAnno import

core/src/main/scala/chisel3/internal/BiConnect.scala, src/test/scala/chiselTests/BulkConnectSpec.scala
This is an attempt to fix #2457 . It should prevent crashes due to FIRRTL bulk connects being emitted on BlackBox IO Bundles.
I was not entirely certain on the best way to catch these cases in the `canBulkConnectAggregates` method. My assumption is that BlackBoxes do not contain any other Bundles than the one IO Bundle. So I am simply checking whether the parent Module of the sink or source Bundle is a BlackBox.
- bug fix
None
Ideally, none. In the worst case it may unnecessarily prevent some FIRRTL bulk connects form being emitted, which should not have any functional impact.
- Squash
=> Prevent FIRRTL bulk connects on BlackBox Bundles.

core/src/main/scala/chisel3/Bits.scala
code cleanup (fix typos)
None
None
Squash
=> Fix small typos in doc comment

core/src/main/scala/chisel3/VerificationStatement.scala
This is a quick fix for issue #2408
=> verification: switch order of assert/assume and printf

core/src/main/scala/chisel3/Mem.scala, src/test/scala/chiselTests/Mem.scala
fixes https://github.com/chipsalliance/chisel3/issues/2470
- bug fix
=> mem: allow creating memories without an implicit clock

build.sc
=> fix plugin while building with mill.

CONTRIBUTING.md
Clarify the backport cleanup process
- documentation                      
No impact
No impact
Update CONTRIBUTING.md with clearer instructions on how to clean up backports
=> Update CONTRIBUTING.md for backport cleanup process

core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala/chiselTests/experimental/DataView.scala
Fixes https://github.com/chipsalliance/chisel3/issues/2508
- bug fix  
No impact
No impact
- Squash
Fix connecting `DontCare` to views via `:=`
=> Support := views to DontCare

macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
=> Backport #2534: Fix cherry-pick conflict

README.md
README's reference to CONTRIBUTING currently goes to a fork of the repo.
=> README: fix link to contributing.md

src/main/scala/chisel3/util/Valid.scala
Follow up from #2604 , should have removed this @nowarn then
- code cleanup                      
No API impact
No impact
Removed a stray @nowarn annotation left over from removing TransitName
=> Remove nowarn TransitName from Valid.scala

src/main/scala/chisel3/util/BitPat.scala
=> BP-fix Refactor TruthTable.apply and add factory method for Espresso (backport #2612)

core/src/main/scala/chisel3/StrongEnum.scala
This is required in order to support peeks in
chiseltest.
- very minor expansion of the API in order to support a feature in `chiseltest`
- none
- suqash
=> ChiselEnum: make factory package private

build.sbt
See https://github.com/chipsalliance/chisel3/pull/2650
=> [3.5.x] Remove chiseltest from defaultVersions

core/src/main/scala/chisel3/internal/Builder.scala
=> Fix 3.5.x PR 2658 backport conflicts

core/src/main/scala/chisel3/VerificationStatement.scala, src/test/scala/chiselTests/Assert.scala
Continuation of #2527 
Additions include unit test for `assume` and Scaladoc group for internal macros
=> Printables for verification preconditions

core/src/main/scala/chisel3/VerificationStatement.scala
=> Privatize trait VerifPrintMacros

src/test/scala/chiselTests/RecordSpec.scala
Change cloneType of record to the right one
=> Update RecordSpec test

src/test/scala/chiselTests/RecordSpec.scala
=> Backport fix for #2701

src/test/scala/chiselTests/RecordSpec.scala
These were incorrectly copy-pasted in #2701
=> Fix CloneTypes in RecordSpec

README.md
I'll move the CCC 2022 to bottom of readme, or remove it from readme next month. 
Others
None
None
None
=> Add links for CCC 2022

.github/workflows/test.yml, src/main/scala/circt/stage/phases/CIRCT.scala
This PR updates the version of CIRCT.
The command line options for firtool command have been updated.
CIRCT release notes here: https://github.com/llvm/circt/releases/tag/sifive%2F1%2F15%2F0
- bug fix
- backend code generation
- Changes the required version of CIRCT.
- Split large variadic operations into expressions, improving VCS compile time
- Squash
=> Update to CIRCT 1.15.0

docs/src/cookbooks/cookbook.md
Add more elaboration-time checks not just compile time checks.
Fix a bunch of elaboration time issues in the cookbooks uncovered as such.
Refactor some things that were hard-coded rather than generated
- bug fix 
No impact
No impact
Fix up cookbooks by relying on mdoc to do more elaboration-time-checking and fixing discovered issues
=> Cookbooks: use more mdoc power, fix issues

core/src/main/scala/chisel3/StrongEnum.scala, src/test/scala/chiselTests/StrongEnum.scala
N/A
ChiselEnums now support Printables; using Printables in `printf` or `asserts` will add a nicer pretty print of the Enum.
ChiselEnums now support Printables.
=> Update toPrintable for Enums

src/test/scala/chiselTests/StrongEnum.scala
This will fix CI by replacing execution test for enum printable with a CHIRRTL matching test. Alternative fix to #2574 
- bug fix 
N/A
N/A
=> Replace StrongEnum execution test with CHIRRTL match test

src/test/scala/chiselTests/naming/PrefixSpec.scala
As encountered in #2790, the associated test for #2789 used a hardware field in a `Bundle`, which is prohibited in 3.5.x but allowed in master due to a bug. This PR merges the modified test from the backport over to master, since it has the correct behavior.
- bug fix
No impact
No change
=> Fix reprefixing/suggestName test to not use hardware-in-bundle type

README.md, ROADMAP.md
- documentation      
No impact
No impact
Publish an Initial Roadmap
=> Publish an Initial Roadmap

.github/workflows/test.yml
=> Bump CIRCT

docs/src/explanations/connectable.md
=> Fixed doc errors in connectable

.github/workflows/test.yml
- CI
No impact
No impact
- Squash
=> [CI] Update Github Actions

.github/workflows/test.yml
- performance improvement 
People following our suggsted workflow would expect to use 1.24.0 CIRCT and we may break things that only worked on earlier circt versions
No impact, this is just for testing though it is basically showing a suggested version.
Bump tested circt version to sifive/1.24.0
=> Bump CIRCT version to test against 1.24.0

src/main/scala/chisel3/util/experimental/decode/decoder.scala, src/test/scala/chiselTests/util/BitSetSpec.scala
- bug fix         
None
It should fix code generation of correct chisel code.
`util.exprimental.decode.bitset` will correctly honor `errorBit` parameter.
=> Fix string interpolation in `util.exprimental.decode.bitset`

README.md
=> Update Yosys URL

.github/workflows/test.yml
=> Whitespace cleanup in .github area, NFC

core/src/main/scala/chisel3/connectable/Connectable.scala, src/test/scala/chiselTests/ConnectableSpec.scala
- bug fix
- new feature/API 
Adds a new API `Connectable.waiveAllAs`, which enables a more succinct syntax for doing "partial-connect-like" connections. Previously, you had to do `foo.waiveAll.asInstanceOf[Connectable[Data]]`.
=> Bugfix waiveEach not casting. Add waiveAllAs

.github/workflows/install-circt/action.yml, .github/workflows/install-espresso/action.yml, .github/workflows/setup-oss-cad-suite/action.yml, .github/workflows/test.yml
Use more composite actions to reduce duplicated code in CI yaml.
=> DRY out CI

.github/workflows/install-circt/action.yml
Use newer CIRCT.  Current `firtool` is not new enough for zero-width integer literals, which requires at least 1.25.0.
=> [CI] Update CIRCT from 1.24.0 -> 1.26.0, accomodate tag name change.

.github/workflows/test.yml
=> Add "Skip chiseltest" label support to github test.yml

build.sbt, core/src/main/scala/chisel3/experimental/package.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/SourceInfo.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/package.scala, docs/src/explanations/annotations.md
- code cleanup   
Public APIs in `chisel3.internal` that never should have been public are being deprecated.
N/A
Internal APIs in package `chisel3.internal` which never should have been public are deprecated.
=> Deprecate public internals and fix warning suppression 

.github/workflows/test.yml, build.sbt, website/build.sbt
=> Publish website to branch

README.md
=> testing website changes

.github/workflows/test.yml
=> more website testing rules

README.md
- bug fix                     
- documentation             
No impact
No change
Fix link to ROADMAP in README
=> Fix link to ROADMAP in README

.github/workflows/test.yml, README.md, website/README.md, website/build.sbt
- new feature/API          
No impact
No IMpact
- Squash: The PR will be squashed and merged (choose this if you have no preference
Publish to GitHub Pages website on pushes to master
=> Publish website to gh-pages branch on pushes to master (#2950)

src/main/scala/chisel3/util/experimental/ForceNames.scala, src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala, src/test/scala/chiselTests/AnnotationNoDedup.scala, src/test/scala/chiselTests/aop/SelectSpec.scala, src/test/scala/chiselTests/experimental/ForceNames.scala
Convert the SelectSpec to use the MFC instead of the SFC.
=> Convert SelectSpec to use MFC

src/test/scala/chiselTests/InvalidateAPISpec.scala
Fix InvalidateAPISpec to use MFC
=> Use deprecatedMFCMessage in TraceSpec

build.sbt, core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/connectable/Connection.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/internal/Error.scala, macros/src/main/scala/chisel3/internal/InstantiableMacro.scala, src/main/scala/chisel3/aop/Select.scala, src/main/scala/chisel3/util/experimental/ForceNames.scala, src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala, src/main/scala/circt/stage/phases/CIRCT.scala, src/test/scala/chiselTests/BetterNamingTests.scala, src/test/scala/chiselTests/ComplexAssign.scala, src/test/scala/chiselTests/Math.scala, src/test/scala/chiselTests/MixedVecSpec.scala, src/test/scala/chiselTests/QueueFlushSpec.scala, src/test/scala/chiselTests/QueueSpec.scala, src/test/scala/chiselTests/UIntOps.scala, src/test/scala/chiselTests/Vec.scala
=> Cleanup warnings 1

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
In preparation for the Chisel 3.6.0-RC1 release.
- bug fix
- backend code generation
- Squash
Bump firtool to 1.30.0
=> Bump firtool to 1.30.0

core/src/main/scala/chisel3/ChiselEnum.scala, core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/BuilderContextCache.scala, src/main/scala/chisel3/util/circt/SizeOf.scala
This is sort of a first attempt at an API discussed https://github.com/chipsalliance/chisel3/pull/2923#issuecomment-1376432828 and https://github.com/chipsalliance/chisel3/pull/2900#discussion_r1085901366, and as such I think it's very useful for https://github.com/chipsalliance/chisel3/pull/2958
See each commit, 1st adds the API, next 3 use it for 3 different use cases. I'm actually not that keen on using it for ChiselEnum just because it turns a static function call into a dynamic map lookup which is extra compute for dubious benefit. I think this is definitely useful for `Instantiate` and the intrinsics (more compute overhead but relatively sparsely used and more functional since it's cleared between elaborations).
This is currently private as I'm just trying to get the ball rolling on …
=> Builder ContextCache

src/main/scala/circt/stage/phases/CIRCT.scala
Drop definition annotations in the CIRCT phase as these are not understood by firtool and have no effect on Verilog compilation.
=> Drop ImportDefinitionAnnotation in CIRCT Phase

.github/workflows/test.yml, build.sbt
Flag is `-DdisableFatalWarnings`
Add flag to a number of places in build.sbt
=> Add sbt flag to disable warnings are fatal

.github/PULL_REQUEST_TEMPLATE.md, .github/configs/mergify_config.yml, .github/mergify/gen-config.sc, .gitignore, .mergify.yml
Script was derived from original Ammonite script:
https://github.com/ucb-bar/chisel-repo-tools/blob/d3432790d746a3e3643acc843377f0d82b830466/scripts/mergify.sc
Updated to use Scala-CLI
Also slight tweaks to the PULL_REQUEST_TEMPLATE
- automation improvements
- code cleanup
No impact
No impact
- Rebase
=> Update Mergify config and add generation script to this repository

website/build.sbt
Partial backport of https://github.com/chipsalliance/chisel/pull/3044, fetching the contributors needs to use the new chisel repo or it will fail.
No impact
No impact
Fix website contributor fetching to not fail now that chisel3 moved to chisel
=> Partial BP #3044 -- update website contributor fetching

docs/src/cookbooks/cookbook.md
No impact
No impact
Fix broken link in the cookbook about resolving UInt index mismatches
=> Fix broken cookbook link

build.sbt
Changes to build.sbt:
* Add developers
* Add ThisBuild / version
* Add organization url
* Simplify pom license and url
Opening PR to kick off CI, this PR **must** be merged with a merge commit since I am doing the actual Sonatype release from a commit on this branch: bb8ee7c3e6599345a714f7353c916b7df0f7cec3
~I need to push another commit that removes the version addition~ Done.
=> Release Chisel v5.0.0-M1

core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/package.scala
=> Remove reflectivelyFindIO, its unused

README.md
The scala version support badge is broken
https://www.chisel-lang.org/
This updates it to the badge url from 
https://index.scala-lang.org/chipsalliance/chisel/badges
=> Update README.md, fix scala version support badge

.github/workflows/test.yml, build.sbt, project/plugins.sbt
- code cleanup
No impact
No impact
- Squash
=> Add SBT aliases for formatting including SBT files

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
- dependency bump
See firtool 1.35.0 release notes: https://github.com/llvm/circt/releases/tag/firtool-1.35.0
- Squash
Bump to firtool 1.35.0, see release notes: https://github.com/llvm/circt/releases/tag/firtool-1.35.0
=> Bump to firtool 1.35.0

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
- dependency bump
See firtool 1.36.0 release notes: https://github.com/llvm/circt/releases/tag/firtool-1.36.0
- Squash
Bump to firtool 1.36.0, see release notes: https://github.com/llvm/circt/releases/tag/firtool-1.36.0
=> Bump to firtool 1.36.0

docs/src/explanations/intrinsics.md
@darthscsi please review
No impact
no impact
Use mdoc to compile check the intrinsics explanation doc
=> mdoc-ify intrinsic explanation

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
See the firtool release notes: https://github.com/llvm/circt/releases/tag/firtool-1.37.0
=> Bump to firtool 1.37.0

integration-tests/src/test/scala/chiselTest/VecSpec.scala, src/test/scala/chiselTests/Vec.scala
* Change many tests from simulation-based to checking the CHIRRTL.
* Move tests that were hard to convert to new VecIntegrationSpec in integration-tests
Before this change, `VecSpec` took over 6 minutes on my laptop, now it takes under 10s and `VecIntegrationSpec` takes ~70s but will be able to run in parallel to the main tests in CI.
This reduced total CI test time for the 2.12.17 tests from 35m37s to 21m4s
It only increased the integration tests from 8m50s to 9m12s--the runners are dual core so there's probably some parallelism being exploited resulting in the relatively modest time increase.
- CI performance improvement
No impact
No impact
- Squash
=> [CI] Revamp VecSpec

core/src/main/scala/chisel3/BlackBox.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/experimental/package.scala
Remove the _compatAutoWrapPorts method as this does nothing.
=> Remove _compatAutoWrapPorts no-op method

README.md
=> Fix three broken links in README.md Documentation section

.github/workflows/require-label.yml
Combined with some work to automatically generate release notes (PR to follow), this is a workflow that will require PRs have one of the labels used by the release notes workflow.
The labels I have created for this purpose (and we can change them) are as follows in this excerpt from the release notes configuration JSON:
```json
{
"categories": [
{
"title": "## Features",
"labels": ["Feature"]
},
{
"title": "## Performance",
"labels": ["Performance"]
},
{
"title": "## API Modification",
"labels": ["API Modification"]
},
{
"title": "## API Deprecation",
"labels": ["Deprecation"]
},
{
"title": "## Fixes",
"labels": ["Bugfix"]
},
{
"title": "## Documentation",
"labels": ["Documentation"]
},
{
"title": "## Dependency Updates",
"labels": ["Dependency Update"]
},
{
"title": "## Build and …
```
=> [CI] Require PRs to main to be labeled

.github/workflows/test.yml
Whoops, forgot this in https://github.com/chipsalliance/chisel/pull/3174
=> [CI] Install firtool in the publish step

website/build.sbt, website/docs/src/main/resources/microsite/data/menu.yml, website/docs/src/main/tut/api/chisel3/3.6/index.md, website/docs/src/main/tut/api/index.md
Bump website to add 3.6 links.
=> Add 3.6 to Chisel Website

core/src/main/scala/chisel3/Aggregate.scala, core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/Element.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/main/scala/chisel3/aop/Select.scala
Remove PartialConnect as it is now impossible for this to be emitted by Chisel.
=> Remove PartialConnect

README.md
=> [docs] Fix README logo and update versions

.github/workflows/build-scala-cli-template/action.yml, .github/workflows/build-scala-cli-template/chisel-template.scala, .github/workflows/scala-cli-template.yml, .github/workflows/test.yml, .gitignore, build.sbt
- Squash
Add a new Chisel template for using Chisel with Scala CLI, and adds some automation for uploading versions of this template on tagged releases (or workflow dispatch).
=> Add Chisel Scala CLI template and automation

core/src/main/scala/chisel3/Mem.scala, macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala, src/test/scala/chiselTests/Mem.scala
Fixes some additional nits and improves code quality in various places which was prompted by #3213, but weren't addressed due to auto-merge. This PR is meant to be an additional part of that PR.
=> Improve SyncReadMem.read, .readWrite

.github/workflows/backport-fixup.yml
Quick fixup to https://github.com/chipsalliance/chisel/pull/3252 for labels with spaces in them.
=> Fix backport-fixup for labels with spaces

src/main/scala/chisel3/util/Arbiter.scala
Just a oneline fix to the comment of Arbiter chosen port
=> [fix] typo fix: chosen port of arbiter is not onehot but UInt

src/main/scala/chisel3/interface/Interface.scala, src/test/scala/chiselTests/interface/InterfaceSpec.scala, src/test/scala/chiselTests/interface/ParametricInterfaceSpec.scala
Enable a user to define Scala-time properties on an Interface.  These
properties require a conformance to examine.  This enables patterns where
a client wants to configure itself based on knowledge of the component,
e.g., when the client is a testbench.
Add properties to Interface.
=> [feature] Add properties to Interface

.github/workflows/test.yml
The updated versions fix warnings about deprecated actions.
=> [CI] Update versions in CI Workflow

svsim/src/main/resources/simulation-driver.cpp
=> Gate sys/personality.h include under define

src/main/scala/chisel3/interface/Interface.scala, src/test/scala/chiselTests/interface/InterfaceSpec.scala
=> Support ref types on interfaces

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
- Squash
See release notes for firtool [1.41.0](https://github.com/llvm/circt/releases/tag/firtool-1.41.0), [1.42.0](https://github.com/llvm/circt/releases/tag/firtool-1.42.0), and [1.43.0](https://github.com/llvm/circt/releases/tag/firtool-1.43.0).
=> Bump to firtool 1.43.0

docs/src/appendix/experimental-features.md, docs/src/explanations/data-types.md
Fixes https://github.com/chipsalliance/chisel/issues/3325
=> Remove references to interval types from the website docs

core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala, src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
I split out a commit of @fabianschuiki's from https://github.com/chipsalliance/chisel/pull/3337 because this should be backported.
- Squash
=> Add support for Instantiate for BlackBox, ExtModule, and IntrinsicModule

README.md
* Update Chisel Dev Meeting time
* Update some uses of 5.0.0-RC1 to 5.0.0
=> Update meeting time and versions in README

.github/workflows/build-scala-cli-template/chisel-template.scala, .github/workflows/test.yml, build.sbt, build.sc, project/plugins.sbt
=> Bump to Scala 2.13.11

src/main/scala/chisel3/ltl/LTL.scala, src/main/scala/chisel3/util/circt/LTLIntrinsics.scala, src/test/scala/chiselTests/LTLSpec.scala
=> Add basic linear temporal logic assertions

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
Bump firtool from 1.43.0 -> 1.44.0.
Bump firtool from 1.43.0 -> 1.44.0.
=> Bump firtool from 1.43.0 -> 1.44.0

README.md
The previous link is no longer working.
=> README.md: Fix link to gitter badge

build.sc
=> Fix BuildInfo in 3.6.x

.github/workflows/setup-oss-cad-suite/action.yml
=> [CI] Bump OSS CAD tools build to 2023-06-21 release

src/main/scala/chisel3/util/circt/Synthesis.scala, src/test/scala/chiselTests/util/circt/Synthesis.scala
This commit adds new intrinsics (MuxCell2 and MuxCell4) to provide users a way to directly use 2-to-1 and 4-to-1 MUX cells in synthesis tools (currently synopsys and cadence are supported) from Chisel level. Appropriate pragmas will be annotated in output verilog. FIRRTL implementation is https://github.com/llvm/circt/pull/5428
=> Add MuxCell intrinsics

README.md
This is required as being part of Chips Alliance, see https://github.com/chipsalliance/tsc/pull/136.
- Squash
=> Add Chips Alliance to README

src/test/scala/chiselTests/interface/TappedInterfaceSpec.scala
=> Un-ignore force tests now we have newer verilator in CI.

.github/workflows/test.yml, build.sc, common.sc
This PR upgrade mill to 0.11.0, which is incompatible with older version, fixes lots of legacy design choice(e.g ammonite, overriding behavior).
- Bugfix
=> upgrade mill to 0.11.0

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
- Squash
Bump to firtool 1.45.0, [see release notes](https://github.com/llvm/circt/releases/tag/firtool-1.45.0).
=> Bump firtool to 1.45.0

docs/src/appendix/versioning.md
- Squash
Describe new use of SemVer and update older text that applies to only Chisel 3.0-3.6.
=> Update versioning.md for Chisel 5.0.0.

.github/workflows/install-circt/action.yml, .github/workflows/test.yml, src/test/scala/chiselTests/DedupSpec.scala, src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
- Squash
Bump to firtool 1.47.0 from 1.45.0. See release notes for [1.46.0](https://github.com/llvm/circt/releases/tag/firtool-1.46.0) and [1.47.0](https://github.com/llvm/circt/releases/tag/firtool-1.47.0).
=> Bump firtool to 1.47.0 from 1.45.0

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/IO.scala, core/src/main/scala/chisel3/Module.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala, core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala, core/src/main/scala/chisel3/experimental/package.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/reflect/DataMirror.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala, src/main/scala/chisel3/aop/Select.scala, src/main/scala/chisel3/simulator/package.scala
=> Add a new BaseType type that Data inherits, and use it for ports.

docs/src/appendix/versioning.md
Also make notice about the older sections bold and thus more noticable.
- Squash
=> [docs] Fix chiseltest version in old compatible versions

.github/workflows/install-circt/action.yml, .github/workflows/test.yml
- Squash
See [firtool 1.48.0 release notes](https://github.com/llvm/circt/releases/tag/firtool-1.48.0).
=> Bump to firtool 1.48.0

.github/workflows/ci.yml
=> [ci] Fix broken all_tests_passed

core/src/main/scala/chisel3/internal/Builder.scala, plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala, src/test/scala/chiselTests/naming/NamePluginSpec.scala
The chisel plugin will now name wires that are part of tuples e.g. `val x = (Wire(Bool()), Wire(Bool()))` will generate wires with names `x_1` and `x_2`
=> update ChiselPlugin to name tuples

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala, src/test/scala/chiselTests/properties/PropertySpec.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
The Integer property type is defined in FIRRTL spec version 3.1.0: https://github.com/chipsalliance/firrtl-spec/releases/tag/v3.1.0.
=> Add support for Integer properties and conversion to FIRRTL.

core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This includes the API, Chisel IR, Converter, FIRRTL IR, and Serializer support for Property literals.
This is currently stacked on #3481 and can be merged after that one.
Property literals are defined in FIRRTL spec version 3.1.0: https://github.com/chipsalliance/firrtl-spec/releases/tag/v3.1.0.
=> Add support for Property literals, starting with existing int types.

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala
- Bugfix
RWTaps are done from inside the module instead of externally, for compatibility.
Add tests for taps and rw-taps of IO's.
=> BoringUtils: rwprobe from inside module, test (rw)taps of IO's.

src/test/scala/chiselTests/ProbeSpec.scala
Demonstrate force/release basic behavior in simulator test.
Some limitations for default simulation environment:
* Verilator's force doesn't update when the RHS changes, as documented, so in tests re-force as needed or otherwise workaround this limitation.
* Verilator rejects designs that attempt to force an input port, with ASSIGNIN.  Force other signals instead.
* `forceInitial` does not appear to work (Verilator?), the generated Verilog works in VCS.  Workaround. (Chisel `forceInitial` -> `initial force the.lhs.target = rhs_value;`)
=> ProbeSpec: Add force/release simulator test.

core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, firrtl/src/main/scala/firrtl/ir/Serializer.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
- Feature
API Modification: Add Boolean support to Property API
=> Add Boolean Property type

core/src/main/scala/chisel3/Annotation.scala, firrtl/src/main/scala/firrtl/transforms/Dedup.scala, src/test/scala/chiselTests/DedupSpec.scala
add annotation case class for [DedupGroupAnnotation](https://github.com/llvm/circt/blob/main/docs/Dialects/FIRRTL/FIRRTLAnnotations.md#dedupgroupannotation) (introduced in firtool 1.51.0)
=> add DedupGroupAnnotation

.github/workflows/build-scala-cli-template/chisel-template.scala, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/test.yml, build.sbt, build.sc
=> Bump to Scala 2.13.12

flake.lock, flake.nix, nix/espresso.nix, overlay.nix
This PR adds `nix flake` template to setup the development environment, which can can more packages dependent by chisel.
=> Add Nix Flake

src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala, src/test/scala/chiselTests/DedupSpec.scala
=> Don't add DedupGroupAnnotation to intrinsics

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/ProbeSpec.scala
Not presently in spec but is supported in CIRCT for few releases.  Don't reject, and add test.
Allow creation of wire of probe, not in specification but supported by CIRCT.
=> Support wire-of-probe.

flake.lock, flake.nix, overlay.nix
=> use flake input to provide circt source

flake.nix, nix/llvm-lit.nix, overlay.nix
Tested with llvm lit built-in example tests directory.
=> Add llvm-lit into nix devShell

binder/src/main/scala/PanamaCIRCT.scala, flake.lock, flake.nix, overlay.nix
=>   fix binding compile due to CAPI change

tests.sc
=> fix litConfig path

core/src/main/scala/chisel3/probe/Probe.scala, core/src/main/scala/chisel3/probe/ProbeValue.scala, src/test/scala/chiselTests/ProbeSpec.scala
Error instead of emitting RW/ProbeValues on literals.
=> Additional checks in probe packagae

src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
Adding a `Phase` which is not of type `chisel3.stage.phase` in subtypes of `AddDedupGroupAnnotations` is causing issues. This minor change should help fix that
Add type specifier to optionalPrerequisites in AddDedupGroupAnnotations phase
=> Add type specifier on AddDedupGroupAnno phase optionalPrerequisites

.github/workflows/ci.yml
This isn't strictly docs but it helps make it easier to see what version was published by a given push to main (which can be used in docs).
- Squash
=> [ci] Record published version in step summary

website/static/robots.txt
This will hopefully make the Algolia web crawler work.
With the website facelift, I'm trying to enable Algolia [Docsearch](https://docsearch.algolia.com). Things seem to be set up properly, but the webcrawler won't index the website. I'm following the instructions here (https://www.algolia.com/doc/tools/crawler/getting-started/verify-domain/) to try to fix this. It's a bit weird that this isn't mentioned in the [Docusaurus docs](https://docusaurus.io/docs/search#using-algolia-docsearch), so we'll see if it fixes things.
- Squash
This will hopefully make the Algolia web crawler work.
=> [website] Add robots.txt

website/docusaurus.config.js
~Currently a draft PR because, while this PR works, the Algolia web crawler currently will not actually crawl chisel-lang.org so there is nothing indexed. I've asked for help on Discourse: https://discourse.algolia.com/t/crawler-skipping-my-website-for-reason-domain-not-allowed/19347?u=jack.koenig~
The web crawler now works--the search index is populated. I know that this change adds the search bar, I don't know if it actually _works_ though. Search doesn't work from a locally hosted build, but I think this might be due to Algolia blocking search requests that don't original from the approved URL (ie. `www.chisel-lang.org`). So sometimes you just gotta test it live!
- Squash
=> [website] Enable Algolia-powered search

website/docusaurus.config.js
- Squash
Redirect links with `.html` or `.htm` (remove the extension). Do this same redirect for old website `/chisel3/...` links as well.
=> [website] More redirects

README.md
This is very minor, I'm mainly doing this PR to trigger the new CLA
- Squash
=> [docs] Update README after 5.1.0 release

docs/src/explanations/layers.md
Fix spelling error in Layers documentation
=> Fix spelling error in Layers documentation layers.md

core/src/main/scala/chisel3/dontTouch.scala, src/test/scala/chiselTests/DontTouchSpec.scala
Go all in on leaf marking for don't touched values.  This preserves current behavior.  As options expand, the API can change then.
don't Touch of aggregates marks leaves, rather than the entire aggregate.  This should result in no functional difference for now.
=> don't Touch without options

binder/includeFunctions.txt, binder/src/main/scala/PanamaCIRCT.scala, binder/src/main/scala/PanamaCIRCTConverter.scala, binder/src/test/scala/BinderSpec.scala, core/src/main/scala/chisel3/internal/CIRCTConverter.scala
Implement probe related stuff for binder.
Still working in progress.
=> [binder] Implement probe IR emissions

core/src/main/scala/chisel3/Data.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
- Bugfix
When we changed Property to extend Element, we needed to update some internal logic that checked "are these Elements the same type". That logic needs to work a little differently for Property, and this internal API is one other place that needed to be updated.
=> Define typeEquivalent specially for Property.

SETUP.md
=> [docs] update firtool version

core/src/main/scala/chisel3/dontTouch.scala, src/test/scala/chiselTests/DontTouchSpec.scala
- (None, title seems sufficient?)
- Bugfix
=> dontTouch: Skip probe and properties.

build.sc
`os.pwd` is not suitable for using chisel as submodule dependency.
- Bugfix
=> fix up path issue in build.sc

flake.nix, overlay.nix
=> symlink all llvm and circt stuff together

.github/workflows/ci.yml
=> Fix publish

build.sbt
h/t @seldridge for noticing this
This issue was introduced by Scala [2.13.12](https://github.com/scala/scala/releases/tag/v2.13.12) to fix https://github.com/scala/bug/issues/12867. It doesn't show up on older release branches so long as we don't bump the default version of Scala on them (which is not something we typically do just being conservative).
- Squash
=> [docs] Fix links from ScalaDoc to source code

build.sbt, build.sc
- Squash
Now it will fetch llvm-firtool with classifier for the current system rather than the full artifact which contains binaries for all platforms.
=> Bump firtool resolver to 1.2.0

binder/src/main/scala/PanamaCIRCTConverter.scala
=> Fix AsyncReset in binder

project/FirtoolVersionsTable.scala
=> [CI] Fix CI flakiness with --server=false

core/src/main/scala/chisel3/IO.scala, core/src/main/scala/chisel3/experimental/package.scala, docs/src/cookbooks/cookbook.md, src/main/scala/chisel3/FixedIOModule.scala, src/main/scala/chisel3/interface/Interface.scala, src/main/scala/chisel3/util/circt/PlusArgsValue.scala, src/test/scala/chiselTests/ExtModule.scala, src/test/scala/chiselTests/experimental/FlatIOSpec.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Also change to an object (from a def) so that it shows up in ScalaDoc search.
- Squash
=> Promote FlatIO to package chisel3

core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/package.scala, src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
Makes `SRAM` targets accessible from `SRAMInterface`s instantiated via the `SRAM` object, which sets the `underlying` field in `SRAMInterface`.
=> make SRAM targets accessible from SRAMInterface

website/src/css/custom.css
=> [website] Make links more obvious

.github/workflows/build-scala-cli-template.yml, .github/workflows/build-scala-cli-template/chisel-template.scala
- Squash
* Use "dep" instead of deprecated "lib"
* Move ChiselStage import above `import chisel3._`
* This makes users less likely to run into issues adding `import chisel3.util._`
* Bump versions in Github workflows
=> Update Scala CLI Template

docs/src/installation.md
=> Homebrew sbt for MacOS

circtpanamabinding/includeFunctions.txt, flake.lock, lit/tests/OMTest.sc, lit/tests/SmokeTest.sc, lit/utility/src/package.scala, panamalib/src/PanamaCIRCT.scala, panamaom/src/PanamaCIRCTOM.scala
- Add OM basic test.
- Support iterating fields of a OM object.
=> Add OM test, support iterating fields of a OM object

.github/mergify/gen-config.sc, .mergify.yml
mergify is not authorized by EasyCLA, this is probably fixable, but we can also just use @chiselbot instead.
See https://github.com/chipsalliance/chisel/pull/3723#issuecomment-1913273415
- Squash
=> [CI] Configure Mergify to use chiselbot as bot account

docs/src/installation.md
=> [docs] Make Quickstart instructions more clear

circtpanamabinding/includeFunctions.txt, circtpanamabinding/includeStructs.txt, circtpanamabinding/includeTypedefs.txt, lit/tests/OMTest.sc, panamaconverter/src/PanamaCIRCTConverter.scala, panamalib/src/PanamaCIRCT.scala
Based on CIRCT upstream PR llvm/circt#6626.
=> [binder] Add instance graph API for iterating HW modules

core/src/main/scala/chisel3/Bits.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/ChiselAnnotations.scala, src/main/scala/chisel3/stage/ChiselOptions.scala, src/main/scala/chisel3/stage/package.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
* Apply some suggestions from post-merge code review
* Add "use" to CLI option: --use-legacy-shift-right-width
* Improve stability of emitted FIRRTL and Verilog when using legacy option
* DRY out the tests
Follow on to https://github.com/chipsalliance/chisel/pull/3824
Note I'm marking this as no release notes and then I will update https://github.com/chipsalliance/chisel/pull/3824's notes to include changes from this so that the release notes for this change are still in a single bullet.
- Squash
=> Static shift right width change part 2

docs/src/installation.md, project/build.properties
I honestly have no idea which label to use
De-bumping to sbt 1.9.7 to avoid glibc issues for users, manifesting as:
```
java.lang.UnsatisfiedLinkError: Error looking up function 'stat': java: undefined symbol: stat
```
=> de-bump to sbt 1.9.7

build.sbt
This is needed to fix CI, it also needs to be backported to fixed CI on 6.x and 5.x
- Bugfix
- Squash
=> [website] Update chisel-template repo link to chipsalliance

build.sbt, docs/src/appendix/migrating-from-chiseltest.md, docs/src/installation.md
Also add Verilator instructions to install page.
=> [docs] Add initial ChiselTest migration doc

.github/workflows/test.yml, docs/src/appendix/migrating-from-chiseltest.md
It is shockingly annoying to get information out of ScalaTest here.
h/t @tymcauley for letting me know about this.
- Squash
=> [docs] Fix ChiselTest migration doc

circtpanamabinding/includeFunctions.txt, panamaconverter/src/Convert.scala, panamaconverter/src/PanamaCIRCTConverter.scala, panamalib/src/PanamaCIRCT.scala
Upstream PR: llvm/circt#6730
Still working in progress.
=> Pass FIRRTL annotations into `CIRCTConverter`

README.md, docs/src/appendix/upgrading-from-scala-2-11.md, docs/src/explanations/blackboxes.md, docs/src/resources.md
Separate from https://github.com/chipsalliance/chisel/pull/3871 because this doesn't need to be backported and I wanted to avoid conflicts.
- Squash
=> [docs] Update links to point to chipsalliance/chisel-template

core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala, core/src/main/scala/chisel3/internal/Builder.scala, docs/src/cookbooks/cookbook.md, docs/src/explanations/warnings.md, firrtl/src/main/scala/logger/Logger.scala, src/main/scala/chisel3/aop/injecting/InjectingAspect.scala, src/main/scala/chisel3/stage/phases/Elaborate.scala, src/main/scala/circt/stage/ChiselStage.scala, src/main/scala/circt/stage/Shell.scala, src/test/scala/circtTests/stage/ChiselStageSpec.scala
I originally set out just to fix the minor issue of Chisel not doing `Logger.withScope`, that ended up being more involved than I expected.
Long-term, we should probably ditch our Logger code and switch to a more robust solution, probably [scribe](https://github.com/outr/scribe) or scribe + a thin wrapper around it. But this fix is needed for anything using firtool-resolver, otherwise it's really painful for the user to debug what is going wrong with that.
- Bugfix
- Squash
* Adds support for `--log-level` to `circt.stage.ChiselStage`
* Previously, `object circt.stage.ChiselStage` was ignoring the Logger.
* Also, Chisel was not creating its own logger scope which could lead to clobbering of the Console when running invoking Chisel in the same process multiple times.
=> Fix ChiselStage and Builder handling of logging

panamaconverter/src/PanamaCIRCTConverter.scala
=> [binder] Specify the new attribute `layers` for `firrtl.instance`

circtpanamabinding/includeFunctions.txt, lit/tests/Property/DocExample.sc, lit/tests/Property/Good.sc, lit/utility/src/package.scala, panamaconverter/src/PanamaCIRCTConverter.scala, panamalib/src/PanamaCIRCT.scala, panamaom/src/PanamaCIRCTOM.scala
~Blocked by upstream PR: llvm/llvm-project#83825. After the LLVM upstream PR gets merged, this PR also needs to wait for CIRCT bump LLVM to contain that commit.~ No longer needed.
This PR adds [the OM example](https://github.com/chipsalliance/chisel/blob/main/docs/src/explanations/properties.md#property-expressions) as a test case.
~Marked as draft because it's still in test.~
=> [binder] Add OM example as a test case

.github/workflows/ci.yml
Publishing appears to be using GPG from the runner image, which is 2.2.27 not the 1.4.23 this action builds from source.
See also upstream issue '8' regarding error it produces.
=> [CI] Drop GPG action as we aren't using its result.

lit/tests/Property/Good.sc
Integration tests in `lit/Property` now pass and make sense (at least for me).
=> Fix integration test for PanamaProperty

panamaconverter/src/PanamaCIRCTConverter.scala
Fixes #3942.
The reason of this bug is that the result of Scala's `BigInt.bitLength` excludes the sign bit.
Reference from Chisel
https://github.com/chipsalliance/chisel/blob/7b9c07c4e5fe4a8174b4f788cf798b3870039e7e/core/src/main/scala/chisel3/internal/firrtl/Converter.scala#L88-L92
I haven't figured out why Chisel always generates `asSInt(UInt())` for `SLit`. However, since `pad` is sign-extends this behavior is documented. I think the fixed version `connect magic, pad(SInt<7>(-42), 8)` and `connect magic, asSInt(UInt<7>(0h56))` should be equivalent?
Feel free to correct me if I'm wrong.
```
| Name | Arguments | Parameters | Arg Types | Result Type | Result Width |
|------|-----------|------------|-----------|-------------|--------------|
| pad  | \(e\)     | \(n\)      | (UInt)    | …
```
=> Fix incorrect width for negative `SInt` literals

circtpanamabinding/includeFunctions.txt, panamalib/src/PanamaCIRCT.scala, panamaom/src/PanamaCIRCTOM.scala
Referenced upstream PR llvm/circt#6785
=> Recognize OM evaluator reference value

docs/src/explanations/muxes-and-input-selection.md
=> Removed FixedPoint reference in muxes-and-input-selection.md

.github/workflows/test.yml, benchmark/src/main/scala/chisel3/benchmark/Benchmark.scala, build.sc
This makes it easier for developers to benchmark certain changes (I built this for some PRs to come).
- Squash
=> Add reference benchmarking flow

.github/workflows/test.yml, CONTRIBUTING.md, benchmark/src/main/scala/chisel3/benchmark/Benchmark.scala, build.sc, common.sc, lit/utility/src/package.scala, panamaconverter/src/PanamaCIRCTConverter.scala, panamaconverter/src/PanamaCIRCTPassManager.scala, panamalib/src/PanamaCIRCT.scala, panamalib/src/PanamaFirtoolOption.scala, panamaom/src/PanamaCIRCTOM.scala, tests.sc
reformat lit and panama and use mill to check format
- Squash
=> Check format with mill

flake.lock, flake.nix, lit/tests/Converter/Circuit.sc, lit/tests/Converter/Debug.sc, lit/tests/Converter/Module.sc, overlay.nix
=> Add integration test for PanamaCIRCT to firrtl converter

src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsSpec.scala
- Bugfix
This follows up on https://github.com/chipsalliance/chisel/pull/3960 to address the behavior at the final module for the sink being driven. We already have special handling for boring out from the original source, and we need the inverse here. When we reach the final sink, if it is an input port, we should use it, rather than boring into the module and connecting to it.
=> In BoringUtils.drive, don't bore into the final module for inputs.

website/src/pages/community.md
=> Add Tywaves project to community projects page

panamaom/src/PanamaCIRCTOM.scala
Subdivide OM primitive values into Scala types
=> Subdivide OM primitive values into Scala types

.github/workflows/build-scala-cli-example/chisel-example.scala, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/test.yml, build.sbt, build.sc, project/plugins.sbt
=> Bump to Scala 2.13.14

src/test/scala/chiselTests/LTLSpec.scala
Follow-up to bugfix in #4061 , rework LTL tests to also ensure these compile fine now and in the future.
=> [LTL] Send generated FIRRTL through to SV to ensure this works.

build.sbt, build.sc
- Squash
* scalatest: 3.2.14 => 3.2.18
* scalacheck-1-16:3.2.14.0 => scalacheck-1-18:3.2.18.0
* json4s-native: 4.0.6 => 4.0.7
* commons-text: 1.10.0 => 1.12.0
* os-lib: 0.9.1 => 0.10.0
* upickle: 3.1.0 => 3.3.0
* Delete moultingyaml, it has been unused for a long time
* Make Mill versions consistent with SBT versions
=> Bump dependencies and delete moultingyaml

src/test/scala/chiselTests/ProbeSpec.scala
https://github.com/llvm/circt/pull/6921 (FIRRTL spec linked from there).
=> Remove input probes in tests

core/src/main/scala/chisel3/Data.scala, core/src/main/scala/chisel3/IO.scala, core/src/main/scala/chisel3/experimental/dataview/package.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, src/test/scala/chiselTests/FixedIOModuleSpec.scala
- Bugfix
Fixes #4102.
Now supported are FlatIO of:
- Probe(Element)
- Probe(Aggregate)
- Aggregate(Probes)
- Aggregates containing any of the above
The tests here are all in FixedIOModules but really they are fixes to FlatIO.
Fix for #4102. Now supported are FlatIO (and therefore FixedIO___Module) of:
- Probe(Element)
- Probe(Aggregate)
- Aggregate(Probes)
- Aggregates containing any of the above
=> FixedIO__Modules with various kinds of probe ports 

.github/workflows/backport-fixup.yml, .github/workflows/build-scala-cli-example.yml, .github/workflows/ci.yml, .github/workflows/enable-bincompat-checking.yml, .github/workflows/install-espresso/action.yml, .github/workflows/install-jextract/action.yml, .github/workflows/release-notes.yml, .github/workflows/require-label.yml, .github/workflows/scala-cli-example.yml, .github/workflows/setup-oss-cad-suite/action.yml, .github/workflows/test.yml
Node 16 is deprecated and will eventually stop being supported.
We get lots of warnings, this should fix most of them. The one that remains is `The following actions uses node12 which is deprecated and will be forced to run on node16: jodersky/setup-mill@v0.3.0.`. That action hasn't been updated in 2 years. We should probably just switch to including the [mill wrapper script](https://github.com/lefou/millw) in tree which is what most projects using mill do[^1][^2].
- Squash
[^1]: https://github.com/Virtuslab/scala-cli
[^2]: https://github.com/coursier/coursier
=> Bump versions of Github actions to versions using Node 20

core/src/main/scala/chisel3/Bits.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/chiselTests/SIntOps.scala, src/test/scala/chiselTests/UIntOps.scala
=> Preserve UInt and SInt literals across .pad

.github/workflows/test.yml
- Squash
Our version of Jekyll is no longer supported by Github Actions. We are not actually doing anything with this legacy website build (it isn't deployed anywhere). This flow is not worth maintaining so just delete it from CI/CD.
=> [5.x] Remove website CI/CD

flake.lock
=> Bump nix flake

core/src/main/scala/chisel3/experimental/Analog.scala, src/test/scala/chiselTests/experimental/hierarchy/Examples.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Fixes #4180 
- Bugfix
- Squash
=> Support XMRs to Analog in D/I

plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
`shouldMatchModule(tpe)` and `shouldMatchInstance(tpe)` conditional body are the same, merge for concise.
=> Merge two conditional due to same body

build.sbt, src/main/scala/chisel3/ltl/LTL.scala
=> [LTL] Deprecate disable intrinsic

src/main/scala/chisel3/ltl/LTL.scala
=> Fix import path in docstring

src/main/scala/chisel3/ltl/LTL.scala
=> [LTL] Remove deprecated disable

src/test/scala/chiselTests/DPISpec.scala, svsim/src/main/resources/simulation-driver.cpp, svsim/src/main/scala/Workspace.scala
This fixes a bug that svsim doesn't properly update svScope before calling exported DPI function in C++. 
- Bugfix
Fix svsim to properly update svScope for calling exported DPI functions
=> Fix svsim to properly update svScope. Update DPISpec for firtool bump

docs/src/appendix/versioning.md
=> Update versioning.md - typo

README.md
=> Update chiseltest uses version to 6.0 in documentation

lit/tests/Converter/Circuit.sc, lit/tests/Converter/Debug.sc, panamaconverter/src/PanamaCIRCTConverter.scala
Support emitting for `DefIntrinsic` and `DefIntrinsicExpr`
=> [binder] Support generic intrinsic emission

core/src/main/scala/chisel3/properties/Property.scala, docs/src/explanations/properties.md, firrtl/src/main/scala/firrtl/ir/IR.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
This adds a list concatenation operation for Property[Seq[T]], using the same typeclass approach used for other Property expressions.
=> Add Property expression for list concatenation.

src/main/scala/circt/OutputDirAnnotation.scala, src/test/scala/circtTests/OutputDirAnnotationSpec.scala
Expose capability to request a Module be placed in a specific directory.
Functions as with Layer output directories.
=> Add support for circt.OutputDirAnnotation.

core/src/main/scala/chisel3/reflect/DataMirror.scala, src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
This allows users to query an Instance without it being closed or forcing it to close, which can be useful in atModuleBodyEnd and other scenarios.
=> Add DataMirror API for currentInstancePorts.

src/main/scala/chisel3/aop/Select.scala, src/test/scala/chiselTests/aop/SelectSpec.scala
This is useful in situations like atModuleBodyEnd to reflect on the current BaseModule before it is closed.
=> Add experimental Select APIs for current instances in a BaseModule.

core/src/main/scala/chisel3/properties/Path.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Adds `Path.apply()` function that support `HasTarget`s, so that the paths of things that extend `HasTarget`, like `SRAM`, can be put into properties.
=> Add `Path.apply()` to support `HasTarget`

website/package.json
=> [website] Update docusaurus 3.1.1 => 3.5.2

src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
Add a `hasDescription` argument to `SRAMInterface` that specifies whether or not it contains a `SRAMDescription`.
Making `description` optional enables users to create `SRAMInterface`s without having to hook up an `SRAMDescription`.
=> make SRAM description value optional in SRAMInterface

build.sc, firrtl/src/test/scala/firrtlTests/FileUtilsSpec.scala, tests.sc
Fixes https://github.com/chipsalliance/chisel/issues/4353.
Another step toward replacing SBT.
I went ahead and used the way of defining tests in Mill rather than doing it more manually. This ensures we get the SBT default `src/test/scala` and `src/test/resource` directories for free. It's also just more idiomatic as this is what the Mill examples do.
These tests can be run in parallel with `./mill -j0 __.test`. I also figured out how to create "aggregate commands" that run in parallel (if you tell mill to use parallelism with `-j`):
```scala
object utils {
// Copied from https://github.com/com-lihaoyi/mill/blob/4caadfb62581b4c1772c14c6f8dc8963011eaec7/main/define/src/mill/define/Task.scala#L55
// This makes it possible to run multiple tasks in parallel (when passing `-j <n>` to mill)
// …
```
=> [mill] Get unit testing working

etc/circt.json
Resolves https://github.com/llvm/circt/issues/7586 for Chisel 6.x users (to be released in Chisel 6.6.0)
- Bugfix
- Squash
* [FIRRTL] LowerToHW: guard against folded operations (https://github.com/llvm/circt/pull/7358)
=> [6.x] Bump to CIRCT 1.62.1

src/main/scala/chisel3/aop/Select.scala, src/test/scala/chiselTests/aop/SelectSpec.scala
Use `collect` in `instances` and other methods, such that they and API using them like `collectDeep` work with regions.
Also tweak `collect` to visit the layer command itself, on principle, should this be reachable or useful in the future.
Add two tests confirming collectDeep now searches within when and layer regions.
- Bugfix
More Select methods support searching into whens and layers.
=> Select.collectDeep and related: search into layers and whens

core/src/main/scala/chisel3/ModuleImpl.scala, src/test/scala/chiselTests/LayerSpec.scala
=> Module: reset layerStack

.github/workflows/build-scala-cli-example/chisel-example.scala, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/test.yml, build.sbt, build.sc
=> Bump to Scala 2.13.15

src/main/scala/chisel3/ltl/LTL.scala, src/test/scala/chiselTests/LTLSpec.scala
- Bugfix
Add source locator for Sequence
=> Add SourceLocator for Sequence

.github/workflows/build-scala-cli-example.yml, .github/workflows/ci.yml, build.sc
* Bring BuildInfo to parity with SBT BuildInfo
* Add custom unidoc implementation
* Only unipublish and plugin should be published
* Add mill-ci-release & use VCSVersion
* Cross compile and publish plugin for all Scala 2.13 minor versions
* Switch to using Mill for publishing in CI and CD
- Squash
=> Switch publishing to use Mill

docs/src/installation.md
The original brew command for installing jdk has been deprecated, this pr now provides a command to adapt to the new version of brew
=> chore: Updating JDK-related docs for macOS Homebrew

core/src/main/scala/chisel3/ModuleImpl.scala, src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Add tests that demonstrate crashing without this change.
Fixes #4441.
- Bugfix
Fix crashing or incorrect behavior in some cases involving use of DI interacting with when's or layer's.
=> Save/restore when+layer stack w/D/I, fix crashes.

core/src/main/scala/chisel3/DataImpl.scala, core/src/main/scala/chisel3/Intrinsic.scala, core/src/main/scala/chisel3/MemImpl.scala, core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/Reg.scala, core/src/main/scala/chisel3/When.scala, core/src/main/scala/chisel3/internal/Binding.scala, core/src/main/scala/chisel3/internal/Builder.scala, core/src/main/scala/chisel3/internal/MonoConnect.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/internal/package.scala, core/src/main/scala/chisel3/probe/PackageImpl.scala, core/src/main/scala/chisel3/probe/ProbeValueBase.scala, core/src/main/scala/chisel3/properties/Class.scala, panamaconverter/src/PanamaCIRCTConverter.scala, src/main/scala/chisel3/aop/Select.scala, src/main/scala/chisel3/choice/ModuleChoiceImpl.scala, src/main/scala/chisel3/util/SRAM.scala, src/main/scala/chisel3/util/experimental/BoringUtils.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala, src/test/scala/chiselTests/WhenSpec.scala
=> Introduce Blocks, track, use for improved scope checking and boring

core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/RawModule.scala, core/src/main/scala/chisel3/internal/firrtl/Converter.scala, core/src/main/scala/chisel3/internal/firrtl/IR.scala, core/src/main/scala/chisel3/properties/Class.scala
=> Block: close earlier, ArraySeq builder and store result, drop unused owner field

src/main/scala/chisel3/util/AttributeAnnotation.scala, src/test/scala/chiselTests/util/AttributeAnnotationSpec.scala
`chisel3.utils` is not a chisel package, change back to `chisel3.util` 
- Bugfix
Fix addAttribute and add AttributesAnnotationSpec.
=> Fix addAttribute and add AttributesAnnotationSpec

src/main/scala/chisel3/util/SRAM.scala, src/test/scala/chiselTests/util/SRAMSpec.scala
We use this api in our flow to replace the sram-repl: 
See https://github.com/chipsalliance/t1/pull/791/commits/7862959c20f7bee83047b9fb33102aac83036b33
- Bugfix
=> switch SRAMDescription to Class

CONTRIBUTING.md, build.sc, common.sc, src/test/scala/chiselTests/ChiselEnum.scala, svsim/src/main/scala/vcs/Backend.scala, tests.sc
This is the official switch over to Mill. All developers, please start using Mill for normal development from the merging of this PR on. Please see `CONTRIBUTING.md` for initial docs and add to them as needed.
Remaining things to migrate (future PRs):
* Mdoc
* Website automations
@adkian-sifive please help me ensure that between https://github.com/chipsalliance/chisel/pull/4431 and this, we add `-Xsource:3` to the chisel build unit in the mill build.
- Squash
Normal development should use Mill instead of SBT from now on.
=> [mill] Copy scalacOptions over to mill, add instructions to CONTRIBUTING

.github/workflows/test.yml, build.sc, core/src/main/scala/chisel3/ModuleImpl.scala, core/src/main/scala/chisel3/internal/Builder.scala
https://github.com/chipsalliance/chisel/pull/4462 broke Chisel because I accidentally deleted the scalacOption for the plugin from the Chisel module. This was missed because CI is still run with SBT. This PR will fix the issue and switch to using Mill for CI so we don't make this mistake again.
- Bugfix
- Squash
=> [CI] Use Mill for testing

build.sc
Update build.sc to match the build.sbt core Scalac compile options - core in SBT now uses Xsource:3
Add `-Xsource:3` to Mill `core` compilation unit
=> [Scala3] [Mill] Add Xsource:3 to core in Mill to match SBT

core/src/main/scala/chisel3/properties/Path.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
=> Have `HasTarget` paths be `IsMemberPath`

src/main/scala/chisel3/experimental/util/SerializableModuleElaborator.scala
Our designs are based on the SerializableModuleElaborator, which doesn't use the cmdopt, thus need to expose `IncludeUtilMetadata` to `SerializableModuleElaborator`.
- Bugfix
=> add additionalAnnotations for SerializableModuleElaborator

src/main/scala/chisel3/FixedIOModule.scala
This PR removes the source locator of io in FixedIOModule since we cannot get the actual location of ioGenerator.
=> fix: remove source locator for IO in FixedIOModule

website/src/css/custom.css
=> Change link colors for aid in readability in dark mode.

src/main/scala/chisel3/util/BitwiseImpl.scala
Fix https://github.com/chipsalliance/chisel/pull/4518#discussion_r1855325583
Reference: https://docs.scala-lang.org/scala3/reference/dropped-features/do-while.html
- Bugfix
=> fix: fix while loop in ReverseImpl

panama.sc
=> fix up wrong build path for panama

panamaom/src/PanamaCIRCTOM.scala
I'm improving the PanamaOM API and using it in the real project.
These API might change at anytime without the deprecation flow, after we polish it to a good status, we will add more examples and tests for them.
- Bugfix
=> add type safe API to access OM

src/test/scala/chiselTests/BoringUtilsSpec.scala, src/test/scala/chiselTests/BoringUtilsTapSpec.scala, src/test/scala/chiselTests/ChiselSpec.scala, src/test/scala/chiselTests/FixedIOModuleSpec.scala, src/test/scala/chiselTests/InlineSpec.scala, src/test/scala/chiselTests/IntrinsicSpec.scala, src/test/scala/chiselTests/ModuleChoiceSpec.scala, src/test/scala/chiselTests/ModulePrefixSpec.scala, src/test/scala/chiselTests/ProbeSpec.scala, src/test/scala/chiselTests/PublicModuleSpec.scala, src/test/scala/chiselTests/RawModuleSpec.scala, src/test/scala/chiselTests/experimental/FlatIOSpec.scala, src/test/scala/chiselTests/naming/NamePluginSpec.scala, src/test/scala/chiselTests/naming/PrefixSpec.scala, src/test/scala/chiselTests/properties/ClassSpec.scala, src/test/scala/chiselTests/properties/ObjectSpec.scala, src/test/scala/chiselTests/properties/PropertySpec.scala
Migrate all tests to FileCheck and delete `matchesAndOmits`.
=> Move to FileCheck

macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Fix typo in scaladoc for sourceInfoTransform macro
=> fix typo in SourceInfoTransform.scala

website/blog/2025/01-07-restarting-the-blog/index.md, website/blog/authors.yml, website/blog/tags.yml, website/docusaurus.config.js
Add a blog to the website. Include a basic blog post indicating that we have a blog.
This is intended to be enough for other authors to figure out how to write posts. E.g., you add yourself as an author, copy the boilerplate, and get writing!
CC: @Ramlakshmi3733, @dtzSiFive
=> [website] Add a blog section and an initial blog post

svsim/src/main/resources/simulation-driver.cpp, svsim/src/test/resources/SIntTest.sv, svsim/src/test/scala/BackendSpec.scala, svsim/src/test/scala/Resources.scala
Although I don't understand the reasons for not using the conversions provided by `stringstream`, this PR fixes one of the edge cases as mentioned in #4593 :
> If bitWidth % 8 == 0, and the bits have a value of -1<<(bitWidth-1), then the most significant bit will be stripped off by mistake.
Fixes https://github.com/chipsalliance/chisel/issues/4593
- Bugfix
--------
This is a manual backport of pull request #4599 done by @jackkoenig
=> Fixes `sendBits()`'s handling of signed numbers in `svsim` (backport #4599)

core/src/main/scala-3/chisel3/experimental/SourceInfo.scala
This is a temporary change till we get the Scala3 macro for SourceInfo merged
Update Scala3 materialize with a temporary placeholder UnlocatableSourceInfo
=> Replace ??? with UnlocatableSourceInfo

docs/src/explanations/operators.md
=> [docs] Fix pipe rendering in markdown table

.github/workflows/ci.yml
=> Fix typo in #4632: correct JVM version

core/src/main/scala/chisel3/Layer.scala, src/test/scala/chiselTests/LayerSpec.scala
Change the `layer.block` API to return values.  If the value is a `Data`,
then create a wire of layer-colored probe type immediately before the
layer block.  Inside the layer block, define this value with a probe of
the return.  If the value is a non-`Data`, then return it directly.
Previously, this API would always return `Unit`.
Add a type class, to be used for layer blocks, that can be used to
post-process a layer block's return value.  Two type class generators are
provided: one that is an identity function and another that returns a
wire of layer-colored probe type.
This latter type class generator has the effect of creating code like the
following without requiring a pre-declared layer:
``` firrtl
wire a: Probe<UInt<1>>
layerblock A:
wire b: UInt<1>
define a = probe(b)
```
CC: …
=> [core] Add layer block that returns colored wire

.github/workflows/ci.yml, CONTRIBUTING.md, plugin/package.mill
* Switch back to plugin cross versions rather than normal scala cross versions.
* Switch to Java 11 for publishing instead of Java 21 so that we can publish the plugin for Scala versions < 2.13.11.
FYI @unlsycn, just minor fixes from the move to Mill 0.12 and Java 21
- Squash
=> Fix chisel-plugin artifact publishing

src/main/scala/chisel3/util/circt/DPI.scala
This updates the example code in the documentation comments for the DPI function call APIs in the chisel3.util.circt.dpi package. The changes align the examples with the existing function call in DPISpec.scala.
=> update DPI function call examples in chisel3.util.circt.dpi

build.mill, core/package.mill, firrtl/package.mill, integration-tests/package.mill, macros/package.mill, plugin/package.mill, stdlib/package.mill, svsim/package.mill
This wasn't previously necessary because we always published using Java 8, but since Mill now requires at least Java 11+, we now need to do this.
I tested this locally by using `import java.util.random.RandomGenerator` (added in Java 17) in our Scala code. This worked before I added the option, then once I added `-release:8` it became a compile error.
- Squash
This ensures published Chisel artifacts work with Java 8--both in generated bytecode (which was previously true because default setting is -target:8), but also in disallowing APIs added in newer JDKs.
=> Add -release:8 to scalacOptions

build.mill
- Squash
This improves firtool-resolver's thread-safety between different processes.
=> Bump firtool-resolver to 2.0.1

CONTRIBUTING.md
=> Update CONTRIBUTING.md build and test instructions

circtpanamabinding/package.mill, panamaconverter/package.mill, panamalib/package.mill, panamaom/package.mill, plugin/package.mill
Revision of #4661 which eliminate implicit dependency
- Bugfix
=> Add publish flow for panama modules

release.mill
Commit [6f8f5cc](https://github.com/chipsalliance/chisel/commit/6f8f5cc26df38b104ced933aab768a026036e0cb) that splits publish traits mistakenly makes `publishVersion` in `unipublish` overridden by `CiReleaseModule` and this patch fixes it.
=> Fix misoverrided publish version

src/main/scala/chisel3/simulator/Simulator.scala
Refactor some code internal to the `Simulator` trait.  This was previously using a pattern that had a lot of nesting which made it difficult for me to follow.  Flatten this.
=> [chiselsim] Flatten out try/Try logic, NFC

src/main/scala/chisel3/util/random/FibonacciLFSR.scala
=> Deterministic FibonacciLFSR reductions

core/src/main/scala/chisel3/Annotation.scala, core/src/main/scala/chisel3/experimental/Targetable.scala, src/test/scala-2/chiselTests/NewAnnotationsSpec.scala
Some minor improvements to the user API for annotating with Targetable
* Support annotating Seq[Targetable] and provide Targetable for AnyTargetable.
* Add AnyTargetable.apply for simpler manual conversions.
* Show tests annotating Seq[Targetable] and manual use of AnyTargetable.
- No Release Notes
Changes to unreleased API
- Squash
=> Refine annotate and Targetable

integration-tests/src/test/scala-2/chiselTest/QueueFlushSpec.scala
Migrate the integration test QueueFlushSpec from ChiselSpec to ChiselSim.
=> [test] Migrate QueueFlushSpec to ChiselSim

src/main/scala/chisel3/simulator/scalatest/WithTestingDirectory.scala
Further exapand the string replacements used when mangling Chiselsim directories derived from Scalatest scopes.  Strip single quotes, double quotes, and hash marks.
Strip `"`, `'`, and `#` in Scalatest-dervied ChiselSim test directory names to avoid Verilator Makefile compilation failures.
=> [chiselsim] Strip quotes, hash in Chiselsim directories

integration-tests/src/test/scala-2/chiselTest/QueueSpec.scala, integration-tests/src/test/scala-2/chiselTest/ShiftRegisterMemSpec.scala, integration-tests/src/test/scala-2/chiselTest/VecIntegrationSpec.scala, integration-tests/src/test/scala-2/chiselTest/util/SparseVecSpec.scala, integration-tests/src/test/scala-2/chiselTest/util/experimental/PlaSpec.scala, integration-tests/src/test/scala-2/chiselTest/util/experimental/TapSpec.scala, src/test/scala-2/chiselTests/AdderTree.scala, src/test/scala-2/chiselTests/AnalogIntegrationSpec.scala, src/test/scala-2/chiselTests/AnalogSpec.scala, src/test/scala-2/chiselTests/AsTypeOfTester.scala, src/test/scala-2/chiselTests/Assert.scala, src/test/scala-2/chiselTests/AsyncResetSpec.scala
Just running CI on some batched test changes.
=> Move some tests from ChiselSpec to ChiselSim

src/test/scala-2/chisel3/internal/ContainsProbeSpec.scala, src/test/scala-2/chisel3/internal/IdentifierSpec.scala, src/test/scala-2/chiselTests/ChiselSpec.scala, src/test/scala-2/chiselTests/ConnectableSpec.scala, src/test/scala-2/chiselTests/SourceLocatorSpec.scala, src/test/scala-2/chiselTests/VecToTargetSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/InstantiateSpec.scala, src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala, src/test/scala-2/chiselTests/naming/IdentifierProposerSpec.scala
Remove ChiselFunSpec in favor of flattening everything to use Scalatest directly.
=> [test] Remove ChiselFunSpec

src/test/scala-2/chiselTests/BulkConnectSpec.scala, src/test/scala-2/chiselTests/ChiselSpec.scala, src/test/scala-2/chiselTests/Direction.scala, src/test/scala-2/chiselTests/EnableShiftRegister.scala, src/test/scala-2/chiselTests/Harness.scala, src/test/scala-2/chiselTests/IOCompatibility.scala, src/test/scala-2/chiselTests/InvalidateAPISpec.scala, src/test/scala-2/chiselTests/Math.scala, src/test/scala-2/chiselTests/MemorySearch.scala, src/test/scala-2/chiselTests/MixedVecSpec.scala, src/test/scala-2/chiselTests/ModuleSpec.scala, src/test/scala-2/chiselTests/Padding.scala, src/test/scala-2/chiselTests/Risc.scala, src/test/scala-2/chiselTests/Stack.scala, src/test/scala-2/chiselTests/Vec.scala, src/test/scala-2/chiselTests/VerificationSpec.scala, src/test/scala-2/chiselTests/naming/PrefixSpec.scala
Remove ChiselPropSpec and replace it with direct usage of Scalatest.
=> [test] Remove ChiselPropSpec

.github/scripts/chisel-example.scala, .github/workflows/ci-circt-nightly.yml, .github/workflows/ci.yml, .github/workflows/test.yml, CONTRIBUTING.md, build.mill
=> Bump to and cross-compile for Scala 2.13.16

svsim/src/main/scala/Workspace.scala
- Bugfix
Fix 'rm' executable dependency on windows.
=> Fix for #4780

svsim/src/main/scala/Workspace.scala
- Bugfix
- Squash
* Use custom FileVisitor for more optimal traversal
* Suppress DirectoryNotEmptyExceptions from failing to delete directories due to systems like FUSE.
=> Make SVSim directory clearing more robust

src/main/scala-2/chisel3/util/SRAM.scala
This PR fixes the inconsistency of argument names in signatures and Scaladocs in two overloads of `SRAM.apply`. It is a pure documentation change and impacts no executable code.
=> [docs] Fix wrong argument docs in SRAM object

core/src/main/scala/chisel3/Num.scala
These were accidentally removed in chipsalliance/chisel#4768.
(technically this touches the API, but this just restores part of the public API that was affected by #4768)
=> Restore NumObject trait and Num object

src/test/scala-2/chiselTests/RegSpec.scala
- No Release Notes (fix to tests)
- Squash
They previously relied on registers initializing to 0 and might have depended on non-determinism between when assert and stop occur in the same cycle.
=> Fix ShiftRegisterSpec and ShiftRegistersSpec

firrtl/src/main/scala/firrtl/annotations/Target.scala, firrtl/src/main/scala/firrtl/annotations/TargetToken.scala, firrtl/src/test/scala/firrtlTests/annotationTests/TargetSpec.scala
Remove unused APIs from FIRRTL's target package.
See individual commits for more information.
=> [firrtl] Remove unused target APIs

docs/src/explanations/testing.md
Expand the documentation about FileCheck to include suggested firtoolOpts settings.
=> [docs] Document FileCheck and firtoolOpts

core/src/main/scala/chisel3/Printable.scala, core/src/main/scala/chisel3/package.scala, docs/src/explanations/printing.md, src/test/scala-2/chiselTests/PrintableSpec.scala, src/test/scala-2/chiselTests/Printf.scala
But no release notes because this feature is not yet released
- Squash
=> Rename and fix firrtl emission for HierarchicalModuleName

src/main/scala-2/chisel3/FixedIOModule.scala, src/main/scala-3/chisel3/FixedIOModule.scala, src/test/scala-2/chiselTests/FixedIOModuleSpec.scala
- Add `FixedIOModule`, which behaves like `FixedIORawModule` but also has a `clock` and `reset` port.
=> Add FixedIOModule

core/src/main/scala/chisel3/Annotation.scala, src/test/scala-2/chiselTests/AnnotationInlineSpec.scala
The existing `InlineInstance` and `InlineInstanceAllowDedup` traits allow users to mark modules/instances for inlining at compile time, but they can't mark modules/instances for inlining at run-time. These new objects give this run-time flexibility to users, similar to the `doNotDedup` API.
Redo of https://github.com/chipsalliance/chisel/pull/4881 because Github is bugging out and I wasn't able to merge it.
Add `chisel3.experimental.inlineInstance` and `chisel3.experimental.inlineInstanceAllowDedup` methods to control module inlining at run-time.
=> Add methods to inline module instances

.github/workflows/require-label.yml, build.mill, docs/package.mill, integration-tests/package.mill, lit/utility/package.mill, panamaconverter/package.mill, plugin/package.mill, stdlib/package.mill
Update build files to replace references to `HasScala2Plugin` to `HasScalaPlugin`. Other small changes and bugfixes to support plugins in Scala 3
Build files have been updated to support plugins in Scala 3.
=> [Scala3] Update build files to support Scala3 plugins

firrtl/src/main/scala/firrtl/annotations/Target.scala
=> Add error message for dynamic index in target

.github/workflows/ci.yml, build.mill, circtpanamabinding/package.mill, panamaconverter/package.mill, panamalib/package.mill, panamaom/package.mill, release.mill
Don't merge this yet, I currently have CI disabled and publishing enabled for branches so that I can see that this publishes SNAPSHOTS properly
- Squash
mill-ci-release is archived and we were accidentally publishing the compiler plugin for Scala 3.
=> Refactor publishing logic

.github/workflows/config/release-notes.json
Marking them as Internal since they aren't really user facing (but may be of interest).
- Squash
=> Support Scala 3 label in release notes generation

website/blog/2025/05-05-latch-up/index.md, website/blog/authors.yml, website/blog/tags.yml
=> [blog] Add blog post about Latch Up 2025

core/src/main/scala/chisel3/Data.scala, src/test/scala-2/chiselTests/ConnectableSpec.scala
Fixes https://github.com/chipsalliance/chisel/issues/4916
- Bugfix
- Squash
=> Improve error for bad connections with null module name

src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
"/" is the path separator in most Unix-based systems. Not mangling it would create a new subfolder. I'm also adding "\" as it's the path separator on Windows.
- Bugfix
=> [testing] Mangle even more directories

src/main/scala/chisel3/testing/FileCheck.scala, src/main/scala/chisel3/testing/HasTestingDirectory.scala, src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala, src/test/scala-2/chiselTests/experimental/TraceSpec.scala, src/test/scala-2/chiselTests/stage/WarningConfigurationSpec.scala, svsim/src/main/scala/Simulation.scala, svsim/src/main/scala/Workspace.scala
Newer versions of `mill` run tests inside a [sandboxed folder](https://mill-build.org/mill/depth/sandboxing.html#_test_sandboxing) under the 'out/' folder.
The current svsim/ChiselSim code does not consider this, resulting in a weird, deeply-nested, and hard to predict simulation path. This can be confusing for users. It's particularly annoying when trying to access trace files created by the simulation.
This is taken from #4911 with some modifications. #4911 will be updated after this PR is merged.
- adds public `getProjectRootOrCwd` in `svsim.Workspace` as a more reliable way to discover the current project's root path, especially in the presence of build-system sandboxing.
- adds workingDirectory to `svsim.Simulation`, resolved absolute path to `workingDirectoryPath`, resolved using …
=> [svsim/ChiselSim] Discover the project's root directory in a sandboxed build

src/main/scala/chisel3/experimental/inlinetest/InlineTest.scala
- Some feedback I missed on https://github.com/chipsalliance/chisel/pull/4946.
=> Make TestChoice.Globs.globs private

docs/src/explanations/blackboxes.md
=> [docs] Fix BlackBoxRealAdd port widths

docs/src/explanations/layers.md
Update the docs to include information about the new temporal layers and
the helper trait to create child temporal layers.
=> [docs] Update layer docs for temporal layer, NFC

docs/src/explanations/layers.md, docs/src/explanations/testing.md
Add light documentation about the automatic disabling of temporal layers
when running with the ChiselSim Cli.Simulator trait.
=> [doc] Document temporal layers and ChiselSim

src/main/scala/chisel3/ltl/LTL.scala, src/main/scala/chisel3/util/circt/LTLIntrinsics.scala
=> [Scala3] Move CIRCT LTL from src/main/scala-2 to src/main/scala/

plugin/src/main/scala-3/chisel3/internal/plugin/BundlePhase.scala, plugin/src/main/scala-3/chisel3/internal/plugin/PluginHelpers.scala
- Add support for ignoreSeq
- Move BundlePhase to run after PickleQuotes
BundlePhase now runs after PickleQuotes to sidestep Scala 3 compiler bug https://github.com/scala/scala3/issues/23793
=> [Scala3] BundlePhase updates

core/src/main/scala-3/chisel3/VerificationStatementIntf.scala, core/src/main/scala-3/chisel3/VerificationStatementMacros.scala
Add apply methods that don't propagate source line info for Scala 3
Added Scala 3 assert, assume, cover apply methods for Scala 3
=> [Scala3] Add apply methods to assert, assume, cover

.github/workflows/test.yml, src/test/scala/chiselTests/BundleSpec.scala
BundleSpec is moved from `src/test/scala-2` to `src/test/scala` and now runs with both Scala2 and Scala3. It didn't require any changes save for handling string representation differences between Scala 2 and 3
Enable CI testing in Scala 3 starting with BundleSpec
=> [Scala3] Add BundleSpec and enable Scala3 CI testing
